### ISSUE TITLE
Add a method to Kademlia to get content of k-buckets

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#1003]
Useful for general diagnostic.

**Comment by tomaka** [comment]
While this has been done in #1016, it would be nice to have a better API for `Kademlia` that allows querying the state of a particular peer, and in general being able to obtain any information we need about the buckets from the external world.

**Comment by romanb** [comment]
It would be good to update this issue in light of the current Kademlia API (or close it). I personally don't really know what's missing.

**Comment by tomaka** [comment]
> I personally don't really know what's missing.

The idea behind this issue was to be able to print out the content of the k-buckets for debugging purposes.

I must admit that I don't remember what's missing apart from `kbuckets_entries`.
