### ISSUE TITLE
Rework the way one combines NetworkBehaviours together

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#1021]
The `NetworkBehaviour` custom derive is a bit weird in terms of API (especially when it comes to the event handling trait and having to override a `poll()` function), and is also imprecise in terms of ordering of operations.

For example, `addresses_of_peers` is supposed to return the addresses in a specific order, but it is unclear to the user how to influence this order.

I think a better solution would be to make the trait easy to implement manually, so that everything is clear.
Additionally, we would provide in libp2p itself some common combinations to easily get started, such as `Ping+Identify+Kademlia+Floodsub+mDNS`.

**Comment by tomaka** [comment]
> I think a better solution would be to make the trait easy to implement manually, so that everything is clear.
> Additionally, we would provide in libp2p itself some common combinations to easily get started, such as Ping+Identify+Kademlia+Floodsub+mDNS.

Alternatively, a different (and IMO better) long term vision for combining network behaviours together would be to do something like that:

```rust
let behaviour = Ping::new().join(Identify::new()).join(Kademlia::new());
let swarm = Swarm::new(behaviour, ...);
```

At the moment the problem with that is that we cannot easily express the type of the `Swarm`. It would be extremely long and annoying to do so. This can be solved:
- Either with `impl Trait` in the future.
- Or by adding a `BoxedNetworkBehaviour` type similar to `BoxedTransport` and `BoxedStreamMuxer`.

**Comment by tomaka** [comment]
Another possibility would be to specialize the `Swarm` a bit more.
Instead of having only `NetworkBehaviour`, we would have several `DiscoveryBehaviour`, `PubsubBehaviour`, etc. traits with a mandatory output event type and a mandatory set of methods to implement. This makes it possible to combine behaviours in a straight-forward way.

**Comment by tomaka** [comment]
> So the first step for this issue would be to create a BoxedNetworkBehaviour that takes as little template parameters as possible (normally just the substream and event type) and makes it possible to abstract over a NetworkBehaviour.

I ended up implementing that (in a local branch).
The problem is that you then cannot call the methods of the `NetworkBehaviour`.

I think that doing this would also be a good idea:

> Instead of having only NetworkBehaviour, we would have several DiscoveryBehaviour, PubsubBehaviour, etc. traits with a mandatory output event type and a mandatory set of methods to implement. This makes it possible to combine behaviours in a straight-forward way.

**Comment by mxinden** [comment]
Related pull request: https://github.com/libp2p/rust-libp2p/pull/1405

**Comment by thomaseizinger** [comment]
I don't think we will be doing this any time soon, closing as stale.
