### ISSUE TITLE
Make it possible to pass metadata from the transport to the protocols handler

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#1030]
At the moment, the `SecioOutput` contains the ephemeral key used during negotiation, but since the `Swarm` requires the transport output to be `(PeerId, impl StreamMuxer)`, we have no way to pass it around.

This is required for https://github.com/paritytech/substrate/issues/271

**Comment by tomaka** [comment]
We don't need it anymore in Substrate, so I'm going to lower the priority tag.

**Comment by thomaseizinger** [comment]
Closing in favor of https://github.com/libp2p/rust-libp2p/issues/2946.
