### ISSUE TITLE
[Question] How to properly shutdown connection with remote Peer?

### ISSUE THREAD

**Issue by echupriyanov** [libp2p/rust-libp2p#1036]
Right now the only way I see to close connection with remote peer is to set KeepAlive::Now on all involved protocol handlers, which requires proper orchestration across NetworkBehaviours.

Is there more streamlined way to do that?

**Comment by tomaka** [comment]
If a protocol handler produces an error in `poll()`, then the connection will be closed.

**Comment by echupriyanov** [comment]
It will also terminate all other mixed protocol handlers for this connection?

**Comment by tomaka** [comment]
Yes!

**Comment by tomaka** [comment]
Closing. Feel free to reopen if you need more info.
