### ISSUE TITLE
Implement an HttpTransport

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#1038]
The `/http` multiaddress seems to correspond to a simple HTTP client/server. We can turn libp2p into a simple HTTP client/server with some minor tweaks.

It should be possible to write an `HttpTransport` whose output is a `(ConnectionId, HttpConnection)`. The `HttpTransport` would be generic over the underlying transport; by default it would be a `TcpConfig`, but something else could be used in practice.
The `ConnectionId` would be the equivalent of `PeerId` and consist in a global linearly-increasing integer.
The `HttpConnection` would implement `StreamMuxer` and would allow only outbound substreams (in the case of a client), or inbound substreams (in the case of a server).

It would be the role of the user to not use behaviours such as `Ping` or `Identify` that always open outbound substreams.

The problem that remains is that we would have a mandatory multistream-select negotiation inside of each request, because rust-libp2p doesn't allow having upgrades that aren't negotiated.

**Comment by tomaka** [comment]
To be clear, the `HttpTransport` shouldn't open any socket itself. It should delegate everything to the underlying transport.

**Comment by montekki** [comment]
I've started looking into it and I have several questions.

1. Why should `http` (only) be a transport protocol? One of the usecases would be to use http on top of tcp+kad+secio so you could end up with something http2-like. We could try creating a `hyper` server/client on top of the `SubstreamRef` or something.

2. http deals with requests, not the connections, i.e. requests from the same client may be delivered to the server via different tcp sessions and also a same tcp session might deliver requests from different users as in the case with keep-alive connections from proxy to a backend. Given that `HttpConnection` doesn't make much sense to me r.n.

**Comment by tomaka** [comment]
I actually have a prototype in an `http` branch: https://github.com/libp2p/rust-libp2p/compare/master...tomaka:http

I indeed ended up writing an `HttpNodeHandler` that handles requests as a `NodeHandler` implementation.

**Comment by tomaka** [comment]
Closing this, as it's just a funny idea that, if implemented, should never be used in production anyway.
