### ISSUE TITLE
Question on implementing `NetworkBehaviour` 

### ISSUE THREAD

**Issue by thomaseizinger** [libp2p/rust-libp2p#1058]
I am trying to use libp2p as the communication layer of a peer-to-peer application and I am running into a few problems.

We have our own protocol and implementing that one in libp2p was fairly straight forward by implementing `ProtocolsHandler`.

As a next step, we implemented a custom `NetworkBehaviour` that uses our `ProtocolsHandler` implementation.

**First question:** I saw that there is a custom-derive for `NetworkBehaviour`. Am I even supposed to implement `NetworkBehaviour` myself or should I always use the custom-derive? From looking at the examples and how libp2p is used in substrate, I looks like the custom-derive is only used for _composing_ `NetworkBehaviour`s. Is that correct?

---
Our application has an external API, through which the user should be able to trigger the sending of messages to other peers. We currently try to do this by having a method on our `NetworkBehaviour` implementation that stores an instance of `NetworkBehaviourAction::SendEvent` in a `VecDeque` inside the behaviour. As the `NetworkBehaviour` gets `poll`ed, we take the events stored in this `VecDeque` and return an `Async::Ready` of the event.

If there are no pending events when `poll` is called, the only thing I can return is `Async::NotReady`.
With tokio, you are not supposed to return `Async::NotReady` unless another task returned `NotReady`. I think I am violating this rule at the moment and it may be the reason why it currently doesn't work.

More specifically, I can see from the logs that the `poll` method is never called again after it was called once and we returned `NotReady`.

**Second question:** How am I supposed to deal with this situation? In particular, what is the intended way to _feed_ events into a `NetworkBehaviour` from other parts of the application? It seems like that I have to _notify_ the current task from inside our custom method on `NetworkBehaviour` to initiate another poll. However, it also feels like this should not be necessary if we go for a different design?

**Third question:** Our own implementation of `NetworkBehaviour` is not very useful at the moment because we don't have any logic that involves multiple peers (contrary to floodsub for example, which communicates with multiple peers upon each event). This means we only delegate through to our `ProtocolsHandler` implementation. Is there an easier way to implement `NetworkBehaviour` in these situations? Maybe a generic implementation I can resort to?

**Fourth question:** Why does the `poll` method API in `NetworkBehaviour` force you to always return an event? It appears to me that it is fairly common that there "nothing to do" at the moment but at the same time, returning `NotReady` would violate the `Future`s contract. But maybe that is just my limited understanding of how things are supposed to work :grimacing:

**Comment by tomaka** [comment]
> First question: I saw that there is a custom-derive for NetworkBehaviour. Am I even supposed to implement NetworkBehaviour myself or should I always use the custom-derive? From looking at the examples and how libp2p is used in substrate, I looks like the custom-derive is only used for composing NetworkBehaviours. Is that correct?

Yes. As a protocol implementer you'd implement the trait manually, and as a user you'd use the custom derive.
The long term idea however would be to remove this custom derive and make the trait easier to implement in general.

**Comment by tomaka** [comment]
> If there are no pending events when poll is called, the only thing I can return is Async::NotReady.
With tokio, you are not supposed to return Async::NotReady unless another task returned NotReady. I think I am violating this rule at the moment and it may be the reason why it currently doesn't work.

That's currently a quirk in the system. It's unfortunately your job to poll the `Swarm` appropriately at the moment.

> Third question: Our own implementation of NetworkBehaviour is not very useful at the moment because we don't have any logic that involves multiple peers (contrary to floodsub for example, which communicates with multiple peers upon each event). This means we only delegate through to our ProtocolsHandler implementation. Is there an easier way to implement NetworkBehaviour in these situations? Maybe a generic implementation I can resort to?

There should indeed be a way in `libp2p-core` to have a dummy network behaviour, but there currently isn't.

> Fourth question: Why does the poll method API in NetworkBehaviour force you to always return an event? It appears to me that it is fairly common that there "nothing to do" at the moment but at the same time, returning NotReady would violate the Futures contract. But maybe that is just my limited understanding of how things are supposed to work grimacing

Well, returning `NotReady` is definitely the right thing to return. I don't really see what else you could return anyway. Again, unfortunately it's your job to poll the `Swarm` after you interact with the behaviour.

**Comment by thomaseizinger** [comment]
Thanks a lot for your response!
I was able to resolve the `Async::NotReady` issue by storing `task::current()` inside the behaviour and notifying it once I add an event. That seems to be working well so far :)
It is actually straight forward once you go through the docs of tokio again, I just forgot about it since it is so uncommon 😅

Unfortunately, I am running into another problem now. My nodes successfully connect to each other, but the connection is never upgraded to the protocol I implemented. Any pointers on how to debug this? How can I make sure that libp2p will try to upgrade a connection to a specific protocol? I tried playing around with combining my behaviour with `Identify` in the hope that this would result in the connection being upgraded but no luck so far :(

**Comment by tomaka** [comment]
> My nodes successfully connect to each other, but the connection is never upgraded to the protocol I implemented.

I'm not sure without looking at your code, but my guess is that you expect it to be automatic while it's not.

It is the role of the implementation of `ProtocolsHandler` to open new substreams and send data in them.
Once a connection is established, the network behaviour gets notified (with `inject_connected`), and typically you would then send a message to the `ProtocolsHandler` to do something. The `ProtocolsHandler` then receives that message and opens the substream.

Note that, while it is not mandatory, you are kind expected to open one substream per request you make. For example, if you send a ping, you open a new substream, send the ping, close the substream. If you want to ping again, or ping a second time simultaneously, you would open another substream.

**Comment by thomaseizinger** [comment]
Ah thank you very much! That was the missing thing!

I never emitted a `ProtocolsHandlerEvent::OutboundSubstreamRequest` event from my protocol handler :see_no_evil: 

> Note that, while it is not mandatory, you are kind expected to open one substream per request you make. For example, if you send a ping, you open a new substream, send the ping, close the substream. If you want to ping again, or ping a second time simultaneously, you would open another substream.

It currently works without doing that. Could you elaborate a bit on why I that is recommended? Under which circumstances could one run into problems if I _don't_ open a new substream for each message?

**Comment by tomaka** [comment]
> It currently works without doing that. Could you elaborate a bit on why I that is recommended? Under which circumstances could one run into problems if I don't open a new substream for each message?

The problem you can run into is: if two nodes connect to each other, and they both open a substream, which one do you keep? In Substrate I "solved" this by having only the connection initiator open a substream (by passing a message), but then we also sometimes want to close this substream and reopen it spontaneously later, and then you run into that problem again.

In general, the advantage of splitting between substreams is that the multiplexer can interleave packets of data. In other words, requests doesn't have to block on earlier requests. The other advantage may come later: if we allow multiple simultaneous connections between nodes, you can then distribute substreams amongst the multiple connections.

**Comment by thomaseizinger** [comment]
Okay, thanks a lot for the explanation! :)

I got the whole thing working now, so I'll close this one.
