### ISSUE TITLE
Kademlia::add_providing reaches unimplemented!()

### ISSUE THREAD

**Issue by rnbguy** [libp2p/rust-libp2p#1089]
I get unimplemented error while using `add_providing` in Kademlia swarm, because of this.

https://github.com/libp2p/rust-libp2p/blob/ca58f8029c70db16774c988f409703f0191609d8/protocols/kad/src/behaviour.rs#L177-L180

It seems the mentioned TODO should work.

https://github.com/libp2p/rust-libp2p/blob/ca58f8029c70db16774c988f409703f0191609d8/protocols/kad/src/behaviour.rs#L127-L130

**Comment by rnbguy** [comment]
Also, is there any reason why `add_providing` requires `key` to be `PeerId`, not `Multihash`? It does `key.clone().into()` or `key.into()` inside the function anyway.

https://github.com/libp2p/rust-libp2p/blob/ca58f8029c70db16774c988f409703f0191609d8/protocols/kad/src/behaviour.rs#L296-L298

**Comment by tomaka** [comment]
`add_providing` is one of these features that is half implemented and not tested. While the code exists, you will run into issues.

As for `PeerId` vs `Multihash` for `add_providing`, this indeed looks like a mistake.

cc @elferdo

**Comment by elferdo** [comment]
> Also, is there any reason why `add_providing` requires `key` to be `PeerId`, not `Multihash`? It does `key.clone().into()` or `key.into()` inside the function anyway.
> 
> https://github.com/libp2p/rust-libp2p/blob/ca58f8029c70db16774c988f409703f0191609d8/protocols/kad/src/behaviour.rs#L296-L298

This is indeed a mistake and should be addressed in https://github.com/libp2p/rust-libp2p/pull/1095
