### ISSUE TITLE
[Question] Peer management / disconnection

### ISSUE THREAD

**Issue by AgeManning** [libp2p/rust-libp2p#1090]
I have a collection of `NetworkBehaviour`'s (and protocols) composed into a singular global `NetworkBehaviour` (via the derive macro). I'm thinking of ways to implement peer management over a collection of behaviours.
Specifically, I'd like to disconnect from peers across a collection of protocols/behaviours. 

My current thinking is to implement a `PeerManagement` behaviour, which has a `DummyProtocolsHandler` that can force a user-controlled disconnect by throwing an error (as in #1036).  This could be composed  with the set of `NetworkBehaviour`'s and protocols that the peer management can control. This should drop a peer across all composed protocols with this behaviour correct?

Is there are more elegant way / design for peer management in `rust-libp2p`?

**Comment by tomaka** [comment]
> Is there are more elegant way / design for peer management in rust-libp2p?

Not really.
A better way could be to add a method on the `Swarm` to force a disconnect.

In my opinion, however, forcing a disconnect is generally an XY problem. What I mean is that I don't see a reason to not have an active connection between nodes, except saving up memory/CPU/file descriptors. It's obviously not something that shouldn't be possible (we don't want to prevent the users from doing what they want to do), but it's also not something that should be seen as normal use case.

**Comment by AgeManning** [comment]
> A better way could be to add a method on the Swarm to force a disconnect.
Not sure I follow. Are you suggesting modifying the `Swarm` struct of libp2p?. Obviously having a `disconnect()` method on the network behaviour will allow a `swarm.disconnect` as `Swarm` derefernces the behaviour. 

My thinking for this logic was for malicious peers. I would like to force a disconnect, then prevent future connections for a period of time from that peer. Also, if a peer is malicious on one protocol, I would like to prevent it from participating in other protocols. I can't think of an easier way of handling this than simply forcing a disconnect. Do you have any suggestions for this problem?

**Comment by AgeManning** [comment]
After a bit more thinking, I think the approach is to write a custom `Swarm` which performs the disconnect and peer management. I guess this is what you were suggesting.

**Comment by tomaka** [comment]
> Not sure I follow. Are you suggesting modifying the Swarm struct of libp2p?

Yes!

> My thinking for this logic was for malicious peers. I would like to force a disconnect, then prevent future connections for a period of time from that peer.

If it's for malicious behaviours, then it makes sense to return an error in the `ProtocolsHandler`.

**Comment by AgeManning** [comment]
Yep awesome thanks. Going to implement a custom `Swarm` for my project, and potentially add a `disconnect()` to the `Swarm` struct of libp2p in a future PR.
