### ISSUE TITLE
We don't use TLS with /wss

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#1094]
When using WebSockets with `/wss`, we should connect to the server through HTTPS and not just HTTP. Right now we're using `async_connect_on`, which doesn't do that.

cc #849 

In general, I think that the libp2p-websocket crate should just be rewritten.

**Comment by noahwolf2001** [comment]
hello

**Comment by twittner** [comment]
Implemented.

**Comment by burdges** [comment]
You've a reasonable TLS for this then?  :)

**Comment by twittner** [comment]
We use https://crates.io/crates/tokio-rustls which in turn uses https://crates.io/crates/rustls and https://crates.io/crates/webpki.

**Comment by burdges** [comment]
so ring under the hood, fine.  :)
