### ISSUE TITLE
Remove dummy handler creation in `Swarm::new`

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#1098]
#1085 is blocked on this issue.

At the moment in `Swarm::new`, we build a dummy listener protocol upgrade in order to determine the list of protocols we support. See https://github.com/libp2p/rust-libp2p/blob/808a7a5ef6ae6cac55971ee234714fbdfb7b7d84/core/src/swarm/swarm.rs#L443-L451.

This is obviously a very bad design, because we're passing the local `PeerId`, and I don't see any perfect straight-forward solution to that.

Some ideas:
- Add a method on `NetworkBehaviour` to return the list of supported protocols, but it would have to be implemented manually, which is a bit annoying, and you have to make sure that you don't forget to propagate any change. It also raises the question of the return type. `Box<Iterator<Item = &dyn ProtocolName>>`?
- Add a method on `IntoProtocolsHandler` that returns the same value as `listen_protocol()`. The advantage is that this can be implemented automatically.

**Comment by twittner** [comment]
+1 for option 2. Shall I open a PR for https://github.com/twittner/rust-libp2p/commit/58e6a089f7843796ba076341dbf35fbdddb06059?

**Comment by tomaka** [comment]
> Shall I open a PR for twittner@58e6a08?

Sure, cool!

**Comment by tomaka** [comment]
Done in #1099
