### ISSUE TITLE
Add a WebSocket transports that outputs Sink/Stream of packets

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#1103]
The WebSockets protocol is about sending frames: either ping/pong frames, text, or binary.

There should be a WebSockets transport in libp2p that gives access to that by having an `Output` that implements the `Stream` and `Sink` traits, where the item is some enum (ping, pong, text, binary).

The "real" WebSockets transport can then be implemented on top of that by wrapping the output in an `RwStreamSink`.

**Comment by tomaka** [comment]
In addition to arguably being a better way to organize the code, the use-case is that I'd like to replace Substrate's telemetry with libp2p, and we need to be able to send precisely-delimited frames of data (as opposed to writing to a stream of bytes).

**Comment by montekki** [comment]
does libp2p have a `Sink + Stream` trait somewhere btw?

**Comment by tomaka** [comment]
> does libp2p have a Sink + Stream trait somewhere btw?

If you're asking about a trait that combines the two, then no.

**Comment by twittner** [comment]
https://github.com/libp2p/rust-libp2p/pull/1150 implemented a strategy similar to this.
