### ISSUE TITLE
Rewrite the protocol.rs file in Kademlia to be more straight-forward

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#1104]
The current `protocol.rs` is quite complex because of backwards-compatibility reasons from a time where we implemented the Kademlia is a way that's incompatible with go-libp2p and js-libp2p.

This was a very long time ago, and it should now be possible to remove this backwards compatibility code and replace it with more straight-forward code.
Inspiration can be taken from the `protocol.rs` file in `Floodsub`.

**Comment by tomaka** [comment]
This could be done on top of #1562

**Comment by thomaseizinger** [comment]
Closed in favor of https://github.com/libp2p/rust-libp2p/issues/3130.
