### ISSUE TITLE
Add TLS Handshake

### ISSUE THREAD

**Issue by g-r-a-n-t** [libp2p/rust-libp2p#1109]
The TLS handshake as described here https://github.com/libp2p/specs/blob/1a5e6eb805fc6c902128288ae1575945bcdc6e2a/tls/design%20considerations.md should be implemented.

**Comment by g-r-a-n-t** [comment]
Hey @tomaka, I sent you message on gitter inquiring about this work, but have not heard back, so I assume you don't check that.

Basically, I'm interested in contributing to libp2p and have heard that this functionality will be useful down the road. So if there aren't any major blockers on this, I'd like to take a crack at it.

**Comment by tomaka** [comment]
You can see some attempt from here in a branch: https://github.com/tomaka/libp2p-rs/blob/29e7b209c3cbdbdff2d7f2e737ea68c71eec4e0f/transports/quic/src/endpoint.rs#L161-L249

One of the main blocker is that the API of `rustls` doesn't have a straight-forward way of seeing the remote's certificate.

**Comment by g-r-a-n-t** [comment]
I'll keep you posted.

**Comment by DemiMarie-parity** [comment]
I had to solve this as part of implementing QUIC.

**Comment by Geo25rey** [comment]
@tomaka It might be worth it to begin the switch to OpenSSL entirely since go-libp2p and go-ipfs have started this transition.
