### ISSUE TITLE
Consider extracting the Swarm/NetworkBehaviour/ProtocolsHandler to a different crate

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#1112]
Right now `libp2p-core` contains two different APIs: the one in the `nodes` module, and the one in the `swarm` and `protocols_handler` module. The latter is built on top of the former.

Maybe it is better if the content of `nodes` (plus `transport`, `upgrade`, `identity`, etc.) were in their own crate, and the content of `swarm` and `protocols_handler` were in a different one on top.
The higher-level crate would re-export the types from the lower-level crate.

**Comment by romanb** [comment]
Can this be considered done?
