### ISSUE TITLE
Make the API of upgrades more intuitive

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#1130]
I don't think there's an issue for that already.
Putting upgrades on top of transports is a bit of a mess at the moment. How to do things is extremely counter-intuitive and undocumented.

**Comment by romanb** [comment]
There is overlap with https://github.com/libp2p/rust-libp2p/issues/953 though, or not?

**Comment by tomaka** [comment]
Ah yeah, this is kind of the same.
