### ISSUE TITLE
Add a time-to-live to external addresses

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#1135]
When, through `identify`, we receive the information about our IP address, we compute an "external address" that goes in a registry. See the `core::swarm::registry` module.

However, while there is a limit to the number of addresses, these addresses never expire and remain valid forever.

Since there is no mechanism that decreases the score of an address, once you reach 30 addresses, any new address will likely remain at the last position of the list even if the first 29 addresses are no longer valid.

This is especially problematic for IPv6, as some home routers automatically change your IP address every few hours for privacy reasons.

**Comment by twittner** [comment]
> Since there is no mechanism that decreases the score of an address, once you reach 30 addresses, any new address will likely remain at the last position of the list even if the first 29 addresses are no longer valid.

If the first 29 addresses are invalid and only the 30th is re-added consistently, it will eventually move to the first position. Scores are computed based on the number of insertions which means that if "identify" continues to report the new address its relative position will improve.

**Comment by twittner** [comment]
There is a ceiling though, which is 2^32. Once an address has been confirmed that often it becomes immortal (relative to the process' lifespan).

**Comment by tomaka** [comment]
> > Since there is no mechanism that decreases the score of an address, once you reach 30 addresses, any new address will likely remain at the last position of the list even if the first 29 addresses are no longer valid.
> 
> If the first 29 addresses are invalid and only the 30th is re-added consistently, it will eventually move to the first position. Scores are computed based on the number of insertions which means that if "identify" continues to report the new address its relative position will improve.

What I had in mind is: assuming that your IP rotates every hour, each hour the new IP will start at the bottom of the list, behind 29 expired addresses. And when the new IP finally catches up, it is time to rotate to a new one. In other words, the single valid address will almost constantly be at the bottom of the list.

**Comment by tomaka** [comment]
Maybe instead of basing this on time, we could decrease the score of every other address when one is reported.

In other words, the score of each address would be proportional to the number of times it has been reported in the latest 50 reports, for example.
