### ISSUE TITLE
Update the /memory multiaddr format

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#1153]
It's been standardized, and the parameter can be any value with a variable-length size.
https://github.com/multiformats/multiaddr/pull/71

Considering that `/memory` multiaddresses are not supposed to leave the current program, it is ok to break their internal representation.

**Comment by twittner** [comment]
The discussion in that PR leaves me a bit puzzled. The `protocols.csv` only specifies the parameter as `V` and remarks it is "arbitrary". The discussion contains a multitude of statements, e.g. the parameter  should be length-prefixed and opaque OR implementation defined OR "varint delimited". Frankly I have no idea what to do here. In case it should be opaque the follow-up question is then of course how the string representation should look?

**Comment by whereistejas** [comment]
Hi @tomaka, I would like to take up the work for this issue, if possible. Could you share a few more details like which part of the codebase I should start with?

**Comment by tomaka** [comment]
Hi,

I'm tempted to close the issue. `/memory` addresses are inherently implementation-specific. It's not wrong for an implementation to only produce numbers (like we're doing now). The spec simply gives the possibility to return something else than numbers.
