### ISSUE TITLE
[kad] RecordsStore trait should be async

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#1159]
Getting or writing a record should be able to not happen immediately.

**Comment by montekki** [comment]
We should probably create a to-do list (meta) issue tracking all needed improvements for records

**Comment by tomaka** [comment]
@montekki Note that you don't have to handle this yourself (unless you need it).

**Comment by thomaseizinger** [comment]
Closed in favor of https://github.com/libp2p/rust-libp2p/issues/3035.
