### ISSUE TITLE
libp2p_websockets::Error doesn't implement Sync

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#1162]

**Comment by twittner** [comment]
Which error are you referring to exactly? AFAICS [`libp2p_websocket::error::Error`](https://docs.rs/libp2p-websocket/0.9.0/libp2p_websocket/error/enum.Error.html) is `Send` and so is [`libp2p_websocket::tls::Error`](https://docs.rs/libp2p-websocket/0.9.0/libp2p_websocket/tls/enum.Error.html).

**Comment by tomaka** [comment]
I see, I misread `Send` as `Sync`.
I'm trying to pass the error to `io::Error::new`, but it unfortunately requires `Sync`: https://doc.rust-lang.org/nightly/std/io/struct.Error.html#method.new

We might close this as "wontfix" though.
