### ISSUE TITLE
Kad query continues beyond sufficient results?

### ISSUE THREAD

**Issue by AgeManning** [libp2p/rust-libp2p#1163]
I've been going through the kad implementation. 

This line seems odd to me:
https://github.com/libp2p/rust-libp2p/blob/master/protocols/kad/src/query.rs#L333

After the query has terminated: consecutive responses return no closer peers and either no new peers were discovered or we found enough peers required for the query, the state becomes frozen. 

The above line, seems to further contact `NotContacted` peers after the frozen state. Is this intended?

**Comment by romanb** [comment]
> I've been going through the kad implementation.
> 
> This line seems odd to me:
> https://github.com/libp2p/rust-libp2p/blob/master/protocols/kad/src/query.rs#L333
> 
> After the query has terminated: consecutive responses return no closer peers and either no new peers were discovered or we found enough peers required for the query, the state becomes frozen.

That is misleading. `Frozen` isn't really supposed to realize a termination condition. It just marks a point in the execution where progress seems to have stalled and I suppose the original intention was to then just make sure we complete the query by contacting all not-yet-contacted peers.

As far as I understand, there are really only supposed to be two termination conditions for a query: 1) All the currently `num_results` closest peers have been successfully contacted, or 2) There are no more peers to contact, despite not yet having reached `num_results` successfully contacted peers. To that end, the termination conditions and in particular the `Frozen` state have been reworked in https://github.com/libp2p/rust-libp2p/pull/1154. `libp2p-kad` is still undergoing many changes.

**Comment by AgeManning** [comment]
Yep thanks. Seems the linked PR addresses a number of changes.
