### ISSUE TITLE
[Question] Supporting multiple protocol-ids

### ISSUE THREAD

**Issue by AgeManning** [libp2p/rust-libp2p#1190]
Consider a protocol with multiple encodings/versions. The streams are segregated by their protocol id's, say `protocol1/encoding1` and `protocol1/encoding2`. 

Although I can negotiate both through mulitstream-select by supporting both id's in `UpgradeInfo::protocol_info()` I cannot easily determine which connected stream came from which Id. 

What is the best way to support multiple encodings/versions for a single protocol/behaviour?

**Comment by tomaka** [comment]
The selected protocol is passed as a parameter to `upgrade_inbound`/`upgrade_outbound`, and you can then do different things based on that.

I don't think there's an example to show you unfortunately.

**Comment by AgeManning** [comment]
Yep that's fine. This is what I was chasing. Thanks.

On a semi-related note. Assuming a simple `protocols_handler` like `OneShot`. All outbound/inbound messages get negotiated through the `upgrade_inbound`/`outbound` to form substreams. In this process `multistream_select` selects the protocol and applies the upgrade. Therefore all messages are going through the `multistream_select` process before forming streams, right?

If this is correct, would it be true that there would be no overhead in building an RPC protocol which uses protocol-id's to segregate message types. An example would be protocol-id's like `/kad/find_node` and `/kad/find_value`.  If `multistream-select` is being called on each message anyway, why not use it to also distinguish rpc message types? Is my understanding correct?

**Comment by tomaka** [comment]
You are correct. One protocol per RPC message is definitely a possibility.

However to me it only makes sense to have multiple different protocols in situations where nodes can support each of them individually.

We also want to be able to do things such as keeping in cache the list of protocols that the remote supports.

**Comment by AgeManning** [comment]
Perfect. Thanks for the quick reply :)
