### ISSUE TITLE
Mplex notifications are racy

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#1206]
Yamux should also be checked, cc @twittner 

The expected behaviour is:

- We try to read from the socket in an asynchronous way, passing a "notifier" object to it.
- If reading from the underlying socket is not ready, we add our local task to the "notifier" and return `NotReady`.
- Later, when data is ready the reader notifies everything.

However, if data happens to be ready between steps 1 and 2, then our local task won't wake up.

We also can't keep the mutex inside of the notifier locked while passing the notifier to the socket, because the socket might notify the current task on purpose (which would require locking the mutex and result in a deadlock).

The only solution that I can see is adding the local task to the notifier all the time.

**Comment by romanb** [comment]
I think this is the issue that was addressed in https://github.com/paritytech/yamux/pull/54.

**Comment by romanb** [comment]
Fixed in https://github.com/libp2p/rust-libp2p/pull/1210.
