### ISSUE TITLE
Implement /plaintext/2.0.0

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#1208]
https://github.com/libp2p/specs/pull/186

**Comment by burdges** [comment]
Do we actually need this for anything?

**Comment by tomaka** [comment]
No.

**Comment by tomaka** [comment]
> Do we actually need this for anything?

This would be useful for the C++ implementation of libp2p to be able to connect to our nodes for testing purposes, without forcing them to implement secio.

**Comment by ackintosh** [comment]
Hi, I'm interested in this issue. ✨  Will tackle to this.
