### ISSUE TITLE
[Question] Plans to implement compression?

### ISSUE THREAD

**Issue by AgeManning** [libp2p/rust-libp2p#1209]
Are there any plans to implement compression on a transport?

We are likely going to build this, which should be pretty easy. Looks like we would use snappy. Is this something that you'd want in the rust-libp2p library?

**Comment by tomaka** [comment]
Sure. Please note that there's already `libp2p-deflate`, though.

However, I'm not an expert, but I've been told that compression wouldn't be very useful without a pre-shared table.

**Comment by AgeManning** [comment]
That's interesting. What kind of pre-shard table are you imagining?

I'm basing it off this: https://eips.ethereum.org/EIPS/eip-706
Which seemed to work for DEVp2p.
