### ISSUE TITLE
Change `ListenerEvent::Upgrade` to use the local address.

### ISSUE THREAD

**Issue by twittner** [libp2p/rust-libp2p#1221]
The current [`ListenerEvent::Upgrade`](https://github.com/libp2p/rust-libp2p/blob/5696b3eb4d285d1e6125f2cefbea130720a6b06e/core/src/transport/mod.rs#L241-L247) includes the remote address of the upgrade and the listen address. Since figuring out the listen address of an incoming connection is [more complicated](https://github.com/libp2p/rust-libp2p/pull/1132) and [fragile](https://github.com/paritytech/substrate/issues/3352) than perhaps initially thought, I would suggest we follow [this suggestion](https://github.com/libp2p/rust-libp2p/pull/1132#issuecomment-497664270) and replace the listen address with the local address of the incoming connection.

This would also mean changing [`ListenersEvent::Incoming`](https://github.com/libp2p/rust-libp2p/blob/5696b3eb4d285d1e6125f2cefbea130720a6b06e/core/src/nodes/listeners.rs#L117-L123) accordingly but, if https://github.com/libp2p/rust-libp2p/pull/1218 is merged, the newly added [`ListenerId`](https://github.com/libp2p/rust-libp2p/pull/1218/files#diff-934ec958acb4de656c28ea2d84af7aceR137) provides as better means to correlate the upgrade with the listener that produced it.

**Comment by tomaka** [comment]
You've got to love the robustness of operating systems.

I agree with the suggestion. As a precedent, we already pass `0.0.0.0` to signify "all interfaces". This means that when it comes to listening, multiaddresses are already more of a hint about what we accept rather than a precise value.
