### ISSUE TITLE
mdns peer discovery is not compliant to latest specification

### ISSUE THREAD

**Issue by shresthagrawal** [libp2p/rust-libp2p#1232]
> If the encoding of the peer's ID exceeds 63 characters, then the Split at 63rd character workaround can be used.  

The [specs](https://github.com/libp2p/specs/blob/master/discovery/mdns.md) for encoding PeerID greater than 63 character requires to perform split and join with a '.' but the current [implementation](https://github.com/libp2p/rust-libp2p/blob/master/misc/mdns/src/dns.rs#L128) doesn't handle such condition!

**Comment by tomaka** [comment]
Done in #1287 I believe.
