### ISSUE TITLE
Don't use a thread pool for DNS resolution

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#1235]
Right now, we use a thread pool dedicated to resolving domain names by calling `to_socket_addrs`. Theoretically, there's no reason for it not to be asynchronous.

In practice, as far as I know, there's no way to do at at the moment. However I'm opening this issue anyway in order to not forget about that in the long term.

**Comment by mxinden** [comment]
Do I understand correctly that *tokio-dns-unofficial* uses the host OS's resolver via a thread pool?

In that case I find the name of the issue a bit misleading. How about "Don't use synchronous host OS's dns resolver via thread pool"?

#### Async in process dns resolution

In case an in-process DNS async resolver adhering to `/etc/resolv.conf` is an option, how about [trust dns resolver](https://docs.rs/trust-dns-resolver/0.12.0/trust_dns_resolver/)?

#### Async OS dns resolution

Or in case we mostly target Linux and fall back to synchronous DNS resolution, something like [`getaddrinfo_a`](http://man7.org/linux/man-pages/man3/getaddrinfo_a.3.html) could be an option.

What do you think @tomaka?

**Comment by tomaka** [comment]
I think that we shouldn't waste any energy on that issue, at least not before async/await.

**Comment by tomaka** [comment]
For what it's worth, async-std decided to use background tasks: https://github.com/async-rs/async-std/pull/74

**Comment by DemiMarie** [comment]
I think we could use either trust-dns or libasr.  The latter is a C library, but it comes from OpenBSD and is used in OpenSMTPD among other projects, so I am quite confident in its security.
