### ISSUE TITLE
Add a way to limit the number of active connections

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#1239]
We currently have no way to limit the number of active connections. In the case of TCP/IP, this can be bad, as the available resources are limited.

I think the system should be in the `Swarm`, as the main objective of a limit here is to prevent DoS attacks.

**Comment by twittner** [comment]
Related: https://github.com/libp2p/rust-libp2p/issues/997.

**Comment by tomaka** [comment]
I think #997 should be done on the transport level, because you only need to limit outgoing TCP connections, and not, for example Unix domain sockets or Bluetooth connections.

Maybe this issue should actually be on the transport level as well. If anything, that would make for a more elegant design.

**Comment by tomaka** [comment]
I had not realized that this was already done :man_facepalming: https://docs.rs/libp2p-core/0.12.0/libp2p_core/nodes/network/struct.Network.html#method.incoming_limit

**Comment by tomaka** [comment]
Although no, that's only for incoming connections. We need a limit for both.

**Comment by romanb** [comment]
`libp2p-core` now has a configurable limit for both the total number of concurrent incoming as well as outgoing connections, but not for the total number of _established_ connections (that would be easy to add though). The reason I did not add such a limit initially is that, compared to the other limits, constraining the total number of connections to prevent excessive resource usage or DoS, as mentioned in the issue description, can always be done effectively at the level of the OS and process limits (e.g. `ulimit`s), though such limits are less fine-grained and at the level of file descriptors / open files. I'm not opposed to adding such a configurable limit to `libp2p-core` itself, however, if it seems useful. Note that `libp2p-core` already has a configurable limit for the number of established connections _per peer_. Also note that, as also mentioned in https://github.com/libp2p/rust-libp2p/issues/997#issuecomment-602711690, the limits in `libp2p-core` for pending incoming or outgoing connections are not strict "rate limits", though they certainly have an indirect effect on the rate at which connections can be established, depending on how quickly connections are negotiated.

**Comment by romanb** [comment]
Should be resolved as of https://github.com/libp2p/rust-libp2p/pull/1848.
