### ISSUE TITLE
multistream-select interoperability issue with JS

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#1241]
When js-libp2p connects to a listener, it starts by sending out `/multistream-select/1.0.0`, then waits for the remote to send back `/multistream-select/1.0.0`, then only sends out the requested protocol.

However, the rust-libp2p listener reads `/multistream-select/1.0.0`, then sends out `/multistream-select/1.0.0`, but doesn't immediately flush that to the TCP socket. It only flushes after having sent back an answer to the requested protocol.

cc @raulk @romanb

**Comment by tomaka** [comment]
The buffering seems to be happening here: https://github.com/libp2p/rust-libp2p/blob/c0b379b908a2f1f622cd205c6890a520bc8f5949/misc/multistream-select/src/length_delimited.rs#L252

Calling `start_send` only pushes data to a buffer without sending it out immediately.

**Comment by romanb** [comment]
This was done intentionally in https://github.com/libp2p/rust-libp2p/pull/1212 - However, if js-libp2p behaves this way and generally it is unfortunately not a requirement of the multistream-select 1.0 spec to send the multistream header together with the first multistream-select request (typically a protocol proposal), there is probably no other option than to immediately flush the multistream-select response header on the listener's side in rust-libp2p. :man_shrugging:

**Comment by romanb** [comment]
@tomaka If you would want to change that, it is only a matter of changing [this line](https://github.com/libp2p/rust-libp2p/blob/master/misc/multistream-select/src/listener_select.rs#L139) to

```rust
self.state = State::Flush { io };
```

`Flush` then transitions to `RecvMessage`.

**Comment by raulk** [comment]
cc @AgeManning

**Comment by romanb** [comment]
Closed by https://github.com/libp2p/rust-libp2p/pull/1245.
