### ISSUE TITLE
[secio] Possible inconsistency between Rust and Go implementations

### ISSUE THREAD

**Issue by michaelvoronov** [libp2p/rust-libp2p#1242]
Hi, guys!

I have found that Go libp2p SECIO implementation uses Go-based AES-CTR mode and Rust uses `aes_ctr` crate for AES-CTR. They have one inconsistency in CTR counter: Go is based (63th row [here](https://golang.org/src/crypto/cipher/ctr.go)) on full 128-bit counter, while `aes_ctr` uses only 64-bit counter and other 64-bits are left immutable (more info [here](https://github.com/RustCrypto/stream-ciphers/issues/12)).

So, very-very rarely when all 64 bit lowest bit are set they could be out of sync. And it could be really painfull for debugging...

**Comment by romanb** [comment]
With the deprecation of SECIO, this is no longer going to be addressed.
