### ISSUE TITLE
[yamux::connection] 9d9580be: 19: buffer of stream grows beyond limit            

### ISSUE THREAD

**Issue by rtsisyk** [libp2p/rust-libp2p#1257]
## Description of problem

I have troubles with implementing basic Producer-Consumer. Yamux resets connection when the input buffer is full on the consumer side.

## Version

libp2p = "0.12.0" with yamux

## How reproducible

1. Create a substream. 
2. Start sending data to the substream until AsynkSink is NotReady().
3. Remote peer will reset the connection:

```
[yamux::connection] 9d9580be: 19: buffer of stream grows beyond limit       
```

## Steps to Reproduce

1. I created a custom protocol which uses Framed codec for messages.

```
impl<TSubstream> ProtocolsHandler for ReplicationHandler<TSubstream>
where
    TSubstream: AsyncRead + AsyncWrite + Send,
{
```

2.  This protocol negotiates just one substream per each peer, i.e. each ProtocolsHandler has exactly one substream:

```
  fn poll(
        &mut self,
    ) -> Poll<
        ProtocolsHandlerEvent<Self::OutboundProtocol, Self::OutboundOpenInfo, Self::OutEvent>,
        io::Error,
    > {

           // [Skipped]

            // Create a new substream if it doesn't exists.
            if self.is_consumer() && self.rx.is_none() {
                /// Request a new stream.
                return Ok(Async::Ready(
                   ProtocolsHandlerEvent::OutboundSubstreamRequest {
                       info: (),
                       protocol: SubstreamProtocol::new(self.config.clone()),
                   },
                ));
           }

           // [Skipped, see below]        
    }

   // [Skipped]

    /// Called when a new substream is negotiated.
    fn inject_fully_negotiated_outbound(
        &mut self,
        protocol: <Self::OutboundProtocol as OutboundUpgrade<TSubstream>>::Output,
        _open_info: Self::OutboundOpenInfo,
    ) {
        // Save created substream.
        let (rx, tx) = protocol.split();
        self.rx = Some(rx); // Save Stream
        self.tx = Some(tx); // Save Sink.
    }

   // [Skipped]
}
```

3. Producer produces events until the sink is full:

```
impl<TSubstream> ProtocolsHandler for ReplicationHandler<TSubstream>
where
    TSubstream: AsyncRead + AsyncWrite + Send,
{

    fn poll(
        &mut self,
    ) -> Poll<
        ProtocolsHandlerEvent<Self::OutboundProtocol, Self::OutboundOpenInfo, Self::OutEvent>,
        io::Error,
    > {
        trace!("Poll");
          
           // [Skipped]

            // Generate events until sink is full.
            if let Some(tx) = &mut self.tx {
                loop {
                       let message: Vec<u8> = self.generate_event();
                        info!("Produced: {:?}", message);
                        match tx.start_send(message) {
                            Ok(AsyncSink::Ready) => {
                                  // The sink is not full, continue producing messages.
                                  trace!("Ready"); 
                              }
                             Ok(AsyncSink::NotReady(_response)) => {
                                  /// The sink is full, pause the production.
                                  trace!("Not ready");
                                 break;
                             }
                              Err(e) => {
                                 panic!("Error: {:?}", e);
                              }
                        }
                  }
              }
         }

        // Flushthe sink.
        if let Err(e) = self.tx.poll_complete() {
               panic!("Skipped");
        }
}
```

4. Consumer reads incoming messages from the stream:

```
      info!("Poll");
      loop {
                match rx.poll().unwrap() {
                    Async::Ready(Some(message)) => {
                        info!("Consume: {:?}", message);
                    }
                    Async::Ready(None) => {
                        info!("EOF");
                        self.rx = None;
                        self.tx = None;
                        return Ok(Async::NotReady);
                    }
                    Async::NotReady => {
                        break; 
                   }
                }
      }
```

I intentionally simplified the code above and kept only important parts.

## Actual results

Producer:

```
Produced: a
Produced: b
Produced: c
Produced: d
Produced: e
Produced: f
Produced: g
Produced: h
Panic: Custom { kind: WriteZero, error: "stream is closed" }
```

Consumer:

```
Poll
Poll
[yamux::connection] 9d9580be: 19: buffer of stream grows beyond limit
```

yamux on the consumer side closes the connection when the input buffer is full.

## Expected results

I expect that libp2p/yamux should stop reading the input stream on the consumer's side if the input buffer is full. If the consumer is slow, yamux should reduce the window size to slow down the producer. In this case, the producer will see AsynkSink::NotReady more othen and it should slow down the production. As a result, the entire system should synchronize.

## Additional info

I found the relevant part of code in yamux:

```
https://github.com/paritytech/yamux/blob/master/src/connection.rs#L458-L472
```

The first condition is weird: "if the input buffer is full, just reset the input stream and send EOF to the remote peer". Seriously? If your input buffer is full - please don't read the socket (and don't forget to shrink the window size)! Can't consume? Don't read! Why closing the stream? If you just RST the connection when you can't consume - that means that you just don't have working flow control. The flow control is the fundamental property of the stream. Without flow control streams in libp2p are just like some kind of loss-less UDP.

Let me show you an analogy from TCP/IP via BSDSOCKETS world:

**Producer:**

1. Try to write(2) to `fd` in a loop until EAGAIN is returned.
2. When EAGAIN is returned, the producer should try to call select(2)/poll(2)/epoll(2) and wait until `fd` is read for WRITE.
3. GOTO 1

**Consumer**:

1. Try to read(2) from `fd` in a loop until EAGAIN is returned.
2. When EAGAIN is returmed, the producer should try to call  call select(2)/poll(2)/epoll(2) and wait until `fd` is read for READ.
3. GOTO 1.

If the consumer is slow and can't consume all messages on time, it should stop reading the socket. In this case his network stack will shrink TCP Window size. Thus, it will affect the producer side. The producer's network stack will flush the output buffer less often. As result, write(2) will return EAGAIN after consuming fewer data. The production will slow down too. Bingo!

I simplified the all things, but I hope that you have got the idea. All parts of this system ARE synchronized. If the consumer is not fast enough, the producer will slow down production too. 

Now replace `write(2)` with `start_send()` and `EAGAIN` with `AsyncSink::NotReady` and you will get the same code I posted above on tokio/libp2p stack. Unfortunately, that doesn't work.

In tokio/yamux/libp2p we have a TCP connection between peers. On the top of this TCP connection yamux implements TCP-like substreams. Yes, an imitation of TCP over the real TCP. Why not? We have nothing else to do, let's invent the TCP/IP again. Anyway, it's Hashicorp, you know. But why RST is sent when the input buffer is full? Why?

I also noted that libp2p/floodsub creates a new substream per each messages. Yes, a new substream is created for each message. I could expect one substream per topic, but not per message. In this case we have SOCK_DGRAM (=floodsub with temporary substreams) over SOCK_STREAM (yamux imitation of TCP) over SOCK_STREAM (real TCP). It is crazy, isn't it?

Any thoughts?

**Comment by twittner** [comment]
Have you seen https://docs.rs/yamux/0.2.1/yamux/enum.WindowUpdateMode.html? It seems that for your use-case `WindowMode::OnRead` might be more appropriate.

**Comment by rtsisyk** [comment]
> This ensures that senders do not overwhelm receivers and keeps buffer usage low. However, depending on the protocol, there is a risk of deadlock, namely if both endpoints want to send data larger than the receivers window and they do not read before finishing their writes. Use this mode only if you are sure that this will never happen, i.e. if
>
>    Endpoints A and B never write at the same time, or
>   Endpoints A and B write at most n frames concurrently such that the sum of the frame lengths is less or equal to the available credit of A and B respectively.

> "A and B never write at the same time".

 This is a socket, not a pipe. Both sides can write at the same time. Requested conditions can't be archived.

Anyway, how does this flag help to fix this bug:

https://github.com/paritytech/yamux/blob/master/src/connection.rs#L458-L472:

```
                if stream.buffer.lock().len().map(move |n| n >= max_buffer_size).unwrap_or(true) {
                    error!("{}: {}: buffer of stream grows beyond limit", self.id, stream_id);
                    self.reset(stream_id)?;
                    return Ok(None)
                }
```

Here Yamix returns EOF instead of stoping reading this stream, But, wait a miniute. Houston, we have a problem here. Yamux can't read streams selectively because ... there is a real  TCP SOCK_STREAM under the hood. You can't read SOCK_STREAM selectively. Surprise! There is no way to control the flow of each specific stream. You need SOCK_DGRAM of raw packets to do that instead of SOCK_STREAM. Looks like this idea with multiple TCP-like streams with custom flow control in each stream is just broken by design.  Please correct me if I'm wrong.

**Comment by twittner** [comment]
> This is a socket, not a pipe. Both sides can write at the same time. Requested conditions can't be archived.

It is not forbidden to write at the same time but as mentioned there are constraints w.r.t. to the amount of data they can write concurrently without reading.

> Anyway, how does this flag help to fix this [...]

Producers are only allowed to send when they have sufficient credit. Assuming default settings, the window size will be 256 KiB and the max. buffer size 1 MiB. When the producer has sent 256 KiB (consuming all its available credit), it has to wait for the consumer to grant additional credit before being able to proceed. With `WindowUpdateMode::OnRead`, this will only happen when the consumer has read the data from the buffer whose size therefore does not exceed 256 KiB, lower than the max. size of 1 MiB. The configured `max_buffer_size` is only a safety net to prevent unbounded resource use.

**Comment by rtsisyk** [comment]
> Producers are only allowed to send when they have sufficient credit. Assuming default settings, the window size will be 256 KiB and the max. buffer size 1 MiB. When the producer has sent 256 KiB (consuming all its available credit), it has to wait for the consumer to grant additional credit before being able to proceed. With WindowUpdateMode::OnRead, this will only happen when the consumer has read the data from the buffer whose size therefore does not exceed 256 KiB, lower than the max. size of 1 MiB. The configured max_buffer_size is only a safety net to prevent unbounded resource use.

This approach should work. I will try to change WindowUpdateMode to OnRead and test on my environment. Thanks a lot!

**Comment by rtsisyk** [comment]
Ok, OnRead more or less works for me. At least it doesn't disconnect on the start. I will test it on the real network on the next week and post an update here.

**Comment by rtsisyk** [comment]
I'm back with the results.

First of all, I can confirm @twittner words that `yamux` can't send payloads whose size exceeds the default window size (256 KiB). In my protocol the average size of each packet is about 100KiB, which makes the default window size (256KiB) is completely non-starter for me. I experimented with various values of window_size/buffer_size: starting from 1Mb up to 100MiB (on both sides). Unfortunately, yamux can't utilize more than 10Mbit even on the loopback interface on Linux. On the real networks  yamux's results are even more worse. I'm talking aboutWindowUpdateMode::OnRead here. WindowUpdateMode::OnReceive just doesn't work at all.

As result, I've switched to `mplex.` I have to say that  `mplex` is more straightforward than `yamux`. No SYN/RST, no TCP Windows and just ~400 lines of code. With set MaxBufferBehaviour::Block, `mplex` blocks the underlying TCP connection if the input buffer is full. TCP does his job after that.
Exactly like I proposed in the my first comment. And it can utilize my network almost fully.

My conclusion is:

- `yamux` is just broken by design. Not this particular implementation in Rust, but the entire idea of emulation TCP over TCP was initially overengineered. This approach doesn't work for real life. If you want to utilize more than 10Mbit - please just forget about `yamux` and use `mplex`.
- `mplex` is pretty simple and straightforward multiplexer. `mplex` overhead is close to zero. `mplex` doesn't try to re-invent the wheel and just use TCP to implement the flow control. `mplex` can utilize the network connection fully without any special tuning of buffers.

Thanks for the help!
