### ISSUE TITLE
could not compile `libp2p-core`

### ISSUE THREAD

**Issue by Tore19** [libp2p/rust-libp2p#1259]
1, git clone https://github.com/libp2p/rust-libp2p.git
2, cd rust-libp2p/core
3, cargo build

  Compiling libp2p-core v0.12.0 (/Users/zhangtong/work/project/rust/rust-libp2p/core)
error[E0433]: failed to resolve: could not find `types` in `protobuf`
   --> core/src/keys_proto.rs:188:98
    |
188 |                 fields.push(::protobuf::reflect::accessor::make_option_accessor::<_, ::protobuf::types::ProtobufTypeEnum<KeyType>>(
    |                                                                                                  ^^^^^ could not find `types` in `protobuf`

error[E0433]: failed to resolve: could not find `types` in `protobuf`
   --> core/src/keys_proto.rs:193:106
    |
193 |                 fields.push(::protobuf::reflect::accessor::make_singular_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
    |                                                                                                          ^^^^^ could not find `types` in `protobuf`

error[E0407]: method `as_ref` is not a member of trait `protobuf::reflect::ProtobufValue`
   --> core/src/keys_proto.rs:233:5
    |
233 | /     fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef<'_> {
234 | |         ::protobuf::reflect::ProtobufValueRef::Message(self)
235 | |     }
    | |_____^ not a member of trait `protobuf::reflect::ProtobufValue`

error[E0433]: failed to resolve: could not find `types` in `protobuf`
   --> core/src/keys_proto.rs:402:98
    |
402 |                 fields.push(::protobuf::reflect::accessor::make_option_accessor::<_, ::protobuf::types::ProtobufTypeEnum<KeyType>>(
    |                                                                                                  ^^^^^ could not find `types` in `protobuf`

error[E0433]: failed to resolve: could not find `types` in `protobuf`
   --> core/src/keys_proto.rs:407:106
    |
407 |                 fields.push(::protobuf::reflect::accessor::make_singular_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
    |                                                                                                          ^^^^^ could not find `types` in `protobuf`

error[E0407]: method `as_ref` is not a member of trait `protobuf::reflect::ProtobufValue`
   --> core/src/keys_proto.rs:447:5
    |
447 | /     fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef<'_> {
448 | |         ::protobuf::reflect::ProtobufValueRef::Message(self)
449 | |     }
    | |_____^ not a member of trait `protobuf::reflect::ProtobufValue`

error[E0407]: method `as_ref` is not a member of trait `protobuf::reflect::ProtobufValue`
   --> core/src/keys_proto.rs:505:5
    |
505 | /     fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef<'_> {
506 | |         ::protobuf::reflect::ProtobufValueRef::Enum(self.descriptor())
507 | |     }
    | |_____^ not a member of trait `protobuf::reflect::ProtobufValue`

error[E0425]: cannot find value `ONCE_INIT` in module `protobuf::lazy`
   --> core/src/keys_proto.rs:182:37
    |
182 |             lock: ::protobuf::lazy::ONCE_INIT,
    |                                     ^^^^^^^^^ not found in `protobuf::lazy`
help: possible candidates are found in other modules, you can import them into scope
    |
21  | use lazy_static::lazy::ONCE_INIT;
    |
21  | use std::sync::ONCE_INIT;
    |

error[E0425]: cannot find function `make_option_accessor` in `protobuf::reflect::accessor`
   --> core/src/keys_proto.rs:188:60
    |
188 |                 fields.push(::protobuf::reflect::accessor::make_option_accessor::<_, ::protobuf::types::ProtobufTypeEnum<KeyType>>(
    |                                                            ^^^^^^^^^^^^^^^^^^^^ not found in `protobuf::reflect::accessor`
help: possible candidate is found in another module, you can import it into scope
    |
21  | use protobuf::reflect::rt::make_option_accessor;
    |

error[E0425]: cannot find function `make_singular_field_accessor` in `protobuf::reflect::accessor`
   --> core/src/keys_proto.rs:193:60
    |
193 |                 fields.push(::protobuf::reflect::accessor::make_singular_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
    |                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `protobuf::reflect::accessor`

error[E0425]: cannot find value `ONCE_INIT` in module `protobuf::lazy`
   --> core/src/keys_proto.rs:209:37
    |
209 |             lock: ::protobuf::lazy::ONCE_INIT,
    |                                     ^^^^^^^^^ not found in `protobuf::lazy`
help: possible candidates are found in other modules, you can import them into scope
    |
21  | use lazy_static::lazy::ONCE_INIT;
    |
21  | use std::sync::ONCE_INIT;
    |

error[E0425]: cannot find value `ONCE_INIT` in module `protobuf::lazy`
   --> core/src/keys_proto.rs:396:37
    |
396 |             lock: ::protobuf::lazy::ONCE_INIT,
    |                                     ^^^^^^^^^ not found in `protobuf::lazy`
help: possible candidates are found in other modules, you can import them into scope
    |
21  | use lazy_static::lazy::ONCE_INIT;
    |
21  | use std::sync::ONCE_INIT;
    |

error[E0425]: cannot find function `make_option_accessor` in `protobuf::reflect::accessor`
   --> core/src/keys_proto.rs:402:60
    |
402 |                 fields.push(::protobuf::reflect::accessor::make_option_accessor::<_, ::protobuf::types::ProtobufTypeEnum<KeyType>>(
    |                                                            ^^^^^^^^^^^^^^^^^^^^ not found in `protobuf::reflect::accessor`
help: possible candidate is found in another module, you can import it into scope
    |
21  | use protobuf::reflect::rt::make_option_accessor;
    |

error[E0425]: cannot find function `make_singular_field_accessor` in `protobuf::reflect::accessor`
   --> core/src/keys_proto.rs:407:60
    |
407 |                 fields.push(::protobuf::reflect::accessor::make_singular_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
    |                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `protobuf::reflect::accessor`

error[E0425]: cannot find value `ONCE_INIT` in module `protobuf::lazy`
   --> core/src/keys_proto.rs:423:37
    |
423 |             lock: ::protobuf::lazy::ONCE_INIT,
    |                                     ^^^^^^^^^ not found in `protobuf::lazy`
help: possible candidates are found in other modules, you can import them into scope
    |
21  | use lazy_static::lazy::ONCE_INIT;
    |
21  | use std::sync::ONCE_INIT;
    |

error[E0425]: cannot find value `ONCE_INIT` in module `protobuf::lazy`
   --> core/src/keys_proto.rs:484:37
    |
484 |             lock: ::protobuf::lazy::ONCE_INIT,
    |                                     ^^^^^^^^^ not found in `protobuf::lazy`
help: possible candidates are found in other modules, you can import them into scope
    |
21  | use lazy_static::lazy::ONCE_INIT;
    |
21  | use std::sync::ONCE_INIT;
    |

error[E0425]: cannot find value `ONCE_INIT` in module `protobuf::lazy`
   --> core/src/keys_proto.rs:543:29
    |
543 |     lock: ::protobuf::lazy::ONCE_INIT,
    |                             ^^^^^^^^^ not found in `protobuf::lazy`
help: possible candidates are found in other modules, you can import them into scope
    |
21  | use lazy_static::lazy::ONCE_INIT;
    |
21  | use std::sync::ONCE_INIT;
    |

error[E0603]: module `accessor` is private
   --> core/src/keys_proto.rs:188:50
    |
188 |                 fields.push(::protobuf::reflect::accessor::make_option_accessor::<_, ::protobuf::types::ProtobufTypeEnum<KeyType>>(
    |                                                  ^^^^^^^^

error[E0603]: module `accessor` is private
   --> core/src/keys_proto.rs:193:50
    |
193 |                 fields.push(::protobuf::reflect::accessor::make_singular_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
    |                                                  ^^^^^^^^

error[E0603]: module `accessor` is private
   --> core/src/keys_proto.rs:402:50
    |
402 |                 fields.push(::protobuf::reflect::accessor::make_option_accessor::<_, ::protobuf::types::ProtobufTypeEnum<KeyType>>(
    |                                                  ^^^^^^^^

error[E0603]: module `accessor` is private
   --> core/src/keys_proto.rs:407:50
    |
407 |                 fields.push(::protobuf::reflect::accessor::make_singular_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
    |                                                  ^^^^^^^^

warning: use of deprecated item 'bs58::decode::DecodeError': Use `bs58::decode::Error` instead
   --> core/src/peer_id.rs:222:16
    |
222 |         B58(e: bs58::decode::DecodeError) {
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: `#[warn(deprecated)]` on by default

warning: use of deprecated item 'bs58::decode::DecodeError': Use `bs58::decode::Error` instead
   --> core/src/peer_id.rs:222:16
    |
222 |         B58(e: bs58::decode::DecodeError) {
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0308]: mismatched types
   --> core/src/keys_proto.rs:183:18
    |
183 |             ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `std::cell::UnsafeCell`, found *-ptr
    |
    = note: expected type `std::cell::UnsafeCell<*const protobuf::reflect::message::MessageDescriptor>`
               found type `*const protobuf::reflect::message::MessageDescriptor`

error[E0308]: mismatched types
   --> core/src/keys_proto.rs:210:18
    |
210 |             ptr: 0 as *const PublicKey,
    |                  ^^^^^^^^^^^^^^^^^^^^^ expected struct `std::cell::UnsafeCell`, found *-ptr
    |
    = note: expected type `std::cell::UnsafeCell<*const keys_proto::PublicKey>`
               found type `*const keys_proto::PublicKey`

error[E0308]: mismatched types
   --> core/src/keys_proto.rs:397:18
    |
397 |             ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `std::cell::UnsafeCell`, found *-ptr
    |
    = note: expected type `std::cell::UnsafeCell<*const protobuf::reflect::message::MessageDescriptor>`
               found type `*const protobuf::reflect::message::MessageDescriptor`

error[E0308]: mismatched types
   --> core/src/keys_proto.rs:424:18
    |
424 |             ptr: 0 as *const PrivateKey,
    |                  ^^^^^^^^^^^^^^^^^^^^^^ expected struct `std::cell::UnsafeCell`, found *-ptr
    |
    = note: expected type `std::cell::UnsafeCell<*const keys_proto::PrivateKey>`
               found type `*const keys_proto::PrivateKey`

error[E0308]: mismatched types
   --> core/src/keys_proto.rs:485:18
    |
485 |             ptr: 0 as *const ::protobuf::reflect::EnumDescriptor,
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `std::cell::UnsafeCell`, found *-ptr
    |
    = note: expected type `std::cell::UnsafeCell<*const protobuf::reflect::enums::EnumDescriptor>`
               found type `*const protobuf::reflect::enums::EnumDescriptor`

error[E0308]: mismatched types
   --> core/src/keys_proto.rs:544:10
    |
544 |     ptr: 0 as *const ::protobuf::descriptor::FileDescriptorProto,
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `std::cell::UnsafeCell`, found *-ptr
    |
    = note: expected type `std::cell::UnsafeCell<*const protobuf::descriptor::FileDescriptorProto>`
               found type `*const protobuf::descriptor::FileDescriptorProto`

error[E0283]: type annotations needed: cannot resolve `_: protobuf::enums::ProtobufEnum`
   --> core/src/keys_proto.rs:489:17
    |
489 |                 ::protobuf::reflect::EnumDescriptor::new("KeyType", file_descriptor_proto())
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
   ::: /Users/zhangtong/.cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-2.9.0/src/reflect/enums.rs:139:19
    |
139 |     pub fn new<E: ProtobufEnum>(
    |                   ------------ required by this bound in `protobuf::reflect::enums::EnumDescriptor::new`

error[E0061]: this function takes 2 parameters but 1 parameter was supplied
   --> core/src/keys_proto.rs:506:9
    |
506 |         ::protobuf::reflect::ProtobufValueRef::Enum(self.descriptor())
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 2 parameters

error: aborting due to 29 previous errors

Some errors have detailed explanations: E0061, E0283, E0308, E0407, E0425, E0433, E0603.
For more information about an error, try `rustc --explain E0061`.
error: could not compile `libp2p-core`.

**Comment by brenzi** [comment]
same issue here. since today. Friday was fine

**Comment by clangenb** [comment]
protobuf update to v2.9 is the issue

**Comment by brenzi** [comment]
temporary workaround: 
` cargo update -p protobuf --precise 2.8.1`

**Comment by mxinden** [comment]
Given that the *protobuf* `2.9` release was removed, I think this issue can be closed, right?

**Comment by brenzi** [comment]
agreed. works again for us now.
