### ISSUE TITLE
ed25519-dalek → ring

### ISSUE THREAD

**Issue by DemiMarie-parity** [libp2p/rust-libp2p#1262]
We already depend on _ring_ via rustls, so this will shrink our dependency graph.

**Comment by tomaka** [comment]
We're trying to switch away from `ring` if possible. If anything, it's `ring` that we should replace with something else.

**Comment by burdges** [comment]
See previous discussions: https://github.com/paritytech/substrate/pull/2415#issuecomment-536992830
