### ISSUE TITLE
Interest in dependency update PR?

### ISSUE THREAD

**Issue by rschulman** [libp2p/rust-libp2p#1264]
I've gone through and updated a bunch of older dependencies in `rust-libp2p` that were preventing it from compiling alongside [Rocket](https://rocket.rs) due to conflicts in the `ring` crate (among others potentially).

Is there any interest in having me open a PR for this update?

**Comment by tomaka** [comment]
Yes!

For what it's worth, we have a list of outdated dependencies pinned to the README (https://deps.rs/repo/github/libp2p/rust-libp2p).

**Comment by tomaka** [comment]
I'm a bit wary of changes that might conflict a lot with the `stable-futures` branch, but I don't think we should have any.

**Comment by rschulman** [comment]
Great. I'll open a PR and you can see what you think.

**Comment by rschulman** [comment]
Should have mentioned here: I opened #1265
