### ISSUE TITLE
Tests fail on systems with strict firewall rules

### ISSUE THREAD

**Issue by Demi-Marie** [libp2p/rust-libp2p#1270]
The multicast discovery test fails on my system due to (very) strict firewall rules.  Being able to send multicast traffic is not guaranteed, especially in virtualized environments.  We should probably skip it on such systems.

**Comment by tomaka** [comment]
What are you suggesting?
To "somehow" detect when the firewall rules are strict and skip the test? But how do you detect that?
To ignore the test if it doesn't work? But then there's no point in having this test.

**Comment by DemiMarie-parity** [comment]
On CI, the test should always run and be expected to pass.  However, it should probably be skipped (or allowed to fail) when running on a developer’s system, or when packaging.  In particular, many package build systems (such as Nix, IIRC) don’t allow the code being built access to the network, except perhaps loopback.  And I know that Debian will consider a build failed if the tests don’t pass.

**Comment by DemiMarie-parity** [comment]
I think the multicast discovery test should be gated by a Cargo feature and/or environment variable, and disabled by default.

**Comment by romanb** [comment]
Since I'm not sure which test(s) this ticket is still referring to and it is a bit dated, I'm closing this and suggest to open specific ticket(s) or PRs for the problematic test(s) in question.
