### ISSUE TITLE
Implement top-level Node or "Host"

### ISSUE THREAD

**Issue by folsen** [libp2p/rust-libp2p#13]
This is what brings it all together into a nice usable format.

See: https://github.com/libp2p/go-libp2p/tree/master/examples/libp2p-host

**Comment by diasdavid** [comment]
For this one, it is definitely better to take a page from the js-libp2p book instead of the go-libp2p book. 

In js-libp2p, a Node is a class that lets you instantiate libp2p Nodes with your own libp2p recipe. Read more at the README here https://github.com/libp2p/js-libp2p#bundles

**Comment by tomaka** [comment]
In the case of `rust-libp2p`, I guess that the host library would simply provide an implementation of the `Transport` trait (TCP+Secio+Multiplex+p2p-circuit in the future).

If it makes sense, this library could use conditional compilation to automatically use TCP on regular operating systems, and websockets on emscripten.

**Comment by tomaka** [comment]
I think that it makes sense to have a library that automatically uses TCP on desktop and websockets on emscripten, and handles making progress on futures (ie. wraps around tokio).

However if the only concern is usability, then I think that the libp2p-swarm library is already simple and clear enough.

**Comment by tomaka** [comment]
Let's close this issue.
