### ISSUE TITLE
Benchmarks do not compile

### ISSUE THREAD

**Issue by Demi-Marie** [libp2p/rust-libp2p#1310]
The benchmarks seem to have bitrotted.  They don’t build anymore, which breaks `cargo fix --all --edition-idioms`.

**Comment by tomaka** [comment]
Triage: this is still the case. Secio uses tokio 0.1 in the benches. We should also add a CI check for them.

**Comment by romanb** [comment]
I guess this was closed by https://github.com/libp2p/rust-libp2p/pull/1661.
