### ISSUE TITLE
IPFS nodes seem to ignore our nodes

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#133]
When we connect to an IPFS Go node, the remote opens three substreams but doesn't use them at all (doesn't send any data on them).

PR #120 allows one to make Kademlia requests to other nodes. I would expect that if we connect to a node through Kademlia, this node would want to get information about us.

Note that if two Rust nodes connect to one another, they will successfully identify each other through a substream. It's only when connecting to a Go node that things don't work.

I am not sure whether this behaviour from Go nodes is expected, or if it's a bug in our code.

cc @diasdavid @whyrusleeping

**Comment by diasdavid** [comment]
Thanks for opening this as a issue, @tomaka. @stebalien you probably know the reason to this problem.

**Comment by diasdavid** [comment]
@tomaka just remembered that go-ipfs gets stuck if Identify doesn't finish successfully. I learned that the hard way, notes here - https://github.com/libp2p/js-libp2p-switch/issues/78

**Comment by whyrusleeping** [comment]
@tomaka Yeah, the issue is likely that go waits for `Identify` to finish (arguably Identify should be privileged and happen inline somehow). Identify also works a little weird (we can talk about changing this moving forward) but it opens a stream to the remote peer, and waits for them to send back the requested information. So you should write your identify response back to the identify stream that go-libp2p opens to you.

**Comment by tomaka** [comment]
`Identify` is supposed to be properly implemented already (well, in #116).

However one thing we don't do is close substreams that we open, maybe that is the problem?
In other words. Let's say that A connects to B and opens a substream for `identify`. Will B wait for that substream to be closed before identifying A?

**Comment by whyrusleeping** [comment]
@tomaka hrm... that shouldnt really matter. Try setting the env var `IPFS_LOGGING=debug` before running the go node and see if you get any extra info out of it.

**Comment by tomaka** [comment]
I tried the following experiment: I disconnected my machine from the Internet so that only my Rust node could connect to my local Go node.

Then my Rust node dials the Go node, then opens a substream for identify (turns out we open 3, probably a bug in our code), then opens a substream for Kademlia, and starts a few `FIND_NODE` queries.

Here are the logs on the Go side: https://pastebin.com/ffV7aWrB
Here are the logs on the Rust side: https://pastebin.com/FNVYYkCT

Note that for logging purposes, on the side of the Rust node I went with a lower-level approach and intercepted anything that goes through Secio (the lowest protocol level).

Also for logging purposes I try to convert all incoming packets to UTF8 so that they're easier to read. `Ok` and `Err(FromUtf8Error))` represent whether or not the packets of data are valid UTF8. No error actually happens, it's just for logging.

Comments on the Rust logs:

- Lines 3 and 4 are part of the end of the secio handshake and are irrelevant.
- After line 11 we are in multiplex world.
- Lines 11-13 we (Rust node) start by opening outgoing substream 0.
- Lines 14-25 we negotiate `/ipfs/kad/1.0.0` on substream 0.
- Lines 26-27 the remote (Go node) opens substream 1.
- Lines 28-29 the remote opens substream 3.
- Lines 30-31 the remote opens substream 5.
- Lines 32-34 we open substream 2.
- Lines 35-46 we negotiate `/ipfs/id/1.0.0` on substream 2.
- Lines 48-50 we open substream 4.
- Lines 51-62 we negotiate `/ipfs/id/1.0.0` on substream 4.
- Lines 63-65 we open substream 6.
- Lines 66-77 we negotiate `/ipfs/id/1.0.0` on substream 6.
- Lines 47 and 78-80 the remote agrees on `/ipfs/kad/1.0.0` on substream 0.
- Lines 81-82 and 854-855 the remote agrees on `/ipfs/id/1.0.0` on substream 2.
- Lines 83-853 we send tons of Kademlia requests through substream 0.
- Lines 856-859 the remote sends us the actual identify information on substream 2.
- Line 860 the remote closes substream 2.
- Lines 861-869 the same but for substream 4 (agreeing on id protocol, sending info, closing).
- Lines 870-878 the same but for substream 6.
- Lines 879-... the remote answers the Kademlia requests on substream 0.

I cut the rest of the logs, but it's basically only sending and answering Kademlia requests.

The substreams 1, 3 and 5 are not actually used at all by the remote. I tried leaving the connection active for a long time, without luck.

**Comment by whyrusleeping** [comment]
@tomaka so it looks like identify is happening successfully (based on the go logs). What are you expecting to happen that isnt happening?

**Comment by tomaka** [comment]
@whyrusleeping I'm wondering whether this is expected that the Go node opens 3 substreams without making use of them, and I'm also confused why the Go node doesn't try to identify the Rust node.
In order for the network to work properly, I would expect that the Go node adds the Rust node to its kbuckets and peer storage.

**Comment by whyrusleeping** [comment]
@tomaka Hrm... the go node should open up one stream for identify, one (epehmeral) stream for figuring out which DHT version you are implementing, and the third might be bitswap (though it should be waiting until it has wants to send you) or it could be pubsub if you have that enabled.

I suspect theres an issue in your multistream implementation where you arent properly doing a multistream handshake and the streams just appear to be hanging.

**Comment by tomaka** [comment]
Which multistream handshake exactly are you thinking of? From my impression, the listener doesn't have anything special to do?

The data in the Rust logs above is exactly the data received on the network (after they being decoded by secio), so any activity should be visible.

**Comment by whyrusleeping** [comment]
The go side of things should be calling `SelectOneOf` (https://github.com/multiformats/go-multistream/blob/master/client.go#L27) to perform the multistream handshake on their side. It sends the multistream protocol, waits for you to send it back, then tries the protocols. 

Is there a way I can easily try this out locally?

**Comment by tomaka** [comment]
> It sends the multistream protocol

That doesn't happen apparently.

> Is there a way I can easily try this out locally?

- If you haven't installed Rust, go to rustup.rs
- Clone my `kademlia` branch: https://github.com/tomaka/libp2p-rs/tree/kademlia
- Then go to the `example` directory and run `cargo run --example kademlia`. It will attempt to connect to `/ip4/127.0.0.1/tcp/4001`.

**Comment by whyrusleeping** [comment]
@tomaka i'm getting some weird stuff here. When i run that, A peer shows up in the go nodes swarm peers listing, but it has a different peer ID than the one that the rust node is claiming to be listening on.

**Comment by tomaka** [comment]
Where does the peer ID you're getting comes from? From the secio layer?

**Comment by whyrusleeping** [comment]
Yeah, it comes from secio

**Comment by Stebalien** [comment]
> It sends the multistream protocol

`SelectOneOf` *does not* send the multistream protocol first. It first *waits* for the other side to send the multistream protocol. That is, the client waits for the server to send first.

However, FYI, we only call `SelectOneOf` if identify hasn't yet completed. However, this obviously doesn't apply for the initial identify connection. I'm guessing that's the issue here.

> go waits for Identify to finish

I'm pretty sure it doesn't. We call the connection handler in a goroutine.

**Comment by tomaka** [comment]
I'm busy with other things right so I can't test, but I've just found out this problem: the [line here](https://github.com/libp2p/rust-libp2p/blob/1e86c6ed352628129d89446e6753fa0f90e29d4d/libp2p-swarm/src/transport.rs#L1003) should read "Listener" and not "Dialer".

Right now our node in some specific situation supposes that it is in dialer mode for identify and therefore waits for a message from the remote.

Not sure if it fixes the problem, but it's a likely cause.

**Comment by tomaka** [comment]
We've fixed so many things that the chances of this being fixed is quite high.
Tackling this issue now would first consist in determining whether this still happens.

**Comment by romanb** [comment]
How would one go about determining whether this problem still exists? We have at least the `ipfs-kad` example that successfully talks to IPFS nodes. Can this be closed?

**Comment by tomaka** [comment]
I guess we can indeed close this. There is a rust-ipfs repository building upon rust-libp2p that will probably report the issues they might face.
