### ISSUE TITLE
floodsub protocol not implement std::error::Error

### ISSUE THREAD

**Issue by gguoss** [libp2p/rust-libp2p#1330]
error[E0277]: the trait bound `<libp2p_floodsub::protocol::FloodsubRpc as libp2p_core::upgrade::OutboundUpgrade<TSubstream>>::Error: std::error::Error` is not satisfied
  --> src/lib.rs:18:10
   |
18 | #[derive(NetworkBehaviour)]
   |          ^^^^^^^^^^^^^^^^ the trait `std::error::Error` is not implemented for `<libp2p_floodsub::protocol::FloodsubRpc as libp2p_core::upgrade::OutboundUpgrade<TSubstream>>::Error`
   |
   = note: required because of the requirements on the impl of `std::error::Error` for `libp2p_swarm::protocols_handler::ProtocolsHandlerUpgrErr<<libp2p_floodsub::protocol::FloodsubRpc as libp2p_core::upgrade::OutboundUpgrade<TSubstream>>::Error>`
   = note: required by `libp2p_swarm::protocols_handler::ProtocolsHandler`

**Comment by mxinden** [comment]
Hi @gguoss ,

In order for me to help you here, I would need more details. On which git commit are you running? What are the changes you made?

As far as [I can tell](https://github.com/libp2p/rust-libp2p/blob/master/protocols/floodsub/src/protocol.rs#L170) `<libp2p_floodsub::protocol::FloodsubRpc as libp2p_core::upgrade::OutboundUpgrade<TSubstream>>::Error` is an `io::Error` which does [implement the `std::error::Error` trait](https://doc.rust-lang.org/std/io/struct.Error.html).

**Comment by gguoss** [comment]
#[derive(NetworkBehaviour)]
#[behaviour(out_event = "BehaviourOut", poll_method = "poll")]
pub struct Behaviour {
    floodsub: Floodsub<Substream<StreamMuxerBox>>,
    kad: Kademlia<Substream<StreamMuxerBox>, MemoryStore>,
    #[behaviour(ignore)]
    events: Vec<BehaviourOut>,
}



libp2p version = 0.12.0

**Comment by mxinden** [comment]
I am closing here. Feel free to reopen in case you are still facing issues.
