### ISSUE TITLE
Document `Transport` invariants

### ISSUE THREAD

**Issue by DemiMarie-parity** [libp2p/rust-libp2p#1333]
When implementing `Transport` and `StreamMuxer`, especially for protocols such as QUIC, it is critical to know the invariants that libp2p will uphold.

Edit: Specific invariants include:

* Do transports and muxers need to be thread-safe?
* If a call to `Transport::write_substream` returns `Poll::Pending`, will subsequent calls use the same (or an equivalent) buffer until `Poll::Ready` is returned?

**Comment by mxinden** [comment]
@DemiMarie-parity would you mind reformulating this in a more actionable manner? Which invariants would you like to see documented?

**Comment by DemiMarie-parity** [comment]
@mxinden done

**Comment by mxinden** [comment]
> If a call to Transport::write_substream returns Poll::Pending, will subsequent calls use the same (or an equivalent) buffer until Poll::Ready is returned?

Given that the caller passes a mutable reference to `write_substream` the implementor can not keep the buffer longer than the lifetime of the function call. Thus it can not enforce to use the same buffer on subsequent calls.

As far as I can tell as a caller  when receiving a `Poll::Pending` from `write_substream` you are expected to call with the same buffer next time though this might not be necessary for all implementations.

In general I think this function aligns with the invariants of [`AsyncWrite::poll_write`](https://docs.rs/futures-preview/0.3.0-alpha.18/futures/io/trait.AsyncWrite.html#tymethod.poll_write). Please correct me if I am wrong.

**Comment by tomaka** [comment]
The methods in `StreamMuxer` were specifically designed to mimic `AsyncWrite::poll_write` (itself mimicking `std::io::Write`), with the exception that they don't take `Pin<&mut Self>` but `&mut self` for now (cc #1329).

**Comment by tomaka** [comment]
Going to close as per my comment :arrow_up: I don't think it's worth documenting more.
