### ISSUE TITLE
Upgrade bytes to 0.5

### ISSUE THREAD

**Issue by expenses** [libp2p/rust-libp2p#1351]
Version 0.5 of the bytes crate has several breaking changes that mean we lose backwards compatibility with older versions. This causes some problems as soketto uses bytes 0.5, while we use bytes 0.4.

**Comment by twittner** [comment]
>  This causes some problems as soketto uses bytes 0.5, while we use bytes 0.4.

What problems exactly?

**Comment by expenses** [comment]
@twittner The versions are incompatible so you can't pass bytes from soketto to libp2p. This prevents me from being able to downgrade a websocket transport to the inner transport and keep the bytes buffer.

**Comment by twittner** [comment]
You can keep and use any bytes-0.5 types encapsulated within your transport. The transport's output type would most likely have to implement `AsyncRead` and `AsyncWrite` and when implementing these traits you are free to operate on those buffers.

**Comment by tomaka** [comment]
#1353 mostly did the upgrade, but leaving open as there's still a `bytes 0.4` in multistream-select.
