### ISSUE TITLE
Add traits that abstracts IO operations for datagram-based transport

### ISSUE THREAD

**Issue by lqf96** [libp2p/rust-libp2p#1357]
Currently, we have `AsyncRead` and `AsyncWrite` trait for stream-based transports. Should we also add traits that abstracts IO operations for datagram-based transport? This will be useful for lots of protocols such as raw IP packet, UDP, DTLS and (possibly) unreliable QUIC extension.

This is somewhat related to issue #46.

**Comment by tomaka** [comment]
There's a fundamental problem with the `Transport` trait: it exposes the concept of an open connection.

For example, imagine a `Transport` that wraps around a single UDP socket. When we receive data, we have to dispatch that data either to a connection open with `dial` or generate a new connection on a stream open with `listen_on`.

In the case of QUIC, connections are stateful, so this is the correct model. In the case of raw UDP, the `Transport` trait is a bad abstraction.

**Comment by tomaka** [comment]
So I'm going to answer the question with "no". Please reopen if you want to continue discussion.
