### ISSUE TITLE
Rip out mplex

### ISSUE THREAD

**Issue by DemiMarie-parity** [libp2p/rust-libp2p#1359]
It doesn’t support decent flow control

**Comment by twittner** [comment]
This is a known limitation and as long as mplex is an active [specification](https://github.com/libp2p/specs/tree/master/mplex) of libp2p I do not see why rust-libp2p should remove the existing support.

**Comment by tomaka** [comment]
As libp2p-mplex is the only multiplexing protocol supported by js-libp2p, we would also break compatibility for no real reason.
