### ISSUE TITLE
Decoding and encoding a secp256k1 key corrupts the key

### ISSUE THREAD

**Issue by DemiMarie-parity** [libp2p/rust-libp2p#1361]
```rust
#[cfg(test)]
mod test {
    #[test]
    fn can_encode_and_decode_key() {
        let keypair = identity::Keypair::generate_secp256k1();
        let public = keypair.public();
        assert_eq!(public, public, "key is not equal to itself?");
        assert_eq!(
            identity::PublicKey::from_protobuf_encoding(&public.clone().into_protobuf_encoding())
                .unwrap(),
            public,
            "encoding and decoding corrupted key!"
        );
    }
}
```

The second comparison causes an assertion failure in `rust-secp256k1`.

**Comment by burdges** [comment]
Is one hashed or compressed or something?

**Comment by DemiMarie-parity** [comment]
No idea.  In any case, it should not cause a panic.

**Comment by romanb** [comment]
This seems to be an issue with a `PartialEq` impl of the `Field` elements making up the public key in the `libsecp256k1` library. See https://github.com/paritytech/libsecp256k1/pull/30. To witness, if you switch the first and second parameter in the comparison in your test, it should no longer fail.

**Comment by DemiMarie-parity** [comment]
This can be closed.
