### ISSUE TITLE
Protobuf version check does not play well with semver

### ISSUE THREAD

**Issue by cheme** [libp2p/rust-libp2p#1363]
This line does not work well with semver cargo expectation:
https://github.com/libp2p/rust-libp2p/blob/1aeb264cbc0e262af219c92e18eb0025724a9005/core/src/keys_proto.rs#L27 result in https://gitlab.parity.io/parity/substrate/-/jobs/341902
It would either require to have a fix versioning in cargo.toml or check over every version that match semver requirement. Not sure what is better.

**Comment by bltavares** [comment]
I've started a test project and found this issue. I've partially solved it by pinning the version of `protobuf` crate on my `Cargo.toml`


```toml
[dependencies]
libp2p = "0.13.1"
protobuf = "=2.8.1"
```

**Comment by tomaka** [comment]
#1353 fixed it for the `stable-futures` branch.
Should we release a version `0.13.2` with `protobuf` pinned down, or is it fine to wait for `0.14`?

**Comment by cheme** [comment]
It seems to break substrate ci so I would +1  0.13.2 with protobuf pinned down.

**Comment by tomaka** [comment]
Theoretically Substrate should only break if someone updates the `Cargo.lock` to use a new protobuf version.

**Comment by cheme** [comment]
Yes, that is the 'try_build' check that breaks:  https://gitlab.parity.io/parity/substrate/-/jobs/341902 (it seems to use its own lock internally, I am not sure of the purpose of this test but it may be to detect such issue).
