### ISSUE TITLE
Automate a bit more releasing a version of this crate

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#1365]
Releasing a new version of libp2p is very painful. One has to bump the version of every crate in all the `Cargo.toml`s, then publish packages one by one in the correct order (as they depend on each other).

Additionally, since there are cyclic dependencies within `dev-dependencies`, one has to actually tweak the `Cargo.toml`s right before publishing to remove `dev-dependencies`, and use `cargo publish --allow-dirty`.

The fact that this is so painful makes it really annoying to release hotfixes for example.

**Comment by LegNeato** [comment]
We have similar constraints to the first requirement in https://github.com/graphql-rust/juniper if you want to see how we solved it.

**Comment by thomaseizinger** [comment]
Closing in favor of https://github.com/libp2p/rust-libp2p/issues/2902.
