### ISSUE TITLE
Change addresses_of_peer to return HashSet

### ISSUE THREAD

**Issue by michaelvoronov** [libp2p/rust-libp2p#1417]
Hi,

It seems that it is more convinient for `addresses_of_peer` to return `HashSet<Multiaddr>` instead of `Vec<Multiaddr>` - there are no any benefits of returning vectors with same addresses. And this can occure while using proc macro `NetworkBehaviour` with several behaviours that track map between PeerId and Multiaddr (like Mdns/Kad/your own).

**Comment by twittner** [comment]
We can not use a set because the order of addresses matters.

**Comment by michaelvoronov** [comment]
Hmm, just curious why does it matter?

**Comment by michaelvoronov** [comment]
What about [linked hash set](https://docs.rs/linked_hash_set/0.1.3/linked_hash_set/struct.LinkedHashSet.html)?

**Comment by tomaka** [comment]
As note: Originally the idea is that we'd use an iterator and add a `type AddressesOfPeerIter;` associated type to the `NetworkBehaviour` trait, but since it would be quite annoying to implement I went for a `Vec` instead.

**Comment by mxinden** [comment]
I am closing here, as it seems the above comments answer the question. Feel free to reopen this issue or a new one in case you have further suggestions.
