### ISSUE TITLE
Make #[derive(NetworkBehaviour)] more customisable

### ISSUE THREAD

**Issue by michaelvoronov** [libp2p/rust-libp2p#1418]
What about adding possibility of calling custom handler not only for `poll` function, but also for all other suitable methods of the `NetworkBehaviour` trait. F.e. I haven't found a more easy way to obtaining notification about peers connection/disconnection with their PeerId and Multiaddr then by adding my own behaviour that push events from `inject_connected`/`inject_disconnected` up to root behaviour (the Identify protocol doesn't privide ability to obtain multiaddr of incoming peer).

**Comment by tomaka** [comment]
> I haven't found a more easy way to obtaining notification about peers connection/disconnection with their PeerId and Multiaddr then by adding my own behaviour that push events from inject_connected/inject_disconnected up to root behaviour (the Identify protocol doesn't privide ability to obtain multiaddr of incoming peer).

This is orthogonal to that issue, but for what it's worth, since v0.14 you can call `Swarm::next_event()` to obtain that info.

**Comment by michaelvoronov** [comment]
Don't know, thank you! But in my case more convenient to use custom `inject_connected/inject_disconnected` and keep logic inside my behaviour then notifying it from the upper level after polling.

**Comment by michaelvoronov** [comment]
If there are no opinions against this change, I would like to make a PR to add at least custom `inject_connected`/`inject_disconnected`.

**Comment by tomaka** [comment]
Go ahead!

**Comment by michaelvoronov** [comment]
We've solved our task without custom `inject_connected`/`inject_disconnected`, so maybe they not so needed.

**Comment by romanb** [comment]
Based on the latest feedback, I guess this can be closed. Feel free to reopen, or ideally open new issues or PRs for specific new features.
