### ISSUE TITLE
Provide fused stream of swarm events

### ISSUE THREAD

**Issue by rklaehn** [libp2p/rust-libp2p#1434]
The current Stream impl for Swarm provides behaviour events. It would be convenient to have a fused stream of full swarm events. If you want just behaviour events, it is very easy to get behaviour events from swarm events by just filtering. 

I guess it is not possible to change the Stream impl for Swarm to produce full SwarmEvents due to backwards compatibility...

A fused stream would enable using the stream in a select! macro.

**Comment by rklaehn** [comment]
related: https://github.com/libp2p/rust-libp2p/pull/1433

**Comment by vorot93** [comment]
FYI Tokio's `select!` does not require `FusedStream`

https://docs.rs/tokio/0.2.11/tokio/macro.select.html

**Comment by rklaehn** [comment]
@vorot93 thanks for the hint. We are still not sure if we are going to go with async_std or tokio internally at Actyx, but since the streams already fulfill the requirements for fused streams, I see no harm in providing instances to just state this fact at type level for whoever needs it.

If only you would not need this wall of type parameters and constraints...

**Comment by tomaka** [comment]
This is done
