### ISSUE TITLE
Get peers on topic 

### ISSUE THREAD

**Issue by AIDXNZ** [libp2p/rust-libp2p#1441]
Is there an easy way of returning all the connected peers on a topic? 

Im new to rust sorry if the answer is obvious.

**Comment by tomaka** [comment]
No there isn't.

**Comment by ericjmiller** [comment]
Wouldn't this meet the criteria?

in `protocols/gossipsub/src/behaviour.rs`
```rust 
   /// Lists all peers for any topic.
    pub fn all_peers(&self) -> impl Iterator<Item = &PeerId> {
        let mut res = BTreeSet::new();
        for peers in self.mesh.values() {
            res.extend(peers);
        }
        res.into_iter()
    }
```

**Comment by mxinden** [comment]
Closing here. Feel free to open up a new issue in case you have further questions.
