### ISSUE TITLE
Implement Kademlia record store

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#146]
It is currently unimplemented.

**Comment by tomaka** [comment]
Record storage is about storing records that other peers want to store on our machine, and then loading them back when requested. More concretely, it's about implementing the `ADD_VALUE` and `GET_VALUE` messages. Right now when we receive such a message we immediately close the Kademlia substream.

The challenge in doing is mostly implementing the signatures system that makes it possible to prove that the record wasn't altered.

**Comment by tomaka** [comment]
Considering that the user may want to store records on the disk, or cache records in a certain way, it is in my opinion preferable to not store the records directly in the `Kademlia` struct, but to let users entirely handle that.
In other words, when a record is requested from the network, an event would be emitted (for example, `KademliaOut::RecordRequest`) and the user would have to answer this request by providing the data.

**Comment by romanb** [comment]
> Considering that the user may want to store records on the disk, or cache records in a certain way, it is in my opinion preferable to not store the records directly in the `Kademlia` struct, but to let users entirely handle that.
> In other words, when a record is requested from the network, an event would be emitted (for example, `KademliaOut::FetchRecord`) and the user would have to answer this request by providing the data.
> A similar event (eg. `KademliaOut::AddRecord`) would of course be emitted when the network wants us to store a record.

I'm not so sure. Implementing record storage and retrieval in such a way that persistence of records has a negligible probability of failure in the context of node failures, nodes joining and leaving seems non-trivial, involving a combination of regularly scheduled operations like bucket refreshes, record re-replication and record re-publication in somewhat carefully chosen intervals. And all of that seems central to a Kademlia DHT implementation. It does of course seem desirable to abstract over the concrete choice of storage (hashmap, files, dbms, ...) through a small interface, combined with configurable intervals for all the necessary regular record gossip. I do think that `libp2p-kad` should ship with an in-memory storage option that can configured or swapped out for something else according to a defined interface (probably containing at least functions along the lines of `get`, `put`, `select` and `validate`, whereby the latter two come from the libp2p spec section regarding entry validation, which I'm not sure we want or need to have?).

**Comment by romanb** [comment]
Closing this as a result of https://github.com/libp2p/rust-libp2p/pull/1189. I think any specific missing pieces or bugs should be filed in new, separate issues.
