### ISSUE TITLE
Potential unbounded buffer growth in background task of pending connection.

### ISSUE THREAD

**Issue by romanb** [libp2p/rust-libp2p#1465]
It was brought up in https://github.com/libp2p/rust-libp2p/pull/1440#discussion_r378945869 that there is a theoretical unbounded growing buffer of pending events for a connection handler in a background `Task`s `events` buffer while the connection is still pending (i.e. being established). While in practice every connection attempt is eventually bound to time out, it may nevertheless be preferable to bound the buffer. My current suggestion would be to add a hard upper limit for the size of the buffer which, when reached, results in the connection attempt to be aborted and the background task dropped.

**Comment by mxinden** [comment]
Implementation suggestion in https://github.com/libp2p/rust-libp2p/pull/1501.
