### ISSUE TITLE
Expire listening addresses if a listener is closed

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#1482]
In `listeners.rs`, if a listener is closed, we emit a `ListenersEvent::Closed` event, but we don't mark the addresses the listener was listening on as "expired".

The `ListenersEvent::Closed` event should contain a list of addresses, and then we should appropriately call `NetworkBehaviour::inject_expired_listen_addr` and emit `SwarmEvent::ExpiredListenAddr`.

**Comment by disfenoid** [comment]
Hello, I would like to take this one, if you don't mind.

**Comment by tcharding** [comment]
[Draft PR](https://github.com/libp2p/rust-libp2p/pull/1485) is an attempt at resolving this.  It is draft because I have some `rustfmt` dramas.
