### ISSUE TITLE
Replace get_if_addrs with a pure Rust library

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#1489]
For the sake of not having to compile any C code, let's try use only pure Rust dependencies.

**Comment by mxinden** [comment]
We could use libpnet's [`interfaces`](https://github.com/libpnet/libpnet/blob/master/pnet_datalink/src/unix_interfaces.rs#L25) instead which for unix would use the systems libc instead of custom C code.

**Comment by DemiMarie-parity** [comment]
Once https://github.com/paritytech/ip-watch is ready, this will be solved.

**Comment by kallisti5** [comment]
It looks like this one is solved?  Having trouble building apps using rust-libp2p 0.22.0 because of poor "non-linux" support.  get_if_addrs is also now read-only and not accepting patches / fixes.

**Comment by mxinden** [comment]
> It looks like this one is solved?

Not quite. I am afraid it gotten even more complicated.

With https://github.com/libp2p/rust-libp2p/pull/1830  `libp2p-mdns` now uses [`if-wtach`](https://github.com/dvc94ch/if-watch/) which uses a Rust implementation on Linux and Windows and [falls back to `if-addrs` on e.g. Mac](https://github.com/dvc94ch/if-watch/blob/master/src/fallback.rs).

`libp2p-tcp` still uses [`if-addr`](https://github.com/messense/if-addrs) which might change to `if-watch` with https://github.com/libp2p/rust-libp2p/pull/1845.

**Comment by dvc94ch** [comment]
this one can be closed now, no?
