### ISSUE TITLE
GetProvidersResult should return unique providers

### ISSUE THREAD

**Issue by michaelvoronov** [libp2p/rust-libp2p#1507]
It seems that `providers` from `GetProvidersResult` could contain non-unique peers. I think that this behaviour could be error-prone for users of rust-libp2p (I've already stumbled with that:)) and providers should be unique.

**Comment by mxinden** [comment]
Given that we don't group the providers by response, we could replace the `Vec` with a `HashSet` within [`GetProviders`](https://github.com/libp2p/rust-libp2p/blob/master/protocols/kad/src/behaviour.rs#L1846).

@romanb what do you think?

**Comment by romanb** [comment]
Sounds ok to me. If we want to introduce a configurable limit on how many providers to look for, terminating the query early if enough providers are found (as I think other libp2p-kad implementations offer), we would need to de-duplicate anyway.

**Comment by mxinden** [comment]
https://github.com/libp2p/rust-libp2p/pull/1528 would fix the duplication.

---

> Furthermore, if we want to introduce a configurable or hard-coded limit on how many providers to look for, terminating the query early if enough providers are found (as I think other libp2p-kad implementations offer), we would need to de-duplicate anyway.

:+1:
