### ISSUE TITLE
Usage question for Noise with IK handshake

### ISSUE THREAD

**Issue by dignifiedquire** [libp2p/rust-libp2p#1525]
I am trying to build a transport that supports doing the Noise IK handshake with `n` different peers. This list of peers is manually added through a command line, and so will change over time. As far as I can tell the docs only really show the IK pattern with a single peer identity known at startup. 

Would appreciate any help on how to best implement this.

**Comment by burdges** [comment]
Why?  If your transport layer is point-to-point then you should normally encrypt point-to-point for authentication.

Are you doing [IP multicast](https://en.wikipedia.org/wiki/IP_multicast) or [similar](https://en.wikipedia.org/wiki/Multicast)?  If so, you need temporary IP addresses for each multicast group, right?  I'd expect group coordination requires separate point-to-point links anyways, right?  You could simply distribute a single symmetric key across these point-to-point links.  You should encrypt each datagram packet separately with random nonces, presumably like [DTLS 1.2](https://en.wikipedia.org/wiki/Datagram_Transport_Layer_Security).  You'll need custom flow control too, for which I'd investigate erasure codes.  

As a warning, there are higher level protocols for Byzantine agreement, etc. that make security assumptions about gossip protocols.  IP multicast depends upon support from intermediate routers.  I'd therefore think gossip over IP multicast needs, not only [reliable multicast](https://en.wikipedia.org/wiki/Reliable_multicast), but cryptographically enforced reliable multicast.  I've no idea if anyone specified such a protocol, but it needs secrets between each broadcaster and each recipient.  In this vein, internet routers should manage IP multicast group addresses through roughly BGP, which gives another vulnerability zoo. 

Are you doing some "messager" with more asynchronous delivery?  As a rule, messengers should employ forward secure "ratchets", which many messengers like [Telegram](https://security.stackexchange.com/a/49802) screw up, and groups make much harder.  [MLS](https://messaginglayersecurity.rocks/) should provide a good solution eventually.  Also [messaging@moderncrypto.org](https://moderncrypto.org/mail-archive/messaging/) has good discussions around this topic.  Afaik, all the current secure group messengers like Signal and Wire employ what Trevor Perrin calls "sender keys".

**Comment by tomaka** [comment]
Afaik the IK handshake isn't really fleshed out in rust-libp2p.
For context: https://github.com/libp2p/rust-libp2p/issues/1423

**Comment by dignifiedquire** [comment]
@burdges thank you for the great comments, but yes I am not trying to do a group key exchange. The goal is to do a permissioned network, where all participants have a shared configuration file communicated out of band ahead of time.

**Comment by dignifiedquire** [comment]
The "dynamic update" capabilities come from the fact that this configuration does get updated from time to time when new members are added to the network.

**Comment by dignifiedquire** [comment]
As an alternative @tomaka is there any way currently to whitelist peers? I have seen the `ban_peer` functionality, but I would want to do the opposite, eg `whitelist_peer` and disallow connections to all other peers.

**Comment by tomaka** [comment]
> As an alternative @tomaka is there any way currently to whitelist peers? 

Not through the swarm, no.

**Comment by mxinden** [comment]
Closing here, as the discussion seems to have stalled. @dignifiedquire please re-open in case you would like to continue the conversation.
