### ISSUE TITLE
What is an efficient use of rust-libp2p when one has to orchestrate a set of oneshot protocols with a single peer?

### ISSUE THREAD

**Issue by thomaseizinger** [libp2p/rust-libp2p#1542]
When we adopted libp2p, we simply ported our existing communication protocol on top of a single libp2p protocol. That was obviously not making use of any of the abstractions present in libp2p.

Given that, we attempted a redesign that makes heavy use of oneshot protocols. This allows us to compose the functionality of several usecases together.

I'll spare you the details and get right to the question:

What is an efficient use of rust-libp2p when one has to orchestrate a set of oneshot protocols with a single peer?

At the moment we have (per libp2p-protocol):

- 1 inbound protocol config (in case we receive a message)
- 1 outbound protocol config (in case we want to send a message)
- the `OneShotHandler`
- our own `OneShotBehaviour` that is based the `OneShotHandler`

This actually works okayish. We simply put our logic of what to do next (i.e. which oneshot protocol to use next) in the implementations of `NetworkBehaviourEventProcess` for the `NetworkBehaviour` that composes several `OneShotBehaviour`s.

What doesn't work so well is spelling out the type of the `ExpandedSwarm` that results out of that :sweat_smile: 
We would really like to stick to oneshot protocols, so combining the protocols is not really an option.
We were thinking of writing a custom `ProtocolsHandler` that can handle several protocols of different types (similar to the multi module that was recently added). Do you think that is a good path to go down or is there a better solution?

**Comment by tomaka** [comment]
> What doesn't work so well is spelling out the type of the ExpandedSwarm that results out of that 

I'm not sure I understand the problem.
Is the `NetworkBehaviour` that composes several `OneShotBehaviour`s not a single type?

**Comment by thomaseizinger** [comment]
> Is there a reason why Swarm doesn't work? It's convenient typedef, the only requirement being that the NetworkBehaviour trait is necessary in order to even build a Swarm;

Ah very interesting, thanks that works!

Apart from that, do you also have input on:

> We were thinking of writing a custom ProtocolsHandler that can handle several protocols of different types (similar to the multi module that was recently added). Do you think that is a good path to go down or is there a better solution?

To expand on that, here is my take on the libp2p abstractions:

- InboundUpgrade/OutboundUpgrade: Substream-local state (1 peer, 1 protocol, 1 substream)
- ProtocolsHandler: Protocol-local state (1 peer, 1 protocol, several substreams)
- NetworkBehaviour: Protocol-"global" state (several peers, 1 protocol, several substreams)
- Swarm: global state (several peers, several protocols, several substreams)

What I am missing is an abstraction for: 1 peer, several protocols :(

**Comment by tomaka** [comment]
Yes, there's nothing that prevents `ProtocolsHandler` and `NetworkBehaviour` from handling several protocols at once.

When you use the custom derive to build a `NetworkBehaviour` that groups multiple behaviours, it is no different than implementing the trait manually and handling multiple protocols.

**Comment by thomaseizinger** [comment]
Okay thanks, I think this can be considered resolved then!

I am gonna try and implement a custom `ProtocolsHandler` that can handler several protocols to eventually specify that one in the `NetworkBehaviour`.
