### ISSUE TITLE
Add a bandwidth management library

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#156]
Would wrap around a `Transport` and implement the `Transport` trait itself.

For uploads, one possible way of implementing this is having a buffer whose content is dispatched over time to the underlying transport (using `tokio-timer` for example). If the buffer is full when we want to send something, return `WouldBlock`. Don't forget to later notify the tasks for which we returned `WouldBlock`.

As for downloads, we can return `WouldBlock` if we detect that the rate would be too fast. We would only read a maximum number of bytes from the underlying transport in order to not go over the rate. If we return `WouldBlock`, then don't forget to notify the tasks later.

**Comment by h4x3rotab** [comment]
Hi @tomaka, is the ratelimit available on substrate?

**Comment by mxinden** [comment]
@h4x3rotab having worked on Substrate myself in the past, I am not aware of such functionality.
