### ISSUE TITLE
kad: FindPeers

### ISSUE THREAD

**Issue by dvc94ch** [libp2p/rust-libp2p#1568]
The go implementation provides a `FindPeers` function. Is this going to be implemented in `libp2p-kad` or should this feature live somewhere else?

**Comment by mxinden** [comment]
I am assuming you are referring to [`FindPeer`](https://github.com/libp2p/go-libp2p-kad-dht/blob/master/routing.go#L619) and not `FindPeers`.

I am not aware of any plans.

As far as I know the way to go as of today is to trigger a `FIND_NODE` query via `Kademlia::get_closest_peers` and either wait for the `KademliaEvent::Discovered` event with the corresponding peer id, or call `<Kademlia as NetworkBehaviour>::addresses_of_peer` after receiving a `KademliaEvent::GetClosestPeersResult`.

**Comment by dvc94ch** [comment]
I see, very useful thanks. I have a question in regards findProviders. I have a test case that is failing and works as follows:
```
swarm1 (no bootstrap nodes)
swarm2.add_address(swarm1)
swarm2.bootstrap()
swarm3.add_address(swarm1)
swarm3.bootstrap()
swarm2.start_providing(key)
swarm3.get_providers(key)
```
swarm3 can't find a provider. is that expected?

**Comment by dvc94ch** [comment]
Created an example here that demonstrates the failure:
https://github.com/dvc94ch/rust-libp2p/blob/get-providers/examples/kad-get-providers.rs

**Comment by mxinden** [comment]
Thanks for the example.

```rust
    swarm1.kad.start_providing(key.clone());
    spawn_swarm(swarm1);
    thread::sleep(Duration::from_secs(30));
```

While `swarm1` is spawned as a task `swarm2` and `swarm3` are not. Thus while `swarm1` will make requests to `swarm2` and `swarm3`, non of the latter will reply as they are not polled.

Does that make sense?

**Comment by dvc94ch** [comment]
:facepalm: that was a dumb thing to do. but I'm still having issues. the original code was using a channel to send messages to the swarm task. I updated the example to do the same. I'm still confused if the example is supposed to work or if my mental model of how it should work is wrong.

```rust
    let key = Key::new(&[1u8]);
    let mut swarm1 = Swarmer::new().await?;
    let mut swarm2 = Swarmer::new().await?;
    let mut swarm3 = Swarmer::new().await?;
    let mut swarm4 = Swarmer::new().await?;

    // bootstrap nodes
    swarm1.add_address(&swarm2);
    swarm2.add_address(&swarm1);

    // peers
    swarm3.add_address(&swarm1);
    swarm3.add_address(&swarm2);
    swarm4.add_address(&swarm1);
    swarm4.add_address(&swarm2);

    let _ = swarm1.spawn().await?;
    let _ = swarm2.spawn().await?;
    let mut swarm3 = swarm3.spawn().await?;
    let mut swarm4 = swarm4.spawn().await?;

    swarm3.start_providing(key.clone()).await;
    thread::sleep(Duration::from_secs(30));
    swarm4.get_provider(key).await?;
```

**Comment by mxinden** [comment]
*I have not actually run your code, so take my comment with a grain of salt.*

When spawning your swarms

```rust
    let _ = swarm1.spawn().await?;
    let _ = swarm2.spawn().await?;
    let mut swarm3 = swarm3.spawn().await?;
    let mut swarm4 = swarm4.spawn().await?;
```

each of these calls execute your custom `spawn` function

```rust
    async fn spawn(mut self) -> Result<Ctrl, InitError> {
        self.swarm.kad.bootstrap();
        match self.swarm.next().await {
            BehaviourEvent::BootstrapOk => {},
            BehaviourEvent::BootstrapError => return Err(InitError::Bootstrap),
        }
        let (tx, mut rx) = mpsc::channel(4);
        let mut swarm = self.swarm;
        task::spawn(poll_fn(move |ctx| {
```

while this `spawn` function does spawn a new task at the very end

```rust
task::spawn(poll_fn(move |ctx| {
```

it does start off on the same task as your main function `run`.

Problem is that it calls `self.swarm.next().await` while still running on the main task, before moving execution into a newly spawned task. Thus it *blocks* the main task, preventing it from making any progress. The main task not making any progress implies that the other swarms won't reply to the first swarm's bootstrap requests and thus you have a dead-lock (at least until time-outs hit).

What you need to do is spawn the swarms onto separate tasks before calling `self.swarm.next().await`.

Let me know if this is of any help.

**Comment by dvc94ch** [comment]
Figured out the trick:

```rust
impl NetworkBehaviourEventProcess<IdentifyEvent> for Behaviour {
    fn inject_event(&mut self, event: IdentifyEvent) {
        match event {
            IdentifyEvent::Received { peer_id, info, .. } => {
                for addr in info.listen_addrs {
                    self.kad.add_address(&peer_id, addr);
                }
            }
            _ => {}
        }
    }
}
```
