### ISSUE TITLE
PUT timeouts on distributed-key-value-store.rs

### ISSUE THREAD

**Issue by ihlec** [libp2p/rust-libp2p#1569]
I am using Kademlia similar to the 'examples/distributed-key-value-store.rs' to save/PUT 1000 values in the DHT.

I achieve rather **poor performance** using 8 peers on a single host. It takes around 15s to PUT 1000 Values, using async PUTs and a blocking task. Also, with a setup of multiple hosts, some PutRecordResult() events run into **timeouts**.
GET performance is fine on the other hand and delivers the 1000 values in under 1s.

Is this a known issue or possibly a flawed usage of the library in my code?

**Comment by romanb** [comment]
We are not aware of any known performance issues in the code itself (which doesn't mean there aren't any). Note that, by definition, storing a value in Kademlia DHT is many times more expensive than looking up a value. A lookup is an iterative query towards the `k` closest nodes to the key that terminates early as soon as a value is found, whereas storing a value is the same iterative query towards the `k` closest nodes the key (to find the nodes where the value should be stored) _followed by_ `k` requests to store the value. So storing a value involves _at least_ `k` (default 20) times the number of requests as a lookup, so there is a lot more I/O. So the difference you're seeing is not really unexpected. Nevertheless, if you think there is a performance bottleneck somewhere that could be avoided, we are happy to look into it given more details and some code to reproduce.

**Comment by ihlec** [comment]
Thank you romanb for the quick and helpful answer. 
I have a followup question regarding the performance issue.

Is it possible to use the QUIC protocol in combination with Kademlia DHT to get rid of the handshake overhead?

I captured the traffic with Wireshark (https://github.com/ag-gipp/bc_p2p/blob/master/lab_notebook/traffic/wireshark_1i_9p.pcapng)

I experienced plenty of duplicated ACKs, retransmissions, and timeouts (tested using Wifi).

My code is at: https://github.com/ag-gipp/bc_p2p/blob/master/src/main.rs
I followed the example as close as possible: https://github.com/libp2p/rust-libp2p/blob/master/examples/distributed-key-value-store.rs

**Comment by mxinden** [comment]
> Is it possible to use the QUIC protocol in combination with Kademlia DHT to get rid of the handshake overhead?

`rust-libp2p` does not yet support QUIC. You can track the current progress in https://github.com/libp2p/rust-libp2p/pull/1334.

> I experienced plenty of duplicated ACKs, retransmissions, and timeouts (tested using Wifi).

Can you add more details on your setup? Am I guessing correctly that this is no the 8 node single host setup anymore you described above?

**Comment by ihlec** [comment]
correct. The setup with package loss was 9 nodes on the first host and the uploading node was a single node on the second host. (Connected via Wifi)

Thank you mxinden for your fast reply. Is there another way to boost performance?

**Comment by mxinden** [comment]
>  GET performance is fine on the other hand and delivers the 1000 values in under 1s.

This is likely due to the fact that in a small cluster each node has each key and thus a GET does not involve any network traffic.

> I experienced plenty of duplicated ACKs, retransmissions, and timeouts (tested using Wifi).

Without having put a lot of thoughts into it, I would guess this is related to your layer 4 (TCP) stack. In case you want to _boost_ performance, this is the place where I would take a deeper look.

**Comment by ihlec** [comment]
Okay. Looking forward to QUIC support then.
Thank you mixnden.
