### ISSUE TITLE
protocols/kad: Why run caching procedure for queries with Quorum::One only?

### ISSUE THREAD

**Issue by mxinden** [libp2p/rust-libp2p#1577]
When querying for a key, Kademlia remembers the closest node that did not have the key to later on store the record on that node.

[Paper](https://pdos.csail.mit.edu/~petar/papers/maymounkov-kademlia-lncs.pdf) page 7:

> For caching purposes, once a lookup suceeds, the requesting node stores the <key, value> pair at the closest node it observed to the key that did not return the value.

This is implemented here:

https://github.com/libp2p/rust-libp2p/blob/c271f6f56b7b5c33b1ced135e01291b1d48e8eb8/protocols/kad/src/behaviour.rs#L1306-L1320

**Why is this procedure only triggered for queries with `Quorum::One`? Why not do this for all queries?**

//CC @romanb

**Comment by romanb** [comment]
I have some difficulties remembering but I thin it really came down to the semantics just being a bit unclear. In standard Kademlia the record is cached at the nearest peer to the key that did not return the value _on a successful lookup_. A successful lookup in standard Kademlia is with quorum 1. If this is done for quorums > 1 as well, then the record will be cached even if, from a user's perspective, the lookup wasn't actually successful (e.g. quorum not satisfied). That said, I don't currently see any harm in doing that either, so if there was a very strong reason, I must have forgotten about it by now.

**Comment by romanb** [comment]
I think I remember now. The question is: With a quorum > 1, which of the returned records do you cache? A choice would be implied there, which we cannot really make.

**Comment by romanb** [comment]
@mxinden Did my last comment answer your question and/or do you have specific suggestions for what we could do?

**Comment by mxinden** [comment]
> I think I remember now. The question is: With a quorum > 1, which of the returned records do you cache? They may not be the same, and the reason someone uses a quorum > 1 to begin with is to make a choice among the obtained results, usually. That is a choice that we cannot make internally in libp2p.

Thanks for the follow up. I agree that this is problematic. I can think of two improvements (not mutually exclusive):
- Once a query with quorum > 1 is finished AND was successful AND all records are the same then cache the record at the closest node.
- Once a query with quorum > 1 is finished but is returned to the user with a diverging set of records, allow the user to choose one to be cached at the closest node via e.g. a function like `cache_record_at_closest_node`.

What do you think? Do you have alternative ideas how to make this integral part of Kademlia work for queries with quorum > 1?

**Comment by romanb** [comment]
> Once a query with quorum > 1 is finished but is returned to the user with a diverging set of records, allow the user to choose one to be cached at the closest node via e.g. a function like cache_record_at_closest_node.

I just realised that you probably mean something along the lines of what I wrote in the last paragraph of my previous comment. For some reason my first reading of this comment of yours was that it suggests having a (configurable) function that decides which record to keep, which I referred to in the second to last paragraph.

**Comment by mxinden** [comment]
> For some reason my first reading of this comment of yours was that it suggests having a (configurable) function that decides which record to keep / cache, which I referred to in the second to last paragraph.

As you stated above, I share the concern that this is an interface hard to get right. Additional complications might arise with people wanting to call an `async` function in that function, which reminds me of the problems we are facing in Substrate with the `GossipValidator` today (see https://github.com/paritytech/substrate/issues/6335).


> It is thus thinkable that we could provide a bit more metadata in a GetRecordResult, like the closest node(s) to the key that did not return a record. If there is then also a put_record API for sending a record to a specific given list of target peers, that might enable client code to do such write-back caching in any way they desire.

I would be in favor of this approach.
