### ISSUE TITLE
Banning a connected peer does not result in calls to NetworkBehaviour methods

### ISSUE THREAD

**Issue by koivunej** [libp2p/rust-libp2p#1584]
Banning a connected peer with `ExpandedSwarm::ban_peer_id` does not seem to result in any NetworkBehaviour method calls by the swarm on the banning peer side. On the banned peer the closed connection(s) and disconnected peer are forwarded to NetworkBehaviour's respective methods.

Can't see any changes to the behaviour in #1440 and the original #1065 which introduced the ban/unban feature seems to work in a similar way. I think the expected behaviour would be to notify the swarm's NetworkBehaviour of the disconnection to allow it/them to cleanup any possible state they may have had regarding the peer. This could probably be done through `inject_connection_closed` and finally `inject_disconnected`.

**Comment by romanb** [comment]
This should be fixed in `master` and thus in the next release.
