### ISSUE TITLE
CI failing because of async-std 1.6

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#1588]
It seems that the upgrade to `async-std` v1.6 broke our tests.

I'm opening this issue mostly to track down whether the problem has been figured out.

**Comment by tomaka** [comment]
One should revert https://github.com/libp2p/rust-libp2p/pull/1589 before this issue is closed.

**Comment by dignifiedquire** [comment]
please let me know if there is anything that needs fixing on the async-std side, 1.6 was a big change but trying hard not to break codes

**Comment by romanb** [comment]
@dignifiedquire We didn't look into it yet, but if you're curious or want to lend a hand, it is the [libp2p-noise integration tests](https://github.com/libp2p/rust-libp2p/blob/master/protocols/noise/tests/smoke.rs) that stall with `1.6` as if there is a missing task wakeup. It is maybe not a minimal test case but the tests are nevertheless relatively small and only use `libp2p-core`. Just running `cargo test` in `protocols/noise` with async-std 1.6 should be sufficient to reproduce.

**Comment by tomaka** [comment]
We're maybe a bit too much on the cautious side here, but I would also like to run libp2p-with-async-std-1.6 with a production load and see if any issue arises.

**Comment by romanb** [comment]
Closed by https://github.com/libp2p/rust-libp2p/pull/1618. See also https://github.com/libp2p/rust-libp2p/pull/1612.
