### ISSUE TITLE
Docs for 0.19.1 failed to build

### ISSUE THREAD

**Issue by thomaseizinger** [libp2p/rust-libp2p#1599]
Not sure if people are already aware of this but the docs for 0.19.1 failed to build. Here is the build log: https://docs.rs/crate/libp2p/0.19.1/builds/253797

**Comment by tomaka** [comment]
I've seen that. It seems that docs.rs uses a nightly Rust, and at the time when 0.19.1 was published the nightly Rust had a regression and were unable to compile js-sys.
Restarting the docs generation now would fix it, but I don't think there's a button for that.

**Comment by thomaseizinger** [comment]
Ok thanks for the update, I guess this can be closed then :)
