### ISSUE TITLE
Our implementation of ping might not be conformant

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#1601]
I'm opening this issue because someone has been reporting this to me a long time ago, but I haven't verified the claim.

In our libp2p-ping implementation we open a new substream every time we want to ping the remote, while for js-libp2p and go-libp2p the substream seems to be kept open.

This needs be checked before actually making any change.

**Comment by tcharding** [comment]
Confirming that the go-libp2p ping implementation does keep the stream open. See https://github.com/libp2p/go-libp2p/blob/master/p2p/protocol/ping/ping.go

For reference:
```
// Ping pings the remote peer until the context is canceled, returning a stream
// of RTTs or errors.
func Ping(ctx context.Context, h host.Host, p peer.ID) <-chan Result {
	s, err := h.NewStream(ctx, p, ID)
    ...
    for ctx.Err() == nil {
			var res Result
			res.RTT, res.Error = ping(s)
   ...
    select {
			case out <- res:
			case <-ctx.Done():
				return
			}
    }
}
```
And `ping` is the same as ours, record start time, write 32 bytes, read and check they are the same bytes written.

**Comment by romanb** [comment]
Are the protocols actually incompatible in the sense that undesirable behaviour or errors result? Or is it just a matter of doing what others do? The [spec for the ping protocol](https://github.com/libp2p/specs/issues/183) is a bit short.

**Comment by tomaka** [comment]
> Are the protocols actually incompatible in the sense that undesirable behaviour or errors result?

I believe that the consequence is that the Go or JS node thinks that the Rust node is unresponsive and shuts down the connection.

It's a tolerable situation considering that the connection will stay open for a few dozen seconds during which everything works fine, but it would still be great to fix.

**Comment by romanb** [comment]
Should be fixed as of https://github.com/libp2p/rust-libp2p/pull/1692.
