### ISSUE TITLE
protocols/kad: Node with incompatible protocol name can be added to routing table

### ISSUE THREAD

**Issue by mxinden** [libp2p/rust-libp2p#1611]
A Kademlia [`NetworkBehaviour`](https://github.com/libp2p/rust-libp2p/blob/master/protocols/kad/src/behaviour.rs#L1241) adds a node to its routing table via the `inject_connection_established` hook:

https://github.com/libp2p/rust-libp2p/blob/44236b5ba39cbd324b029cb9fb5ed77a75806706/protocols/kad/src/behaviour.rs#L1280-L1291

This hook is triggered before the protocol negotiation on substreams. Thereby a remote node with a protocol name other than the [set protocol name](https://github.com/libp2p/rust-libp2p/blob/master/protocols/kad/src/behaviour.rs#L132) could be added to the local node's routing table.

See https://github.com/libp2p/rust-libp2p/pull/1473#discussion_r440218337 for details.

**Comment by romanb** [comment]
It should be noted though that, being disconnected shortly after, these peers don't have a high chance of _staying_ in the routing table, meaning peers that connect with the correct protocol name have a strong tendency to push these unwanted peers out of the buckets. Nevertheless, I think this issue shows that customising the protocol name on the negotiated substreams, while still useful, is not the right approach to clean segregation of DHTs. The options stated inhttps://github.com/libp2p/rust-libp2p/issues/1560 are more appropriate to achieve that in a cleaner way.
