### ISSUE TITLE
libp2p-noise incompatible with go-libp2p-noise

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#1631]
Our implementation of noise isn't compatible with go-libp2p.
While Noise messages do function properly, the problem lies in the protobuf message exchange inside of the Noise messages.

rust-libp2p expects the protobuf handshake messages to be prefixed with their length (as seen [here](https://github.com/libp2p/rust-libp2p/blob/bd5e81fedbc5aa9bf941a8ba5da02dee26f291e3/protocols/noise/src/io/handshake.rs#L362-L364) and [here](https://github.com/libp2p/rust-libp2p/blob/bd5e81fedbc5aa9bf941a8ba5da02dee26f291e3/protocols/noise/src/io/handshake.rs#L401-L402)) while go-libp2p doesn't send any length.

I have managed to successfully connect to go-libp2p after I removed [sending the prefix](https://github.com/libp2p/rust-libp2p/blob/bd5e81fedbc5aa9bf941a8ba5da02dee26f291e3/protocols/noise/src/io/handshake.rs#L401-L402) and temporarily replacing [these lines](https://github.com/libp2p/rust-libp2p/blob/bd5e81fedbc5aa9bf941a8ba5da02dee26f291e3/protocols/noise/src/io/handshake.rs#L362-L364) with a hard-coded length.

**Comment by burdges** [comment]
https://eli.thegreenplace.net/2011/08/02/length-prefix-framing-for-protocol-buffers

**Comment by tomaka** [comment]
In this situation we know that the first Noise messages exchanged consist entirely in a protobuf message and nothing else.
Noise messages themselves are length-delimited, so I suppose that it wasn't deemed necessary to indicate the length again inside of the encrypted messages themselves.

**Comment by tomaka** [comment]
> In this situation we know that the first Noise messages exchanged consist entirely in a protobuf message and nothing else.

Although this isn't necessarily the case in the absolute as far as I understand, and length-prefixing the protobuf messages would probably have been a good idea.

**Comment by pawanjay176** [comment]
Isn't the noise spec wire format saying that we _do_ require length prefix for handshake payloads as well?!
https://github.com/libp2p/specs/tree/master/noise#wire-format

**Comment by sinkingsugar** [comment]
Well, the spec got changed. go follows it as now nim too:
https://github.com/status-im/nim-libp2p/commit/7852c6dd0f00f40463227a39a9ec6ea5782c5d36

**Comment by tomaka** [comment]
I believe that it should be possible to be both compatible with go-libp2p and rust-libp2p by trying to parse the handshake either with or without a length prefix. We should probably try to parse the handshake first as if it had a length prefix, as the chances that a protobuf message is encoded as a sequence of bytes that is accidentally representing a length prefix plus another valid protobuf handshake seem extremely low to me.

As a cryptography layman I'm wondering if this could lead to a security vulnerability.
Considering that protobuf messages can be encoded in multiple different ways, it is already the case that multiple different handshakes represent the same public key. Accepting a handshake either with or without a length prefix can be considered as another potential variation in the input.

**Comment by tomaka** [comment]
@romanb Would you mind looking into this?

**Comment by romanb** [comment]
As of [libp2p-0.23](https://crates.io/crates/libp2p/0.23.0), the `libp2p-noise` implementation should be interoperable by default.
