### ISSUE TITLE
Refactoring??

### ISSUE THREAD

**Issue by kingwel-xie** [libp2p/rust-libp2p#1659]
Hi,

I'm new to rust but have some expierence on go-libp2p. With all due resepct, this repo seems very hard to understand for developers who want to do some stuff. I tend to believe it is because the code is a bit old fashion without good support on async/await at that time. Futhermore, the generic traits look somehow abused which makes it is even harder to figure out which is what. 

I can give an example here. Looking at the go implementation, the echo example is quite simple but it could take more than 1000 lines to make an equivalent with rust-libp2p. Actually I think all we want is a substream which implements AsyncRead/AsyncWrite, so that we can read/write with .await.

So, my question is, is there a plan to refactor or even to start over?

Regards,
Kingwel

**Comment by tomaka** [comment]
While it's true that the library is a bit more complicated than it could be, keep in mind that many of the complications exist for a reason. Any non-trivial networking is inherently complicated, and I think that logically correct code and proper flow control is a more important criteria than the complexity of a ping example.

I do personally believe that `libp2p-core` is a very good foundation on top of which one can write any kind of API.

On top of `libp2p-core` there is `libp2p-swarm` whose complexity mostly comes from the problem of how to combine multiple protocols in a generic way without causing troublesome interactions between them.

I also do believe that one could expose a very simply API by adding another layer on top of `libp2p-swarm` and the various protocols.

**Comment by kingwel-xie** [comment]
Thanks for the answer. Unfortunately it doesn't sound very convincing. 

Again, the code is too complicated, and extremely tightly coupled, with stacked state matchines. I think it doesn't make sense to mantain or even to evolve code written like this.

Sorry for all the negative information, but I have to move on...

**Comment by mxinden** [comment]
> but I have to move on...

Closing here then. For anyone with concrete or actionable suggestions, feel free to open up another issue.

**Comment by tomaka** [comment]
> Again, the code is too complicated, and extremely tightly coupled, with stacked state matchines. I think it doesn't make sense to mantain or even to evolve code written like this.

Feel free to write an alternative implementation.
