### ISSUE TITLE
mDNS not compatible with go 

### ISSUE THREAD

**Issue by semtexzv** [libp2p/rust-libp2p#1678]
I have implementation of simple p2p application running in both go and rust. When testing, go can reach go nodes using mDNS, and rust can reach rust nodes, but not accross. It seems that the implementations are incompatible.

Go code:
https://github.com/semtexzv/go-ipcs/blob/master/node/node.go
Rust code:
https://github.com/semtexzv/ipcs/blob/master/node/src/net/mod.rs

**Comment by tomaka** [comment]
As far as I know, rust-libp2p follows the libp2p specifications, and it's Go and JS which aren't compliant here.

**Comment by semtexzv** [comment]
Just opened https://github.com/libp2p/specs/blob/master/discovery/mdns.md. Seems you're right

Rust uses the `_p2p._udp.local` service name, while go uses `_ipfs-discovery._udp.local`.

**Comment by gobengo** [comment]
> it's Go and JS which aren't compliant here.

It appears that js-libp2p-mdns uses the newest specced `_p2p._udp.local` as of version `7` in March 2023
https://github.com/libp2p/js-libp2p-mdns/blame/cb8e2aebf46381038f6959a2c7dbd1f10c68a301/src/index.ts#L43
