### ISSUE TITLE
Unable to find keys.proto file on NixOS

### ISSUE THREAD

**Issue by jaybutera** [libp2p/rust-libp2p#1689]
Currently, building fails on libp2p-core in NixOS:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/casper/.cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-core-0.20.1/build.rs:22:5
```

The line that fails can't find the `keys.proto` file which is specified as a raw path:
```
prost_build::compile_protos(&["src/keys.proto"], &["src"]).unwrap();
```

**Comment by bkchr** [comment]
Hey, I don't have any problems on NixOS. I'm using the following `shell.nix` file:
https://github.com/bkchr/nixos-config/blob/85ff64fc050604fdcf59ff7ed46328083656c048/home/files/projects/parity/shell.nix#L13

**Comment by jaybutera** [comment]
Awesome thank you! This works. I modified the spec for an explicit Mozilla overlay
[https://gist.github.com/jaybutera/b8f800d0c421fffd9ac2cd5a3f36d037](https://gist.github.com/jaybutera/b8f800d0c421fffd9ac2cd5a3f36d037)
