### ISSUE TITLE
Specifying scope for IPv6 link local addresses.

### ISSUE THREAD

**Issue by jeandudey** [libp2p/rust-libp2p#1703]
Currently `Multiaddr` can't be used to create an IPv6 address with an scope identifier for link local addresses, on the majority of Operating Systems they're used to disambiguate the network interface where the address belongs to. This is a blocker on IPv6 only networks that aren't connected to internet and don't have any kind of global IPv6 addresses (even without ULA addresses), just a plain disconnected IPv6 network.

I'm not sure how this can be handled on the `Multiaddr` syntax, or if it's wanted to do so _- It would be very bad for IPv6 users if not :-( -__

RFC 6874 specifies a syntax for the scope id (or zone identifier), being it:

```
addr := <ip6addr> '%'  <ascii letters that don't contain URI reserved characters>
```

Maybe a syntax for Multiaddr like this could be used:

```
/ip6/fe80::1%lan0/tcp/0
```

But it would break the existing implementation as it would require to modify `Protocol::Ip6` with something like `Protocol::Ip6(Ipv6Addr, Option<String>)`. Other option I see is to create a new `Protocol` entry called `Protocol::Ip6ZoneId(String)` and with a syntax like:

```
/ip6/fe80::1/ip6-zone-id/lan0/tcp/0
```

**See also**

- [RFC 2535, 3.3 Socket Address Structure for 4.3BSD-Based Systems](https://tools.ietf.org/html/rfc2553#section-3.3)
- [RFC 6874](https://tools.ietf.org/html/rfc6874)
- #873 , without proper handling for zones we couldn't use AAAA records, as they're link local.

**Comment by mxinden** [comment]
@jeandudey thanks for the detailed issue!

This multiaddr implementation follows the specification, thus I think it is a better idea to discuss this in https://github.com/multiformats/multiaddr/ and not here.

Browsing through the issues I have found https://github.com/multiformats/multiaddr/issues/87 which also covers IPv6 link scopes.

**Comment by mxinden** [comment]
I interpret your :+1: as agreement and thus I am closing this issue. Feel free to open a follow up issue in case we can be of any other help.
