### ISSUE TITLE
`ProtocolsHandler` methods need to be implemented in helpers.

### ISSUE THREAD

**Issue by twittner** [libp2p/rust-libp2p#1707]
The `ProtocolsHandler` trait has several methods with default implementations, in particular

- `inject_address_change`
- `inject_listen_upgrade_error`

It also has some helper functionality like `map_in`, `map_out` or `select`. The traits impls from those do not implement these methods by forwarding the calls to their inner impls. `ProtocolsHandler` types which have been mapped or selected, will thus miss those callback.

**Comment by romanb** [comment]
Closed by https://github.com/libp2p/rust-libp2p/issues/1707, though there may be more refinements later.
