### ISSUE TITLE
Unconventional use of Poll::Pending in network behaviours and protocol handlers

### ISSUE THREAD

**Issue by mzabaluev** [libp2p/rust-libp2p#1728]
The existing implementations of `NetworkBehaviour::poll` and `ProtocolsHandler::poll` tend to return `Poll::Pending` when there is nothing to do, without arranging a wakeup via the `Context`. This violates [the general convention](https://doc.rust-lang.org/std/task/enum.Poll.html#variant.Pending) for polling methods, meant to prevent task hangups. Currently the call sites in the library appear to mask this by also polling I/O objects and doing keep-alive processing using a separately implemented method, but this is prone to subtle breakage under changes, as the non-conventional polling behaviour needs to be taken account of differently from conventionally behaving pollable objects. For an example, it's not easy for me to tell if this [poll method implementation](https://github.com/libp2p/rust-libp2p/blob/0b05b2109358d064b2aab286cb7170e763793e38/swarm/src/protocols_handler/node_handler.rs#L232-L232) never causes the task to hang up.

I suggest a simple refactoring to remove this quirk: add an `Idle` variant to the enum types returned in `Poll::Ready`, to be used instead of `Poll::Pending` when the implementing object has neither work to do nor a wakeup scheduled later. At present, the code using `ProtocolsHandler::poll` calls `ProtocolsHandler::connection_keep_alive` immediately after as part of processing for the idle case, so it may also make sense to include a `KeepAlive` value in the `Idle` variant and eliminate the separate `connection_keep_alive` method.

**Comment by tomaka** [comment]
I do believe that or usage of `Pending` is correct. Situations where we don't arrange a wakeup exist because there isn't any situation that could ever warrant a wakeup.

After one of the `inject_*` methods is called, which have the effect of changing the internal state of the `NetworkBehaviour` or `ProtocolsHandler`, our knowledge of the "polling status" changes from "pending" to "unknown".
This is why, for both of these traits, it is required that `poll` gets called after every call to one of the `inject_*` methods.
I'm pretty confident that this was explicitly documented at some point, but it might have been lost with all the refactorings we've had over time.

**Comment by mzabaluev** [comment]
While not knowing the code in detail, I'm concerned about dead end situations where a task never calls `inject_*` because no event to trigger this was returned from a poll and no wakeup was scheduled. As far as I understand, this is currently prevented by making polls for I/O objects and timeouts in the same loop with polling the handler impl. So there should be always something else to make progress on, but the async logic is spread between the library and client-provided trait implementations and is therefore more difficult to follow.

Having said that, I'm not aware of any preferred paradigm to organize asynchronous event-driven processing in Rust. The network frameworks I've had experience with tend to provide IoC-style APIs, where the application provides async trait implementations for the functionality, but does not get to plug into the control loop in more explicit ways. `request_response` is one libp2p example where the library has control over polling, making it more convenient to implement the protocol (at the cost of removing any async processing from the application). Other protocol impls I've looked at in rust-libp2p, substrate, and lighthouse tend to heavily involve event queues internally, suggesting that there may be more use cases where the library can take responsibility over driving the state machine.

**Comment by mzabaluev** [comment]
As there is no consensus on whether there is a problem, let's close this issue.
