### ISSUE TITLE
Ping protocol tests fail when mplex is used instead of yamux. 

### ISSUE THREAD

**Issue by artemii235** [libp2p/rust-libp2p#1758]
#### Some background

Our team is using Ping protocol as part of bigger combined behaviour that derives `NetworkBehaviour`. We had few issues with Yamux so switched to Mplex. We've noticed ping timeouts while there's no actual reason for this to happen so I started digging and discovered that Ping doesn't seem to work properly when Mplex is used.

#### How to reproduce:

1. Rust toolchain used: `nightly-2020-02-01-x86_64-apple-darwin`
1. Use the latest master state.
1. Use Mplex instead of Yamux at https://github.com/libp2p/rust-libp2p/blob/master/protocols/ping/tests/ping.rs#L209
1. Run Ping protocol tests.

#### Expected behavior:

Tests pass

#### Actual behavior

`max_failures` fails and `ping_pong` runs indefinitely.

**Comment by romanb** [comment]
> We had few issues with Yamux so switched to Mplex.

It would be great if you could report any issues you encountered at https://github.com/paritytech/yamux, if you think there is a problem in the Yamux implementation.

**Comment by artemii235** [comment]
> It would be great if you could report any issues you encountered at https://github.com/paritytech/yamux

We did our tests a couple of months ago, things might have changed as yamux version was upgraded. I'm going to retest the yamux today and check whether problems we encountered are solved. If not I will create an issue in yamux repo.

**Comment by romanb** [comment]
This should now be fixed in `master` and there will probably be new releases this week. Thanks a lot for the report.
