### ISSUE TITLE
core: "No such file or directory" when building

### ISSUE THREAD

**Issue by xwvvvvwx** [libp2p/rust-libp2p#1774]
I get an error when building `libp2p-core` using `cargo 1.45.1`:

```
error: failed to run custom build command for `libp2p-core v0.22.1`

Caused by:
  process didn't exit successfully: `/home/me/code/mine/libp2p-failing/target/debug/build/libp2p-core-c77ba72de18eca7e/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-core-0.22.1/build.rs:22:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

warning: build failed, waiting for other jobs to finish...
error: build failed
```

I created a small repo that I can use to reproduce the issue: https://github.com/xwvvvvwx/libp2p-rs-failing-example

It appears to be failing because it can't find the `src/keys.proto` file [here](https://github.com/libp2p/rust-libp2p/blob/master/core/build.rs#L22).

I'm building on nixos unstable.

I'm pretty new to rust, so apologies if I'm missing something obvious...

**Comment by romanb** [comment]
Maybe the comments in https://github.com/libp2p/rust-libp2p/issues/1689 help since it seems to be the same problem?

**Comment by xwvvvvwx** [comment]
This was exactly the problem. Thanks!!!
