### ISSUE TITLE
ProtocolsHandler::listen_protocol should have &mut self recipient

### ISSUE THREAD

**Issue by mzabaluev** [libp2p/rust-libp2p#1777]
It's useful to be able to mutate the object state when calling `listen_protocol`, so as to return distinct values in `InboundProtocol`/`InboundOpenInfo`. As a case in point, `request_response` works around this by incrementing an `AtomicU64` member which does not have other genuine needs to be atomic.

**Comment by romanb** [comment]
Off the top of my head, there is one thing to keep in mind that may make such a change not straight-forward: Recording local state in `listen_protocol()`, which becomes easy with `&mut self`, can result in a potential memory leak if not every call to `listen_protocol()` is guaranteed to be paired eventually with either `inject_fully_negotiated_inbound` or `inject_listen_upgrade_error`. However, that is easily violated if `listen_protocol()` combines multiple alternatives by calling `listen_protocol()` on nested handlers, like the [MultiHandler does](https://github.com/libp2p/rust-libp2p/blob/0b05b2109358d064b2aab286cb7170e763793e38/swarm/src/protocols_handler/multi.rs#L102-L114). However, at the end only one of these protocols is actually negotiated and upgraded, and so only one of the nested handlers will get one of the other callbacks invoked.

This then either means that nesting handlers in this way is declared generally unsound or, rather, that the approach for when to call `inbound_protocol()` and hence the upgrade process needs to be rethought, possibly by splitting it in two steps where the first is really just about asking handlers for supported alternative protocols, which can be combined from multiple handlers, and only once protocol negotiation is complete the handler is asked for the `SubstreamProtocol` upgrade for the negotiated protocol. That is likely a very invasive change.

At least, if `&mut` is offered in the current implementation, it should be clearly documented that calls to `listen_protocol()` should not "grow" the local state (or if so, that `poll()` must then eventually shrink it again), as it may not be followed by a call to `inject_fully_negotiated_inbound` or `inject_listen_upgrade_error` which would allow to reverse such a change of state.

**Comment by mzabaluev** [comment]
@romanb Thank you, I see that resolving this properly would require a more substantial redesign.
