### ISSUE TITLE
replace code-gen macros in tcp and uds with async-io

### ISSUE THREAD

**Issue by dvc94ch** [libp2p/rust-libp2p#1787]
While working on refactoring the transport trait to accomodate quic or port reuse in tcp, it seemed like the code needs some maintainance. I think async-io should work fine for any executor, so the `TokioTcp` and `Tcp` stuff can be simplified to just `Tcp`. Unless there are any objections I'll submit a PR as soon as https://github.com/stjepang/async-io/issues/36 gets fixed.

**Comment by ericjmiller** [comment]
I think this could affect implementation of #1820.

**Comment by dvc94ch** [comment]
This issue was resolved I guess.
