### ISSUE TITLE
Use the protobuf-codegen library to generate the protobuf at compile-time

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#183]
This wasn't done before because this requires installing `protoc` on the machine that compiles `libp2p`.
However a new crate https://crates.io/crates/protobuf-codegen was released, and is pure Rust and can thus be used.

**Comment by jamesray1** [comment]
Hmmm I'm having trouble with this: https://github.com/jamesray1/rust-libp2p/tree/master/floodsub. I just went by the example in https://github.com/stepancheg/rust-protobuf/tree/master/protobuf-codegen-pure.

**Comment by Vurich** [comment]
Currently this is impossible because (as far as I can tell) `protobuf-codegen-pure` doesn't correctly implement all the features of protobuf that we use. Their tests pass but on our codebase (specifically, as @jamesray1 said, on floodsub) it generates code using a private module.

**Comment by jamesray1** [comment]
OK, so as per comments in https://github.com/stepancheg/rust-protobuf/issues/307#issuecomment-398592473, I'm getting an error with ring on Windows.

Here is the branch to run: https://github.com/jamesray1/rust-libp2p/tree/protobuf-codegen-pure.

**Comment by jamesray1** [comment]
Oh, I see you've made a PR.

**Comment by tomaka** [comment]
See comments in #255

**Comment by tomaka** [comment]
Done in #1390
