### ISSUE TITLE
Yamux: add the possibility to increase the window size of the remote in anticipation

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#1849]
The default yamux window size is 256kiB (according to the yamux specifications).

What this means is that, when a substream is opened, each side is allowed to send 256kiB of data, after which the remote must send a "window update" frame similar to a TCP ACK.
See [the specs](https://github.com/hashicorp/yamux/blob/master/spec.md#flow-control) for more information.
I'm not totally sure, but by looking at the code, I believe that our current yamux implementation [always sends back windows updates of 256kB](https://github.com/paritytech/yamux/blob/df476efbaf6ba3852c0ccd964601acd243ad7fb8/src/connection/stream.rs#L311).

In the scope of request-response protocols, a substream is opened specifically for this request and response.
If the response is, for example, 10MiB, the first 256kiB will be sent on the network, then the emitter has to wait for the window update, then the next 256kiB are sent, then the emitter waits, and so on. Sending the entire 10MiB of data would take 39 round trip times.

In order to solve that problem, I think it makes sense to expose on the `StreamMuxer` trait a way to send a big window size frame to the remote, in anticipation. The size of this window size frame could be the maximum allowed size of the response according to the higher-level protocol.

**Comment by romanb** [comment]
I'm not sure I understand. If the client sending the requests for which it is expecting 10MiB responses configures a `receive_window` of `10MiB` or more, the substream will be initiated by the requester with an appropriate window update and hence the responder can send the `10MiB` happily, right?

**Comment by tomaka** [comment]
> I'm not sure I understand the problem. If the client sending the requests for which it is expecting 10MiB responses configures a receive_window of 10MiB or more, the substream will be initiated by the requester with an appropriate window update and hence the responder can send the 10MiB happily, right?

Indeed!
The problem is that we only want to use a receive window of 10MiB for specifically *that* substream, which isn't possible at the moment as far as I know.

**Comment by romanb** [comment]
Understood, so this is a request for a substream-specific receive window configuration and exposing it via the `StreamMuxer` API. It may make sense to also open a separate ticket for `yamux`. @mxinden since you volunteered, I'm taking the liberty of assigning you already, just for clarity.

**Comment by romanb** [comment]
So, despite not permitting configuration of the receive window for particular substreams, is https://github.com/paritytech/yamux/pull/114 and in particular the early sending of window updates supposed to be sufficient to address this issue?

**Comment by tomaka** [comment]
We want to be able to transfer 10MiB as quickly as possible. In other words, sending 10MiB over a Yamux substream should be approximately the same speed as sending 10MiB over a plain TCP connection with a realistic ping (say ~100-200ms).

I doubt this is possible by just doing implicit magic within `yamux`, but I'm willing to be proven wrong.

**Comment by romanb** [comment]
It would be good to get https://github.com/paritytech/yamux/pull/114 integrated into a `libp2p` release though, so that we can try it out in substrate. Since Max no longer has write access to that repository, I need an approval from someone who does :pray: .

**Comment by mxinden** [comment]
> So, despite not permitting configuration of the receive window for particular substreams, is [paritytech/yamux#114](https://github.com/paritytech/yamux/pull/114) and in particular the early sending of window updates supposed to be sufficient to address this issue?

I would expect https://github.com/paritytech/yamux/pull/114 to achieve the same performance improvement as the solution proposed in this pull request.

> We want to be able to transfer 10MiB as quickly as possible. In other words, sending 10MiB over a Yamux substream should be approximately the same speed as sending 10MiB over a plain TCP connection with a realistic ping (say ~100-200ms).

Simulating different networks, among others a mobile connections with a 100ms round trip time, showed that https://github.com/paritytech/yamux/pull/114 achieves the same performance improvement as setting the receive window to 10MiB up front, as suggested in this Github issue. See the [concrete numbers here](https://github.com/paritytech/yamux/issues/100#issuecomment-774461550).

Of course, the simulations I used are a simplification of the real-world. I only tested https://github.com/paritytech/yamux/pull/114 in one real-world scenario, namely a libp2p connection between Berlin and Helsinki with an 11 MBit/s [iperf](https://en.wikipedia.org/wiki/Iperf) throughput. In this setup https://github.com/paritytech/yamux/pull/114 did show a considerable performance improvement (namely from previous 7 MBit/s to now 8.7 MBit/s). See [this comment for the concrete numbers](https://github.com/paritytech/yamux/issues/100#issuecomment-777046696). I would consider a throughput of 8.7 MBit/s on top of Yamux and Noise to be quite close to a plain TCP connection with 11 MBit/s.

> I doubt this is possible by just doing implicit magic within yamux, but I'm willing to be proven wrong.

> It would be good to get paritytech/yamux#114 integrated into a libp2p release though, so that we can try it out in substrate.

Thank you @romanb and @tomaka for giving this a shot.

**Comment by thomaseizinger** [comment]
Closing this as resolved, plus we are likely going to focus future efforts on QUIC.
