### ISSUE TITLE
How can I use libp2p simply for NAT traversal?

### ISSUE THREAD

**Issue by actuday6418** [libp2p/rust-libp2p#1861]
Disclaimer: I don't have an education in networking, so please forgive my naivety.

Hey, 
I want to send data over the internet from one computer behind a router to another also behind a router. I don't need this data to be encrypted or anything. I don't need the computers to discover each other either. 

The way I understand it, NAT works by forwarding traffic from the router's public address to a device's private one. If there is a way for the router to know that the incoming data must go to a particular node in it's private network, shouldn't there be some way of identifying to which node within a private network a data packet must go? So then the data packet will have some identifying characteristic ( address, port? ). Can I determine this address and then use that to send data from one computer to another?

**Comment by mxinden** [comment]
Hi @actuday6418,

I think the concept of NAT is too complex to summarize in a single Github issue. As a first introduction I would propose reading through the [Wiki article](https://en.wikipedia.org/wiki/NAT_traversal). As `rust-libp2p` uses TCP as its underlying transport protocol the [TCP hole punching](https://en.wikipedia.org/wiki/TCP_hole_punching) article might be of some help as well.

Today `rust-libp2p` does not offer any NAT traversal strategies. You can follow current efforts on https://github.com/libp2p/rust-libp2p/issues/1722.

In case you control the routers in front of both machines you might be able to open and forward specific ports from those routers to your machines. For details see the [port forwarding](https://en.wikipedia.org/wiki/Port_forwarding) article.

**Comment by actuday6418** [comment]
@mxinden Unfortunately, I don't control the routers. What I said originally was a simplified version of the truth. My ISP has got NAT too other than that in my router (router's WAN address was different from my public address). So port forwarding won't help.

I'll definitely look into TCP hole punching. Thanks for the info. As an afterthought, does  

> Today rust-libp2p does not offer any NAT traversal strategies

mean there is no way for two peers behind NAT not controlled by them to communicate using libp2p? Or is that specific to the Rust implementation?

**Comment by mxinden** [comment]
> mean there is no way for two peers behind NAT not controlled by them to communicate using libp2p? Or is that specific to the Rust implementation?

This is specific  to the Rust implementation, which does not support NAT traversal _yet_. Take a look at the [general libp2p docs](https://docs.libp2p.io/concepts/nat/) to find out more about other implementations.

**Comment by romanb** [comment]
> This is specific to the Rust implementation, which does not support NAT traversal yet. 

I don't think (TCP) hole punching works with any libp2p implementation beyond very simple cases of NAT (https://github.com/libp2p/specs/pull/196). Related discussions include https://github.com/libp2p/rust-libp2p/issues/1690#issuecomment-669931399 and https://github.com/libp2p/rust-libp2p/issues/1563.

**Comment by romanb** [comment]
There is a recent effort to revive the libp2p relay protocol (https://github.com/libp2p/rust-libp2p/pull/1838), which is practically speaking the option for NAT traversal that has the highest change of success in any network setup. As alluded to earlier, sophisticated hole punching techniques that function without intermediate relays are not really possible with `rust-libp2p` at this time. I'm considering this question answered, but feel free to open new specific issues or new [discussions](https://github.com/libp2p/rust-libp2p/discussions).

**Comment by lukebelbina** [comment]
Out of curiosity is there a link to a discussion on why this is not possible in rust? Is it a language issue (it would be possible in other languages) or an architectural issue?

**Comment by mxinden** [comment]
> > There is a recent effort to revive the libp2p relay protocol (#1838), which is practically speaking the option for NAT traversal that has the highest chance of success in many network setups. As alluded to earlier, sophisticated hole punching techniques that function without intermediate relays are not really possible with `rust-libp2p` at this time. I'm considering this question answered, but feel free to open new specific issues or new [discussions](https://github.com/libp2p/rust-libp2p/discussions).
> 
> Out of curiosity is there a link to a discussion on why this is not possible in rust? Is it a language issue (it would be possible in other languages) or an architectural issue?

@lukebelbina the important bit is "with `rust-libp2p` **at this time**". NAT hole punching is currently under development for go-libp2p (see https://github.com/protocol/web3-dev-team/pull/21/files) and will eventually make it into rust-libp2p as well. As always, help would be appreciated.

**Comment by mxinden** [comment]
Following up here for future readers: Progress is tracked in https://github.com/libp2p/rust-libp2p/issues/2052.
