### ISSUE TITLE
[ci]: `broken_intra_doc_links` is stabilized in Rust 1.48

### ISSUE THREAD

**Issue by niklasad1** [libp2p/rust-libp2p#1864]
https://doc.rust-lang.org/rustdoc/lints.html#broken_intra_doc_links is stablized in `Rust 1.48`, pinning a specific nightly version for it is not needed anymore.

Thus,  https://github.com/libp2p/rust-libp2p/blob/master/.github/workflows/ci.yml#L104-#L107 can be removed.

**Comment by mxinden** [comment]
Thanks @niklasad1!
