### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by jamesray1** [libp2p/rust-libp2p#187]
https://github.com/libp2p/specs/ doesn't mention rust libp2p much. Could you open up a project tracker for this repo, documenting what has been done, what is in progress and what needs to be done?

I am looking at using rust-libp2p for Ethereum sharding with [Drops of Diamond](https://github.com/Drops-of-Diamond/diamond_drops).

The following features don't show up for rust-libp2p or in search results, so I suggest adding them to issues and the project tracker:
- [ ] [interface-transport](https://github.com/libp2p/interface-transport)
- [x] [Circuit Relay](https://github.com/libp2p/specs/tree/master/relay)
- [ ] https://github.com/libp2p/interface-connection
- [ ] https://github.com/multiformats/multiaddr#implementations (listed as a beta for Rust)
- [ ] https://github.com/libp2p/interface-stream-muxer
- [ ] https://github.com/multiformats/multicodec#implementations
- [ ] gossipsub, see https://github.com/libp2p/go-floodsub/issues/77 for an introduction
- [ ] random-walk
- [ ] NAT traversal, e.g. `libnice`, `libwebrtc`, or `natty`. This actually [appears to be implemented](https://github.com/libp2p/rust-libp2p/search?utf8=%E2%9C%93&q=nat_traversal&type=0, it is just not too easy to find, so this is more of a docs issue.

> There are Rust implementations of all the major formats that IPFS is using:

> <ul>
> <li><a href="https://github.com/multiformats/rust-multiaddr">rust-multiaddr</a></li>
> <li><a href="https://github.com/multiformats/rust-multihash">rust-multihash</a></li>
> <li><a href="https://github.com/multiformats/rust-multibase">rust-mutlibase</a></li>
> <li><a href="https://github.com/ipld/rust-cid">rust-cid</a></li>
> </ul>
> — https://github.com/libp2p/libp2p/issues/33#issuecomment-392007707

What's already done in rust-libp2p:
<p>This repository includes a facade crate named <code>libp2p</code>, which reexports the rest of the repository.</p>
<h2><a id="user-content-general-overview-of-the-architecture" class="anchor" aria-hidden="true" href="#general-overview-of-the-architecture"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M4 9h1v1H4c-1.5 0-3-1.69-3-3.5S2.55 3 4 3h4c1.45 0 3 1.69 3 3.5 0 1.41-.91 2.72-2 3.25V8.59c.58-.45 1-1.27 1-2.09C10 5.22 8.98 4 8 4H4c-.98 0-2 1.22-2 2.5S3 9 4 9zm9-3h-1v1h1c1 0 2 1.22 2 2.5S13.98 12 13 12H9c-.98 0-2-1.22-2-2.5 0-.83.42-1.64 1-2.09V6.25c-1.09.53-2 1.84-2 3.25C6 11.31 7.55 13 9 13h4c1.45 0 3-1.69 3-3.5S14.5 6 13 6z"></path></svg></a>General overview of the architecture</h2>
<p>Architecture of the other crates of this repository:</p>
<ul>
<li><code>datastore</code>: Utility library whose API provides a key-value storage with multiple possible
backends. Used by <code>peerstore</code>.</li>
<li><code>example</code>: Example usages of this library.</li>
<li><code>libp2p-identify</code>: Protocol implementation that allows a node A to query another node B what
information B knows about A. Implements the <code>ConnectionUpgrade</code> trait of <code>libp2p-core</code>.</li>
<li><code>libp2p-peerstore</code>: Generic storage for information about remote peers (their multiaddresses and
their public key), with multiple possible backends. Each multiaddress also has a time-to-live.
Used by <code>libp2p-core</code>.</li>
<li><code>libp2p-ping</code>: Implementation of the <code>ping</code> protocol (the exact protocol is specific to libp2p).
Implements the <code>ConnectionUpgrade</code> trait of <code>libp2p-core</code>.</li>
<li><code>libp2p-secio</code>: Implementation of the <code>secio</code> protocol. Encrypts communications. Implements the
<code>ConnectionUpgrade</code> trait of <code>libp2p-core</code>.</li>
<li><code>libp2p-core</code>: Core library that contains all the traits of <em>libp2p</em> and plugs things together.</li>
<li><code>libp2p-tcp-transport</code>: Implementation of the <code>Transport</code> trait of <code>libp2p-core</code> for TCP/IP.</li>
<li><code>libp2p-websocket</code>: Implementation of the <code>Transport</code> trait of <code>libp2p-core</code> for Websockets.</li>
<li><code>multistream-select</code>: Implementation of the <code>multistream-select</code> protocol, which is used to
negotiate a protocol over a newly-established connection with a peer, or after a connection
upgrade.</li>
<li><code>rw-stream-sink</code>: Utility library that makes it possible to wrap around a tokio <code>Stream + Sink</code>
of bytes and implements <code>AsyncRead + AsyncWrite</code>.</li>
</ul>

**Comment by tomaka** [comment]
For `circuit-relay`, there is an open pull request here: #175 

For the rest, the API of rust-libp2p is slightly different from the one of other libp2p implementations because we've been trying to maximize performances as much as possible.
Also note that rust-libp2p is maintained mainly by Parity (and not by Protocol Labs), so we've been having a different look at things compared to the other two implementations.

**Comment by tomaka** [comment]
For general questions about the direction of the project, I would suggest joining the #libp2p IRC channel on Freenode.

**Comment by jamesray1** [comment]
Will do, thanks! Note that the intention is for the Drops of Diamond sharding implementation to eventually integrate with Parity.

**Comment by jamesray1** [comment]
I just added another one: gossipsub, see https://github.com/libp2p/go-floodsub/issues/77 for an introduction.

**Comment by jamesray1** [comment]
According to https://github.com/libp2p/libp2p/issues/33, gossipsub is preferable to floodsub for sharding implementation.

**Comment by jamesray1** [comment]
protobuf isn't supported for Rust, so I'll have to use something else.

**Comment by tomaka** [comment]
Let's close this issue as it is one and a half years old.
