### ISSUE TITLE
Remove redundant cloning of `PeerId`s

### ISSUE THREAD

**Issue by romanb** [libp2p/rust-libp2p#1888]
After https://github.com/libp2p/rust-libp2p/pull/1874 there are likely still unnecessary `.clone()` calls being made throughout the code base. These should be removed.

**Comment by jgraef** [comment]
Hey. I have a branch that actually addresses this in a couple of places by changing some functions to take the `PeerId` by reference.

I'm pretty sure I didn't find all the places where unnecessary `clone`s are done, but it might be a start.

I think my branch also includes some other changes*, but I could separate them.

Anyway, I might not have time to work on this right now. My changes are here: https://github.com/jgraef/rust-libp2p/tree/janosch/serde

* The other changes are adding `serde::{Serialize, Deserailize}` to some types, but gated behind a feature-flag. If anyone is interested in that.
