### ISSUE TITLE
Update salsa20 dependency version to 0.7

### ISSUE THREAD

**Issue by elenaf9** [libp2p/rust-libp2p#1890]
Libp2p-pnet still depends on the older version `salsa20-0.6.0`, which itself depends on the deprecated crate `stream-cipher`.
The salsa20 crate solved that issue with version `0.7`.
Ref [stronghold.rs#74](https://github.com/iotaledger/stronghold.rs/issues/74)

**Comment by elenaf9** [comment]
Additional note: libp2p-secio isn't a dependency of libp2p, but it has the same issue due to it's dependency to `aes-ctr-0.3` and `ctr-0.3`. Maybe also consider updating this to the current versions  `aes-ctr-0.6` and `ctr-0.6`.

**Comment by mxinden** [comment]
Thanks for the report @elenaf9!

> Additional note: libp2p-secio isn't a dependency of libp2p, but it has the same issue due to it's dependency to aes-ctr-0.3 and ctr-0.3.

Given that secio [is deprecated](https://blog.ipfs.io/2020-08-07-deprecating-secio/) we no longer actively maintain the `libp2p-secio` Rust implementation. In case there is interest to maintain it anyways, we welcome pull requests. See also https://github.com/libp2p/rust-libp2p/pull/1802.
