### ISSUE TITLE
New get_closest_peers signature prevents me to use arbitrary key (as was available in 0.31 version)

### ISSUE THREAD

**Issue by izderadicka** [libp2p/rust-libp2p#1898]
Hi, 
in 0.33 version kad method `get_closest_peers` changed signature:
```rust
pub fn get_closest_peers<K>(&mut self, key: K) -> QueryId
    where
        K: Into<kbucket::Key<K>> + Into<Vec<u8>> + Clone
```

With this signature I'm struggling how to submit arbitrary key -   like record::Key or Vec<8>.   From for kbucket::Key is implemented only for PeerId and Multihash.   Is this intentional?   How to use now with arbitrary key?

**Comment by mxinden** [comment]
First off @izderadicka do I understand correctly that you are using `get_closest_peers` to find a node closest to a given key, but retrieve the actual value corresponding to the key out-of-band i.e. with something other than `libp2p-kad`?

For the record this change was introduced in https://github.com/libp2p/rust-libp2p/pull/1874, you can find more details in https://github.com/libp2p/rust-libp2p/pull/1874#discussion_r537415361.

Off the top of my head I would suggest adding a `From<Vec<u8>> for Key<Vec<u8>>`:

```diff
diff --git a/protocols/kad/src/kbucket/key.rs b/protocols/kad/src/kbucket/key.rs
index e8d1af3e..7768d99c 100644
--- a/protocols/kad/src/kbucket/key.rs
+++ b/protocols/kad/src/kbucket/key.rs
@@ -111,6 +111,16 @@ impl From<PeerId> for Key<PeerId> {
     }
 }
 
+impl From<Vec<u8>> for Key<Vec<u8>> {
+    fn from(v: Vec<u8>) -> Self {
+        let bytes = KeyBytes(Sha256::digest(v.as_ref()));
+        Key {
+            preimage: v,
+            bytes
+        }
+    }
+}
```

That would allow you to call `get_closest_peers` with a `Vec<u8>`:

```diff
diff --git a/protocols/kad/src/behaviour.rs b/protocols/kad/src/behaviour.rs
index 5cfd12ca..97105e78 100644
--- a/protocols/kad/src/behaviour.rs
+++ b/protocols/kad/src/behaviour.rs
@@ -560,6 +560,15 @@ where
     ///
     /// The result of the query is delivered in a
     /// [`KademliaEvent::QueryResult{QueryResult::GetClosestPeers}`].
+    ///
+    /// ```
+    /// use libp2p_kad::{store::MemoryStore, Kademlia};
+    /// use libp2p_core::PeerId;
+    /// let peer_id = PeerId::random();
+    /// let store = MemoryStore::new(peer_id);
+    /// let mut behaviour = Kademlia::new(peer_id, store);
+    /// behaviour.get_closest_peers(vec![1, 2, 3, 4, 5]);
+    /// ```
     pub fn get_closest_peers<K>(&mut self, key: K) -> QueryId
```

@romanb given that you wrote most of this logic, does the above sound reasonable to you?

**Comment by izderadicka** [comment]
@mxinden purpose was somehow similar -  for testing and diagnostics -    get closes  peers for given key and then explore them.

**Comment by romanb** [comment]
This looks like an oversight. There should be `From<record::Key>` and `From<Vec<u8>>` instances for `kbucket::Key` that just delegate to `kbucket::Key::new`.

**Comment by mxinden** [comment]
@izderadicka do you want to prepare a pull request?

**Comment by mxinden** [comment]
Fixed with https://github.com/libp2p/rust-libp2p/pull/1909.
