### ISSUE TITLE
MDNS: Support multiple simultaneous interfaces

### ISSUE THREAD

**Issue by eskimor** [libp2p/rust-libp2p#1905]
While [this](https://github.com/libp2p/rust-libp2p/pull/1830) pull handles changes in the default interfaces well, it does not yet support multiple interfaces at the same time. This can be handled by using [platform specific functions](https://github.com/libp2p/rust-libp2p/pull/1750/files#diff-d82ec3ce9fb38291708105fbda3b4caeb5aa4d2d44a59b27c1e5a5679f9b9badR236) for specifying the outgoing interface for sending messages. By default, the implementation will pick the default interface for multicast messages, which works fine if there is only one interface.

**Comment by cryptoquick** [comment]
Would this be helpful if, say, I wanted peer discovery on a VPN, say, using https://github.com/dswd/vpncloud ? It sets up a separate network interface device, under `/sys/class/net` on Linux.

**Comment by eskimor** [comment]
I believe so - yes.

**Comment by cryptoquick** [comment]
That was the one thing I cratered on last I tried. This'd be a big help.

**Comment by dvc94ch** [comment]
this one can be closed
