### ISSUE TITLE
Gossipsub: unable to re-publish message after failed attempts.

### ISSUE THREAD

**Issue by xu-cheng** [libp2p/rust-libp2p#1926]
Sometimes, publishing message may fail in `Gossipsub` due to `PublishError::InsufficientPeers`. In this case, the application may want to retry the publish later. However, the subsequent re-publish would fail due to `PublishError::Duplicate` when a content-based hash is used to compute message id.

I think if a message fails to be published, it should be removed from `duplicate_cache` also maybe `mcache`.

**Comment by mxinden** [comment]
@AgeManning @blacktemplar would you mind taking a look?

**Comment by AgeManning** [comment]
Thanks for raising this edge case. 

This is an issue with content-addressed messages. I've updated the gossipsub protocol in #1930 to only add messages to the caches if they have been sent to at least one peer.

**Comment by romanb** [comment]
Closed by https://github.com/libp2p/rust-libp2p/pull/1930.
