### ISSUE TITLE
Debug implementation of `PublicKey` is too verbose

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#1939]
Printing the `PublicKey` enum is in my opinion way to verbose when using the `Ed25519` variant, which leads to a lot of pollution in logs.

It uses this underlying `Debug` implementation: https://github.com/dalek-cryptography/ed25519-dalek/blob/925eb9ea56192053c9eb93b9d30d1b9419eee128/src/public.rs#L44
Which in turn uses this `Debug` implementation: https://github.com/dalek-cryptography/curve25519-dalek/blob/b307c155c966c16b81f63a5872a1ec1977829ddf/src/edwards.rs#L928-L929

Simply printing the hexadecimal public key is in my opinion more than enough.

**Comment by romanb** [comment]
> Simply printing the hexadecimal public key is in my opinion more than enough.

I think only a hexadecimal encoding of the public key may be fine for `Display`, but for `Debug` I'd think you also at least want to see the type of key (`ed25519`, `rsa`, `secp256k1`).
