### ISSUE TITLE
deactivating dns-feature doesn't compile

### ISSUE THREAD

**Issue by gnunicorn** [libp2p/rust-libp2p#1952]
In substrate we are (effectively) building libp2p (`0.34.0` but I can also reproduce it on latest `master`) for `sc-network` as/with

```
cargo build --no-default-features --features "identify,kad,mdns,mplex,noise,ping,request-response,tcp-async-io,websocket,yamux"
```

[Which fails](https://gitlab.parity.io/parity/substrate/-/jobs/806889#L9444), `dns` is not activated but used by `build_tcp_ws_noise_mplex_yamux`:
```
   Compiling libp2p v0.35.0 (/home/ben/Dev/parity/rust-libp2p)
error[E0433]: failed to resolve: use of undeclared crate or module `dns`
   --> src/lib.rs:293:25
    |
293 |         let transport = dns::DnsConfig::new(tcp)?;
    |                         ^^^ use of undeclared crate or module `dns`

error: aborting due to previous error

```

This probably didn't  show up earlier, as we rarely build that package separately and in `node/cli` build it with default-features enabled. Adding `dns` to the feature list and all goes fine.

**Comment by romanb** [comment]
This has been addressed along the way in https://github.com/libp2p/rust-libp2p/pull/1927, which can hopefully be merged and released soon. Of course, if this issue has any urgency, we could patch it separately before #1927 is merged.

**Comment by gnunicorn** [comment]
no urgency. the now here linked patch shows that it actually originated from a wrong specification of features in substrate, so adding `dns` there was all that's needed for us to continue. The issues state here is still correct though.
