### ISSUE TITLE
libsecp256k1 is out of date and introduces a vulnerability

### ISSUE THREAD

**Issue by nothingismagick** [libp2p/rust-libp2p#1980]
libsecp256k1 is out of date, should be at `0.4.0`. The current `0.3.1` version is bringing in a vulnerable transitive dependency via `sha2 0.8.2`, which itself is ok, but requires `block-buffer 0.7.3` that uses the vunerable `generic-array 0.12.3`.

See: https://rustsec.org/advisories/RUSTSEC-2020-0146.html

https://github.com/libp2p/rust-libp2p/blob/6b5fa0324d65d363e0d7c9b3badad9307b8284af/core/Cargo.toml#L21

**Comment by nothingismagick** [comment]
https://github.com/paritytech/libsecp256k1/issues/66

**Comment by nothingismagick** [comment]
On a sidenote: 0.3.1 has been yanked. see: https://docs.rs/libsecp256k1/0.3.1/secp256k1/index.html

**Comment by dvc94ch** [comment]
Maybe we can deprecate rsa and secp256k1? I'd be happy to simply remove them, but not sure if they are widely used.

**Comment by thomaseizinger** [comment]
According to https://github.com/paritytech/libsecp256k1/issues/66#issuecomment-789018220, there is now a patch-release for `generic-array` so downstream projects should be able to fix that without `rust-libp2p` having to do anything.

**Comment by mxinden** [comment]
As far as I can tell, this is fixed with https://github.com/libp2p/rust-libp2p/pull/2074.
