### ISSUE TITLE
tcp port reuse is broken

### ISSUE THREAD

**Issue by dvc94ch** [libp2p/rust-libp2p#1991]
`inject_addr_reach_failure` and `inject_dial_failure` are called before `inject_connected`. a successful connection should not call those methods.

**Comment by mxinden** [comment]
@dvc94ch would you mind updating your report with more details as well as a way to reproduce the issue?

**Comment by dvc94ch** [comment]
I guess you can close it for now. I haven't had more time to look into it yet, but enabling port reuse breaks ipfs-embed.
