### ISSUE TITLE
Implement `std::error::Error` for `InboundFailure` and `OutboundFailure` of `request-response`?

### ISSUE THREAD

**Issue by thomaseizinger** [libp2p/rust-libp2p#2017]
It would be nice if these two types would implement `std::error::Error` and thereby `Display`. I am finding myself wanting to consolidate them using `anyhow` but that doesn't work at the moment.

**Comment by mxinden** [comment]
I don't have an opinion on `std::error::Error`. I though we discussed this in the past but I might be mistaken, at least I can't find a past discussion on this.

@thomaseizinger do you want to prepare a patch?
