### ISSUE TITLE
`/dns/` is no longer resolving records that are actually resolvable

### ISSUE THREAD

**Issue by montekki** [libp2p/rust-libp2p#2022]
Addr of bootnode in form `/dns/bootnode/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp` can no longer be reached, however `curl bootnode:9944` there from the node's machine works perfectly fine, [here are the logs of the node](https://gist.github.com/montekki/59af216a353e624c05e896bd8933f32b).

**Comment by tomaka** [comment]
Did you replace the actual domain name with `bootnode` in the logs, or is `bootnode` some sort of alias?
If it's an alias, we'll need more information.

**Comment by montekki** [comment]
The logs are unmodified copypaste, the `bootnode` is the name within the k8s cluster enviroment that can be `nslookup`ed: 

```
kubectl exec -i -t dnsutils -n fedor-gurke -- nslookup bootnode
Server:         10.27.240.10
Address:        10.27.240.10#53

Name:   bootnode.fedor-gurke.svc.cluster.local
Address: 10.27.247.34
```

**Comment by tomaka** [comment]
Ah, so it's not a full qualified domain name.

@mxinden Do you know why we do [this](https://github.com/libp2p/rust-libp2p/blob/bb206bcfdb8f43b71a560cc6938080369b033d48/transports/dns/src/lib.rs#L485-L491)?

**Comment by romanb** [comment]
> Do you know why we do this?

Really just as a naive attempt at optimisation that I didn't think much about, i.e. [from the docs](https://docs.rs/trust-dns-resolver/0.20.1/trust_dns_resolver/struct.Resolver.html#method.lookup_ip):

> For the least expensive query a fully-qualified-domain-name, FQDN, which ends in a final ., e.g. www.example.com., will only issue one query. Anything else will always incur the cost of querying the ResolverConfig::domain and ResolverConfig::search.

This obviously does not work with these kinds of indirections that require taking into account the local domain or search domains from the resolver configuration. I didn't really consider that at the time (i.e. we're taking about [this](https://github.com/bluejekyll/trust-dns/blob/main/crates/resolver/src/async_resolver.rs#L304-L341)). In hindsight we certainly cannot assume to always be given a domain that is an FQDN if we just stick a `.` at the end.

**Comment by montekki** [comment]
So, is there a chance for a fix, or should we just continue with FQDNs for now (a bit tricky for our case)?

**Comment by mxinden** [comment]
> `libp2p-dns` `v0.28.1` is [published](https://crates.io/crates/libp2p-dns/0.28.1) and [tagged](https://github.com/libp2p/rust-libp2p/releases/tag/libp2p-dns-0.28.1).
