### ISSUE TITLE
Implement Kademlia pinging oldest nodes to empty the k-buckets

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#206]
This is currently implemented with TODOs in the `libp2p-kad` crate.

**Comment by anacrolix** [comment]
What's driving this suggestion? I don't think go or js are doing this, and I don't know if it's specified anywhere.

**Comment by tomaka** [comment]
> What's driving this suggestion? I don't think go or js are doing this, and I don't know if it's specified anywhere.

That's what the original Kademlia paper says we should do. I have no idea what go-libp2p-kad and js-libp2p-kad do, but I opened this issue expecting that they more or less follow what the original Kademlia algorithm is.

However this issue can be closed. What rust-libp2p does now is try to connect to the oldest node. Considering that in libp2p pinging is done over TCP, there is little point in actually pinging the node if you have managed to successfully connect to it.
