### ISSUE TITLE
muxers/mplex: Allow up to 60 bit long stream IDs

### ISSUE THREAD

**Issue by mxinden** [libp2p/rust-libp2p#2061]
According to the [mplex specification](https://github.com/libp2p/specs/blob/master/mplex/README.md) a stream ID embedded in an mplex header can be up to 60 bit long.

> The maximum header length is 9 bytes (per the unsigned-varint spec). With 9 continuation bits and 3 message flag bits the maximum stream ID is 60 bits (maximum value of 2^60 - 1).

Today, Rust `libp2p-mplex` restricts mplex headers to 32 bit.

https://github.com/libp2p/rust-libp2p/blob/29d969be340b610e19bf05661b731883f25e6821/muxers/mplex/src/codec.rs#L156

The rust `libp2p-mplex` implementation should support up 60 bit long stream IDs like specified in the mplex specification.

See https://github.com/libp2p/specs/pull/317 for details.

**Comment by whereistejas** [comment]
Hi @mxinden ! If possible, I would love to take up this issue.

**Comment by mxinden** [comment]
Closing here since https://github.com/libp2p/rust-libp2p/pull/2094 is merged.
