### ISSUE TITLE
Multiaddr::to_url()

### ISSUE THREAD

**Issue by cryptoquick** [libp2p/rust-libp2p#2073]
Is there an easy way to turn a Multiaddr into an http url? Or a way to do something like this?

```rust
fn to_url(ma: Multiaddr) -> String {
    format!("{}://{}:{}/{}", ma.protocol(), ma.host(), ma.port(), ma.path())
}
```

**Comment by cryptoquick** [comment]
I got excited when I saw this, but oof
https://docs.rs/parity-multiaddr/0.11.2/parity_multiaddr/enum.Protocol.html

guess I'll just have to, hm, do some manual string parsing or something

**Comment by thomaseizinger** [comment]
A multiaddr can express a lot more things than a URL can so the mapping is not exactly trivial.

Can you provide an example multiaddr that you would like to convert to a URL?

**Comment by cryptoquick** [comment]
Sure:

`const DEFAULT_MULTIADDRESS: &str = "/ip4/127.0.0.1/tcp/1234/http";`
`const DEFAULT_URL: &str = "http://127.0.0.1:1234/rpc/v0";`

I came up with the following naive implementation, because, of course, you're right about that.

```rust
/// Parses an ip4 multiaddress into an HTTP URL
fn multiaddress_to_url(ma_str: String) -> String {
    // Example haystack: "/ip4/127.0.0.1/tcp/1234/http"
    let regex = Regex::new(r"/ip4/(?P<protocol>.*)/tcp/(?P<host>.*)/(?P<port>.*)").unwrap();

    // Parse multiaddress using regex named captures.
    // If the regex cannot match, log an error and return the default URL.
    let url = match regex.captures(&ma_str) {
        Some(segments) => {
            let protocol = segments.name("protocol").unwrap().as_str();
            let host = segments.name("host").unwrap().as_str();
            let port = segments.name("port").unwrap().as_str();
            let path = RPC_ENDPOINT;
            format!(
                "{protocol}://{host}:{port}/{path}",
                protocol = protocol,
                host = host,
                port = port,
                path = path
            )
        }
        None => {
            error!(
                "Error: {} could not be parsed as a ip4 multiaddress",
                ma_str
            );
            DEFAULT_URL.to_owned()
        }
    };

    // Print and return the URL
    println!("Using JSON-RPC v2 HTTP URL: {}", url);
    url
}
```

Not sure if this would be useful or fit within the scope of the project. Hopefully it'll at least help others with a similar need.

**Comment by mxinden** [comment]
@cryptoquick can you expand on your concrete use case?

Whether offering this function is a good idea or not, I would not use a regex, but instead leverage the already existing parsing functionality of `parity-multiaddr`:

```rust
use parity_multiaddr::{Multiaddr, Protocol};

fn main() {
    let addr: Multiaddr = "/ip6/2001:db8::/tcp/80/http".parse().unwrap();
    let mut addr_iter = addr.into_iter();

    let protocol;
    let port;
    let host;

    match addr_iter.next().unwrap() {
        Protocol::Ip6(ip) => {
            host = ip.to_string();
        }
        Protocol::Ip4(_) => {
            unimplemented!()
        }
        _ => unimplemented!(),
    }

    match addr_iter.next().unwrap() {
        Protocol::Tcp(p) => {
            port = p;
        }
        _ => unimplemented!(),
    }

    match addr_iter.next().unwrap() {
        Protocol::Http => {
            protocol = "http".to_string();
        }
        _ => unimplemented!(),
    }

    println!("{}://{}:{}/", protocol, host, port);
}

```

**Comment by cryptoquick** [comment]
I solved this in my code with this:

```rust
use parity_multiaddr::{Multiaddr, Protocol};

struct URL {
    protocol: String,
    port: String,
    host: String,
}

/// Parses a multiaddress into a URL
fn multiaddress_to_url(ma_str: String) -> String {
    // Parse Multiaddress string
    let ma: Multiaddr = ma_str.parse().expect("Parse multiaddress");

    // Fold Multiaddress into a URL struct
    let addr = ma.into_iter().fold(
        URL {
            protocol: DEFAULT_PROTOCOL.to_owned(),
            port: DEFAULT_PORT.to_owned(),
            host: DEFAULT_HOST.to_owned(),
        },
        |mut addr, protocol| {
            match protocol {
                Protocol::Ip6(ip) => {
                    addr.host = ip.to_string();
                }
                Protocol::Ip4(ip) => {
                    addr.host = ip.to_string();
                }
                Protocol::Dns(dns) => {
                    addr.host = dns.to_string();
                }
                Protocol::Dns4(dns) => {
                    addr.host = dns.to_string();
                }
                Protocol::Dns6(dns) => {
                    addr.host = dns.to_string();
                }
                Protocol::Dnsaddr(dns) => {
                    addr.host = dns.to_string();
                }
                Protocol::Tcp(p) => {
                    addr.port = p.to_string();
                }
                Protocol::Http => {
                    addr.protocol = "http".to_string();
                }
                Protocol::Https => {
                    addr.protocol = "https".to_string();
                }
                _ => {}
            };
            addr
        },
    );

    // Format, print and return the URL
    let url = format!(
        "{}://{}:{}/{}",
        addr.protocol, addr.host, addr.port, RPC_ENDPOINT
    );
    info!("Using JSON-RPC v2 HTTP URL: {}", url);
    url
}
```

If you think this would be helpful for others, let me know and I can open a PR.

Otherwise, feel free to close.

**Comment by mxinden** [comment]
> If you think this would be helpful for others, let me know and I can open a PR.

Sure, in case this can be helpful for others, I think we should include it. Though with https://github.com/libp2p/rust-libp2p/pull/2075 this should go into the upstream `multiaddr` crate, more particularly next to the [`from_url`](https://github.com/multiformats/rust-multiaddr/blob/master/src/from_url.rs) module. Though in my opinion an implementation should be a lot more strict e.g. only parse reasonable `Protocol` orders, ...

**Comment by mxinden** [comment]
> Though with #2075 this should go into the upstream multiaddr crate, more particularly next to the from_url module.

With the above in mind, I am closing here, suggesting to move this to the `multiaddr` crate.

**Comment by AnmolBansalDEV** [comment]
was this ever added to the `multiaddr` crate? I'm unable to find this method in it. Thanks!

**Comment by elenaf9** [comment]
> was this ever added to the `multiaddr` crate? I'm unable to find this method in it. Thanks!

No I don't think so. 
However, reading the discussion in https://github.com/multiformats/rust-multiaddr/issues/71 I am also not sure if adding it is still desirable, since it has been discussed that the public API of `multiaddr` should be kept small in order to avoid breaking changes.
If the logic is needed, one can easily implement it themself, e.g. with the above code, right?
