### ISSUE TITLE
Yamux Error

### ISSUE THREAD

**Issue by AgeManning** [libp2p/rust-libp2p#2089]
I've been testing out the new update to yamux (the network I'm using still likely has old clients with early yamux versions). 

We're seeing a few of:
```
[2021-06-01T08:52:54Z ERROR yamux::connection] c0a39001/5: buffer of stream grows beyond limit
```
I was expecting some stream resets (https://github.com/libp2p/rust-libp2p/pull/1960) just wanted to double check that this error is also expected from the yamux upgrade.

**Comment by mxinden** [comment]
> I've been testing out the new update to yamux

That is great. Thank you for testing and also thank you for the bug report.

Yamux uses the notion of a _Window_ to do flow control. Put simply the sender has a send budget (the _Window_). Whenever the sender exhausts the budget the receiver send a _Window Update_ back to the sender allowing the sender to send more data.

There are two `WindowUpdateMode`s in `rust-yamux` namely `OnReceive` and `OnRead`.

```rust
/// Specifies when window update frames are sent.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum WindowUpdateMode {
    /// Send window updates as soon as a [`Stream`]'s receive window drops to 0.
    ///
    /// This ensures that the sender can resume sending more data as soon as possible
    /// but a slow reader on the receiving side may be overwhelmed, i.e. it accumulates
    /// data in its buffer which may reach its limit (see `set_max_buffer_size`).
    /// In this mode, window updates merely prevent head of line blocking but do not
    /// effectively exercise back pressure on senders.
    OnReceive,

    /// Send window updates only when data is read on the receiving end.
    ///
    /// This ensures that senders do not overwhelm receivers and keeps buffer usage
    /// low. However, depending on the protocol, there is a risk of deadlock, namely
    /// if both endpoints want to send data larger than the receivers window and they
    /// do not read before finishing their writes. Use this mode only if you are sure
    /// that this will never happen, i.e. if
    ///
    /// - Endpoints *A* and *B* never write at the same time, *or*
    /// - Endpoints *A* and *B* write at most *n* frames concurrently such that the sum
    ///   of the frame lengths is less or equal to the available credit of *A* and *B*
    ///   respectively.
    OnRead
}
```

https://github.com/libp2p/rust-yamux/blob/e2368ec9617de40e46dc7b8535421377044f38bf/src/lib.rs#L59-L84

Today the default is `OnReceive`. In my eyes the default should be `OnRead`.

As far as I can tell [you are using `OnReceive` in lighthouse](https://github.com/sigp/lighthouse/blob/3a24ca5f14c6e6d6612fd43eca82aa0c1e6aba16/beacon_node/eth2_libp2p/src/service.rs#L374) and are thus seeing these errors.

I recommend using `OnRead`, see docs above.

> I was expecting some stream resets (#1960) just wanted to double check that this error is also expected from the yamux upgrade.

I would be surprised if this is related to the recent version update (#1960) though it might be amplified through the eager sending of _Window updates_. Just to double check, you are not seeing these log lines on previous versions?

**Comment by AgeManning** [comment]
Oh perfect. Thanks. 

This definitely sounds unrelated to #1960. There is a very large update that we're testing quite extensively which includes the libp2p update. The nodes we are testing on are likely under more load than previously, potentially causing this buffer issue. 

I hadn't noticed it on earlier versions (although it is likely to be there in periods of high compute time, i imagine). I'll modify to `OnRead` and re-open if there are any other issues. 

Thanks!
