### ISSUE TITLE
Use a HD wallet with libp2p

### ISSUE THREAD

**Issue by izolyomi** [libp2p/rust-libp2p#2091]
Being aware of the libp2p project for a long time, I recently started experimenting with its current capabilities as a newbie. I planned to start with a hierarchical deterministic (HD) wallet that can generate both ed25519 and secp256k1 keys and use libp2p for safe authenticated communicate between the generated keys.

Unfortunately, I've found that the current `core::identity::{ed25519, secp256k1}` implementations do not seem to allow creating libp2p identities from an existing `ed25119_dalek::KeyPair` or a `PeerId` from a dalek or secp PublicKey, the preferred way of creating identities is always generating a random new one inside libp2p. In some cases, this might be worked around by hacking with serializing the keys to/from some byte formats, but not always and I don't think it's proper usage of the library.

Was disallowing construction of such identities intentional or just wasn't needed so far thus not implemented *yet*? If it wasn't a well-informed intentional decision, are you willing to implement this or accept related PRs to libp2p?

**Comment by tomaka** [comment]
I'm answering to give the historical context.

> Was disallowing construction of such identities intentional 

Yes! The reason is to not expose any type from the `ed25519_dalek` library (or any other library for that matter) in the public API of libp2p, as `ed25519_dalek` is an implementation detail.
Exposing the types of `ed25519_dalek` would, in turn, make it annoying to use libp2p with, for example, `ed25519_zebra`, and would require libp2p to publish a breaking change version if it bumps its version of `ed25519_dalek`.

> this might be worked around by hacking with serializing the keys to/from some byte formats, but not always and I don't think it's proper usage of the library

That's indeed how you're supposed to do it!

**Comment by izolyomi** [comment]
Thanks for the fast answer.

I understand the intention and concept by the explanation, but do not find this approach any clearer at first sight. What you suggest is essentially using an internal serialization byte format that is conceptually also a part of the library specs but is undocumented (at least I couldn't find any description), more volatile and harder to even detect changes in its format being unversioned.

Do I maybe misunderstand something here? Is the binary serialization format really supposed to provide a reasonable interface to connect a HD wallet to libp2p identities?

**Comment by tomaka** [comment]
> an internal serialization byte format that is conceptually also a part of the library specs but is undocumented (at least I couldn't find any description)

I'm quite confident that it's this format described here: https://datatracker.ietf.org/doc/html/rfc8032#section-5.1.5

> The public key A is the encoding of the point [s]B.  First,
>       encode the y-coordinate (in the range 0 <= y < p) as a little-
>       endian string of 32 octets.

**Comment by izolyomi** [comment]
Ah, so binary formats are more portable, e.g. between dalek and zebra libs. This explanation with the reasons of the design decisions would worth some Rust doc comments in the codebase and pointing to the format link above.

Makes sense then, thank you for the answers, I'm closing this issue.

**Comment by mxinden** [comment]
> This explanation with the reasons of the design decisions would worth some Rust doc comments in the codebase and pointing to the format link above.

@izolyomi would you mind creating a small pull request updating the docs? That would be very much appreciated.

**Comment by izolyomi** [comment]
> @izolyomi would you mind creating a small pull request updating the docs? That would be very much appreciated.

First I'd like to come to a conclusion with my experiments on the communication capabilities of rust-libp2p. If then I can find the required time and enthusiasm, will definitely send a PR.

**Comment by izolyomi** [comment]
> @izolyomi would you mind creating a small pull request updating the docs? That would be very much appreciated.

I've just tried with the pull request above, I hope you expected something like this. :)

**Comment by mxinden** [comment]
Crossreferencing https://github.com/libp2p/rust-libp2p/pull/2142 here. //CC @izolyomi.
