### ISSUE TITLE
libp2p-request-response: No way to efficiently interrupt an ongoing request

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#2095]
In order to send out a request with `libp2p-request-response`, one is supposed to use [this function](https://docs.rs/libp2p-request-response/0.11.0/libp2p_request_response/struct.RequestResponse.html#method.send_request).
It returns a `RequestId`, and the response is later reported by an event.

It is, however, not possible to cancel an ongoing request.

If a node is no longer interested in a response, we will receive the response only to discard it afterwards. This is a pure loss of bandwidth.

**Comment by tomaka** [comment]
Implementing this is rather complicated, because the reception of the response is done directly in `upgrade_outbound`:

https://github.com/libp2p/rust-libp2p/blob/a24e4221bdeeffc9260e6e08636bc7f8f231e168/protocols/request-response/src/handler/protocol.rs#L166

We would need to either refactor libp2p-request-response to not receive the response in `upgrade_outbound`, or implement some sort of hacky interruption system.

**Comment by thomaseizinger** [comment]
> We would need to either refactor libp2p-request-response to not receive the response in `upgrade_outbound`

This is now happening as a result of other efforts: https://github.com/libp2p/rust-libp2p/pull/3914

**Comment by thomaseizinger** [comment]
But I am going to close this as stale. If the feature request arises again, users can open a new issue.
