### ISSUE TITLE
rust-libp2p for browser-to-browser communication

### ISSUE THREAD

**Issue by thankrandomness** [libp2p/rust-libp2p#2108]
Hi! I am aware of [js-libp2p](https://github.com/libp2p/js-libp2p). I wanted to check if there's a wasm compilation of rust-libp2p that anyone used for browser-to-browser communication. - Thanks!

**Comment by mxinden** [comment]
Hi @thankrandomness,

Yes, rust-libp2p [compiles to WASM](https://github.com/libp2p/rust-libp2p/blob/master/.github/workflows/ci.yml#L43) and is used to run in browsers e.g. via https://github.com/paritytech/substrate.

Note: In order for two browsers to communicate you need some intermediary relay or coordination point for hole punching, given the restrictions of browser platforms. See https://github.com/mxinden/specs/blob/hole-punching/connections/hole-punching.md and https://github.com/libp2p/specs/issues/312 for details.

**Comment by mxinden** [comment]
Closing here. Feel free to comment or open a new issue in case you have more questions @thankrandomness.
