### ISSUE TITLE
Feature Request: Support Proxy Protocol 

### ISSUE THREAD

**Issue by vlvrd** [libp2p/rust-libp2p#2116]
### Feature Request

Include [Proxy Protocol](https://www.haproxy.com/blog/haproxy/proxy-protocol/) to support the use of Load Balancers and Reverse Proxies.

This is the same feature request from @stongo in the Go implementation: https://github.com/libp2p/go-libp2p/issues/1065

## Background

The current behaviour of a libp2p node behind a load balancer is to reflect a server's private IP or loopback interface as the source IP address of upstream peer connections established through a Load Balancer or Reverse Proxy.

This is a well known TCP load balancing issue, with a conventional but complex workaround to use Transparent Proxies. This requires kernel and iptables configuration, which creates a high barrier to success running libp2p nodes in this use case.

For Proxy Protocol to be fully supported, the downstream endpoint (libp2p node) should support Proxy Protocol 1 and 2 to establish the client's IP address (upstream libp2p peer).

## Current pitfalls without Proxy Protocol support

- Negative peer scores resulting from duplicate peer IPs (private IP reflection or loopback)
- Restricted auditing capabilities

**Comment by mxinden** [comment]
If I understand the _Proxy Protocol_ correctly, this could be done by a wrapper implementing the [`Transport`](https://docs.rs/libp2p/0.38.0/libp2p/trait.Transport.html) trait, wrapping e.g. a [`TcpConfig`](https://docs.rs/libp2p/0.38.0/libp2p/tcp/type.TcpConfig.html).

What do you think @vlvrd?

**Comment by vlvrd** [comment]
I think that's all it takes too, a wrapper similar to the DNS one. It's what I hoped at least. :relieved:

**Comment by h4x3rotab** [comment]
This will be very useful for running a cluster of substrate node in a Kubernetes stateful set
