### ISSUE TITLE
WASM regression: Usage of std::time::Instant

### ISSUE THREAD

**Issue by fusetim** [libp2p/rust-libp2p#2134]
While creating my custom node based on rust-libp2p, I rediscovered some uses of `std::time::Instant` in the Gossipsub and Kadmelia modules. As previously done by the PR #1071 (issue #900), the remaining `std::time::Instant` should again be replaced with `wasm_timer::Instant` to allow Wasm compatibility.

The spotted ones:
- [ ] https://github.com/libp2p/rust-libp2p/blob/ee11922d978834c0d5180eb8bc9e482f7945ecfa/protocols/gossipsub/src/time_cache.rs#L29
- [ ] https://github.com/libp2p/rust-libp2p/blob/ee11922d978834c0d5180eb8bc9e482f7945ecfa/protocols/gossipsub/src/peer_score.rs#L30
- [ ] https://github.com/libp2p/rust-libp2p/blob/ee11922d978834c0d5180eb8bc9e482f7945ecfa/protocols/mdns/src/behaviour.rs#L45
- [ ] https://github.com/libp2p/rust-libp2p/blob/ee11922d978834c0d5180eb8bc9e482f7945ecfa/protocols/kad/src/kbucket.rs#L80

**Comment by fusetim** [comment]
We will need an update of `wasm-timer`, I think, but otherwise nothing seems to break and in every case, the use of Instant was inside the crate only. 
```
Compiling libp2p-gossipsub v0.32.0 (/mnt/storagedisk/Developing/IntelliJ/rust-libp2p/protocols/gossipsub)
error[E0599]: no method named `checked_add` found for struct `wasm_timer::Instant` in the current scope
   --> /mnt/storagedisk/Developing/IntelliJ/rust-libp2p/protocols/gossipsub/src/peer_score.rs:848:34
    |
848 | ...                   .checked_add(topic_params.mesh_message_deliveries_window)
    |                        ^^^^^^^^^^^ method not found in `wasm_timer::Instant`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: could not compile `libp2p-gossipsub```

**Comment by fusetim** [comment]
Fixed by #2245.

However, I am still worried about this import in Kadmelia in "master" (f701b24 at the time).
https://github.com/libp2p/rust-libp2p/blob/f701b24ec0f99be49444a6e7de950c66b01b2f3f/protocols/kad/src/kbucket.rs#L80
https://github.com/libp2p/rust-libp2p/blob/f701b24ec0f99be49444a6e7de950c66b01b2f3f/protocols/kad/src/kbucket.rs#L721

I might be missing something, but it seems to me, that KAD should be WASM-compatible, and the other inner modules seems to use a correct instant::Intant import. May @wngr could enlighten this ?

**Comment by wngr** [comment]
From what I see this is only used in a test, that's why I didn't change it. Should have changed the import scope, though.

**Comment by fusetim** [comment]
Oh you're right, I missed the `#[test]`, the issue can be closed now. Thank you for your time 👍
