### ISSUE TITLE
Kademlia: record validation

### ISSUE THREAD

**Issue by rubdos** [libp2p/rust-libp2p#2140]
I'm toying with the Kademlia implementation, and noticed that the [record filtering and validation](https://github.com/libp2p/specs/tree/master/kad-dht#entry-validation) does not seem to have an API, currently.  I assume this is needed in, for instance, IPFS' IPNS, and this is something I also need in my application (validating signatures and clocks).

I currently solved this by implementing a `RecordStore` that filters records and returns `ValueTooLarge` when a PUT request is potentially harmful.

The [Entry Validation API specification](https://github.com/libp2p/specs/tree/master/kad-dht#entry-validation) (same link as above) prescribes/suggests a `select` and `validate` API when storing and merging records. I'm actually quite a fan of the filtering approach in `RecordStore` itself, although not by hijacking an existing error variant.

Does the `rust-libp2p` community see anything wrong with something like

```rust
#[derive(Debug)]                                                           
pub enum Error {                                                           
    /// The store is at capacity w.r.t. the total number of stored records.
    MaxRecords,                                                            
    /// The store is at capacity w.r.t. the total number of stored keys for
    /// provider records.                                                  
    MaxProvidedKeys,                                                       
    /// The value of a record to be stored is too large.                   
    ValueTooLarge,                                                         
    /// The store failed to validate the record.
    RecordValidationError(Option<String>),
}                                                                          
```

... potentially substituting the `Option<String>` by a "real" error of some kind? I think this could be a pretty clean way to comply with entry validation. I'd be glad to submit a PR for this, or to implement something completely different and make a PR for that.

**Comment by mxinden** [comment]
:wave: Hi @rubdos,

_Kademlia specification author and rust-libp2p maintainer here_.

> I'm toying with the Kademlia implementation, and noticed that the record filtering and validation does not seem to have an API, currently.

Correct. Also note, that rust-libp2p currently lacks behind, in other words, does not strictly validate records, nor giving downstream users the chance to do so. That said, I would very much like to see proper support for this in rust-libp2p.

I think we can agree on to keep basic (provider-) record validation in `libp2p-kad` itself, as already done today. E.g. making sure the peer ID of a provider record equals the peer ID of the remote. 

> The Entry Validation API specification (same link as above) prescribes/suggests a select and validate API when storing and merging records.

Though the sample interface is really only an example. I don't think the "Injecting a type implementing the synchronous `Validator` trait" abstraction fits well into rust-libp2p's asynchronous message driven architecture.

Instead I would see two possible solutions, to enable application specific (provider-) record validation, e.g. for IPFS ensure an IPNS record is valid, through the downstream user who using `libp2p-kad` crate, with the latter being the one you favor / suggested above:

1. When receiving an incoming `PutRecord` or `AddProvider` request the `Kademlia` `NetworkBehaviour` would emit an event, e.g. `KademliaEvent::NewRecord`, with the record, allowing the user to validate the event and, if valid, pass it back to the user via e.g. `Kademlia::put_record`. The record would then be added to the `RecordStore`.

    A similar style is followed for new peers before being added to the routing table. See https://github.com/libp2p/rust-libp2p/blob/20183c1ea152f5bfe183543e4934e082c1428011/protocols/kad/src/behaviour.rs#L110-L132

2. When receiving an incoming `PutRecord` or `AddProvider` request the `Kademlia` `NetworkBehaviour` would call `RecordStore::put` or `RecordStore::add_provider`. The `RecordStore` could then validate the (provider-) record, returning a custom error in case it is invalid.

I see two problems with option (2):

- The `RecordStore` interface is synchronous. What if users would like to validate records in an asynchronous fashion, e.g. involving network calls?
- In my eyes, it mixes concerns. While the `RecordStore` is an abstraction over storing blobs of data, it is not an abstraction over application specific validation. E.g. let's say I write a Sqlite implementation for `RecordStore` for an IPFS implementation. If this implementation includes IPFS specific record validation, other people could not reuse the same implementation for some other application use-case.

@rubdos does the above make sense? What do you think? Would you be interested in contributing a mechanism to allow users to write application specific (provider-) record validation?

**Comment by rubdos** [comment]
> A similar style is followed for new peers before being added to the routing table. See

This confused me before; I had no idea this was actually a configuration option and had no idea the default was manual. I kind-of assumed that was a bug! Maybe stuff for a separate issue, to add this to the example code. It's also a bit painful that there's no warning or type-enforced "thing" going on that tells the user at compile time that *something* might be off.

> @rubdos does the above make sense? What do you think? Would you be interested in contributing a mechanism to allow users to write application specific (provider-) record validation?

Yes, makes a ton of sense! Online record validation (on the network), goes a bit against the autonomy of a node, which I don't expect to happen in "good" applications, but there's more use cases to `async` validation than the network (e.g. verifying signatures and zero-knowledge proofs on a thread pool). So, async validation++.

I also side with you on separation of concerns. The idea of emitting a NewRecord event and having to manually inject the record seems a bit annoying, but not unmanageable if well documented (see my point on the routing table).

I'm interested in contributing the mechanism. I could probably spend a day next week on it. Since you say that there's some form of provider-record validation going on, would you mind pointing me where that happens, and what should happen to it in my contribution?

**Comment by mxinden** [comment]
> I had no idea this was actually a configuration option and had no idea the default was manual.

The default is not `Manual`:

https://github.com/libp2p/rust-libp2p/blob/20183c1ea152f5bfe183543e4934e082c1428011/protocols/kad/src/behaviour.rs#L181

> It's also a bit painful that there's no warning or type-enforced "thing" going on that tells the user at compile time that something might be off.

I can understand that. Happy for alternative suggestions.

> I'm interested in contributing the mechanism. I could probably spend a day next week on it. Since you say that there's some form of provider-record validation going on, would you mind pointing me where that happens, and what should happen to it in my contribution?

Great to hear that. Thanks @rubdos! Let me know if you need any help.

I might have oversold the "provider-record validation". The only validation currently happening is that the provider in the provider record is the same peer that send the provider record:

https://github.com/libp2p/rust-libp2p/blob/20183c1ea152f5bfe183543e4934e082c1428011/protocols/kad/src/behaviour.rs#L1526-L1528

I think this should stay as is, though I open for alternative suggestions.
