### ISSUE TITLE
Serialize/Deserialize for Multihash

### ISSUE THREAD

**Issue by FelipeRosa** [libp2p/rust-libp2p#2147]
Hi folks,

What's the reason for not implementing `Serialize`/`Deserialize` for `Multihash`?

At the moment, in my project, I have a newtype wrapping `PeerId` so I can serialize/deserialize it to/from `String`s.

I can see the ambiguity that can arise when trying to ser/de because `Multihash` can be represented as a string or as digest in different contexts. I'm curious about what has been thought about that.

**Comment by thomaseizinger** [comment]
That is a feature-request for upstream: https://github.com/multiformats/rust-multihash

**Comment by FelipeRosa** [comment]
Oh! Didn't see the upstream crate.

Thanks for the quick response and pointers!
