### ISSUE TITLE
(Tokio) Tcp port reuse: picking unconnectable interfaces?

### ISSUE THREAD

**Issue by rubdos** [libp2p/rust-libp2p#2152]
Hi!

I'm testing some things with Kademlia in a pretty specific situation:

- I have 50 nodes running on a private subnet (somewhere in 10.20.0.0/16 and some fd00::/7 subnet).
- One node running on a publicly reachable, fixed port IPv4 and IPv6 address.
- My laptop, which is connected via two separate interfaces. One of them can reach 10.20.0.0/16, the other interface can reach the public node.

The 50 private nodes and the one public node are connected. My goal is to connect to the public node, which sends me K private nodes with their potentially reachable addresses.

When I *enable* port reuse on the laptop through
```rust
let tcp = libp2p::tcp::TokioTcpConfig::new()
    .nodelay(true) ‣GenTcpConfig<Tcp>
    .port_reuse(true);
```
then `rust-libp2p` (seemingly random, needs more tests) reuses the private 10.20.0.0-ranged address on my laptop to connect to the public node (which I use as bootstrap). This address is bound to the private-only interface, and as such cannot reach the public node.

Turning off `port_reuse` on my laptop creates a new 0.0.0.0 socket, and connects successfully.

I would think that the `port_reuse` option chooses the local interface more wisely; am I missing something here?

**Comment by mxinden** [comment]
This is indeed surprising and a bit hard to debug without a reproducer. Might it be that your public interface does not support port-reuse? Which `NewListenAddr` are reported? We might be choosing the wrong interface when dialing. Can you log the output of the following trace level output?

https://github.com/libp2p/rust-libp2p/blob/e437c009dc80777300e56c0c06d73ff14e5449a1/transports/tcp/src/lib.rs#L349-L351

**Comment by dvc94ch** [comment]
ah that does sound like the likely cause [0]. not sure what we can do to improve it. @rubdos do you have a better suggestion for a heuristic to select an address to reuse if you have multiple interfaces with different routes?

- [0] https://github.com/libp2p/rust-libp2p/blob/master/transports/tcp/src/lib.rs#L151

**Comment by rubdos** [comment]
Hi, sorry for not coming back to this yet. Other priorities...

@dvc94ch, I'm not exactly sure, but can't you reuse the binding address instead of the listen address?  E.g., I bind on `0.0.0.0:0`, which yields a bunch of listening addresses on port `x`, and then `local_dial_addr` returns `0.0.0.0:x`? Not exactly sure whether that's legal though.

**Comment by dvc94ch** [comment]
if-watch already listens for address changes. we could extend it to listen for routes too. I believe windows would also be straight forward to support, but macos don't know. anyway this does sound like a few days of work.

**Comment by rkuhn** [comment]
FYI: This issue caused some head scratching for us as well, the only solution is to switch off port reuse (which I’ve done on the sim-open branch in the Actyx fork of ipfs-embed). This whole setup seems much too fragile to me, as you’d have to basically redo all the (rather powerful) Linux routing logic — and Windows will very likely be even harder to support (as always). Would it not work better to bind to INADDR_ANY with port 4001?

**Comment by rkuhn** [comment]
This actually does work (at least on Linux), so would this be an acceptable solution?

/cc @mxinden (This is the bug I mentioned a few days back that “I’ll need to raise an issue for” :-) )
