### ISSUE TITLE
Two nodes are not connecting with each other using ping.rs if both nodes are running into different regions on IBM.

### ISSUE THREAD

**Issue by aiyajsupra** [libp2p/rust-libp2p#2154]
Two nodes are not connecting with each other using ping.rs if both nodes are running into different regions on IBM. I checked terminal ping on both servers, they are pinging each other using private ips. Any idea?

**Comment by thomaseizinger** [comment]
Did you establish a connection between the two nodes? Connections need to be established [explicitely](https://github.com/libp2p/rust-libp2p/blob/20183c1ea152f5bfe183543e4934e082c1428011/examples/ipfs-private.rs#L263) before they can start pinging each other.

**Comment by aiyajsupra** [comment]
@thomaseizinger yes they are able to ping each other via private ips using ping command on terminal. Is there any configuration needed on ipfs side? Because it works fine when two nodes are in same region.

**Comment by thomaseizinger** [comment]
I don't quite understand. How are you establishing connections between your nodes? Any chance you can post the code you are running?

If two nodes are not in the same network and behind NAT, you will need to open and forward ports. I am not sure if this is why it works in one _region_ (whatever that means?) but if region == [subnet](https://en.wikipedia.org/wiki/Subnetwork) then your issue is most likely that ports are not forwarded.

**Comment by khalaniaiyaj** [comment]
@thomaseizinger 
I am using https://github.com/libp2p/rust-libp2p/blob/master/examples/ping.rs this example.

We are running command "cargo run --example ping" in one virtual instance of london region on IBM cloud.

We are running command  "cargo run --example ping -- /tcp/<private_ip_of_first_node>/port/" in one virtual instance of Frankfurt regionon IBM cloud.

We have created VPC to connect both region via private ip and both are connected successfully. but p2p is not able to communicate with each other.

If we put both virtual machine in london region then it able to communicate using p2p.

**Comment by thomaseizinger** [comment]
> We have created VPC to connect both region via private ip and both are connected successfully.

How did you verify that they are connected successfully? Can you f.e. `telnet` from one node to the other?

**Comment by jayesh-remo** [comment]
@thomaseizinger using ping command, 
ping <private_ip of frankfurt region> -> hit this command from london region

ping <private_ip of london region> -> hit this command from frankfurt region

both are sending successful packates to each other.

**Comment by thomaseizinger** [comment]
Can you post the log outputs? Without anything we are just taking wild guesses here.

Have you tried logging more events as part of the eventloop?

**Comment by mahendra-supraoracle** [comment]
@thomaseizinger :

see the logs :

**1st Peer runniing on `frankfurt1`**

```
root@instance-frankfurt1:/# ifconfig
ens3: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.243.68.4  netmask 255.255.252.0  broadcast 10.243.71.255
        inet6 fe80::1ff:fe20:6fca  prefixlen 64  scopeid 0x20<link>
        ether 02:00:01:20:6f:ca  txqueuelen 1000  (Ethernet)
        RX packets 524473  bytes 1601448531 (1.6 GB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 649007  bytes 100803125 (100.8 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 13068  bytes 1310433 (1.3 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 13068  bytes 1310433 (1.3 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@instance-frankfurt1:/#
root@instance-frankfurt1:/# ping 10.244.64.111
PING 10.244.64.111 (10.244.64.111) 56(84) bytes of data.
64 bytes from 10.244.64.111: icmp_seq=1 ttl=45 time=255 ms
64 bytes from 10.244.64.111: icmp_seq=2 ttl=45 time=255 ms
64 bytes from 10.244.64.111: icmp_seq=3 ttl=45 time=255 ms
64 bytes from 10.244.64.111: icmp_seq=4 ttl=45 time=255 ms
64 bytes from 10.244.64.111: icmp_seq=5 ttl=45 time=255 ms
^C
--- 10.244.64.111 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4002ms
rtt min/avg/max/mdev = 254.585/254.644/254.734/0.056 ms
root@instance-frankfurt1:/#
```

**2nd Peer runniing on `tokyo1`**

```
root@instance-tokyo1:/# ifconfig
ens3: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.244.64.111  netmask 255.255.255.0  broadcast 10.244.64.255
        inet6 fe80::4:4cff:fe1d:26f2  prefixlen 64  scopeid 0x20<link>
        ether 02:04:4c:1d:26:f2  txqueuelen 1000  (Ethernet)
        RX packets 513094  bytes 652468796 (652.4 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 576446  bytes 98888354 (98.8 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 740  bytes 82460 (82.4 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 740  bytes 82460 (82.4 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@instance-tokyo1:/#
root@instance-tokyo1:/# ping 10.243.68.4
PING 10.243.68.4 (10.243.68.4) 56(84) bytes of data.
64 bytes from 10.243.68.4: icmp_seq=1 ttl=45 time=255 ms
64 bytes from 10.243.68.4: icmp_seq=2 ttl=45 time=255 ms
64 bytes from 10.243.68.4: icmp_seq=3 ttl=45 time=255 ms
64 bytes from 10.243.68.4: icmp_seq=4 ttl=45 time=255 ms
64 bytes from 10.243.68.4: icmp_seq=5 ttl=45 time=255 ms
^C
--- 10.243.68.4 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4003ms
rtt min/avg/max/mdev = 254.564/254.740/254.865/0.099 ms
root@instance-tokyo1:/#
```

and,

Transit gateway is configured and the vpc of different regions are mapped.

**Comment by thomaseizinger** [comment]
Thank you, that is already interesting. I see that the network adapter in the frankfurt node is on a different subnet (255.255.252.0) compared to the tokyo node (255.255.255.0). I didn't do the math but if they are reachable via ping, then I guess they are in the same network.

Can you run a traceroute as well?

What is the output of the rust-libp2p ping examples?
Before you run them, can you extend `examples/ping.rs` to log all `SwarmEvent`s in the loop at the bottom of the file? Using `dbg!` should be good enough for debug purposes.

**Comment by mxinden** [comment]
Can this issue be closed?
