### ISSUE TITLE
Retrieve results from Kademlia lookup

### ISSUE THREAD

**Issue by umgefahren** [libp2p/rust-libp2p#2160]
Hey,
I really looked into khd in this project, but I just couldn't figure out how, in an application, one would get the results of a Khd lookup back. Why is i.e. `.get` not an asynchronous function where you can lookup the results of the query by just calling `.await`?
Maybe I just need some guidance on how to implement that for an actual application. I'm just kind of stuck with the Documentation and the examples and I wasn't able to figure this out.

**Comment by thomaseizinger** [comment]
rust-libp2p employs an event-driven design.

When you poll the swarm, it will return `SwarmEvent`s. One variant in there is `Behaviour` which is going to have a `KademliaEvent` somewhere if you use `Kademlia`.

These `KademliaEvent`s are going to map back to IDs your receive when issuing queries.

There are some posts under "Discussions" that discuss this in more detail.

**Comment by mxinden** [comment]
:+1: on @thomaseizinger response above.

To add some additional background: The reason why `.get` does not return a `Future` eventually resolving to the lookup result is (a) historical given that rust-libp2p was started in the early async Rust days and (b) to not mix poll-style async Rust with async/await Rust.

Long story short, take a look at https://github.com/libp2p/rust-libp2p/issues/2158 for some pointers.

**Comment by umgefahren** [comment]
I intend to resolve this in #2158
