### ISSUE TITLE
Kademlia graceful shutdown

### ISSUE THREAD

**Issue by rubdos** [libp2p/rust-libp2p#2164]
I'm not 100% on what the libp2p specs say, but should the Kademlia subsystem implement a graceful shutdown, or at least have the option to do so?

Such a shutdown should probably entail stopping to accept new records, and re-replicating the locally available records.

**Comment by mxinden** [comment]
> but should the Kademlia subsystem implement a graceful shutdown

I haven't had the need for it thus far, though I am not opposed to it. Would you mind expanding on your concrete use-case?

Also see https://github.com/libp2p/rust-libp2p/pull/1682 for a similar effort on the larger libp2p level.

**Comment by rubdos** [comment]
> Would you mind expanding on your concrete use-case?

Sure! It's mostly in my current test case, where I have between 50 and 300 nodes running on Kubernetes to do some tests. I notice that Kubernetes is quite aggressive in scaling down, so when I start testing with actual content on the network, I'm afraid that stuff will get lost.

I guess in real-life this shouldn't™ happen, statistically speaking.

Another case would be extremely low $k$ or $\alpha$ values. I recall reading a paper about using $k=2$ and $k=4$ settings, where they required graceful shutdown and some other tricks to really get the replication factors down to extremely low values. I've given my Zotero a quick skim, but can't seem to currently find the paper.
