### ISSUE TITLE
WASM support

### ISSUE THREAD

**Issue by genderev** [libp2p/rust-libp2p#2166]
Does rust-libp2p support the wasm32-unknown-unknown target? I tried to compile the [ping](https://github.com/libp2p/rust-libp2p/blob/master/examples/ping.rs) example with wasm-pack. 

I thought the issue would be that the example relies on `println!` which is not available to the browser, but I actually got this error:

```
Compiling getrandom v0.2.3

error: the wasm32-unknown-unknown target is not supported by default, you may need to enable the "js" feature. For more information see: https://docs.rs/getrandom/#webassembly-support

```

**Comment by fusetim** [comment]
You just need to add this to your Cargo.toml:
`getrandom = { version = "0.2", features = ["js"] }`

More info there: https://docs.rs/getrandom/0.2.3/getrandom/#webassembly-support

**Comment by mxinden** [comment]
Closing here. Let me know if you need any further help @genderev.

Thanks @fusetim for respoding!
