### ISSUE TITLE
Refactor or remove request_response::throttled module because of licensing issues

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#2196]
The `libp2p-request-request` library currently depends on the `minicbor` library, which uses the `BlueOaks` license.
Unfortunately, the BlueOaks license isn't recognized by the `cargo-deny` tool and because it is a very new license its compatibility with existing licenses is kind of sketchy.

The author of `minicbor` [doesn't seem to be willing](https://gitlab.com/twittner/minicbor/-/issues/5) to change the license of his library.
Consequently, would you be ok with removing usage of this library? This can be done either by replacing `minicbor` with another library, or by simply removing the `throttled` module (that uses it) altogether. Considering that this `throttled` protocol isn't standard and isn't used by anyone, I would suggest going for that solution.

**Comment by mxinden** [comment]
I am fine either way. Feel free to propose a pull request either removing the `Throttled` behaviour or replacing the usage of `minicbor` with Protocol Buffers?
