### ISSUE TITLE
question about message forwarding

### ISSUE THREAD

**Issue by OfekShochat** [libp2p/rust-libp2p#2205]
hello, sorry for the second question; but when I receive a message from one of my peers (through a floodsub event), do I forward that message to all of my peers (thus propagating that message to all of the network)?
thanks aot

**Comment by mxinden** [comment]
Hi @OfekShochat,

_Meta: Please use the GitHub Discussions feature for usage related questions. Also see https://github.com/libp2p/rust-libp2p#getting-started for more pointers._

> but when I receive a message from one of my peers (through a floodsub event), do I forward that message to all of my peers (thus propagating that message to all of the network)?

You don't do so actively, but the Floodsub implementation does so for you.

https://github.com/libp2p/rust-libp2p/blob/d617105233dd2def6d038806557b180f68d4d284/protocols/floodsub/src/layer.rs#L388-L412

**Comment by OfekShochat** [comment]
thank you so much. so it does propegate the message through the peers. next time Ill use the discussion page for this. thanks

**Comment by mxinden** [comment]
Great. Let us know what you end up building.

**Comment by OfekShochat** [comment]
oh @mxinden, can I, in special occasions, opt out of this message forwarding?
