### ISSUE TITLE
Doesn't resolve hostnames in /etc/hosts anymore

### ISSUE THREAD

**Issue by stormstriver** [libp2p/rust-libp2p#2237]
I try to connect to an address like `/dns4/my.custom.domain/tcp/8443/ws`, where `my.custom.domain` is an entry in my `/etc/hosts` file. This used to work, but after updating to the latest libp2p version, it doesn't anymore.
Instead, I get an `ResolveError` (`NoRecordsFound`) now. I looked at the packets being sent, and there is a DNS query being sent to my DNS server, which of course doesn't yield answers. Running a local DNS server that answers this query makes it "work".
I saw that libp2p switched to using the `trust-dns-resolver`, however that library seems to use my `/etc/hosts` file just fine. That makes me wonder if this could be an issue in libp2p?

**Comment by wngr** [comment]
`trust-dns-resolver` only resolves `/etc/hosts` on startup, and also only if you use the `system` config, for example:
https://github.com/libp2p/rust-libp2p/blob/b79fd02f0bdde07f437c691e278a16cf9024036a/transports/dns/src/lib.rs#L122-L125

Could you provide the code you used to setup the DNS transport?

**Comment by stormstriver** [comment]
I'm setting up the DNS transport as `dns::TokioDnsConfig::system( tcp::TokioTcpConfig::new().nodelay(true), )?`. As far as I understand, my `/etc/hosts` should thus be taken into account, however it isn't.

The rest of my code looks like this:

```rust
#[tokio::main]
async fn main() -> Result<(), Box<dyn Error>> {
    let local_key = identity::Keypair::generate_ed25519();
    let local_peer_id = PeerId::from(local_key.public());
    println!("Local peer id: {:?}", local_peer_id);

    let noise_keys = noise::Keypair::<noise::X25519Spec>::new().into_authentic(&local_key).unwrap();

    let transport = websocket::WsConfig::new(dns::TokioDnsConfig::system( tcp::TokioTcpConfig::new().nodelay(true), )?)
        .upgrade(upgrade::Version::V1)
        .authenticate(noise::NoiseConfig::xx(noise_keys).into_authenticated())
        .multiplex(mplex::MplexConfig::new())
        .boxed();

    let mut swarm = SwarmBuilder::new(transport, Behaviour {}, local_peer_id)
        .executor(Box::new(|fut| { tokio::spawn(fut); }))
        .build();

    swarm.listen_on("/ip4/0.0.0.0/tcp/0/ws".parse()?)?;

    let addr_str = "/dns4/my.custom.domain/tcp/8443/ws";
    swarm.dial_addr(addr_str.parse()?)?;
    println!("Dialed {}", addr_str);

    block_on(future::poll_fn(move |cx|
        loop {
            swarm.poll_next_unpin(cx);
            Poll::Pending
        }
    ));
    Ok(())
}
```

`Behaviour` is just a dummy implementation with a `DummyProtocolsHandler` and a `inject_addr_reach_failure` function that prints the respective details.

**Comment by mxinden** [comment]
@stormstriver can you try `/dns/my.custom.domain/tcp/8443/ws` instead of `/dns4/my.custom.domain/tcp/8443/ws`? While `/dns4` does not resolve from my `/etc/hosts`, `/dns` does.

**Comment by stormstriver** [comment]
Writing `/dns` instead of `/dns4` indeed makes it resolve, thank you. However I'd assume that `/dns4` should ideally work as well.

**Comment by mxinden** [comment]
> However I'd assume that /dns4 should ideally work as well.

Same here. I would guess you would find the answer for _why this is the case_ in [`async_resolver.rs`](https://docs.rs/trust-dns-resolver/0.20.3/src/trust_dns_resolver/async_resolver.rs.html) within the trust-dns codebase. Sorry, but I don't have enough time right now to debug this myself.

**Comment by thomaseizinger** [comment]
Let me know if this is still an issue.
