### ISSUE TITLE
/p2p/... suffix found when calling libp2p_kad::Kademlia::addresses_of_peer

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#2280]
I unfortunately can't find the corresponding PR, but [since libp2p-core 0.28.0](https://github.com/libp2p/rust-libp2p/blob/master/core/CHANGELOG.md#0280-2021-03-17) we now pass a `/p2p/...` suffix when calling `Transport::dial`.

Unfortunately, this leads libp2p-kad to insert addresses with `/p2p/` in its routing table, here: https://github.com/libp2p/rust-libp2p/blob/937b59de8946eb3773e292691dac4e5f3e081706/protocols/kad/src/behaviour.rs#L1926

In the code base of Substrate, this leads to these addresses with `/p2p/` being propagated around and poisoning a bit everything.

I would suggest to strongly clarify _everywhere_ a multiaddress is used whether it has or has not this `/p2p/` (for example `ConnectedPoint::Dialing` have it but not `ConnectedPoint::Listener`), or better: to pass the `PeerId` as a separate parameter to `dial`, in order to have a guarantee that this `/p2p/` isn't found anywhere.

**Comment by tomaka** [comment]
I would add that in my opinion it doesn't make sense for `ConnectedPoint::Dialing` to contain a multiaddr with a `/p2p/` suffix, as this information is already always given by the context. You never have a `ConnectedPoint` alone, you always have one associated with a `PeerId`. This redundant `/p2p/...` just brings confusion.

**Comment by mxinden** [comment]
> I unfortunately can't find the corresponding PR

I think you are referring to https://github.com/libp2p/rust-libp2p/pull/1931.

**Comment by thomaseizinger** [comment]
Closing as stale. If it is still an issue for users, they should open another issue.

I am of the opinion that because a `Multiaddr` allows for `/p2p`, we can statically guarantee anyway that it is _not_ present so downstream code just needs to be prepared to handle its presence.
