### ISSUE TITLE
Allow validation from upper layer in kademlia

### ISSUE THREAD

**Issue by supercmmetry** [libp2p/rust-libp2p#2281]
I have been trying to intercept an inbound request in `kademlia` to perform validation on the records before they are inserted into the `MemoryStore`. I found that there was a related `todo`.

https://github.com/libp2p/rust-libp2p/blob/57f34f6f266ad67e33e53236bd0c95af0ed9f833/protocols/kad/src/behaviour.rs#L2452-L2460

Would be great if this is implemented. If you have any suggestions to tackle this problem now, please do tell.

**Comment by mxinden** [comment]
Hi @supercmmetry,

Validation has been added in https://github.com/libp2p/rust-libp2p/pull/2163 and will be included in the next release. Does that address you need?

The TODO entry is outdated. Would you mind filing a pull request removing it?

**Comment by mxinden** [comment]
Credit for #2163 goes to @rubdos.

**Comment by supercmmetry** [comment]
Yeah, #2163 perfectly fits my usecase. I'll put up a PR to remove that TODO.
