### ISSUE TITLE
Metrics dependencies are always pulled via protocol features

### ISSUE THREAD

**Issue by thomaseizinger** [libp2p/rust-libp2p#2286]
I am not sure if there is much we can do about it but I noticed that `libp2p-metrics` is automatically pulled in if any of the protocols that activate metrics features are activated.

When trying to upgrade to the most recent rust-libp2p HEAD, I saw `libp2p-metrics` come in as a dependency even though we are not specifying it as a feature. I suspect it is being pulled in by cargo due to `ping` activating `libp2p-metrics/ping`.

https://github.com/libp2p/rust-libp2p/blob/6d3ab8a3debe8d69dcd004173999732f12d0da96/Cargo.toml#L47

Is there a way of how we can design this differently? Perhaps having a dedicated `metrics` feature within each protocol would solve this?

**Comment by mxinden** [comment]
Good catch!

Corresponding upstream tracking issue (_weak dependency feature_): https://github.com/rust-lang/cargo/issues/8832

As far as I can tell there is no solution to this today.

I don't it hurts much, given that `libp2p-metrics` is a pretty light-weight dependency. Still it would be great to not pull it in each time e.g. when the `ping` feature is set.

**Comment by thomaseizinger** [comment]
Thanks for pointing me to that, I had no idea that this is being worked on! Very exciting :)

**Comment by mxinden** [comment]
If I am not mistaken, this can be fixed with Rust `1.60`. Anyone interested in sending a patch?

https://blog.rust-lang.org/2022/04/07/Rust-1.60.0.html

**Comment by maschad** [comment]
Hey @mxinden I've added a patch in this [PR](https://github.com/libp2p/rust-libp2p/pull/2646). Lmk what you think.

**Comment by mxinden** [comment]
Closing here, since fixed by @maschad :tada:
