### ISSUE TITLE
protocols/identify: Validate addresses before caching

### ISSUE THREAD

**Issue by mxinden** [libp2p/rust-libp2p#2302]
With https://github.com/libp2p/rust-libp2p/pull/2232 `libp2p-identify` caches discovered listen addresses to provide additional addresses when dialing a peer via `NetworkBehaviour::addresses_of_peer`.

Before caching received listen addresses, `libp2p-identify` should validate these addresses. Validations:

- If the address contains a `/p2p/QmXXX` make sure `QmXX` matches the peer's `PeerId`.
- ...

//CC @AgeManning: This might be the reason for the dial failures you are seeing.

**Comment by thomaseizinger** [comment]
Do we want to treat validation errors as bad behaviour and disconnect from that peer?

**Comment by mxinden** [comment]
For now I would suggest we just ignore those addresses with a peer ID mismatch in `libp2p-identify`.

Reasoning: Maybe there is a benign way (in old versions) how this could happen. Disconnecting on mismatch might lead to large disconnects in live networks. Without measuring this beforehand, I would deem this change too risky.

Do you have some time to file a patch? I am sorry, I am a bit low on time / energy (sick). If not, I can just set the default value of `cache_size` to `0` for `v0.40.0` and re-enable it by default with the patch in `v0.41.0`.

**Comment by thomaseizinger** [comment]
> Do you have some time to file a patch?

Not at the moment but I am okay with disabling the current behaviour if it causes problems.

**Comment by MarcoPolo** [comment]
@thomaseizinger I'll pick this up unless you're working on it, thanks!

**Comment by thomaseizinger** [comment]
> @thomaseizinger I'll pick this up unless you're working on it, thanks!

Go for it! I haven't started on this yet :)
