### ISSUE TITLE
Deriving NetworkBehaviour seems to be broken in 0.40.0

### ISSUE THREAD

**Issue by hamamo** [libp2p/rust-libp2p#2328]
When switching to libp2p 0.40.0, I get the following kind of error for every NetworkBehaviour that I compose using #[derive(NetworkBehaviour]:

```
error[E0277]: the trait bound `(): From<PingEvent>` is not satisfied
  --> src/reputation_net/mod.rs:42:10
   |
42 | #[derive(NetworkBehaviour)]
   |          ^^^^^^^^^^^^^^^^ the trait `From<PingEvent>` is not implemented for `()`
   |
   = help: see issue #48214
   = note: this error originates in the derive macro `NetworkBehaviour` (in Nightly builds, run with -Z macro-backtrace for more info)
```

Is this a known issue with 0.40.0? There are a number of changes documented in the various CHANGELOGs related to NetworkBehaviour, but I haven't been able to pinpoint where exactly I could find out what I need to change to make my code working again.

**Comment by wngr** [comment]
I was running into a similar issue. Solution for me was to group all ignored member fields..

**Comment by hamamo** [comment]
You mean putting them into a separate struct so that only one field is marked with `#[behaviour(ignore)]`?

That didn't work for me. Of course it's possible I misunderstood your approach.

**Comment by elenaf9** [comment]
With issue #2190  / the associated PR #2214 the `NetworkBehaviour` derive macro was changed to per default set `event_process` to _false_. When it was set to _true,_ it was expected that `NetworkBehaviourEventProcess<T>` was implemented for all behaviour events, and events were handled via that implementation. 
Now that it is per default _false_, events are not handled through `NetworkBehaviourEventProcess`, but instead returned as `SwarmEvent::Behaviour(event)` when polling the swarm. The type of that event is with the attribute macro `#[behaviour(out_event = "OutEvent")]`, per default it is `()`, and is expected that `From<T>` is implemented for it for the events of the inner behaviours (which I believe is what causes your error). 
To solve this you have the following options:
1.  set the attribute macro `event_process = true` if you'd like to keep the old logic, e.g. as done here: https://github.com/libp2p/rust-libp2p/blob/8b68026bb04a469654020a8dcfe68308404e2510/examples/chat-tokio.rs#L89-L94
2. define some `OutEvent`, and implement `From<T> for OutEvent` for the behaviour events e.g. as it is done here: 
https://github.com/libp2p/rust-libp2p/blob/8b68026bb04a469654020a8dcfe68308404e2510/examples/chat.rs#L85-L113
  and poll events via `Swarm::poll`.

You can find more info on that in the docs: https://docs.rs/libp2p/0.40.0/libp2p/swarm/trait.NetworkBehaviour.html#deriving-networkbehaviour. Does this help?

**Comment by hamamo** [comment]
Thank you very much, this indeed explains the situation well. I wasn't aware that the `event_process` setting could have this effect.

Will try with `event_process = true` (corrected after response) later today, and read up on whether setting `out_event` is an option for me.

**Comment by elenaf9** [comment]
@hamamo just to quickly correct myself: if you'd like to keep the old logic, you have to set it to `event_process = true`. I edited my above comment.

**Comment by hamamo** [comment]
Looks like one last thing was confusing me - rust-analyzer has some checks beyond what `cargo check` does, and it complains with an `add-reference-here` notification (https://rust-analyzer.github.io/manual.html#add-reference-here) for each composed network behaviour at the `#[derive(NetworkBehaviour)]` line. Since cargo compiles the code without complaints now, and I'm too lazy to analyze the result of the macro expansion to find the real culprit, I'm leaving it at that :-)
