### ISSUE TITLE
Error Compiling libp2p v0.40.0

### ISSUE THREAD

**Issue by canewsin** [libp2p/rust-libp2p#2333]
Error : 
>  Compiling libp2p-metrics v0.1.0 (C:\Users\PramUkesh\Documents\SkyNet Project\rust-libp2p\misc\metrics)
error[E0308]: mismatched types
   --> misc\metrics\src\kad.rs:150:13
    |
94  |             Family::new_with_constructor(|| Histogram::new(exponential_buckets(1.0, 2.0, 10)));
    |                                          ---------------------------------------------------- the found closure
...
150 |             query_result_num_requests,
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^ expected fn pointer, found closure
    |
    = note: expected struct `Family<kad::QueryResult, _, fn() -> open_metrics_client::metrics::histogram::Histogram>`
               found struct `Family<_, _, [closure@misc\metrics\src\kad.rs:94:42: 94:94]>`

> error[E0308]: mismatched types
   --> misc\metrics\src\kad.rs:151:13
    |
102 |             Family::new_with_constructor(|| Histogram::new(exponential_buckets(1.0, 2.0, 10)));
    |                                          ---------------------------------------------------- the found closure
...
151 |             query_result_num_success,
    |             ^^^^^^^^^^^^^^^^^^^^^^^^ expected fn pointer, found closure
    |
    = note: expected struct `Family<kad::QueryResult, _, fn() -> open_metrics_client::metrics::histogram::Histogram>`
               found struct `Family<_, _, [closure@misc\metrics\src\kad.rs:102:42: 102:94]>`

> error[E0308]: mismatched types
   --> misc\metrics\src\kad.rs:152:13
    |
110 |             Family::new_with_constructor(|| Histogram::new(exponential_buckets(1.0, 2.0, 10)));
    |                                          ---------------------------------------------------- the found closure
...
152 |             query_result_num_failure,
    |             ^^^^^^^^^^^^^^^^^^^^^^^^ expected fn pointer, found closure
    |
    = note: expected struct `Family<kad::QueryResult, _, fn() -> open_metrics_client::metrics::histogram::Histogram>`
               found struct `Family<_, _, [closure@misc\metrics\src\kad.rs:110:42: 110:94]>`

> error[E0308]: mismatched types
   --> misc\metrics\src\kad.rs:153:13
    |
118 |             Family::new_with_constructor(|| Histogram::new(exponential_buckets(0.1, 2.0, 10)));
    |                                          ---------------------------------------------------- the found closure
...
153 |             query_result_duration,
    |             ^^^^^^^^^^^^^^^^^^^^^ expected fn pointer, found closure
    |
    = note: expected struct `Family<kad::QueryResult, _, fn() -> open_metrics_client::metrics::histogram::Histogram>`
               found struct `Family<_, _, [closure@misc\metrics\src\kad.rs:118:42: 118:94]>`

For more information about this error, try `rustc --explain E0308`.
error: could not compile `libp2p-metrics` due to 4 previous errors

**Comment by canewsin** [comment]
same issue present on master.

**Comment by karim-agha** [comment]
same issue, on master and on 0.40.0

**Comment by canewsin** [comment]
> same issue, on master and on 0.40.0

temp fix 
`libp2p = {git = "https://github.com/decentnetwork/rust-libp2p.git", branch = "fix-compiling-v0.40"}`

**Comment by karim-agha** [comment]
> > same issue, on master and on 0.40.0
> 
> temp fix `libp2p = {git = "https://github.com/decentnetwork/rust-libp2p.git", branch = "fix-compiling-v0.40"}`

Thank you, I added your fix to my `Cargo.toml`, much appreciated for unblocking me.

```toml
[patch.crates-io]
# temporary fix for https://github.com/libp2p/rust-libp2p/issues/2333 until gets merged to master
libp2p-metrics = { version = "0.1.0", git = "https://github.com/decentnetwork/rust-libp2p.git", branch = "fix-compiling-v0.40" }
```

**Comment by mxinden** [comment]
My bad. `open-metrics-client` `v0.12.1` introduces a breaking change and thus should have been `v0.13.0`. I yanked `v0.12.1`. I will cut a new release (`v0.13.0`) tomorrow.

I am sorry for the trouble @canewsin and @karim-agha. Updating your `Cargo.lock` to use `open-metrics-client` `v0.12.0` should fix the issue above.

See https://github.com/mxinden/rust-open-metrics-client/pull/24.

**Comment by mxinden** [comment]
Closing here for now. Moving the discussion on how to proceed to https://github.com/mxinden/rust-open-metrics-client/pull/24.

**Comment by canewsin** [comment]
@mxinden error happening on latest stable also

**Comment by mxinden** [comment]
> @mxinden error happening on latest stable also

Can you be more specific? Just to make sure, did you downgrade to `open-metrics-client` `v0.12.0` in your `Cargo.lock`? Yanking `v0.12.1` does not automatically downgrade it in your `Cargo.lock`.

**Comment by karim-agha** [comment]
building a new project fails on this. on 0.40 and 0.41
