### ISSUE TITLE
Types should eagerly implement common traits

### ISSUE THREAD

**Issue by elenaf9** [libp2p/rust-libp2p#2341]
At the moment many config-, event- and error-types that are exposed to the user do not implement `Clone`, some not even `Debug`. This can be very inconvenient for the user and force them to create their own copy of the type just to derive the required traits. 
Following chapter [C-COMMON-TRAITS  of the Rust API Guidlines](https://rust-lang.github.io/api-guidelines/interoperability.html#c-common-traits):

> Rust's trait system does not allow orphans: roughly, every impl must live either in the crate that defines the trait or the implementing type. Consequently, crates that define new types should eagerly implement all applicable, common traits.

For rust-libp2p, I would suggest to at least derive `Clone`, `Debug` and `PartialEq` for every type. The latter mostly for convenience, quoting _Rust for Rustaceans_, Chapter 3 _Common Traits for Types_:

> The `PartialEq` trait is particularly desirable, because users will at some point inevitably have two instances of your type that they wish to compare with `==` or `assert_eq!`. Even if your type would compare equal for only the same instance of the type, it’s worth implementing `PartialEq` to enable your users to use `assert_eq!`.

Apart from these very basic traits, I would like to put up for discussion if it would make sense to also derive `serde::{Deserialize, Serialize}` for all types, quoting again _Rust for Rustaceans_:

> Finally, for most types, it makes sense to implement the serde crate’s Serialize and Deserialize traits. These can be easily derived, and the serde_derive crate even comes with mechanisms for overwriting the serialization for just one field or enum variant. Since serde is a third-party crate, you may not wish to add a required dependency on it. Most libraries therefore choose to provide a serde feature that adds support for serde only when the user opts into it.

At least in our project, this is quite relevant and it would make things easier to have them implemented.

Now I don't know how easy it is to derive `Serialize` and `Deserialize` for libp2p, especially for types that libp2p inherits from its dependencies, but if this is generally something that you'd approve, I would have a look at it.
And of course also `Clone`, `Debug` and `PartialEq`, which should imo added either way and not be much work.

**Comment by thomaseizinger** [comment]
I agree with Clone, Debug and PartialEq, esp. for config and event types.

For serde I think we would have to decide on a case by case basis by generally happy to provide it, although I think it should be feature-flagged and off by default.

Which types would you like to serialize/deserialize?

One thing to consider is that the serialization of structs is essentially part of our API and thus changes to it can be breaking. For types with private fields - which would normally allow changes without breaking things - we would therefore definitely need tests that freeze the serde implementation.

**Comment by mxinden** [comment]
> For rust-libp2p, I would suggest to at least derive Clone, Debug and PartialEq for every type.

:+1: 

> Apart from these very basic traits, I would like to put up for discussion if it would make sense to also derive serde::{Deserialize, Serialize} for all types, quoting again Rust for Rustaceans:

Fine by me, though I don't quite understand why this would be helpful for all types. Also in favor of this being feature-flagged.

**Comment by elenaf9** [comment]
So I did some experimental implementation of `Debug`, `Clone` & `PartialEq` for the types in libp2p-core. It's not too much work as it can be done with some simple search and replace (+ manually remove again if there are errors), but it touches almost all types in the code: https://github.com/libp2p/rust-libp2p/commit/7b2f1b846bcd13c1d81ecb37a3672f2903aed8aa
For some of those types this derivation may be unnecessary, but imo there's no reason not to do it, and it's easier to do it for all types rather than evaluating every type individually.
If the amount of affected types is not an issue, I would do a PR for this and also add it for the other folders? Or only for libp2p-core?

> Which types would you like to serialize/deserialize?

> One thing to consider is that the serialization of structs is essentially part of our API and thus changes to it can be breaking. For types with private fields - which would normally allow changes without breaking things - we would therefore definitely need tests that freeze the serde implementation.

That's a very good point that I didn't consider yet.  In my case it would already help a lot just to have it for `PeerId`.
But generally I think it would make sense for the Id-types (`ListenerId`, `ConnectionId`, `PeerId`, ..) / all public newtypes were the inner type already implements serialize (e.g. also `ed25519::Keypair`). Apart from that I would propose implement it for all config, event and error types, since those are quite likely to also be passed around in the user's application. And for these types I would think a change is most of the time a breaking change anyway. Wdyt?

> although I think it should be feature-flagged and off by default.

I agree.

**Comment by thomaseizinger** [comment]
> That's a very good point that I didn't consider yet. In my case it would already help a lot just to have it for `PeerId`.
> But generally I think it would make sense for the Id-types (`ListenerId`, `ConnectionId`, `PeerId`, ..) / all public newtypes were the inner type already implements serialize (e.g. also `ed25519::Keypair`). Apart from that I would propose implement it for all config, event and error types, since those are quite likely to also be passed around in the user's application. And for these types I would think a change is most of the time a breaking change anyway. Wdyt?

Sounds good to me modulo the `Error` types. Why would those need to be `Serialize`?

Unit tests with `serde_test` should be part of this IMO.

**Comment by thomaseizinger** [comment]
Closing as stale. Contributions still welcome but they seem to happen naturally anyway for this kind of issue :)
