### ISSUE TITLE
examples/*: Rewrite event loops using async/await

### ISSUE THREAD

**Issue by mxinden** [libp2p/rust-libp2p#2345]
Today, event loops in `examples/` use poll-style futures. Using async/await simplifies the examples, thus helping newcomers to get started easier.

Example of a complicated poll-style loop:

https://github.com/libp2p/rust-libp2p/blob/4bd44c812a577d0889f9b57f5dcda98113a35573/examples/chat.rs#L142-L195

Example of a simple async/await loop:

https://github.com/libp2p/rust-libp2p/blob/4bd44c812a577d0889f9b57f5dcda98113a35573/protocols/rendezvous/examples/discover.rs#L63-L121

**Comment by jochasinga** [comment]
There is a [chat-tokio.rs](./examples/chat-tokio.rs) that is using an async-await on tokio runtime. Maybe we should also update other outdated examples to use tokio instead of async_std?

**Comment by thomaseizinger** [comment]
The others are not outdated as such! Rust-libp2p supports multiple runtimes, hence there are examples on how to use either.

Tokio requires a bit more configuration, hence there is a dedicated example.

**Comment by mxinden** [comment]
Closing here with https://github.com/libp2p/rust-libp2p/pull/2356 merged.
