### ISSUE TITLE
Deriving NetworkBehaviour for Enums.

### ISSUE THREAD

**Issue by canewsin** [libp2p/rust-libp2p#2353]
Eg:
```
#[derive(Clone)]
pub enum RendezvousBehaviour {
    Client(RendezvousClientBehaviour),
    Server(RendezvousServerBehaviour),
}

#[derive(NetworkBehaviour)]
#[behaviour(event_process = false)]
#[behaviour(out_event = "NetworkEvent")]
pub struct CustomNetworkBehaviour {
    pub ping: Ping,
    pub rend: RendezvousBehaviour ,
}

pub enum NetworkEvent {
    Ping(PingEvent),
}

impl From<PingEvent> for NetworkEvent {
    fn from(event: PingEvent) -> Self {
        NetworkEvent::Ping(event)
    }
}
```
Here macro don't know how to convert RendezvousBehaviour Events to their respective Events(Client/Server).

**Comment by canewsin** [comment]
only solution here i got is 2 seperate behaviours for server and client, but it will break impl code logic to two whole pieces. which results in code duplication of everything. This is same case for `#[behaviour(event_process = true)]`.  Any Suggestions ?

**Comment by mxinden** [comment]
Unfortunately we are missing an `EitherBehaviour`, along the lines of the [`Either` `ProtocolsHandler`](https://github.com/libp2p/rust-libp2p/blob/master/swarm/src/protocols_handler/either.rs). Contribution of an `EitherBehaviour` would be very much appreciated.

In the meantime you could use [`Toggle`](https://github.com/libp2p/rust-libp2p/blob/master/swarm/src/toggle.rs) to enable and disable one of them.

**Comment by mexskican** [comment]
@mxinden Could you assign this to me? I would like to submit a PR for `EitherBehaviour`
