### ISSUE TITLE
swarm-derive/: Do not default `out_event` to `()` when `event_process=false`

### ISSUE THREAD

**Issue by mxinden** [libp2p/rust-libp2p#2373]
By default the `NetworkBehaviour` derive macro `out_event` attribute is `()`. This makes sense when the `event_process` attribute is set to `true`, though with https://github.com/libp2p/rust-libp2p/pull/2214 the `NetworkBehaviour` derive macro `event_process` attribute is `false` by default. Not processing the event (`event_process=false`) and setting an empty out event (`()`) defeats the purpose of the event mechanism of the `NetworkBehaviour` trait.

I suggest requiring a user to set `out_event` to a custom `enum` when `event_process` is `false`.

This has been raised by @thomaseizinger in https://github.com/libp2p/rust-libp2p/pull/2361#discussion_r760618372.

**Comment by thomaseizinger** [comment]
We now automatically generate the out event.
