### ISSUE TITLE
libp2p connections can stick around in zombi mode

### ISSUE THREAD

**Issue by dvc94ch** [libp2p/rust-libp2p#2388]
this happens reliably when hot reloading our flutter application during testing. there is no `inject_disconnected` or `inject_connected` emitted, just a new `inject_connection_established`. this causes all sorts of weird behaviour as the other application when using `NotifyHandler::Any` will send the on the old connection that refuses to die.

**Comment by canewsin** [comment]
Oh My, this is the reason My Flutter App hangs after hot reload, have to close and restart the App.

**Comment by mxinden** [comment]
Does this happen on `v0.41.0` or `master`? In other words, does this happen with https://github.com/libp2p/rust-libp2p/pull/2350 included?

**Comment by dvc94ch** [comment]
happens with #2350 included. but banning doesn't have anything to do with it. I'm thinking one solution would be to generate a random number at startup and send it with multistream-select. then if there was a state loss the other peer would detect it by receiving a new connection with a new session id or whatever you want to call it. that would then cause the swarm to close all the expired sessions and emit the proper events.

**Comment by mxinden** [comment]
I am not sure I follow on the bug report itself. Would you mind describing the steps involved? How do connections get into the "zombie" state? Does one endpoint disconnect?

**Comment by dvc94ch** [comment]
a connects to b
swarm a restarts
a connects to b
b has two connections from a
b sends messages on first connection which never arrive (which can be checked by using `NotifyHandler::One(connection_id)` instead of `NotifyHandler::Any`.

would add a test to reproduce it but it requires tons of boilerplate. wasn't there an effort to add an add_address to the swarm?

**Comment by dvc94ch** [comment]
actually never mind. just thought that the other explanation is that the old swarm isn't shut down and somehow still around. seems like that's more likely
