### ISSUE TITLE
gossipsub peer sharing

### ISSUE THREAD

**Issue by Frederik-Baetens** [libp2p/rust-libp2p#2391]
I'm trying to build a system where nodes connect to a set of known nodes to join the gossipsub network.

However, it seems like these peers don't reach out to eachother after establishing a connection to the known nodes.

Is there any way to get some sort of peer sharing & automatic connection handling?

I saw [this pr](https://github.com/libp2p/rust-libp2p/pull/1720) and it mentions peer eXchange being held up by [an addition to the spec](https://github.com/libp2p/specs/pull/217) which has been merged for a while now, but i'm not sure if that spec has been implemented yet.

An example of what i'm trying to do (adapted from the libp2p examples): https://github.com/Frederik-Baetens/libp2p-tokiochat

It allows starting the first node with `cargo run`. The following nodes are then connected with `cargo run  -- *multiaddr of first node*`

I'd like the additional nodes to find eachother, and for the chat application to keep working after the first node has been shut down. Currently I get an insufficientpeers error after the original node gets shut down.

Am I supposed to implement this functionality myself based on things like https://docs.rs/libp2p/latest/libp2p/core/struct.Network.html#method.connected_peers ? Or could this be made to work of the box?

Older issue about this: https://github.com/libp2p/rust-libp2p/issues/1559

**Comment by mxinden** [comment]
Thanks for the detailed issue @Frederik-Baetens. Are you calling `GossipsubConfig::do_px`?

**Comment by Frederik-Baetens** [comment]
I'm constructing my config as follows:

```
        // Set a custom gossipsub
        let gossipsub_config = gossipsub::GossipsubConfigBuilder::default()
            .heartbeat_interval(Duration::from_secs(10)) // This is set to aid debugging by not cluttering the log space
            .validation_mode(ValidationMode::Strict) // This sets the kind of message validation. The default is Strict (enforce message signing)
            .message_id_fn(message_id_fn) // content-address messages. No two messages of the
            // same content will be propagated.
            .build()
            .expect("Valid config");
```

So i think it should be enabled, since it says that it's enabled by default in the docs. I tried adding .do_px() explicitly to the configbuilder, but that doesn't seem to make a difference. Should I do something for peer exchange when calling the eventloop/handling gossipsub events?

**Comment by Frederik-Baetens** [comment]
I've pushed an update to my example repository with the explicit do_px(). It still doesn't seem to work.

I made a small recording of what happens:

https://user-images.githubusercontent.com/18269095/146755337-04f97d7a-1218-4e32-8a21-6ae2ed8c00f1.mp4

**Comment by AgeManning** [comment]
Yes. Sorry this was not documented well. Gossipsub currently does not support peer exchange because rust-libp2p did not support signed peer records.

I've not been up to date with the current state of the peer records, but we will add this feature when we can.

**Comment by AgeManning** [comment]
Please see this for more details: https://github.com/libp2p/rust-libp2p/pull/2397

**Comment by thomaseizinger** [comment]
> I've not been up to date with the current state of the peer records, but we will add this feature when we can.

We have peer records now! They were added as part of the rendezvous protocol!

See: https://github.com/libp2p/rust-libp2p/blob/master/core/src/peer_record.rs

**Comment by Frederik-Baetens** [comment]
So should this feature work? Does do_px actually do anything?

**Comment by mxinden** [comment]
> So should this feature work? Does do_px actually do anything?

Unfortunately it does not, thus for now you need to rely on a different discovery mechanism (e.g. `libp2p-kad`, `libp2p-rendezvous` or `libp2p-mdns`). 

Tracked here https://github.com/libp2p/rust-libp2p/issues/2398. Contributions are welcome, right @AgeManning?

**Comment by AgeManning** [comment]
> Tracked here #2398. Contributions are welcome, right @AgeManning?

Absolutely. 

If you dont want to build this yourself. We will get to it, its just going to take some time, pretty flat out at the moment :).
