### ISSUE TITLE
libp2p-mdns should use a non standard multicast address to prevent detecting non libp2p nodes

### ISSUE THREAD

**Issue by dvc94ch** [libp2p/rust-libp2p#2394]

**Comment by thomaseizinger** [comment]
I am not sure I understand correctly. What is a non-standard multicast address?

Also, that topic is maybe better discussed at https://github.com/libp2p/specs?

**Comment by dvc94ch** [comment]
their goal is some compatibility with mdns even though it's not really compatible. the mdns multicast address is `224.0.0.251`. the easiest way to break compatibility is by using a different address like `224.0.0.252`.

**Comment by thomaseizinger** [comment]
Closing as would have to be discussed in `libp2p/specs`.
