### ISSUE TITLE
Kademlia nodes cannot communicate if protocol name is set

### ISSUE THREAD

**Issue by laptou** [libp2p/rust-libp2p#2420]
I tried to create a custom Kademlia network by changing the protocol name with `KademliaConfig::set_protocol_name()`. However, even though I used the same protocol name for all of my nodes, this would cause them to fail to communicate with each other, instead giving an error `Upgrade(Upgrade(Select(ProtocolError(InvalidProtocol))))`. Is there anything else I need to do to make this work properly?

**Comment by mxinden** [comment]
Does your protocol name start with a `/` @laptou? See:

https://github.com/libp2p/rust-libp2p/blob/e19391e966d64aad1839aa7781a275c64100c75a/misc/multistream-select/src/protocol.rs#L82-L87

**Comment by laptou** [comment]
Ah, it did not. I can whip up a PR to document this requirement; where would be the best places to put that information?

**Comment by mxinden** [comment]
> I can whip up a PR to document this requirement

:rocket: 

I would suggest documenting it on `Protocol`:

https://github.com/libp2p/rust-libp2p/blob/5617481e56e3949dabc7ead26f15a75c0f50136f/misc/multistream-select/src/protocol.rs#L69-L71

and linking to `Protocol` in

https://github.com/libp2p/rust-libp2p/blob/5617481e56e3949dabc7ead26f15a75c0f50136f/protocols/kad/src/behaviour.rs#L218-L226

**Comment by mxinden** [comment]
@laptou friendly ping. Would you still be up for documenting this?
