### ISSUE TITLE
Example about file-sharing

### ISSUE THREAD

**Issue by fanux** [libp2p/rust-libp2p#2426]
https://github.com/libp2p/rust-libp2p/blob/master/examples/file-sharing.rs 

The example read all the file content, how to share a big file. The provider read it from disk, receiver read file stream and dump to disk?

**Comment by mxinden** [comment]
In the case of a big file you would likely want to stream the content instead of reading it into memory all at once.

**Comment by fanux** [comment]
@mxinden Yes, but how?

**Comment by mxinden** [comment]
I am closing here. Feel free to re-open, but please help us help you by being more specific.
