### ISSUE TITLE
libp2p-websocket: replace /wss with /tls/ws

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#2449]
According to the multiaddr spec, the `/wss` specifier is deprecated and `/tls/ws` should be preferred.
`libp2p-websocket` only supports `/wss`.

(I've taken the liberty to mark this as "easy", as it's just about interpreting the multiaddr)

**Comment by jochasinga** [comment]
Shouldn't this change be made on the multiaddr crate too?

**Comment by mxinden** [comment]
> Shouldn't this change be made on the multiaddr crate too?

Should be done via https://github.com/multiformats/rust-multiaddr/pull/48/.

**Comment by jochasinga** [comment]
I can tackle this @mxinden @tomaka.

**Comment by jochasinga** [comment]
Looks to me like even `/wss` scheme isn't supported currently? Keep getting `MultiaddrNotSupported("/ip6/::1/tcp/0/wss")` running test.

Since [multiformats/rust-multiaddr#48 ](https://github.com/multiformats/rust-multiaddr/pull/48) added tls support, will this be just upgrading libp2p-websocket to use it?

**Comment by jochasinga** [comment]
Does this test case for rust-multiaddr make sense @tomaka?

```rust

// rust-multiaddr/src/from_url.rs

#[test]
fn normal_usage_wss() {
    let addr = from_url("wss://127.0.0.1:8000").unwrap();
    assert_eq!(addr, "/ip4/127.0.0.1/tcp/8000/tls/ws".parse().unwrap());
    assert_eq!(addr, "/ip4/127.0.0.1/tcp/8000/wss".parse().unwrap());
}
```

Basically, when parsing a multiaddress, when a `tls` is found, we peek to see if the next one is "ws" and write that off as `Protocol::Wss(..)`.

**Comment by tomaka** [comment]
I don't think it's a good idea to make `/tls/ws` and `/wss` equal. This is too magic and could lead to violated assumptions.
In my opinion the only change needed is making `libp2p-websocket` support `/tls/ws`.

**Comment by navasvarela** [comment]
Hello everyone, are there any updates on TLS support for websockets?

**Comment by thomaseizinger** [comment]
> Hello everyone, are there any updates on TLS support for websockets? 

Support is there and there is an example in the docs! This ticket is only about the deprecated multiaddr component.

**Comment by navasvarela** [comment]
Thank you!

**Comment by navasvarela** [comment]
> > Hello everyone, are there any updates on TLS support for websockets?
> 
> Support is there and there is an example in the docs! This ticket is only about the deprecated multiaddr component.

Thank you! Would you be able to point me to the example?

**Comment by thomaseizinger** [comment]
> > > Hello everyone, are there any updates on TLS support for websockets?
> > 
> > 
> > Support is there and there is an example in the docs! This ticket is only about the deprecated multiaddr component.
> 
> Thank you! Would you be able to point me to the example?

See https://docs.rs/libp2p-websocket/latest/libp2p_websocket/struct.WsConfig.html#examples. It is a bit hard to discover. We are in the process of making the APIs of our crates more consistent, see https://github.com/libp2p/rust-libp2p/issues/2217. Help in doing that for `libp2p-websocket` would be appreciated :)

**Comment by thomaseizinger** [comment]
Closing in favor of https://github.com/multiformats/rust-multiaddr/issues/100.
