### ISSUE TITLE
Inconsistent `Swarm::listen_on()` behavior

### ISSUE THREAD

**Issue by altonen** [libp2p/rust-libp2p#2451]
Hi, I'm working on a project that uses rust-libp2p and when I was writing a test that tries to bind to same interface twice to verify that the second bind would fail, I got inconsistent results. On Linux the second call to `listen_on()` fails whereas on Windows both calls succeed. Is this a bug in rust-libp2p or am I using the library incorrectly? Below is a small example that reproduces the bug.

```rust
use libp2p::{
    ping,
    core::upgrade,
    identity, mplex,
    noise,
    swarm::SwarmBuilder,
    tcp::TcpConfig,
    Transport,
};

fn main() {
    let id_keys = identity::Keypair::generate_ed25519();
    let peer_id = id_keys.public().to_peer_id();
    let noise_keys = noise::Keypair::<noise::X25519Spec>::new().into_authentic(&id_keys).unwrap();

    let transport = TcpConfig::new()
        .nodelay(true)
        .port_reuse(false)
        .upgrade(upgrade::Version::V1)
        .authenticate(noise::NoiseConfig::xx(noise_keys).into_authenticated())
        .multiplex(mplex::MplexConfig::new())
        .boxed();

    let mut swarm = SwarmBuilder::new(
        transport,
        ping::Behaviour::new(ping::Config::new().with_keep_alive(true)),
        peer_id,
    )
    .build();

    // first `listen_on()` succeeds as it should
    assert!(swarm.listen_on("/ip6/::1/tcp/8888".parse().unwrap()).is_ok());

    // second `listen_on()` fails on linux and succeeds on windows
    assert!(swarm.listen_on("/ip6/::1/tcp/8888".parse().unwrap()).is_err());
}
```

**Comment by mxinden** [comment]
Unfortunately I am not very familiar with the TCP network stack on Windows. Might it be that we are not explicitly setting [`SO_EXCLUSIVEADDRUSE`](https://docs.microsoft.com/en-us/windows/win32/winsock/using-so-reuseaddr-and-so-exclusiveaddruse#using-so_exclusiveaddruse) on windows?

**Comment by rkuhn** [comment]
While I can’t check libp2p code right now I can confirm that on Windows a special flag is needed so that the second bind is denied.

**Comment by altonen** [comment]
Thank you both for your responses. I'll check if I can fix this issue with your suggestion @mxinden and open a PR if it works.
