### ISSUE TITLE
Kademlia key value validation

### ISSUE THREAD

**Issue by nazar-pc** [libp2p/rust-libp2p#2478]
It is quite often the case that the value stored on DHT is addressed by its hash. If this is the case, it is only needed to find one node that can return value whose hash corresponds to the key.

Right now there is no mechanism to "inject" value validation and stop lookup before quorum is reached or nodes towards the target are checked if correct value is already found.

With that I think there would be a value to have an API that can support value validation to more closely mimic some of the Mainline DHT functionality, http://ll.www.bittorrent.org/beps/bep_0044.html specifically for both puts and gets:
* puts can be validated to either be content-addressable or to have signature that corresponds to the key if key is a public key hash
* gets can be validated in a similar way and optimized for speed in case of content addressable variant (for signatures there could be several revisions and it might be desirable to collect all known revisions before deciding which one to pick)

**Comment by mxinden** [comment]
Would using a read quorum of 1 and record filtering be enough to support your use case?

https://github.com/libp2p/rust-libp2p/blob/8d1366616714083617a1fa6e83b4e54effb1d8dc/protocols/kad/src/behaviour.rs#L139-L160

**Comment by nazar-pc** [comment]
I don't think so. Record filtering should help with inserts, but during retrieval what I'd like to do is to get 1 correct value (let's say whose hash is equal to the key), not just 1 result even if it is not correct.

**Comment by thomaseizinger** [comment]
Closing as stale.
