### ISSUE TITLE
Implementing utp for rust-libp2p

### ISSUE THREAD

**Issue by oslfmt** [libp2p/rust-libp2p#2479]
What is the status of utp development for rust libp2p? Afaik, there is no implementation, and I don't see any PRs that have started implementation. If no effort has been made to start development, I may be interested in potentially starting an implementation.

**Comment by mxinden** [comment]
I am a bit confused. Are you referring to U**D**P?

**Comment by nikoPLP** [comment]
I believe he is referring to https://github.com/libp2p/go-utp-transport.
I understands that QUIC is the current way to do UDP connections.

**Comment by oslfmt** [comment]
@nikoPLP is correct. I saw on the libp2p.io site that currently the rust implementation is missing a utp implementation. As far as I understand utp is just a reliable data stream abstracted over UDP, it is like a TCP clone over UDP, similar to how QUIC operates I think. It stands for "uTorrent transport protocol": https://www.bittorrent.org/beps/bep_0029.html

**Comment by dignifiedquire** [comment]
> I understands that QUIC is the current way to do UDP connections.

"current way" is a stretch, it is one way of doing it, which is heavily optimized for specific use cases (namely replacing http), so having other UDP based transports would be very useful imho.

**Comment by danielSanchezQ** [comment]
@victor-wei126 , actually there are PRs. [Latest](https://github.com/libp2p/rust-libp2p/pull/2289)
