### ISSUE TITLE
protocols/gossipsub: Unexpected delivery trace

### ISSUE THREAD

**Issue by jsdanielh** [libp2p/rust-libp2p#2494]
After upgrading to 0.42.0 (gossipsub 0.35.0) I started to see this message when rejecting a message (reporting an `Ignore` or `Reject` as message validation):
```
Unexpected delivery trace: Message from 12D3KooWSsDZA2nT4WGsZ5Sd1qsrVjMt5pY8p7urwGQPLdHtoKia was first seen 0s ago and has a delivery status Ignored
```
This also using content base addressing (using the hash of the message as `MessageId`).

After digging a little more, the change that is making the message to appear comes from [this change](https://github.com/libp2p/rust-libp2p/pull/2327) where specifically [here](https://github.com/libp2p/rust-libp2p/pull/2327/files#diff-368386d6c30a7eb4d60fcddda689bba01e9e215451a387fa58ff93b12fb914deR809-R811) the code is now calling `reject_message` for different peers. 
But when it goes inside [the function](https://github.com/libp2p/rust-libp2p/blob/17861d9cac121f7e448585a7f052d5eab4618826/protocols/gossipsub/src/peer_score.rs#L642-L645) the `deliveries` `TimeCache` is addressed by `MessageId` (which in my case is the hash of the message) and thus when called for [the second time](https://github.com/libp2p/rust-libp2p/pull/2327/files#diff-368386d6c30a7eb4d60fcddda689bba01e9e215451a387fa58ff93b12fb914deR809-R811), the record hash returns the record as already validated and then the message is printed and no further code is executed in this function.

**Comment by AgeManning** [comment]
Hey. Yes. This is an oversight on my behalf. 

The original scoring was not designed for the optimization that I added, and I missed this warning. It is harmless though. 

We have been looking more deeply into gossipsub. If you are using it there are some other more significant issues we are dealing with which should be patched in the next version.

**Comment by mxinden** [comment]
Closing here with #2496 merged. Thanks for the report and the quick fix!
