### ISSUE TITLE
Can't generate /src/rpc_proto.rs locally on my Manjaro computer,

### ISSUE THREAD

**Issue by jamesray1** [libp2p/rust-libp2p#250]
On a related note to #183, I can't generate /src/rpc_proto.rs locally on my Manjaro computer, so my options are:
- rewrite regen_structs_proto.sh to handle different linux distros e.g. as per https://unix.stackexchange.com/a/6348/262632
- set up a Ubuntu VM on top of Manjaro
- run Ubuntu on my dual boot;
- test with Travis (not good practice).

I need to do this to start test driven development of gossipsub, starting with using the modified rpc.proto.

**Comment by tomaka** [comment]
cc #183

**Comment by Vurich** [comment]
What error are you seeing?

**Comment by jamesray1** [comment]
It's alright I'll handle it via #183. The script is using aptitude which is Ubuntu specific.

**Comment by jamesray1** [comment]
It's alright I'll handle it via #183. The script is using aptitude which is Ubuntu specific.
