### ISSUE TITLE
libp2p_dns and circuit-relay v2 missbehaving

### ISSUE THREAD

**Issue by demfabris** [libp2p/rust-libp2p#2503]
## Issue
Dialing a relayed address with DNS transport enabled fails with `MultiaddrNotSupported`

## Culprit
The execution fails in this function https://github.com/libp2p/rust-libp2p/blob/b39770b8e9bfb113235c9ab8f7f2df2392482073/transports/tcp/src/lib.rs#L678

## Reproducing
Implemented a reproducible example over the existing `relay_v2.rs` example
PR: #2502

Head to `protocols/relay`
Open 3 terminal windows and follow this instructions **in order**:
1. first terminal window:
```shell 
$ RUST_LOG=info cargo run --example relay_v2 -- --port 4005 --secret-key-seed 123
```
2. second terminal window:
```shell
$ RUST_LOG=info cargo run --example relay_v2 -- --port 4006 --secret-key-seed 234 --dial /ip4/192.168.1.77/tcp/4005/p2p/12D3KooWLGGpq6Ro6AnCPQzryEbsKBdyksQGpdymNryMBjBzVxfD
```
3. third terminal window: 
```shell
RUST_LOG=info cargo run --example relay_v2 -- --port 4007 --secret-key-seed 111 --dial /ip4/192.168.1.77/tcp/4005/p2p/12D3KooWLGGpq6Ro6AnCPQzryEbsKBdyksQGpdymNryMBjBzVxfD/p2p-circuit/p2p/12D3KooWACdDu7PiwBBukn58ZSjmMKucbB1KvuYPGStzihqSkJVs
```
_I think these `secret-key-seed` arguments guarantee the same peer ids as above, not positive on that. In the case that the peers differ simply swap the peer ids with the ones that appear on stdout when executing._

## Error
terminal window 3 will probably contain:
```text
[2022-02-10T02:10:03Z INFO  relay_v2] OutgoingConnectionError { peer_id: Some(PeerId("12D3KooWACdDu7PiwBBukn58ZSjmMKucbB1KvuYPGStzihqSkJVs")),
 error: Transport([("/ip4/192.168.1.77/tcp/4005/p2p/12D3KooWLGGpq6Ro6AnCPQzryEbsKBdyksQGpdymNryMBjBzVxfD/p2p-circuit/p2p/12D3KooWACdDu7PiwBBukn58ZSjmMKucbB1KvuYPGStzihqSkJVs", 
Other(Custom { kind: Other, error: Other(A(A(A(MultiaddrNotSupported("/ip4/192.168.1.77/tcp/4005/p2p/12D3KooWLGGpq6Ro6AnCPQzryEbsKBdyksQGpdymNryMBjBzVxfD/p2p-circuit/p2p/12D3KooWACdDu7PiwBBukn58ZSjmMKucbB1KvuYPGStzihqSkJVs"))))) }))]) }
```

Disable the `dns` transport in the example and you'll see that the process above works

**Comment by thomaseizinger** [comment]
Closing as stale. From what I saw in the linked PR, the issue got resolved.
