### ISSUE TITLE
core/src/signed_envelope: Enforce verification of public key on `SignedEnvelope::payload`

### ISSUE THREAD

**Issue by mxinden** [libp2p/rust-libp2p#2511]
`PeerRecord::from_signed_envelope` would previously (before https://github.com/libp2p/rust-libp2p/pull/2491) not validate that the public key of the `SignedEnvelope` matches the `PeerId` of the `PeerRecord`.

Today `PeerRecord` directly accesses `SignedEnvelope::key` as a quick fix. Long term we should enforce verification through the type system. Ideas thus far:

- @MarcoPolo: Return both the payload and the public key on `SignedEnvelope::payload`.
- @thomaseizinger: Require passing a close to `SignedEnvelope::payload` validating the public key.

Any additional suggestions? Thoughts? Volunteers?

**Comment by MarcoPolo** [comment]
Happy to take this. @thomaseizinger can you elaborate a bit more on the closure approach? Specifically what is the type signature? I'm fine with either. Though the closure approach seems a little better since it seems a bit harder to ignore.
