### ISSUE TITLE
trait bound for deriving `NetworkBehaviour`

### ISSUE THREAD

**Issue by divagant-martian** [libp2p/rust-libp2p#2524]
When deriving `NetworkBehaviour` on a struct with generics, not being able to include bounds in the resulting trait implementation forces the bounds to be added to the struct and not the impl only. This potentially generates a great deal of trait propagation (in behaviour composition, for example)

Maybe there is a way to do this but I don't seem to find it in the docs

**Comment by mxinden** [comment]
@divagant-martian would you mind providing an example?

> not being able to include bounds in the resulting trait implementation

I am not sure I follow. Why can you not add a bound to the trait implementation?

For example, the below compiles:

``` rust
trait ToBeImplemented {}

trait SomeBound {}

struct Foo<T> {
    something: T,
}

impl<T> ToBeImplemented for Foo<T> where T: SomeBound {}
```

**Comment by divagant-martian** [comment]
@mxinden as I said, the problem is in the derivation of the `NetworkBehaviour` implementation. I don't understand what is your example trying to prove. That's exactly what I would like.. for the _derived_ `NetworkBehaviour` impl

**Comment by mxinden** [comment]
Ah, sorry I didn't read properly.

> Maybe there is a way to do this but I don't seem to find it in the docs

I am not aware of such mechanism.

**Comment by divagant-martian** [comment]
Got it. I'll check around how it's usually done in derive macros, and if possible implement it

**Comment by thomaseizinger** [comment]
Let me know if still an issue.

**Comment by divagant-martian** [comment]
No longer an issue!
