### ISSUE TITLE
Unicast communication

### ISSUE THREAD

**Issue by StefanoSetti** [libp2p/rust-libp2p#2545]
What i want to achieve is to send a message in gossip in a network from **peer A**, and each peer in the network (in case they want to answer) should response in unicast to **peer A**.

Is there a protocol already implemented? Or do i need to implement a custom one (if yes, how to do it?)

**Comment by mxinden** [comment]
Checkout `libp2p-request-response`.

https://github.com/libp2p/rust-libp2p/tree/master/protocols/request-response

**Comment by StefanoSetti** [comment]
I'm trying to implement it in a custom behaviour,

```rust
#[derive(NetworkBehaviour)]
#[behaviour(out_event = "ComposedEvent")]
struct ComposedBehaviour {
    identify: Identify,
    kademlia: Kademlia<MemoryStore>,
    gossip: Gossipsub,
    reqres: RequestResponse<>,
    #[behaviour(ignore)]
    network: String,
    #[behaviour(ignore)]
    peer_id: PeerId,
}
```

what should I put in  `RequestResponse<>` as generic parameter? Which are my choices?

**Comment by mxinden** [comment]
See an example here: https://github.com/libp2p/rust-libp2p/blob/a168410dbed0d0941f2e5a14543206044ccb2260/protocols/request-response/tests/ping.rs#L314-L390

**Comment by StefanoSetti** [comment]
Thanks a lot!
