### ISSUE TITLE
`chat-tokio` example. Network dies.

### ISSUE THREAD

**Issue by Jerrody** [libp2p/rust-libp2p#2556]
After a while, the network just dies. Every peer stops receiving or sending messages.

As you can see in the screenshot, other peers don't get messages from others.
![image](https://user-images.githubusercontent.com/68968657/158071251-212c7f2b-5331-44c5-83ad-0c31c357551a.png)

Code:
```rs
#![feature(trivial_bounds)]

use libp2p::core::upgrade::Version::V1;
use libp2p::futures::StreamExt;
use libp2p::swarm::{NetworkBehaviourEventProcess, SwarmBuilder};
use libp2p::tcp::TokioTcpConfig;
use libp2p::{floodsub::{self, Floodsub, FloodsubEvent}, mdns::{Mdns, MdnsEvent}, mplex, swarm::SwarmEvent, NetworkBehaviour, Transport, Multiaddr};
use tokio::io::AsyncBufReadExt;
use tokio::select;

#[derive(NetworkBehaviour)]
#[behaviour(event_process = true)]
struct Behavior {
    floodsub: Floodsub,
    mdns: Mdns,
    // #[behavior(ignore)]
    // ignored_number: bool,
}

impl Behavior {
    pub fn new(floodsub: Floodsub, mdns: Mdns) -> Self {
        Self { floodsub, mdns }
    }
}

impl NetworkBehaviourEventProcess<FloodsubEvent> for Behavior {
    // Called when `floodsub` produces an event.
    fn inject_event(&mut self, message: FloodsubEvent) {
        if let FloodsubEvent::Message(message) = message {
            println!(
                "Received: '{:?}' from {:?}",
                String::from_utf8_lossy(&message.data),
                message.source
            );
        }
    }
}

impl NetworkBehaviourEventProcess<MdnsEvent> for Behavior {
    // Called when `mdns` produces an event.
    fn inject_event(&mut self, event: MdnsEvent) {
        match event {
            MdnsEvent::Discovered(list) => {
                for (peer, _) in list {
                    println!("New peer: {:?}", peer);
                    self.floodsub.add_node_to_partial_view(peer);
                }
            }
            MdnsEvent::Expired(list) => {
                for (peer, _) in list {
                    if !self.mdns.has_node(&peer) {
                        println!("Deleted peer: {:?}", peer);
                        self.floodsub.remove_node_from_partial_view(&peer);
                    }
                }
            }
        }
    }
}

#[tokio::main]
async fn main() {
    let local_key = libp2p::identity::Keypair::generate_ed25519();
    let local_peer_id = libp2p::PeerId::from(local_key.public());

    let noise_key = libp2p::noise::Keypair::<libp2p::noise::X25519Spec>::new()
        .into_authentic(&local_key)
        .unwrap();
    let transport = TokioTcpConfig::new()
        .nodelay(true)
        .upgrade(V1)
        .authenticate(libp2p::noise::NoiseConfig::xx(noise_key).into_authenticated())
        .multiplex(mplex::MplexConfig::default())
        .boxed();
    let topic = floodsub::Topic::new("chat");

    let mut swarm = {
        let mdns = Mdns::new(libp2p::mdns::MdnsConfig::default())
            .await
            .unwrap();

        let mut behaviour = Behavior::new(Floodsub::new(local_peer_id), mdns);
        behaviour.floodsub.subscribe(topic.clone());

        SwarmBuilder::new(transport, behaviour, local_peer_id)
            .executor(Box::new(|future| {
                tokio::spawn(future);
            }))
            .build()
    };

    if let Some(to_dial) = std::env::args().nth(1) {
        let addr: Multiaddr = to_dial.parse().unwrap();
        swarm.dial(addr).unwrap();
        println!("Dialed {:?}", to_dial);
    }

    swarm
        .listen_on("/ip4/0.0.0.0/tcp/0".parse().unwrap())
        .unwrap();

    let mut stdin = tokio::io::BufReader::new(tokio::io::stdin()).lines();

    loop {
        select! {
            line = stdin.next_line() => {
                let line = line.unwrap().expect("stdin closed");
                swarm.behaviour_mut().floodsub.publish(topic.clone(), line.as_bytes());
            }
            event = swarm.select_next_some() => {
                if let SwarmEvent::NewListenAddr { address, ..} = event {
                    println!("Listening new address: {:?}", address);
                }
            }
        }
    }
}
```

P.S.
Okay, I understand the reason, that expires TTL of the Peer. How can I do this unlimited or make a big expiration date of this? How this address can be refreshed?
```rs
 MdnsEvent::Expired(list) => {
                for (peer, _) in list {
                    if !self.mdns.has_node(&peer) {
                        println!("Deleted peer: {:?}", peer);
                        self.floodsub.remove_node_from_partial_view(&peer);
                    }
                }
            }
```
*The given combinations of PeerId and Multiaddr have expired.
Each discovered record has a time-to-live. When this TTL expires and the address hasn't been refreshed, we remove it from the list and emit it as an Expired event.*

**Comment by Jerrody** [comment]
Okay, I understand the reason, That expires TTL of the Peer. How can I do this unlimited or make a big expiration date of this?
```rs
 MdnsEvent::Expired(list) => {
                for (peer, _) in list {
                    if !self.mdns.has_node(&peer) {
                        println!("Deleted peer: {:?}", peer);
                        self.floodsub.remove_node_from_partial_view(&peer);
                    }
                }
            }
```
*The given combinations of PeerId and Multiaddr have expired.
Each discovered record has a time-to-live. When this TTL expires and the address hasn't been refreshed, we remove it from the list and emit it as an Expired event.*

**Comment by mxinden** [comment]
`libp2p-mdns` should continuously exchange UDP packets, thus peers should never expire and thus never be removed from floodsub.

Which versions are you running? Can you take a look with `RUST_LOG=debug`, more specifically focus on the `libp2p-mdns` logs.

**Comment by Jerrody** [comment]
> `libp2p-mdns` should continuously exchange UDP packets, thus peers should never expire and thus never be removed from floodsub.
> 
> Which versions are you running? Can you take a look with `RUST_LOG=debug`, more specifically focus on the `libp2p-mdns` logs.

Roger that I will try to get logs.

**Comment by Jerrody** [comment]
> `libp2p-mdns` should continuously exchange UDP packets, thus peers should never expire and thus never be removed from floodsub.
> 
> Which versions are you running? Can you take a look with `RUST_LOG=debug`, more specifically focus on the `libp2p-mdns` logs.

```rs
[2022-03-14T19:53:50Z DEBUG libp2p_mplex::io] 9f41e4309ba830af: Multiplexed connection failed: Kind(UnexpectedEof)
[2022-03-14T19:53:50Z DEBUG libp2p_swarm] Connection closed with error KeepAliveTimeout: Connected { endpoint: Listener { local_addr: "/ip4/26.191.225.201/tcp/1480", send_back_addr: "/ip4/26.191.225.201/tcp/1486" }, peer_id: PeerId(
"12D3KooWKJt1n8y2wCiWC2c3NYwatADbA5reWS3jwH2QnKfZ82d7") }; Total (peer): 1.
[2022-03-14T19:53:50Z DEBUG libp2p_swarm] Connection closed with error IO(Kind(UnexpectedEof)): Connected { endpoint: Dialer { address: "/ip4/26.191.225.201/tcp/1478/p2p/12D3KooWKJt1n8y2wCiWC2c3NYwatADbA5reWS3jwH2QnKfZ82d7", role_ov
erride: Dialer }, peer_id: PeerId("12D3KooWKJt1n8y2wCiWC2c3NYwatADbA5reWS3jwH2QnKfZ82d7") }; Total (peer): 0.
```

**Comment by Jerrody** [comment]
> `libp2p-mdns` should continuously exchange UDP packets, thus peers should never expire and thus never be removed from floodsub.
> 
> Which versions are you running? Can you take a look with `RUST_LOG=debug`, more specifically focus on the `libp2p-mdns` logs.

And the question about `Gossipsub`. How to connect to another peers without `swarm.dial()`? I try to use `add_explicit_peer` for to connect, but nothing happens. I just get:
```rs
[2022-03-14T20:08:05Z DEBUG libp2p_gossipsub::behaviour] Adding explicit peer 12D3KooWQmsWSq2iuUFBCJzE5BFnBNZVLXf44cywGaUM5QYPbXwK
[2022-03-14T20:08:05Z DEBUG libp2p_gossipsub::behaviour] Connecting to explicit peer PeerId("12D3KooWQmsWSq2iuUFBCJzE5BFnBNZVLXf44cywGaUM5QYPbXwK")
```
But I can't get any message.

And if I try to dial with known `peer_id`. I get an error:
```rs
        swarm.dial(peer_id).unwrap();
```
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NoAddresses', examples\gossipsub-chat.rs:122:29
```

**Comment by StefanoSetti** [comment]
do you have closed the issue because a solution was found?

**Comment by Jerrody** [comment]
> do you have closed the issue because a solution was found?

Yep.

**Comment by Camusugar** [comment]
How did you solve this problem? Can you share it，Thank you

**Comment by zscott** [comment]
I am also having a similar issue running the chat example unmodified.
`
[2022-06-29T14:22:24Z DEBUG libp2p_swarm] Connection closed with error KeepAliveTimeout: Connected { endpoint: Dialer { address: "/ip4/10.2.255.190/tcp/50788/p2p/12D3KooWCEnPXGiSuyszQo342rTo7uDD3cvBGph7qzPGcYTiHs34", role_override: Dialer }, peer_id: PeerId("12D3KooWCEnPXGiSuyszQo342rTo7uDD3cvBGph7qzPGcYTiHs34") }; Total (peer): 1.
[2022-06-29T14:22:24Z DEBUG libp2p_swarm] Connection closed with error KeepAliveTimeout: Connected { endpoint: Listener { local_addr: "/ip4/10.2.255.190/tcp/50791", send_back_addr: "/ip4/10.2.255.190/tcp/50795" }, peer_id: PeerId("12D3KooWCEnPXGiSuyszQo342rTo7uDD3cvBGph7qzPGcYTiHs34") }; Total (peer): 0.
`

Not sure what the solution is. Would also like to know how you solved this problem in case it might help.

**Comment by mxinden** [comment]
@zscott do you see the same thing happening with the gossipsub-chat example?

**Comment by zscott** [comment]
Have not tried that, but will. Is gossipsub preferred over floodsub?

**Comment by mxinden** [comment]
> Is gossipsub preferred over floodsub?

Yes. In case you find a place to better point that out, a pull request would be very much appreciated.
