### ISSUE TITLE
`gossipsub-chat` example is non-working.

### ISSUE THREAD

**Issue by Jerrody** [libp2p/rust-libp2p#2557]
When I try to launch an example and print a message I get this:
`
Publish error: InsufficientPeers
`

Where it happens:
```rs
                if let Err(e) = swarm
                    .behaviour_mut()
                    .publish(topic.clone(), line.expect("Stdin not to close").as_bytes())
                {
                    println!("Publish error: {:?}", e);
                }
```

**Comment by Jerrody** [comment]
Okay, it's my bad. I didn't understand what's wrong :D

**Comment by Strange21** [comment]
Hey, Can you throw some light on how you solved the problem. 
I am trying to communicate using the gossipsub-chat example, and I am able to successfully communicate within the personal Network.
But once I try to connect to the peer over the internet I get the same error message: 
```Publish error: InsufficientPeers```

I have done the port forwarding on my router, and trying to connect to 1st machine from 2nd machine over internet using 1st machines public IP address and Forwarded Port.

Is there something I am missing out?

**Comment by elenaf9** [comment]
@Strange21 Could you please change the following line so that all swarm events are printed, and share you debug output?
```diff
diff --git a/examples/gossipsub-chat.rs b/examples/gossipsub-chat.rs
index d6ea44dc..f314ebd8 100644
--- a/examples/gossipsub-chat.rs
+++ b/examples/gossipsub-chat.rs
@@ -153,7 +153,7 @@ async fn main() -> Result<(), Box<dyn Error>> {
                 SwarmEvent::NewListenAddr { address, .. } => {
                     println!("Listening on {:?}", address);
                 }
-                _ => {}
+                other => println!("Swarm event: {:?}", other),
             }
         }
     }
```
