### ISSUE TITLE
cargo audit failed

### ISSUE THREAD

**Issue by fishseabowl** [libp2p/rust-libp2p#2571]
version: cargo-audit 0.16.0

Details:

Crate:         prost-types
Version:       0.7.0
Title:         Conversion from `prost_types::Timestamp` to `SystemTime` can cause an overflow and panic
Date:          2021-07-08
ID:            RUSTSEC-2021-0073
URL:           https://rustsec.org/advisories/RUSTSEC-2021-0073
Solution:      Upgrade to >=0.8.0
Dependency tree: 
prost-types 0.7.0

Crate:         regex
Version:       1.5.4
Title:         Regexes with large repetitions on empty sub-expressions take a very long time to parse
Date:          2022-03-08
ID:            RUSTSEC-2022-0013
URL:           https://rustsec.org/advisories/RUSTSEC-2022-0013
Solution:      Upgrade to >=1.5.5
Dependency tree: 
regex 1.5.4
├── prost-build 0.9.0
├── libp2p-gossipsub 0.37.0
│   ├── libp2p-metrics 0.5.0
│   │   └── libp2p 0.44.0
│   │       ├── libp2p-swarm-derive 0.27.0
│   │       │   └── libp2p 0.44.0
│   │       ├── libp2p-swarm 0.35.0
│   │       │   ├── multistream-select 0.11.0
│   │       │   │   └── libp2p-core 0.32.1
│   │       │   │       ├── multistream-select 0.11.0
│   │       │   │       ├── libp2p-yamux 0.36.0
│   │       │   │       │   ├── libp2p-request-response 0.17.0
│   │       │   │       │   │   ├── libp2p-autonat 0.3.0
│   │       │   │       │   │   │   └── libp2p 0.44.0
│   │       │   │       │   │   └── libp2p 0.44.0
│   │       │   │       │   ├── libp2p-relay 0.8.0
│   │       │   │       │   │   ├── libp2p-metrics 0.5.0
│   │       │   │       │   │   ├── libp2p-dcutr 0.2.0
│   │       │   │       │   │   │   ├── libp2p-metrics 0.5.0
│   │       │   │       │   │   │   └── libp2p 0.44.0
│   │       │   │       │   │   └── libp2p 0.44.0
│   │       │   │       │   ├── libp2p-ping 0.35.0
│   │       │   │       │   │   ├── libp2p-relay 0.8.0
│   │       │   │       │   │   ├── libp2p-metrics 0.5.0
│   │       │   │       │   │   └── libp2p 0.44.0
│   │       │   │       │   ├── libp2p-kad 0.36.0
│   │       │   │       │   │   ├── libp2p-relay 0.8.0
│   │       │   │       │   │   ├── libp2p-metrics 0.5.0
│   │       │   │       │   │   └── libp2p 0.44.0
│   │       │   │       │   ├── libp2p-gossipsub 0.37.0
│   │       │   │       │   ├── libp2p-dcutr 0.2.0
│   │       │   │       │   └── libp2p 0.44.0
│   │       │   │       ├── libp2p-websocket 0.34.0
│   │       │   │       │   └── libp2p 0.44.0
│   │       │   │       ├── libp2p-wasm-ext 0.32.0
│   │       │   │       │   └── libp2p 0.44.0
│   │       │   │       ├── libp2p-uds 0.32.0
│   │       │   │       │   └── libp2p 0.44.0
│   │       │   │       ├── libp2p-tcp 0.32.0
│   │       │   │       │   ├── libp2p-websocket 0.34.0
│   │       │   │       │   ├── libp2p-swarm 0.35.0
│   │       │   │       │   ├── libp2p-request-response 0.17.0
│   │       │   │       │   ├── libp2p-ping 0.35.0
│   │       │   │       │   ├── libp2p-noise 0.35.0
│   │       │   │       │   │   ├── libp2p-swarm 0.35.0
│   │       │   │       │   │   ├── libp2p-request-response 0.17.0
│   │       │   │       │   │   ├── libp2p-ping 0.35.0
│   │       │   │       │   │   ├── libp2p-kad 0.36.0
│   │       │   │       │   │   ├── libp2p-identify 0.35.0
│   │       │   │       │   │   │   ├── libp2p-relay 0.8.0
│   │       │   │       │   │   │   ├── libp2p-metrics 0.5.0
│   │       │   │       │   │   │   ├── libp2p-dcutr 0.2.0
│   │       │   │       │   │   │   └── libp2p 0.44.0
│   │       │   │       │   │   ├── libp2p-gossipsub 0.37.0
│   │       │   │       │   │   ├── libp2p-core 0.32.1
│   │       │   │       │   │   └── libp2p 0.44.0
│   │       │   │       │   ├── libp2p-mplex 0.32.0
│   │       │   │       │   │   ├── multistream-select 0.11.0
│   │       │   │       │   │   ├── libp2p-swarm 0.35.0
│   │       │   │       │   │   ├── libp2p-ping 0.35.0
│   │       │   │       │   │   ├── libp2p-identify 0.35.0
│   │       │   │       │   │   ├── libp2p-gossipsub 0.37.0
│   │       │   │       │   │   ├── libp2p-core 0.32.1
│   │       │   │       │   │   └── libp2p 0.44.0
│   │       │   │       │   ├── libp2p-identify 0.35.0
│   │       │   │       │   ├── libp2p-deflate 0.32.0
│   │       │   │       │   │   └── libp2p 0.44.0
│   │       │   │       │   ├── libp2p-core 0.32.1
│   │       │   │       │   └── libp2p 0.44.0
│   │       │   │       ├── libp2p-swarm 0.35.0
│   │       │   │       ├── libp2p-request-response 0.17.0
│   │       │   │       ├── libp2p-rendezvous 0.5.0
│   │       │   │       │   └── libp2p 0.44.0
│   │       │   │       ├── libp2p-relay 0.8.0
│   │       │   │       ├── libp2p-plaintext 0.32.0
│   │       │   │       │   ├── multistream-select 0.11.0
│   │       │   │       │   ├── libp2p-relay 0.8.0
│   │       │   │       │   ├── libp2p-mplex 0.32.0
│   │       │   │       │   ├── libp2p-gossipsub 0.37.0
│   │       │   │       │   ├── libp2p-dcutr 0.2.0
│   │       │   │       │   └── libp2p 0.44.0
│   │       │   │       ├── libp2p-ping 0.35.0
│   │       │   │       ├── libp2p-noise 0.35.0
│   │       │   │       ├── libp2p-mplex 0.32.0
│   │       │   │       ├── libp2p-metrics 0.5.0
│   │       │   │       ├── libp2p-mdns 0.36.0
│   │       │   │       │   └── libp2p 0.44.0
│   │       │   │       ├── libp2p-kad 0.36.0
│   │       │   │       ├── libp2p-identify 0.35.0
│   │       │   │       ├── libp2p-gossipsub 0.37.0
│   │       │   │       ├── libp2p-floodsub 0.35.0
│   │       │   │       │   └── libp2p 0.44.0
│   │       │   │       ├── libp2p-dns 0.32.1
│   │       │   │       │   └── libp2p 0.44.0
│   │       │   │       ├── libp2p-deflate 0.32.0
│   │       │   │       ├── libp2p-dcutr 0.2.0
│   │       │   │       ├── libp2p-autonat 0.3.0
│   │       │   │       ├── libp2p 0.44.0
│   │       │   │       └── keygen 0.1.0
│   │       │   ├── libp2p-request-response 0.17.0
│   │       │   ├── libp2p-rendezvous 0.5.0
│   │       │   ├── libp2p-relay 0.8.0
│   │       │   ├── libp2p-ping 0.35.0
│   │       │   ├── libp2p-metrics 0.5.0
│   │       │   ├── libp2p-mdns 0.36.0
│   │       │   ├── libp2p-kad 0.36.0
│   │       │   ├── libp2p-identify 0.35.0
│   │       │   ├── libp2p-gossipsub 0.37.0
│   │       │   ├── libp2p-floodsub 0.35.0
│   │       │   ├── libp2p-dcutr 0.2.0
│   │       │   ├── libp2p-autonat 0.3.0
│   │       │   └── libp2p 0.44.0
│   │       ├── libp2p-rendezvous 0.5.0
│   │       ├── libp2p-relay 0.8.0
│   │       ├── libp2p-metrics 0.5.0
│   │       ├── libp2p-mdns 0.36.0
│   │       ├── libp2p-dcutr 0.2.0
│   │       └── libp2p-autonat 0.3.0
│   └── libp2p 0.44.0
├── env_logger 0.9.0
├── env_logger 0.8.4
├── env_logger 0.7.1
└── criterion 0.3.5
    ├── libp2p-mplex 0.32.0
    └── libp2p-core 0.32.1

**Comment by mxinden** [comment]
Thanks for raising this @fishseabowl.

I bumped the dependencies and added https://github.com/libp2p/rust-libp2p/pull/2430 which checks `cargo audit` on an automated schedule.

Let me know in case you still see any audit failures.

**Comment by mxinden** [comment]
Closing here. Feel free to comment for follow-ups.
