### ISSUE TITLE
protocols/ping: Reduce noise on logs

### ISSUE THREAD

**Issue by mxinden** [libp2p/rust-libp2p#2583]
Instead of printing the random ping payload, the log should print who we are sending a ping to and from whom we received a ping.

https://github.com/libp2p/rust-libp2p/blob/0c24821a144b10ba805e3648e05c5d44bbd59e42/protocols/ping/src/protocol.rs#L88

**Comment by leviathanbeak** [comment]
Hi @mxinden I could tackle this one, by "who we are sending a ping to" you mean remote's PeerId?, if that's correct from what I see we don't have the access to the peer_id in the protocol part.

Could we store it within the `ConnectionHandler { remote_id: PeerId , ..}`, and then pass it like this
```
fn inject_fully_negotiated_inbound(&mut self, stream: NegotiatedSubstream, (): ()) {
    self.inbound = Some(protocol::recv_ping(stream, self.remote_id).boxed());
}
```

Or is there another/better way?

**Comment by mxinden** [comment]
Appreciate the help @leviathanbeak.

Instead of passing the `PeerId` into the protocol, have you considered doing the logging within the handler instead? Just a thought.

**Comment by leviathanbeak** [comment]
Yes, that's also an option I considered but went along the current implementation of logging inside the protocol.

If I log it inside the handler, I'd still need access to remote's `PeerId`, does the handler have access to it already or should I pass it via behaviour, for example via `inject_connection_established(&mut self, peer_id...)` ?

**Comment by elenaf9** [comment]
> If I log it inside the handler, I'd still need access to remote's PeerId, does the handler have access to it already or should I pass it via behaviour,

You could use the `swarm::IntoConnectionHandler` trait, which would allow you to pass the remote's peer-id to the handler upon creation. 
Something similar is done e.g. in kademlia to pass the endpoint info to the handler: https://github.com/libp2p/rust-libp2p/blob/90140a6eafd8a500e654b14040941f9f5074474d/protocols/kad/src/handler.rs#L57-L62
You would need to change `<ping::Behaviour as NetworkBehaviour>::Handler` to a new type `HandlerProto`, and manually implement `IntoConnectionHandler` for `HandlerProto` to create the actual handler. 

Alternative you could log the events in `Behaviour::inject_event`.

Does this help?

**Comment by leviathanbeak** [comment]
thank you @elenaf9 for clarifying that part, that's what I wanted to know (regardless if we go that route).

Good point also on logging it in the behaviour itself, @mxinden if we're gonna move the logging out of the protocol, it could also be in the Behaviour as well right? Either way, whichever you choose I'm fine with it, let me know so that I can make a PR.

Logging in the Behaviour would be something like this:

```
fn poll(
        &mut self,
        _: &mut Context<'_>,
        _: &mut impl PollParameters,
    ) -> Poll<NetworkBehaviourAction<Self::OutEvent, Self::ConnectionHandler>> {
        if let Some(e) = self.events.pop_back() {
            let Event { result, peer } = &e;

            match result {
                Ok(Success::Ping { .. }) => log::debug!("Ping sent to {:?}", peer),
                Ok(Success::Pong) => log::debug!("Ping received from {:?}", peer),
                _ => {}
            }

            Poll::Ready(NetworkBehaviourAction::GenerateEvent(e))
        } else {
            Poll::Pending
        }
    }
```

**Comment by mxinden** [comment]
No preference on my end. I suggest we go for whatever is best readable from a code perspective.

**Comment by leviathanbeak** [comment]
well then the cleanest solution would be moving the logging to the Behaviour, I will make the PR soon
