### ISSUE TITLE
Insufficient peers after dialing 

### ISSUE THREAD

**Issue by shot-codes** [libp2p/rust-libp2p#2585]
Hey there, I am working on a project based on [the provided gossipsub example](https://github.com/libp2p/rust-libp2p/blob/master/examples/gossipsub-chat.rs) and I am seeing some behaviour that I don't quite understand. After dialing a specific address I am attempting to publish to a topic but I am told there are insufficient peers, I am still perfectly able to publish to a topic via text from the stdin as per the example however. I thought initially that introducing some time between dialing and publishing would resolve it, but regardless of asking the thread to sleep, it still is unable to publish. 

The repo can be found [here](https://github.com/libp2p/rust-libp2p/blob/master/examples/gossipsub-chat.rs) - there isn't much different from the example and the portion of the code of interest is [here](https://github.com/TheFoolishPupil/drone2drone/blob/2577e06821ee51dff990b3f64da58bf09743311a/src/main.rs#L108); to run it set the env variable ACTOR=Mothership and use cargo run, then in a separate window set the env variable to ACTOR=Minion, and you should see the behaviour I describe.

Any help with understanding what is going on would be greatly appreciated :)

**Comment by mxinden** [comment]
Is the publishing peer connected to one or more other peers? In other words is the dial successful? (You can see this setting `RUST_LOG=debug`.)

**Comment by shot-codes** [comment]
I'm setting the environment as you mention but can't seem to see any additional info. The dial must be successful though, as after the failed attempt I am able to publish from stdin; the code below describes what I am seeing.

```rust
    // This succeeds
    match swarm.dial(address.clone()) {
        Ok(_) => println!("Dialed {:?}", address),
        Err(e) => println!("Dial {:?} failed: {:?}", address, e),
    };

    // No peers are connected
    for peer in swarm.connected_peers() {
        println!("{:?}", peer);
    };
  
    // Fails with insufficient peers
    if let Err(e) = swarm
        .behaviour_mut()
        .publish(topic_mission.clone(), String::from("test").as_bytes())
    {
        println!("Publish error: {:?}", e);
    };

    let mut stdin = io::BufReader::new(io::stdin()).lines().fuse();

    loop {
        select! {

            // This publishes just fine
            _line = stdin.select_next_some() => {
                if let Err(e) = swarm
                    .behaviour_mut()
                    .publish(topic_mission.clone(), String::from("test").as_bytes())
                {
                    println!("Publish error: {:?}", e);
                };
            },
...
```

**Comment by shot-codes** [comment]
Any other tips? Perhaps I am not understanding how to run the code with RUST_LOG=debug, as it doesn't seem to provide me with any extra information when I set it as an env variable. I have also tried the following, which should ensure that the dial up is successful but I see the same behaviour:

```rust
let address: Multiaddr = "/ip4/192.168.1.61/tcp/60740".parse().unwrap();
    match swarm.dial(address.clone()) {
        Ok(_) => {
            println!("Dialed {:?}", address);
            if let Err(e) = swarm
                .behaviour_mut()
                .publish(topic.clone(), "THIS IS A TEST".as_bytes())
            {
                println!("Publish error: {:?}", e);
            };
        },
        Err(e) => println!("Dial {:?} failed: {:?}", address, e),
    };
```

**Comment by elenaf9** [comment]
I think the issue is that you are not polling the swarm after the dial, before publishing to the topic.

In general, the network does not make any progress unless you are polling the `Stream` implementation of the Swarm  (e.g. via `swarm.next().await` or `swarm.select_next_some().await`.
`swarm.dial(..)` only initiates the dial, but it does not mean that the remote is immediately connected. Only when you then poll  the swarm it it will try to establish a connection and either succeed of fail. And only once the connection succeeded the gossipsub protocol will add it to its list of connected peers, to whom messages can be sent.

So in order for this to work, you would have to do something like this:
```rust
let address: Multiaddr = "/ip4/192.168.1.61/tcp/60740".parse().unwrap();
    match swarm.dial(address.clone()) {
        Ok(_) => {
            println!("Dialed {:?}", address);

            // Poll the swarm until a connection was established or the dial failed.
            loop {
                  match swarm.select_next_some().await {
                      SwarmEvent::ConnectionEstablished {..} => break,
                      SwarmEvent::OutgoingConnectionError {..} => todo!() // connection failed
                      _ => {}
            }

            if let Err(e) = swarm
                .behaviour_mut()
                .publish(topic.clone(), "THIS IS A TEST".as_bytes())
            {
                println!("Publish error: {:?}", e);
            };
        },
        Err(e) => println!("Dial {:?} failed: {:?}", address, e),
    };
```

Does that solve the problem?

**Comment by shot-codes** [comment]
Thanks for the response @elenaf9! Unfortunately I am still unable to send for the same reasons, despite polling to establish the connection as you suggest. 

This does however explain why when I remove the polling of the swarm from my `select!` I am no longer to publish from the stdin stream.

What I am attempting to accomplish is essentially a script that sends a single message on a topic and exits, and so I have a workaround where publish from within the stdin poll but this means that I have to hit the enter key in the terminal window to initiate the send. Additionally it makes my script confusing to understand as it is doing a whole bunch of unnecessary things. So if you have any other ideas I would love to hear them :)

**Comment by elenaf9** [comment]
Could you please share again a link to the repo / file with the code? The above link does not work, perhaps the repo is private?

**Comment by shot-codes** [comment]
Sorry it has since moved to another repo: https://github.com/TheFoolishPupil/libd2d, you can start with running `cargo run --bin mothership` and then separately `cargo run --bin launch_mission`. The area of interest is beyond line 65 in bin/launch_mission.rs. You should see that publishing fails until you focus the window running the launch_mission binary and hit the enter key. :)

**Comment by elenaf9** [comment]
Ok so actually it's also not enough to just wait for the connection establishment. I did not consider that once the connection is established, the two peers also need to communicate to each other what topic they are subscribed to (this happens automatically). So you need to poll the swarm even after the connection was established until you received an event: `SwarmEvent::Behaviour(GossipsubEvent::Subscribed {topic: t, ..}) if t == topic.hash()`. 
This event indicates you that the remote has informed your gossip behaviour of an topic that it subscribes to. And after you received this event it should finally work.

**Comment by rkuhn** [comment]
As far as I can see there are no guarantees about “things will work” in the absence of continual polling — I think the approach of “pull until X” is fundamentally flawed since none of the behaviours were coded with this usage mode in mind. The swarm is an active entity that needs to run its own errands in order to function properly.

**Comment by elenaf9** [comment]
Good point @rkuhn, my phrasing was probably a bit misleading. Indeed you should always continuously poll the swarm as long as you want the network to make any progress, and not just stop after a specific event happened. 
That being said, you still sometimes need to "poll until X", if you want to trigger an action that depends on X. Otherwise there is no way of knowing the state of the swarm. But of course you still have to continue polling afterwards, e.g. in the above case so that the message is actually published.

**Comment by rkuhn** [comment]
Right. I’d phrase this as “have a task polling the swarm unconditionally and send the events to interested parties that can then react to the aspects they’re interested in” :-) This is why I’m toying with a more actor-like shell for the swarm, as I don’t think the big state machine approach suits all needs. But my progress unfortunately is very slow right now due to other things interfering.

**Comment by shot-codes** [comment]
Okay I think I have a better understanding now; The swarm must be continuously polled in order to make progress. I can then catch a specific event that I need (as you point out @elenaf9, in my case it is `GossipsubEvent::Subscribed`) after which I can use the swarm as I please (publishing my message). So the entire idea of a "procedural script" that simply makes the connection and blindly publishes to a topic is fundamentally flawed it seems. Thats fine, with my current understanding I am able to avoid using stdin by simply polling for the subscribed event as such:
```rust
loop {
    select! {
          event = swarm.select_next_some() => match event {
                SwarmEvent::Behaviour(GossipsubEvent::Subscribed {
                    topic: t, 
                    ..
                })  if t == topic.hash() => {
                       // Publish my message
                }
          }
    }
}
```
Thanks so much for the help guys. It certainly seems like I am missing some understanding of asynchronous rust in general, but your thorough assistance is helping me get there! cheers

**Comment by shot-codes** [comment]
Hey I actually had a question that is sort of related to this. I am trying to implement my own heartbeat so to speak; I would like to, every N seconds send out some data to all peers on a specific topic. My current approach now is to create a stream that when polled checks the contents of a vector. This vector is periodically adding an element every N seconds in another thread. the idea is that every N seconds there will be a value in the vector, triggering the stream to return Poll:Ready(Some(X)) at which point I can 'catch' this event in my select! and then emit my custom heartbeat.

Is there a more appropriate way to achieve this? I can see that there is a heartbeat as part of the libp2p implementation but I couldn't find out from the docs if it is possible to customize the data being passed there.
