### ISSUE TITLE
Sending duplicate messages (Gossipsub)

### ISSUE THREAD

**Issue by shot-codes** [libp2p/rust-libp2p#2587]
I am using content-address messages but am expecting to send and receive duplicates. I have attempted to set the duplicate_cache_time on the GossipsubConfigBuilder as follows
```rust
let gossipsub_config = gossipsub::GossipsubConfigBuilder::default()
            .heartbeat_interval(Duration::from_secs(10)) // This is set to aid debugging by not cluttering the log space
            .validation_mode(ValidationMode::Strict) // This sets the kind of message validation. The default is Strict (enforce message signing)
            .message_id_fn(message_id_fn) // content-address messages. No two messages of the same content will be propagated.
            .duplicate_cache_time(Duration::from_secs(1))
            .build()
            .expect("Valid config");
```
However I am never able to send duplicate messages, nor after the 1 minute default. Am I somehow setting the duplicate cache timer incorrectly? I am also open to a solution that involves a different message_id_fn that ensures all messages have a unique id. Thanks!

**Comment by mxinden** [comment]
Can you expand on why you are sending duplicate messages in the first place? Would it not make sense to include a version number in those messages in order for a remote to detect that this is not the first iteration in which this message was sent?

**Comment by shot-codes** [comment]
I am implementing a protocol where many of the same messages are expected to e be sent/received. That being said, I suppose adding a version number does no harm and addresses my issue. Thanks
