### ISSUE TITLE
calrification on `failed to dial the requested peer` request-response error

### ISSUE THREAD

**Issue by StefanoSetti** [libp2p/rust-libp2p#2588]
I'm using **lib-p2p** version: `0.43.0`, as layers i use:

- kad
- mdsn
- gossip
- identify
- request-response

during communication between peers some times a peer while sending a request response message it launches the following error:

`failed to dial the requested peer` 

even if the printed peer is up and alive. What can go wrong?

**Comment by mxinden** [comment]
I would need more info to debug the issue. Can you post a log output (`RUST_LOG=debug`) of two nodes failing to connect?

**Comment by StefanoSetti** [comment]
To be clear about the fixed problem:

the local peer didn't know the address of the requested peer. I just had to add the address to the peer and everything was smooth.
