### ISSUE TITLE
Behavior Upgrade similar to Connection Upgrade performed via DCUtR

### ISSUE THREAD

**Issue by canewsin** [libp2p/rust-libp2p#2593]
Is Behavior Upgrade Possible After Peer Connection is Established ?

With Current code logic swarm depends predefined network behavior before peer connection, Some times different clients have different feature sets based on their hardware capabilities, EitherBehavior might not work in all such cases, instead I would like to see Behavior Upgrade Possibility after similar to Connection Upgrade, even though they are not similar, I am just curious whether It could be possible with current code base.

This is because, I feel increase in Behavior Payload may lead to unsuccessful hole punch attempts, even though devices capable of doing such things with Light Behavior.

This could also help cross device/version communicational behavior upgrades i.e. bluetooth may not be supported by all clients.

May be Related : https://github.com/libp2p/rust-libp2p/issues/2590

**Comment by mxinden** [comment]
> This is because, I feel increase in Behavior Payload may lead to unsuccessful hole punch attempts, even though devices capable of doing such things with Light Behavior.

I think we should solve this issue directly, instead of providing an "upgrade" mechanism for `NetworkBehaviour`s.

**Comment by thomaseizinger** [comment]
Closing as stale.
