### ISSUE TITLE
Implement Error trait for GetRecordError (Kad)

### ISSUE THREAD

**Issue by Janmajayamall** [libp2p/rust-libp2p#2612]
I am not sure why Error trait hasn't been implemented for GetRecordError ([ref](https://github.com/libp2p/rust-libp2p/blob/a1f3547b43bfac17ef50248e4a8ce1523d3aaa76/protocols/kad/src/behaviour.rs#L2558)).

**Comment by elenaf9** [comment]
Error was implemented for all other kademlia error types in #2414, I would guess it was an oversight. Would you mind doing a PR for this?

**Comment by thomaseizinger** [comment]
Let me know if this is still an issue.
