### ISSUE TITLE
*: Consider using semverver

### ISSUE THREAD

**Issue by mxinden** [libp2p/rust-libp2p#2635]
## Description

Consider using https://github.com/rust-lang/rust-semverver to enforce semantic versioning. Instructions on how to integrate semverver in CI can be found on https://github.com/rust-lang/rust-semverver#ci-setup.

## Motivation

Complying with Semver makes it easier for users to consume rust-libp2p. Having an automated compliance check makes maintaining rust-libp2p easier.

## Are you planning to do it yourself in a pull request?

Help wanted!

**Comment by maschad** [comment]
> ## Description
> Consider using [rust-lang/rust-semverver](https://github.com/rust-lang/rust-semverver) to enforce semantic versioning. Instructions on how to integrate semverver in CI can be found on [rust-lang/rust-semverver#ci-setup](https://github.com/rust-lang/rust-semverver#ci-setup).
> 
> ## Motivation
> Complying with Semver makes it easier for users to consume rust-libp2p. Having an automated compliance check makes maintaining rust-libp2p easier.
> 
> ## Are you planning to do it yourself in a pull request?
> Help wanted!

Hey @mxinden  I am giving this a shot. Please see this [PR](https://github.com/libp2p/rust-libp2p/pull/2647)

**Comment by maschad** [comment]
Hey @mxinden I am giving this a shot. Please see this [PR](https://github.com/libp2p/rust-libp2p/pull/2647)

**Comment by maschad** [comment]
Our current version bump results in a build failure see https://github.com/libp2p/rust-libp2p/pull/2647#issuecomment-1135208285

**Comment by mxinden** [comment]
Instead of `semverver`, we could consider using https://crates.io/crates/cargo-semver-checks.

**Comment by maschad** [comment]
Thanks for reviving this @mxinden - I had lost track of it because of work,  I agree, particularly because semverver is tightly coupled to specific nightly compiler versions and [takes work to stay in sync](https://github.com/rust-lang/rust-semverver/search?q=Rustup+to&type=commits). I will give it a try on the PR.

**Comment by mxinden** [comment]
With https://github.com/libp2p/rust-libp2p/pull/2647 I am closing here.
