### ISSUE TITLE
swarm-derive/: Replace mentions of ProtocolsHandler with ConnectionHandler

### ISSUE THREAD

**Issue by mxinden** [libp2p/rust-libp2p#2637]
`ProtocolsHandler` has been renamed to `ConnectionHandler`, see https://github.com/libp2p/rust-libp2p/pull/2527. Unfortunately I missed to patch `swarm-derive`, for example the line below.

https://github.com/libp2p/rust-libp2p/blob/5cf68902ced96175165699c115f160f3361422a7/swarm-derive/src/lib.rs#L54

**Comment by maschad** [comment]
> `ProtocolsHandler` has been renamed to `ConnectionHandler`, see #2527. Unfortunately I missed to patch `swarm-derive`, for example the line below.
> 
> https://github.com/libp2p/rust-libp2p/blob/5cf68902ced96175165699c115f160f3361422a7/swarm-derive/src/lib.rs#L54

Hey @mxinden this seems straightforward enough, I created a [PR](https://github.com/libp2p/rust-libp2p/pull/2640). Lmk what you think.
