### ISSUE TITLE
Tcp transport port_reuse_dialing test missing some assert

### ISSUE THREAD

**Issue by stormshield-pj50** [libp2p/rust-libp2p#2651]
## Summary
The port_reuse_dialing test in transports/tcp/lib.rs seems to be incomplete, it does not check for port reuse.

## Expected behaviour
In this test the dialer outgoing connection must reuse the listener port. So an assert like this should be added near line 930 in the port_reuse_dialing/dialer function:
```
assert!(tcp.port_reuse.local_dial_addr(&listener.listen_addr.ip()).is_some());
```

## Actual behaviour
The assert is missing and if I add it it fails. It seems to be a consequence of the commit https://github.com/libp2p/rust-libp2p/commit/2ad905f35a61d7588f74aeea4e8010ccfbc70fcf. Previously the listen_addrs field in PortReuse was a Arc<RwLock<HashSet<(IpAddr, Port)>>> so it could be shared between GenTcpConfig and TcpListenStream. One ugly work around to make the assert pass in the test is to clone listener.port_reuse into tcp:
```
tcp.port_reuse = listener.port_reuse.clone(); 
```

## Possible Solution
Don't know if only the test is broken or if libp2p port reuse feature is also broken.

## Would you like to work on fixing this bug?
Yes

**Comment by mxinden** [comment]
Thanks for the bug report @pj50. Great job catching this! This was my mistake.

For others following along here is where the `HashMap` instead of the  `Arc` is being cloned.

https://github.com/libp2p/rust-libp2p/blob/d21cd5fed76d879b02c4f78ea00e02737498b8ca/transports/tcp/src/lib.rs#L327

> Would you like to work on fixing this bug?
> 
> Yes

Great! Let me know in case you need any help.

**Comment by mxinden** [comment]
Friendly ping @pj50. Still interested in providing a patch?

**Comment by stormshield-pj50** [comment]
Sorry being late for a patch, I had to work on other topics last week. Working on it now.

**Comment by mxinden** [comment]
Closing here with https://github.com/libp2p/rust-libp2p/pull/2670 merged.
