### ISSUE TITLE
mDNS: LabelIsNotAscii

### ISSUE THREAD

**Issue by thearossman** [libp2p/rust-libp2p#2676]
## Summary

mDNS discovery sometimes fails with "parsing MDNS packet failed" message; may be an old `mdns_parser` issue in general? 

## Expected behaviour

I'd *assume* that all mDNS packets sent/received should be correctly parsed? And that I shouldn't see this error message? 

## Actual behaviour

mDNS sometimes works, and sometimes prints the debug message: `DEBUG libp2p_mdns::behaviour::iface::query] Parsing mdns packet failed: LabelIsNotAscii`. 

After a threshold of errors, mDNS seems to begin behaving inconsistently -- e.g., expiring peers and erroneously disconnecting. (So, for example, if I'm using mDNS to do peer discovery for a GossipSub network, the network will eventually fail w/ insufficient peers or uptime will suffer.)

This first showed up on a separate project, but I was able to observe the same behavior running the `chat-tokio` example, which uses mDNS. I've reproduced this on multiple libp2p versions, including the most recent (0.44.0) and older (e.g., 0.39.1).

```
[2022-05-28T01:49:34Z DEBUG libp2p_mdns::behaviour::iface::query] Parsing mdns packet failed: LabelIsNotAscii
[2022-05-28T01:49:35Z DEBUG libp2p_mdns::behaviour::iface::query] Parsing mdns packet failed: LabelIsNotAscii
[2022-05-28T01:49:36Z DEBUG libp2p_mdns::behaviour::iface::query] Parsing mdns packet failed: LabelIsNotAscii
```

## Possible Solution

This is an error from dns_parser [here](https://github.com/tailhook/dns-parser/blob/191266705b30feabe9fbf9289b4cb4da0ea2be31/src/error.rs). Seems like others have encountered it [before](https://github.com/dylanmckay/mdns/issues/13).

I've been working around with a high TTL and query interval. 

## Version
0.44.0, 0.39.1 (I've been able to reproduce this on multiple versions)

**Comment by mxinden** [comment]
Do these mdns packets come from libp2p hosts? If no, this should not affect `libp2p-mdns`.

**Comment by thearossman** [comment]
I believe they come from libp2p hosts -- we're not using anything else, and we were able to get the same error just by running the chat-tokio example with nothing else (https://github.com/libp2p/rust-libp2p/blob/master/examples/chat-tokio.rs).

**Comment by mxinden** [comment]
@thearossman can you use wireshark to post a dump of the original packet here?

**Comment by mxinden** [comment]
Friendly ping @thearossman.

**Comment by thearossman** [comment]
Thanks so much for the ping; apologies for dropping this. 

This is from running the `chat-tokio` example with two hosts, running for about 30 seconds. You can see the MDNS error message; in this case, the hosts didn't disconnect from each other. 

Partial log from one of the hosts (you can see the mdns error message): [debuglog-libp2p-mdns.txt](https://github.com/libp2p/rust-libp2p/files/9795953/debuglog-libp2p-mdns.txt)

Here's a pcap -- can't upload to Github; so it's on Google Drive [here](https://drive.google.com/file/d/1DKASUCpFuFtHLd4lLvY3ojQP3rcwcUk3/view?usp=sharing)
