### ISSUE TITLE
swarm/: Set dial concurrency factor default value to > 1

### ISSUE THREAD

**Issue by mxinden** [libp2p/rust-libp2p#2678]
## Description

I propose increasing the default dial concurrency factor to some value larger than 1.

You can use https://kademlia-exporter.max-inden.de/d/Pfr0Fj6Mk/rust-libp2p (bottom) to determine how many addresses nodes advertise for the various libp2p networks.

Also worth checking what go-libp2p uses as a default value.

## Motivation

Dialing addresses of a single dial concurrently gives a significant improvement in latency.

Feature was introduced in https://github.com/libp2p/rust-libp2p/pull/2404.

Default value is set here:

https://github.com/libp2p/rust-libp2p/blob/8361fabb479650f736f71ba8f253ed49f38ee4ff/swarm/src/connection/pool.rs#L1164-L1165

//CC @dignifiedquire who has recently stumbled across this.

**Comment by maschad** [comment]
For some reason I am getting a `502` on the Grafana dashboard 
<img width="547" alt="image" src="https://user-images.githubusercontent.com/9755286/176086179-86ca2f0b-cb43-4b38-bf73-5bca64c7941a.png">

But it seems that [go-libp2p uses a dial concurrency factor of 8](https://github.com/libp2p/go-libp2p/blob/master/p2p/net/swarm/swarm_dial.go#L68) if I'm not mistaken, it could be one of the other constants though as the terms are a bit convoluting.

**Comment by mxinden** [comment]
Sorry, kademlia-exporter.max-inden.de has some uptime issues currently. Posting a screenshot here for now:

![image](https://user-images.githubusercontent.com/7047859/176365365-b6d40b50-43c4-46c0-a312-dac657f4bac8.png)



> But it seems that [go-libp2p uses a dial concurrency factor of 8](https://github.com/libp2p/go-libp2p/blob/master/p2p/net/swarm/swarm_dial.go#L68) if I'm not mistaken, it could be one of the other constants though as the terms are a bit convoluting.

Seems to be right :+1:

**Comment by maschad** [comment]
Kademlia seems to be back up now, I created a PR https://github.com/libp2p/rust-libp2p/pull/2741

**Comment by mxinden** [comment]
Closing here with https://github.com/libp2p/rust-libp2p/pull/2741 merged.
