### ISSUE TITLE
Introduce a 32-bytes key type without additional hashing to Kademlia DHT

### ISSUE THREAD

**Issue by shamil-gadelshin** [libp2p/rust-libp2p#2690]
## Description

We need to use DHT to find closest peers with exact PeerId to the exact key value in our network. Currently, both rust and canonical golang implementations seem to hash both PeerId and all the provided keys regardless of the initial format (using SHA256 hasher) to get 32-bytes hash before computing the XOR-distance. But what if we pre-hash our data and provide the 32-bytes as PeerId and 32-bytes key value as they are? Is it possible to have an additional way to create keys to calculate the XOR-distance without the additional hashing? 

In our use case we attach semantics to both PeerId and look-up keys (related to local data ranges), but the second hashing destroys that. Currently, I use unsafe memory operations to bypass such a limitation but there should be a better way. Also, I don't see any limitations to this change in the original Kademlia paper. 

Please, advise - is it possible to add exact keys(without the second hashing) to kademlia operations?

## Motivation

This change will enable use-cases that depend on unmodified peer IDs or look-up keys.

## Current Implementation

The current implementation hashes the provided keys even if the underlying data is 32-bytes array.

## Are you planning to do it yourself in a pull request?

If the proposed enhancement looks reasonable we could implement it.

**Comment by mxinden** [comment]
> In our use case we attach semantics to both PeerId and look-up keys 

Would the key space still be uniform? Do note that you are sacrificing security in favor of this functionality.

What are these semantics?


> If the proposed enhancement looks reasonable we could implement it.

Given that this is not specific to rust-libp2p, I think this discussion should be moved to https://github.com/libp2p/specs/.

**Comment by shamil-gadelshin** [comment]
> What are these semantics?

We're building the distributed storage network with nodes saving the data chunks within their responsibility range. This range could be derived from the node's PeerId. Kademlia and it's XOR-metrics works well here. The issue comes when we look for the node responsible for some range. When we try to find a node by some parameter (let's say a middle of the range - also 32-bytes) we expect to compare (calculate XOR-distance) our unmodified 32-bytes PeerId with unmodified 32-bytes key (middle of the range) which is not possible at the moment because of the existing unavoidable key hashing. So, answering to your original question - we attach a notion of ranges to the keys.

> Would the key space still be uniform? Do note that you are sacrificing security in favor of this functionality.

Could you be more specific on a security issue? We plan to use Sr25519 public key which is 32 bytes as the PeerId and the same SHA-256 hash (also 32 bytes) as the look-up key. The key space looks the same.

> Given that this is not specific to rust-libp2p, I think this discussion should be moved to https://github.com/libp2p/specs/.

It could be a rust implementation detail similar to the golang version of the `Key` structure with the `KeySpace` concept that is missing in the rust implementation but Ok - I could move it if you consider the `specs` repo would be a better place for this issue.

**Comment by nazar-pc** [comment]
> Would the key space still be uniform? Do note that you are sacrificing security in favor of this functionality.

Keys we have on the network are implicitly mapped to PeerId. But because PeerId is just a pre-image for the actual contents of k-buckets in libp2p, we can no longer look up nodes close to pre-image, which is a problem for us.

It isn't any less secure than hashing. Just like user can grind on public keys to get tehm in the specific location of the key space, they can grind on public key hashes.

**Comment by shamil-gadelshin** [comment]
Moved to [libp2p/specs](https://github.com/libp2p/specs/issues/421) as requested by @mxinden.
