### ISSUE TITLE
Override protocol id prefix on GossipsubConfigBuilder

### ISSUE THREAD

**Issue by bernardoaraujor** [libp2p/rust-libp2p#2709]
## Description

I need to be able to set the entire `GossipSub`'s `ProtocolId`, not only the prefix.

## Motivation

I'm working on a Rust implementation of [Waku](https://rfc.vac.dev/spec/10/), an evolution of Ethereum Whisper: https://github.com/bernardoaraujor/waku-rs

At this point, I have a minimal working implementation of [11/WAKU2-RELAY](https://rfc.vac.dev/spec/11/), [13/WAKU2-STORE](https://rfc.vac.dev/spec/13/) and [19/WAKU2-LIGHTPUSH](https://rfc.vac.dev/spec/19/).

When trying to connect it to the [Nim reference implementation](https://github.com/status-im/nwaku) without success, I noticed the following messages on the Nim logs:
```
DBG 2022-06-15 18:23:17.558-03:00 no handlers                                topics="libp2p multistream" tid=77736 file=multistream.nim:173 conn=12D*PH8vPd:62aa4dc5649138700bc0af39 protocol=//vac/waku/relay/2.0.0/1.1.0
DBG 2022-06-15 18:23:17.558-03:00 Could not establish send connection        topics="libp2p pubsubpeer" tid=77736 file=pubsubpeer.nim:205 msg="Unable to select sub-protocol @[\"/vac/waku/relay/2.0.0\", \"/vac/waku/relay/2.0.0\"]
```

where `protocol=//vac/waku/relay/2.0.0/1.1.0` is clearly not what I intended with [`RELAY_PROTOCOL_ID`](https://github.com/bernardoaraujor/waku-rs/blob/1176db196b720545ebb3e3150142b38c10e8dad8/waku-protocol/src/waku_relay/network_behaviour.rs#L16).

It turns out that's a result of [`GossipsubConfigBuilder::default().protocol_id_prefix(RELAY_PROTOCOL_ID)`](https://github.com/bernardoaraujor/waku-rs/blob/1176db196b720545ebb3e3150142b38c10e8dad8/waku-protocol/src/waku_relay/network_behaviour.rs#L44), which [uses `RELAY_PROTOCOL_ID` as a mere prefix](https://docs.rs/libp2p-gossipsub/latest/src/libp2p_gossipsub/protocol.rs.html#97) for `ProtocolId`, adding extra `/` and `/1.1.0`.

## Requirements

A way to set `ProtocolId` on `GossipSub` without prefix logic.

## Open questions

- What is the feasibility of this feature? 
- Are there any reasons **not** to have this feature on `GossipSub`?

## Are you planning to do it yourself in a pull request?

Maybe. I would probably need some guidance.

**Comment by mxinden** [comment]
Hi @bernardoaraujor,

Thanks for the detailed feature request.

> Are there any reasons **not** to have this feature on `GossipSub`?

I don't see a reason why not to support your use-case.

> It turns out that's a result of [`GossipsubConfigBuilder::default().protocol_id_prefix(RELAY_PROTOCOL_ID)`](https://github.com/bernardoaraujor/waku-rs/blob/1176db196b720545ebb3e3150142b38c10e8dad8/waku-protocol/src/waku_relay/network_behaviour.rs#L44), which [uses `RELAY_PROTOCOL_ID` as a mere prefix](https://docs.rs/libp2p-gossipsub/latest/src/libp2p_gossipsub/protocol.rs.html#97) for `ProtocolId`, adding extra `/` and `/1.1.0`.

How about adding an additional method e.g. `GossipsubConfigBuilder::protocol_id` to be able to set the whole id?

> Maybe. I would probably need some guidance.

Great. I am happy to help.

**Comment by mxinden** [comment]
Closing here with https://github.com/libp2p/rust-libp2p/pull/2718 merged.
