### ISSUE TITLE
lib2p-uds didn't get bumped in libp2p 0.45

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#2715]
The current version of `libp2p` published on crates.io is 0.45.1.

`libp2p` 0.45.1 depends (amongst others) on `libp2p-uds` v0.32.0 and on `libp2p-core` v0.33.0
`libp2p-uds` v0.32.0, however, depends on `libp2p-core` v0.32.0

This means that if you depend on `libp2p` and enable the `uds` feature (it's enabled by default), you will have `libp2p-core` twice in your dependencies graph.

I haven't tested this, but it seems that it also renders `libp2p-uds` unusable, as the traits of `libp2p-core` v0.32 and v0.33 are considered as not the same by the compiler.

**Comment by kpp** [comment]
That's strange because libp2p-core was bumped in uds in 2ad905f35a61d

**Comment by mxinden** [comment]
> `libp2p` 0.45.1 depends (amongst others) on `libp2p-uds` v0.32.0 and on `libp2p-core` v0.33.0
> `libp2p-uds` v0.32.0, however, depends on `libp2p-core` v0.32.0

Thanks. My bad. You are right. Will cut a new release of `libp2p-uds` and a patch release of `libp2p`.

_As an aside, is anyone using `libp2p-uds`?_

**Comment by mxinden** [comment]
> That's strange because libp2p-core was bumped in uds in [2ad905f](https://github.com/libp2p/rust-libp2p/commit/2ad905f35a61d7588f74aeea4e8010ccfbc70fcf)

Yes, but I forgot to bump the `libp2p-uds` version itself and thus didn't cut a new `libp2p-uds` release.

**Comment by kpp** [comment]
Can you publish 0.45.2 after resolving this issue?

**Comment by mxinden** [comment]
@kpp I am targeting `libp2p` `v0.46.0` with https://github.com/libp2p/rust-libp2p/pull/2720/, is that good enough for you?

Out of curiosity, where in your stack are you using `libp2p-uds`?

**Comment by kpp** [comment]
> is that good enough for you?

Yes

> where in your stack are you using libp2p-uds

We don't use it. It's a default feature.

**Comment by thomaseizinger** [comment]
> > where in your stack are you using libp2p-uds
> 
> We don't use it. It's a default feature.

Related: https://github.com/libp2p/rust-libp2p/issues/2173
