### ISSUE TITLE
swarm/src/behaviour: Add `AndBehaviour`

### ISSUE THREAD

**Issue by mxinden** [libp2p/rust-libp2p#2719]
## Description

To combine two `NetworkBehaviour` implementations `libp2p-swarm` should provide a combinator. Contrary to [`NetworkBehaviour` implementation of `Either`](https://github.com/libp2p/rust-libp2p/blob/master/swarm/src/behaviour/either.rs) both `NetworkBehaviour` implementations would be running concurrently.

## Motivation

One use-case is when wanting to either enable two `NetworkBehaviour`s or disable both, but never enable one but disable the other.

`Toggle<And<BehaviourA, BehaviourB>>`

Came up here: https://github.com/n0-computer/iroh/pull/126#discussion_r901236064

## Open questions

- What is the ideal name? Off the top of my head it should be `And`.

## Are you planning to do it yourself in a pull request?

No. Though happy to support anyone interested in contributing this.

**Comment by GlenDC** [comment]
Is it ok for me @mxinden to pick up this one, or do you have another one in mind that you want me to look at?

**Comment by mxinden** [comment]
Please prioritize any WebRTC and Testground related work. That said, yes, help here is very much appreciated whenever you are blocked on WebRTC and Testground. Let us know in case you need any help @GlenDC.

**Comment by GlenDC** [comment]
Understood. I am going to continue to give all my love and energy in the Protocol Labs context to Testground. Let's do it!

**Comment by thomaseizinger** [comment]
I think we agreed to not do this in #3366.
