### ISSUE TITLE
Remove flush_all from docs

### ISSUE THREAD

**Issue by kpp** [libp2p/rust-libp2p#2721]
https://github.com/libp2p/rust-libp2p/blob/cb3784a8b307bf1da9cc0956f2ed60081dad2ac7/core/src/muxing.rs#L68

Because the method was removed in https://github.com/libp2p/rust-libp2p/pull/2669

cc @thomaseizinger

**Comment by thomaseizinger** [comment]
Thanks! That was indeed an oversight.

The docs will re-worked here: https://github.com/libp2p/rust-libp2p/pull/2707/files#diff-1d8f8fba36155ce3fd2849bc74180b4aa5399051838235c3dcbd5b99b8ed908eR64-R71

I'll attach this issue as being fixed with #2707.
