### ISSUE TITLE
Add a spam filtering for request-response protocol.

### ISSUE THREAD

**Issue by shamil-gadelshin** [libp2p/rust-libp2p#2735]
## Description

Rust libp2p stack implementation contains `request-response` protocol but it lacks a spam protection mechanism. It seems like a problem and some projects created workarounds for this issue, for example: Parity Substrate framework contains a peer reputation system for this protocol which they use to provide a spam protection for their nodes.

## Motivation

Spam seems like a valid threat in p2p protocols. Gossipsub was upgraded to v1.1 partially to counter such threats. S/Kademlia introduced some features to prevent it.

## Current Implementation

The currrent implementation doesn't contain a spam protection mechanism.

## Are you planning to do it yourself in a pull request?

Maybe in the future.

**Comment by drHuangMHT** [comment]
I don't think `request-response` is part of libp2p spec or anything official. What do you think? ping @thomaseizinger

**Comment by thomaseizinger** [comment]
> I don't think `request-response` is part of libp2p spec or anything official. What do you think? ping @thomaseizinger

Correct. `libp2p-request-response` is merely a tool to help people in building protocols without much boilerplate. Due to its generic nature, we don't know anything about the protocol so I think we also cannot implement any form of spam filtering.

I'll close here for now.
