### ISSUE TITLE
swarm/: Expose time to establish connection

### ISSUE THREAD

**Issue by mxinden** [libp2p/rust-libp2p#2745]
## Description

Expose the time it takes to establish an inbound or outbound connection.

## Motivation

Needed for monitoring purposes, e.g. to be exposed to Prometheus via `libp2p-metrics`. Especially relevant now that we are adding two more transport protocols and thus might want to compare them. #2622 #2289 

## Open questions

- Likely best tracked in `Pool`, thus not requiring `Transport` to be aware of it.

## Are you planning to do it yourself in a pull request?

Likely not.

**Comment by GlenDC** [comment]
I'm planning to pick this one up @mxinden , is that ok, or do you have something else in mind for me?

**Comment by mxinden** [comment]
Please prioritize any WebRTC and Testground related work. That said, yes, help here is very much appreciated whenever you are blocked on WebRTC and Testground. Let us know in case you need any help @GlenDC.

**Comment by GlenDC** [comment]
Understood. I am going to continue to give all my love and energy in the Protocol Labs context to Testground. Let's do it!

**Comment by John-LittleBearLabs** [comment]
I'm considering implementing this as a [Histogram](https://docs.rs/prometheus-client/0.18.0/prometheus_client/metrics/histogram/struct.Histogram.html), but if so I'll need to come up with buckets - basically I'll need to know the resolution we're interested in.

Since we're talking about networking, I'm guessing somewhere on the order of magnitude of ms or perhaps 10s of ms?

**Comment by mxinden** [comment]
> Since we're talking about networking, I'm guessing somewhere on the order of magnitude of ms or perhaps 10s of ms?

We can experiment with this over time. I suggest using [`exponential_buckets`](https://docs.rs/prometheus-client/0.18.1/prometheus_client/metrics/histogram/fn.exponential_buckets.html). Something along the lines of:

``` rust
exponential_buckets(0.001 /* 1ms*/, 2, 16)
```

**Comment by thomaseizinger** [comment]
Thinking out loud: If we had a callback on behaviours for pending connections, this could be tracked in a behaviour with tracking the time inside `Swarm`.

**Comment by thomaseizinger** [comment]
The latest proposal of https://github.com/libp2p/rust-libp2p/pull/3099 would allow this to be implemented as a `NetworkBehaviour`.

**Comment by thomaseizinger** [comment]
Done in https://github.com/libp2p/rust-libp2p/pull/3134.
