### ISSUE TITLE
0.46.1 on crates.io but not github releases

### ISSUE THREAD

**Issue by DieracDelta** [libp2p/rust-libp2p#2750]
## Summary

It looks like version 0.46.1 is on [crates.io](https://crates.io/crates/libp2p), but not included in [github's releases](https://github.com/libp2p/rust-libp2p/releases). Any chance it could be added to the releases?

## Expected behaviour

0.46.1 listed on github's release page.

## Actual behaviour

0.46.0 is the latest listed release.

**Comment by mxinden** [comment]
:+1: Thanks for the ping @DieracDelta.  Included now:  https://github.com/libp2p/rust-libp2p/releases/tag/v0.46.1
