### ISSUE TITLE
Gossipsub permissive ignores anonymous messages 

### ISSUE THREAD

**Issue by mriise** [libp2p/rust-libp2p#2755]
## Summary

Gossipsub silently rejects future messages from anonymous messages senders after the first message while using permissive validation 

## Expected behaviour

emit event on message or peer rejection when validation mode is permissive

## Actual behaviour

Silently ignores messages from anonymous senders

<details><summary>Debug Output</summary>
<p>

```
<output>
```
</p>
</details>

## Possible Solution
Push event message information as to why future messages are ignored 

## Version

- libp2p version (version number, commit, or branch): master

## Would you like to work on fixing this bug?

Maybe

**Comment by mriise** [comment]
There is more context and research to be done on my side to track down where/why it happens, so feel free to ping me if I haven't gotten around to updating in a week.

**Comment by dariusc93** [comment]
I would have to check the documents again but if i recall `ValidationMode::Permissive` would reject messages containing the author, seq and/or signature, which means you might not have your `MessageAuthenticity` set to `MessageAuthenticity::Anonymous`. Could you provide any code @mriise?

**Comment by mxinden** [comment]
Friendly ping @mriise. Does this issue still persist?

**Comment by mriise** [comment]
After updating the code that displayed this behavior to the current version of libp2p I no longer see this behavior. I'm not sure exactly when or what caused this since I haven't touched said code in almost a year. I am no longer able to reproduce so will close.
