### ISSUE TITLE
transports/noise: Expose Prologue mechanism

### ISSUE THREAD

**Issue by mxinden** [libp2p/rust-libp2p#2791]
## Description

Enable users to provide a [Noise Prologue](https://noiseprotocol.org/noise.html#prologue) via [Builder::prologue](https://docs.rs/snow/latest/snow/struct.Builder.html#method.prologue).

## Motivation

Needed for https://github.com/libp2p/rust-libp2p/pull/2622, more specifically to validate the remote's TLS fingerprints. See https://github.com/libp2p/specs/pull/412#discussion_r930582351.

## Are you planning to do it yourself in a pull request?

Maybe. In case someone wants to pick this up instead, please comment to make sure we are not duplicating work.

**Comment by mxinden** [comment]
Corresponding pull request on the Golang side: https://github.com/libp2p/go-libp2p/pull/1663

**Comment by thomaseizinger** [comment]
@melekes Let me know if you are going to pick this up, otherwise I'll take it :)

**Comment by melekes** [comment]
Please go ahead. I will focus more on smoldot / substrate side for now.
