### ISSUE TITLE
Remove `PendingUpgrade` in favor of `DeniedUpgrade`

### ISSUE THREAD

**Issue by thomaseizinger** [libp2p/rust-libp2p#2856]
## Description

In https://github.com/libp2p/rust-libp2p/pull/2785, we added a `PendingUpgrade` implementation that is essentially equivalent to `DeniedUpgrade` apart from also needing a protocol. @mxinden was this on purpose or an oversight? `DeniedUpgrade` has quite some usage throughout the codebase but I think I prefer the name `PendingUpgrade` as it reflects the use of `futures::pending`. At the same time, passing a protocol to `PendingUpgrade` is unnecessary IMO.

What do people think of removing

## Motivation

Having two upgrades with the same functionality is unnecessary.

## Are you planning to do it yourself in a pull request?

Maybe.

**Comment by mxinden** [comment]
> In #2785, we added a `PendingUpgrade` implementation that is essentially equivalent to `DeniedUpgrade` apart from also needing a protocol. @mxinden was this on purpose or an oversight?

They serve two different purposes. `PendingUpgrade` provides a protocol name during `multistream-select` negotiation, but never proceeds once the protocol has been negotiated. `DeniedUpgrade` provides no protocol name during `multistream-select` negotiation, thereby the `multistream-select` negotiation fails.

I can not think of a use-case for `PendingUpgrade` beyond testing, though I think that is enough to justify its existence.

Does the above make sense?

**Comment by thomaseizinger** [comment]
Does make sense, thanks for the explanation!
