### ISSUE TITLE
transports/noise: Use proto2

### ISSUE THREAD

**Issue by mxinden** [libp2p/rust-libp2p#2924]
## Description

Update `libp2p-noise` to the latest specification change in https://github.com/libp2p/specs/pull/456.

See https://github.com/libp2p/specs/pull/456#pullrequestreview-1113439351 for a draft of a unit test to test compatibility. Might be helpful.

## Motivation

See https://github.com/libp2p/specs/pull/456.

## Are you planning to do it yourself in a pull request?

No

**Comment by mxinden** [comment]
See https://github.com/libp2p/go-libp2p/pull/1762 for the corresponding change on go-libp2p.

**Comment by nloadholtes** [comment]
Hi @mxinden I'm a Python dev who is looking at learning Rust. This is my first time really messing with a Rust project, so early apologies if I miss anything "obvious". :smile: 

Also, I am new to libp2p (very interested in it, and trying to learn more about it). Any advice/feedback is welcomed. Thank you!

**Comment by drHuangMHT** [comment]
Should we close this issue because we are moving towards proto3? @thomaseizinger

**Comment by thomaseizinger** [comment]
I'll leave that for future maintainers to decide.

**Comment by jxs** [comment]
Since https://github.com/libp2p/specs/issues/465 was accepted and https://github.com/libp2p/rust-libp2p/pull/3007 was closed, I'd say it makes sense to also close this one right?
