### ISSUE TITLE
Can gossip decide on different broadcast algorithms for message delivery?

### ISSUE THREAD

**Issue by rv64m** [libp2p/rust-libp2p#2926]
## Description
I found out that the messages currently used by GossipSub are random sequence numbers. I'd like to use it under gossipsub
1. fifo broadcast.
2. causal broadcast.

so sorry I am not sure whether this is a feature request or can be realized based on the existing functions. If the existing functions can be realized, what should I do?

## Requirements

Two broadcast algorithms based gossip
1. FIFO broadcast
2. causal broadcast

## Are you planning to do it yourself in a pull request?

Maybe.

**Comment by mxinden** [comment]
Can you expand on your motivation for FIFO and causal boardcast? Would a wrapper around `GossipSub` suffice which caches events and only emits them based on your policy?

**Comment by rv64m** [comment]
> Can you expand on your motivation for FIFO and causal boardcast? Would a wrapper around `GossipSub` suffice which caches events and only emits them based on your policy?

Ok
