### ISSUE TITLE
Consider changing identify cache default to be non-zero

### ISSUE THREAD

**Issue by thomaseizinger** [libp2p/rust-libp2p#2933]
## Description

The `rust-libp2p` identify implementation has a cache that remembers the reported addresses from the last X connected peers even once they get disconnected. By default, X is zero.

## Motivation

Most users probably don't know about this cache and thus, do not benefit from it. If we make the default value 100, the maximum memory footprint will still be < 500kb (1 identify message has max 4096 bytes, that * 100 is still only 400kb and there is more than just addresses in the message).

## Are you planning to do it yourself in a pull request?

Maybe.

**Comment by mxinden** [comment]
I am in favor of this.

**Comment by nloadholtes** [comment]
Hi, I've got a draft PR, but it feels too.... simple. :grin: Did I miss something big in the PR, or is that really all there is?

**Comment by thomaseizinger** [comment]
> Hi, I've got a draft PR, but it feels too.... simple. :grin: Did I miss something big in the PR, or is that really all there is?

We already have https://github.com/libp2p/rust-libp2p/pull/2995 open for this 🙈

Sorry, should have maybe made that more obvious in the issue here!

It is quite a simple change yeah, we are just separating it so bisecting is easier in case something breaks!

**Comment by nloadholtes** [comment]
No prob! I'm just happy my change was about 90% there :joy:  I'll close out my PR.

**Comment by jxs** [comment]
fixed with #2995
