### ISSUE TITLE
Add a kind of bot that notifies authors about merge conflicts

### ISSUE THREAD

**Issue by thomaseizinger** [libp2p/rust-libp2p#2948]
## Description

Have an automation that comments with something like: `Hey @author, please resolve the merge conflicts with the base branch.`. We should be able to do that with a GitHub workflow that runs on the `synchronize` activity of the [`pull_request`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request) event. The `mergable` property will have the value `CONFLICTING` if there are any conflicts. To avoid double commenting if a PR already has conflicts, we can set a label or something and exclude the workflow from those PRs.

## Motivation

GitHub does not send a notification when a PR has merge conflicts because the base branch changed. Having to manually check one's open PRs or wait for maintainers to pick them up is cumbersome.

## Are you planning to do it yourself in a pull request?

Maybe.

**Comment by jxs** [comment]
addressed with https://github.com/libp2p/rust-libp2p/pull/3026
