### ISSUE TITLE
Remove the various unimplemented!() from the code

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#295]
Right now it's possible to crash a server running libp2p by triggering one of the `unimplemented!()` of the code base.

Either an error should be returned, or the feature should be implemented.

**Comment by romanb** [comment]
After https://github.com/libp2p/rust-libp2p/issues/1089 is resolved by https://github.com/libp2p/rust-libp2p/pull/1189, I guess this issue can be closed, as I can find no other occurrences of `unimplemented` besides two in `core-drive` which seem irrelevant for this issue.
