### ISSUE TITLE
Properly set rustdoc attributes for docs.rs

### ISSUE THREAD

**Issue by thomaseizinger** [libp2p/rust-libp2p#2950]
On the topic of:

```toml
[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
rustc-args = ["--cfg", "docsrs"]
```

What this does is tell docs.rs to pass the `docsrs` conditional compilation flag to rustc, meaning any code that is guarded with `cfg(docsrs)` will now be included in the build.

We use this in the `libp2p` root crate to conditionally include the `doc` attribute: https://github.com/libp2p/rust-libp2p/blob/04b07c4d14a0a6ec350fc21261a33d859fc71289/src/lib.rs#L53

We need to do this conditionally because the `#[doc(cfg)]` attribute is [not yet stable](https://github.com/rust-lang/rust/issues/43781). docs.rs runs all their build pipelines on nightly so we can use it there.

Now, interestingly, we don't set this in our `libp2p` crate so all of these `cfg_attr` attributes have been doing nothing all this time :)

In this crate, it is used here: https://github.com/umgefahren/rust-libp2p/blob/6f4bca5bbfd141bc18d9d931c5d28b50a212f0fe/transports/onion/src/provider.rs#L31-L36

And will tell docs.rs to include a little "only available with feature `tokio`" tag next to the item.

_Originally posted by @thomaseizinger in https://github.com/libp2p/rust-libp2p/pull/2899#discussion_r982971842_

**Comment by umgefahren** [comment]
I'm currently working on it, however it is a lot of effort, since I have to go through nearly every single line of code here.

I will make a pull request with the changes I applied to libp2p-core, so you can judge wether the changes are good.
