### ISSUE TITLE
More comprehensive CI test matrix

### ISSUE THREAD

**Issue by thomaseizinger** [libp2p/rust-libp2p#2951]
## Description

Change our CI to run on:
- latest stable
- latest beta
- our MSRV

## Motivation

MSRV: We set a rust-version in our manifest but we don't actually run CI against that version.
Beta: Rust beta's are cut 6 week before landing on stable. This gives us enough time to know ahead of time, which lints are coming and also to notify the Rust devs in case anything that is about to hit stable breaks our build.

## Current Implementation

We only run CI against latest stable Rust.

## Are you planning to do it yourself in a pull request?

Maybe.

**Comment by umgefahren** [comment]
Just a general question on MSRV: I never quite understood why that was a thing. Are there any real reasons not to use the latest version of Rust stable?

**Comment by thomaseizinger** [comment]
> Just a general question on MSRV: I never quite understood why that was a thing. Are there any real reasons not to use the latest version of Rust stable?

Yes, multiple reasons in fact:

- Not all users use rustup to install Rust. Some rely on the version that comes with their package manager. Distros update a lot less frequently than Rust. [Debian stable](https://packages.debian.org/search?keywords=rust&searchon=names&suite=stable&section=all) for example ships with Rust 1.48.
- For compliance reasons, companies might have a process that toolchain updates need to go through before they can be used in their product. For industries like aviation and cars, these regulations are very strict. After all, a software bug might kill people. See [this](https://rustacean-station.org/episode/067-quentin-ochem-florian-gilcher/) podcast episode if you are interested.
- Despite going through nightly and a 6 week beta, new releases are a lot less vetted than older ones, so even without strict regulations, you might want to stay a couple of versions behind latest stable to f.e. not disrupt your development process as much.

Even ignoring all of that, depending on newer features will cause compilation with an older compiler to break. According to semver, breaking changes need to come with an appropriate bump. If we ignore this part, we are violating semver which can cause major headaches because software like `cargo` implements these rules when running its dependency version resolution algorithm. Software will just break from one day to another then without the user taking an explicit action.

Thus, even if we don't have a strict MSRV policy, our CI should tell us if we are making a breaking change because we are bumping the MSRV :)

**Comment by umgefahren** [comment]
Those are some very good reasons. Thanks a lot for explaining! I will take a spin at implanting this issue if I've got the time then

**Comment by umgefahren** [comment]
I didn't find any GitHub Action that did what I was looking for. Gonna write my own.

**Comment by thomaseizinger** [comment]
> I didn't find any GitHub Action that did what I was looking for. Gonna write my own.

There should be no need for a GitHub action really. We just need a matrix :)

See https://github.com/Restioson/xtra/blob/master/.github/workflows/ci.yml for example.

**Comment by umgefahren** [comment]
Oh, than there has been a misunderstanding. I thought you wanted an Action to tell you what the MSRV for a crate is. If it's just a very big matrix were we test a lot of versions, that is easier.

**Comment by thomaseizinger** [comment]
> Oh, than there has been a misunderstanding. I thought you wanted an Action to tell you what the MSRV for a crate is. If it's just a very big matrix were we test a lot of versions, that is easier.

You can get the MSRV from the manifest with some shell scripting: https://github.com/testcontainers/testcontainers-rs/blob/d7534a56d4313c8c707a1975d70874eff8a67d69/.github/workflows/ci.yml#L11

**Comment by umgefahren** [comment]
Adding a CI for that was a very good idea 😅, as it turns out we actually don't compile on Rust 1.60.0 (as we say), because a dependency of multihash (in the latest version), arbitrary (also latest version), uses `core::array::from_fn` which is a Rust 1.63 feature (very good though).

**Comment by thomaseizinger** [comment]
At the moment, we have a `rust-version` attribute in all of our crates. If we want to take this seriously, then we should really verify the MSRV of each individual crate. I think that would require us to split out the jobs _per crate_, similarly to what we are attempting to do in https://github.com/libp2p/rust-libp2p/pull/2647.

Note that we only need to run a `cargo build --all-features` for the MSRV version. dev-dependencies and tests don't need to respect MSRV.

The matrix for stable and beta should only apply to tests and clippy. Those we can run on the full workspace as we currently do.

**Comment by umgefahren** [comment]
But how should i handle the invalid rust-version?

**Comment by thomaseizinger** [comment]
> But how should i handle the invalid rust-version?

We just need to set it to the correct one, i.e. what it effectively is.

**Comment by thomaseizinger** [comment]
https://github.com/libp2p/rust-libp2p/pull/2996 mentions another error case where a regular `cargo test` failed, likely because the required features are not specified. I think our CI missed that because we don't check the default configuration of every crate.

**Comment by thomaseizinger** [comment]
Not running CI on beta causes unrelated CI failures on new stable releases: https://github.com/libp2p/rust-libp2p/actions/runs/3390658695/jobs/5635053146

**Comment by thomaseizinger** [comment]
As noted on #2289, it would be useful to have a feature for all protocols/transports and then selectively test whether it all builds with only `tokio` or `async-std` enabled!
