### ISSUE TITLE
Implement the rendezvous protocol

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#297]

**Comment by thomaseizinger** [comment]
We are working on an implementation of the rendezvous protocol and plan on upstreaming it to here.

**Comment by FelipeRosa** [comment]
I'm interested in using this in a personal project. Is there any tracking issues I could get a more detailed view on the current progress and, if needed, also help?

**Comment by mxinden** [comment]
> Is there any tracking issues I could get a more detailed view on the current progress

@FelipeRosa see https://github.com/libp2p/rust-libp2p/pull/2107.

> and, if needed, also help?

@thomaseizinger need some extra hands?

**Comment by thomaseizinger** [comment]
> @thomaseizinger need some extra hands?

Yes, could use some help actually (@FelipeRosa):

1. Feedback on the API would be great. We are still iterating on it while we are building https://github.com/comit-network/rendezvous-server and integrating it here https://github.com/comit-network/xmr-btc-swap/pull/593. If you have any feedback, feel free to comment on #2107.
2. The implementation also needs docs. Feel free to open PRs against the [`rendezvous`](https://github.com/comit-network/rust-libp2p/tree/rendezvous) branch of our fork.
3. Some of TODOs in the PR are also still open. If you want to tackle any of those, just ping me there!

**Comment by FelipeRosa** [comment]
Cool! I'll see where I can help once I start working on this in my project.

Thanks for pointing directions @thomaseizinger.

**Comment by mxinden** [comment]
Great work. And thanks for the reminder @thomaseizinger!

(rust-libp2p is the first libp2p implementation with a merged rendezvous implementation https://github.com/libp2p/website/pull/123/files.)
