### ISSUE TITLE
Persist peers for bootstrapping

### ISSUE THREAD

**Issue by Winterhuman** [libp2p/rust-libp2p#2987]
## Description

Mirroring https://github.com/libp2p/go-libp2p-kad-dht/issues/254, it would be great if long-lasting peers were persisted and used for bootstrapping later.

## Motivation

Using bootstrap nodes outside of the default ones improves network resiliency, and potentially improves initial connections times when the new bootstrap nodes are closer than they otherwise would be.

## Requirements

1. Save the longest lasting peer(s) from each k-bucket where it can be re-used for bootstrapping.

## Open questions

- Which k-buckets are considered, and how many peers are picked from each bucket?
- Should latency be factored into picking future bootstrap nodes? If so, how?
- Other open questions mentioned at https://github.com/ipfs/kubo/issues/3926 and https://github.com/libp2p/go-libp2p-kad-dht/issues/254.

## Are you planning to do it yourself in a pull request?

No

**Comment by dariusc93** [comment]
If im understanding the issue correctly, one could implement their own store for `RecordStore`. Something like sled or rocksdb could be a good place to start for persistence and move up from there for different backend stores, though something to be included for rust-libp2p is hard to say. Mostly feel that it should be an outside implementation.

**Comment by Winterhuman** [comment]
Perhaps you're right, I mainly opened this to mirror https://github.com/libp2p/go-libp2p-kad-dht/issues/254 which targets `go-libp2p` as opposed to Kubo, although https://github.com/ipfs/kubo/pull/8856 being open at the same time confuses things as to where this sort of code should belong

**Comment by thomaseizinger** [comment]
In `rust-libp2p`, `PeerId`s are resolved to addresses by querying all configured behaviours via `NetworkBehaviour::addresses_of_peer`. It should be relatively straight-forward to implement your own `NetworkBehaviour` that extracts addresses from the `NetworkBehaviour::inject_connection_established` callback, stores them in some persistent way and queries that storage whenever `addresses_of_peer` is called.

To avoid latency issues, I'd be best to not do any IO in the `NetworkBehaviour::poll` method as that is run as part of the main event loop of a `Swarm`.

**Comment by Winterhuman** [comment]
Closing since this can be implemented independently
