### ISSUE TITLE
Quic attempt v3 vs v4 benchmarking

### ISSUE THREAD

**Issue by stormshield-pj50** [libp2p/rust-libp2p#3020]
Hello there, we (at Stormshield) have been benchmarking various async Quic implementations between a client and a remote server VMs with dedicated vswitch (1 connection with 1 substream, 1 second keep-alive, AES_256_GCM_SHA_384, upload only)
Average bandwidth on 10 run each 80GBytes upload:
- tcp with s2n netbench (plaintext/nocipher): 12,4 GBit/s
- tcp + tls with s2n netbench: 4,1 GBit/s
- s2n-quic + s2n-tls: 3,9 GBit/s
- s2n-quic + rustls: 3.8 GBit/s
- quinn using quinn-perf: 3.3 GBit/s
- libp2p + Quic attempt-v4 with libp2p_perf (patched to use latest tokio): 3.2 GBit/s
- libp2p + Quic attempt-v3 with libp2p_perf (patched to use latest tokio): **730 MBit/s**

So it seems that Quinn is slower than s2n-quic. Quic attempt-v4 has the same performance as Quinn, and Quic attempt-v3 has really poor performance. 

## Summary
To benchmark Quic attempt v3/v4:
- Have a look at https://github.com/pj50/libp2p-perf/tree/perf_v3_v4. 
- Use kpp libp2p-quic branch for v3 attempt and quic-attempt-4 branch for v4.
- Locally checkout kpp. 
- Patch the kpp branch with one of the two top commits and checkout the third or fourth top commit in order to build libp2p_perf with attempt v3 or v4.

## Expected behaviour
Performance should be as close as possible as when using standalone Quinn.

## Actual behaviour
Bad performance using Quic attempt v3.

## Possible Solution
N/A

## Version
- libp2p version (version number, commit, or branch):
0.45.0

## Would you like to work on fixing this bug?
No

**Comment by thomaseizinger** [comment]
I repeated these benchmarks on my machine and I did get similar results, albeit not quite as bad:

- v3: 1.3 GBit
- v4: 2.3 GBit

**Comment by thomaseizinger** [comment]
I've flamegraphed both implementations. One thing I found out is that the two branches as of today don't use the same cipher suite:

v3 uses `CHACHA20_POLY1305_SHA256`: https://github.com/kpp/rust-libp2p/blob/b51f28055dc1f358967b4733596221dbdbfc6f94/transports/quic/src/tls/mod.rs#L36-L44
v4 uses `TLS13_AES_256_GCM_SHA384`: https://github.com/kpp/rust-libp2p/blob/0e86fb2fd60da3459d8dc9e892af06a40f390ccd/transports/quic/src/tls/mod.rs#L36-L44

If I change v4 to also use `CHACHA20_POLY1305_SHA256`, the performance drops to about 2.0 GBit. Interestingly, switching v3 to `TLS13_AES_256_GCM_SHA384` doesn't make much of a difference, we still only get ~ 1.2GBit.

Which cipher suites do the other implementations use?

**Comment by thomaseizinger** [comment]
Silly me, I just re-read your post and saw that you are already accounting for that. Ah well.

**Comment by thomaseizinger** [comment]
Anyway, something else that I found during flamegraphing is that we spend about 13% of our time within `futures_channel` functions in the v3 implementation.

[server_flamegraphs.zip](https://github.com/libp2p/rust-libp2p/files/9797542/server_flamegraphs.zip)

**Comment by thomaseizinger** [comment]
[`async_std::ReceiveStream`](https://github.com/kpp/rust-libp2p/blob/b51f28055dc1f358967b4733596221dbdbfc6f94/transports/quic/src/provider/async_std.rs#L94-L134) also costs us about 7%.

**Comment by thomaseizinger** [comment]
Another interesting statistic:

In v3 we spend about 37% of our time in `quinn_proto`, in v4 it is 49%.

**Comment by thomaseizinger** [comment]
I did an initial run with tokio as well and the performance was actually worse. I haven't looked at that flamegraph in detail yet.

**Comment by stormshield-damiend** [comment]
Hi, something to take into account:
- attempt v3 uses standard udp sockets which send and recv one packet at a time
- attempt v4 uses quinn-udp which abstract sockets and on Linux use GSO / GRO to send / receive batch of packets instead of one packet at a time

This will reduce a lot the amount of syscalls between userland and kernel to handle packets and result to a performance increase (for V4).

**Comment by thomaseizinger** [comment]
Closing this as stale as we have already settled on a QUIC implementation and we are going to migrate to the upstream `quinn` implementation eventually.
