### ISSUE TITLE
Migrate from `protoc` to `quick-protobuf` and remove the buildscripts

### ISSUE THREAD

**Issue by thomaseizinger** [libp2p/rust-libp2p#3024]
## Description

Migrate our codebase from `protoc` to `quick-protobuf`.
We also want to get rid of the buildscripts and instead check the generated code into Git and add a CI step that verifies that they are directly generated from the protobuf files.

## Motivation

- Users are irritated about the dependencies required to build rust-libp2p: https://github.com/libp2p/rust-libp2p/issues/2645
- It causes bloat in our CI workflow: Every job needs to install protoc.
- We sometimes get CI failures in installing protoc: https://github.com/libp2p/rust-libp2p/actions/runs/3243659893/jobs/5327292307

## Current Implementation

We depend on protoc being installed because prost no longer ships with it.

## Are you planning to do it yourself in a pull request?

No.

**Comment by dariusc93** [comment]
Havent ran into any issues relating to CI and protoc, but migrating from it to `rust-protobuf` would possibly be one less external dependency needed and would cause less confusion for users building the code

**Comment by mxinden** [comment]
Adding another data point. We facilitated a rust-libp2p workshop today. Installing `protoc` was a significant slow down for many semi technical participants.

**Comment by thomaseizinger** [comment]
I'd really appreciate help on this front @nloadholtes :)

**Comment by thomaseizinger** [comment]
> I'd really appreciate help on this front @nloadholtes :)

Just a heads-up that there is now https://github.com/libp2p/rust-libp2p/pull/3050 @nloadholtes.

**Comment by thomaseizinger** [comment]
@kckeiks Thanks a lot for your efforts on this issue! I also have to apologize for not putting my thoughts / intentions into this more clearly. The main thing I/we'd want out of this is to get rid of the `protoc` dependency. There are numerous ways of achieving this and I should have been more clear that particularly migrating to `rust-protobuf` is only one of the options.

As I mentioned on https://github.com/libp2p/rust-libp2p/pull/3066, I'd prefer the code that `quick-protobuf` generates. Whilst thinking about this, I did have another idea. Our protobuf files basically never change because they are part of the spec. Instead of generating them on build-time, we could also just check them into Git. I see several benefits:

- Faster builds because no build scripts
- Better IDE integration
- Better auditability (for example regarding the `unsafe` code I linked in https://github.com/libp2p/rust-libp2p/pull/3066)

There are however also some downsides:

- We need a separate CI job that ensures the generated code does not get modified
- Some people may disagree on the aesthetics on generated code in Git

I'd also like to mention that this is what used to be done (https://github.com/libp2p/rust-libp2p/issues/183) and later changed to `prost` in https://github.com/libp2p/rust-libp2p/pull/1390.

@tomaka Did you experience any problems back then with the "checking in the generated code" approach that caused you to move away from it?

@libp2p/rust-libp2p-maintainers Please voice your opinion on this!

**Comment by tomaka** [comment]
> @tomaka Did you experience any problems back then with the "checking in the generated code" approach that caused you to move away from it?

No, as far as I remember I was in favor of keeping the "checking in the generator code" approach.

**Comment by mxinden** [comment]
> We need a separate CI job that ensures the generated code does not get modified

As long as we can make sure the checked-in code is correct, i.e. as long as we have a CI step, I am in favor of checking in the generated code.

> @kckeiks Thanks a lot for your efforts on this issue!

Also want to thank you here for your work. Sorry in case it does not end up being merged.

**Comment by kckeiks** [comment]
> > @kckeiks Thanks a lot for your efforts on this issue!
> 
> Also want to thank you here for your work. Sorry in case it does not end up being merged.

No worries! I'm glad we did not rush in :)

**Comment by thomaseizinger** [comment]
> @libp2p/rust-libp2p-maintainers Please voice your opinion on this!

It's been almost 3 weeks so I think we can move forward here! :)

@kckeiks Would you be open to expand https://github.com/libp2p/rust-libp2p/pull/3066 to all crates but with checking the generated code into VCS instead of generating it with a build script?

**Comment by thomaseizinger** [comment]
Our CI is failing a lot recently due to the `protoc` action getting rate-limited in downloading `protoc`. I am aware that there are likely solutions to work around that but I am gonna take that as an opportunity to go ahead with this migration at the same time since we also want that unless someone beats me to it!

**Comment by kckeiks** [comment]
> > @libp2p/rust-libp2p-maintainers Please voice your opinion on this!
> 
> It's been almost 3 weeks so I think we can move forward here! :)
> 
> @kckeiks Would you be open to expand #3066 to all crates but with checking the generated code into VCS instead of generating it with a build script?

Hey @thomaseizinger I'm sorry I did not see your message before. Yeah, I would be happy to help out here and expand #3066. Have you started by any chance? I don't want our patches to overlap. I'll start working on this this coming week.

**Comment by thomaseizinger** [comment]
Nope, I haven't started yet, so feel free to go ahead. Thank you! :)
