### ISSUE TITLE
Semver issues with `libp2p-swarm-derive:0.30.1` - please yank

### ISSUE THREAD

**Issue by Voxelot** [libp2p/rust-libp2p#3029]
Related to: #2907 

When `libp2p-swarm-derive:0.30.1` was released today, it started causing our libraries to fail to compile due to breaking changes in #2907 being released as a patch version. While the PR is a good improvement, we had already made the appropriate workarounds to deal with these generics in our own published crates.

My suggestion would be that libp2p should properly bump the version of libp2p-swarm-derive to `0.31.0` and yank `0.30.1` to avoid causing unexpected build failures for libp2p users.

cc @mxinden

**Comment by thomaseizinger** [comment]
Can you post the piece of code that would compile before but doesn't now?

**Comment by mxinden** [comment]
Closing here. @Voxelot please let us know in case you are still facing this issue.
