### ISSUE TITLE
improve rendering of dial error on connection limit

### ISSUE THREAD

**Issue by rkuhn** [libp2p/rust-libp2p#3037]
https://github.com/libp2p/rust-libp2p/blob/4d4833f8c2622018b5b775896905a534b8624d3c/swarm/src/connection.rs#L350

How about `"connection limit exceeded ({}/{})"`?

**Comment by thomaseizinger** [comment]
Isn't the number always the same in that case? Probably worth printing only the limit.

**Comment by rkuhn** [comment]
With the direct interpretation of the fields’ doc comments I would agree, but there are two fields and this error may be constructed with different values for `current` and `limit`, so I’d print both. “5 of 5” is also somewhat established to show that a limit of five was reached, despite the redundancy.
