### ISSUE TITLE
rendezvous: Unregister peer on connection close.

### ISSUE THREAD

**Issue by dgrr** [libp2p/rust-libp2p#3061]
## Description

Rendezvous servers are not automatically unregistering the peers that disconnect, thus keeping the peer on the rendezvous list.
It would be nice if the server behavior unregisters the peer automatically or upon parameter request (something like a Config when creating the server behavior).
Maybe this behavior (pun intended) is expected, but I think it's not desirable for the user. Mainly because a peer might fail due to unexpected reasons and the peer might be still present in the server. So letting the unregister up to the user might not always be a possibility. 

## Motivation

Because it allows users to easily create rendezvous servers and not give fake peers that aren't present in the rendezvous server.

## Current Implementation

Does not remove the peer automatically.

## Are you planning to do it yourself in a pull request?

Maybe, but probably not.

**Comment by dariusc93** [comment]
Should be easy to do with `NetworkBehaviour::inject_connection_closed` and others but I guess the question would be is there a use case where one would want to keep the list of peers that did once connect to the rendezvous node? I honestly cant think of any but like you said could probably be a configuration to allow the peer to remain on the list.

**Comment by thomaseizinger** [comment]
Idle connections should be closed to not use unnecessary resources IMO.

Just because a peer disconnects from a rendezvous server doesn't mean that they stopped offering the registered service.
