### ISSUE TITLE
Error while building libp2p-core

### ISSUE THREAD

**Issue by gabrieldemian** [libp2p/rust-libp2p#3088]
## Summary

Hello, I'm trying to build my project but I always have this error: 

```
error: failed to run custom build command for `libp2p-core v0.37.0`

Caused by:
  process didn't exit successfully: `/home/demian/code/rust/blockchain/target/debug/build/libp2p-core-7659726096d24e39/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'Could not find `protoc` installation and this build crate cannot proceed without

      this knowledge. If `protoc` is installed and this crate had trouble finding
      it, you can set the `PROTOC` environment variable with the specific path to your
      installed `protoc` binary.If
```

## Version
0.49

## Would you like to work on fixing this bug?
Yes

**Comment by p-shahi** [comment]
> Could not find `protoc` installation

@gabrieldemian you need to install `protoc` on your machine.
You can do `apt install -y protobuf-compiler` on Ubuntu or `brew install protobuf` on Mac.

Since this isn't an issue with the implementation, I'll close this issue for now.

**Comment by thomaseizinger** [comment]
For reference, we are working on moving away from protoc: https://github.com/libp2p/rust-libp2p/issues/3024

**Comment by gabrieldemian** [comment]
Thank you for replying to my issue, I installed protobuf on my machine but now I have a new issue:

```
❯ cargo build
   Compiling blockchain v0.1.0 (/home/demian/code/rust/blockchain)
error[E0432]: unresolved import `libp2p::gossipsub`
 --> src/models/p2p.rs:1:5
  |
1 | use libp2p::gossipsub;
  |     ^^^^^^^^^^^^^^^^^ no `gossipsub` in the root

For more information about this error, try `rustc --explain E0432`.
error: could not compile `blockchain` due to previous error
```

**Comment by gabrieldemian** [comment]
Thank you for replying to my issue, I installed protobuf on my machine and built the project with no errors
