### ISSUE TITLE
*: Deprecated lazy_static in favor of once_cell

### ISSUE THREAD

**Issue by umgefahren** [libp2p/rust-libp2p#3109]
## Description

lazy_static is used 3 times in this project. It has some downsides and could be replaced with once_cell while improving compile time and, once once_cell is stable, reducing dependencies.

The priority is very low here. It might increase once once_cell is stable.

## Motivation

lazy_static is very widely used in the Rust community and is very battle-tested. However, it uses a proc_macro to expand and thus increases compile time. As far as I'm aware Rust is heading towards once_cell instead, since it offers lower compile time and will be integrated into the standard library.

## Current Implementation

Currently, lazy_static is used.

## Are you planning to do it yourself in a pull request?

Yes.

**Comment by thomaseizinger** [comment]
I am in favor.
