### ISSUE TITLE
examples/ping build errors

### ISSUE THREAD

**Issue by wvdji** [libp2p/rust-libp2p#3112]
error[E0432]: unresolved import `libp2p::ping`
  --> src/main.rs:26:24
   |
26 | use libp2p::{identity, ping, Multiaddr, PeerId};
   |                        ^^^^ no `ping` in the root

error[E0432]: unresolved import `libp2p_swarm`
  --> src/main.rs:27:5
   |
27 | use libp2p_swarm::keep_alive;
   |     ^^^^^^^^^^^^ use of undeclared crate or module `libp2p_swarm`

error[E0433]: failed to resolve: use of undeclared crate or module `async_std`
  --> src/main.rs:30:3
   |
30 | #[async_std::main]
   |   ^^^^^^^^^ use of undeclared crate or module `async_std`

error[E0425]: cannot find function `development_transport` in crate `libp2p`
  --> src/main.rs:36:29
   |
36 |     let transport = libp2p::development_transport(local_key).await?;
   |                             ^^^^^^^^^^^^^^^^^^^^^ not found in `libp2p`

error[E0599]: no method named `select_next_some` found for struct `Swarm` in the current scope
  --> src/main.rs:53:21
   |
53 |         match swarm.select_next_some().await {
   |                     ^^^^^^^^^^^^^^^^ method not found in `Swarm<Behaviour>`

**Comment by umgefahren** [comment]
Could you give a bit more context here? What exactly is the issue and could you give the complete code? From the first look of it you copy-and-pastet the ping example into a project of your own, but you forgot to enable the necessary features of libp2p and add the libp2p_swarm dependency.

**Comment by dariusc93** [comment]
I agree with @umgefahren, Although the errors dont provide much context, it only make me assume you didnt have all of the dependencies apart of your project as well as having the features enabled in your `Cargo.toml`.

**Comment by thomaseizinger** [comment]
Related: https://github.com/libp2p/rust-libp2p/issues/3111

**Comment by wvdji** [comment]
Sorry, I'm new to Rust. Problem solved.

**Comment by umgefahren** [comment]
No problem

Part of the problem might be the fact that the ping example uses libp2p_swarm instead of libp2p.
