### ISSUE TITLE
swarm: Rename `NetworkBehaviourAction` to `ToSwarm`

### ISSUE THREAD

**Issue by thomaseizinger** [libp2p/rust-libp2p#3123]
## Description

Similar to https://github.com/libp2p/rust-libp2p/issues/2854, what do people think of renaming `NetworkBehaviourAction` to `ToSwarm`?

## Motivation

Consistent naming of messages between our "actors".

## Current Implementation

The current naming is very inconsistent which makes things hard to understand.

## Are you planning to do it yourself in a pull request?

Maybe.

**Comment by mxinden** [comment]
I am in favor of a rename for the sake of consistency. I don't have a strong opinion on the name. `ToSwarm` sounds good to me.

**Comment by thomaseizinger** [comment]
Hmm, I just realised that `ToSwarm` doesn't quite work because we also have a `NotifyHandler` variant in there.

**Comment by mxinden** [comment]
Given that the `NotifyHandler` event is passed through the `Swarm` one could argue that `ToSwarm` is still a valid name.

**Comment by thomaseizinger** [comment]
It even says in the documentation:

> Instructs the `Swarm` to send an event to the handler dedicated to a connection with a peer.

**Comment by mxinden** [comment]
Based on out-of-band discussion, updating labels here. Please comment in case you think this is not appropriate.

**Comment by thomaseizinger** [comment]
If we end up succeeding with https://github.com/libp2p/rust-libp2p/issues/3591, the 2nd type parameter will go away through that, thus, I don't think it is worth going into the direction of https://github.com/libp2p/rust-libp2p/pull/3273 but instead do a simple rename with a type alias to retain backwards-compatibility.

Based on that, I think this is `difficulty:easy`.
