### ISSUE TITLE
Properly send a close message for mplex substreams

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#313]
When an `mplex` substream is dropped, we try to send a close message to the remote.
However if the current output buffer is full, the message will not get through.

**Comment by tomaka** [comment]
Some things have changed in mplex, but this issue is still there.

If we destroy a substream with `destroy_substream` and this substream was still open, we currently don't notify the remote. Instead we should send a `Reset` message.

There's still the problem that `destroy_substream` must return instantly, therefore we can't return `NotReady`, and we need to add some sort of send buffer.

**Comment by romanb** [comment]
Closed by #1769.
