### ISSUE TITLE
feat(swarm): expose duration of a connection

### ISSUE THREAD

**Issue by mxinden** [libp2p/rust-libp2p#3135]
## Description

Expose the duration a connection was alive.

I would assume the easiest way to expose this is via `SwarmEvent::ConnectionClosed`.

https://github.com/libp2p/rust-libp2p/blob/7803524a76fb52817b00bcb61544be3a1a317ebd/swarm/src/lib.rs#L195-L207

## Motivation

Needed for monitoring purposes, e.g. to be exposed to Prometheus via libp2p-metrics.

## Are you planning to do it yourself in a pull request?

No

**Comment by thomaseizinger** [comment]
I've been wondering, would it make more sense to implement a `NetworkBehaviour` that captures the metrics that we are currently capturing via `SwarmEvent`s?

I think that might be easier to integrate compared to hooking into their event loop.

**Comment by mxinden** [comment]
Good thought @thomaseizinger! I think this would be significantly less intrusive than the current approach.

How would one capture events from other `NetworkBehaviour` implementations? Would one `derive` `NetworkBehaviour` for the set of `NetworkBehaviour`'s and then wrap that derived `NetworkBehaviour` in a metrics `NetworkBehaviour`?

Something along the lines of:

``` rust
    #[derive(NetworkBehaviour)]
    struct MyBehaviour {
        floodsub: Floodsub,
        mdns: Mdns,
    }
    let my_behaviour = MyBehaviour::default();
    let my_instrumented_behaviour = libp2p_metrics::Behaviour::new(my_behaviour);
```

I would guess that this needs some macro magic. Not to say that it is not worth exploring.

**Comment by thomaseizinger** [comment]
Either a wrapper as you said or we add metrics to the individual behaviours.

**Comment by thomaseizinger** [comment]
Something like the following could work:

```rust
pub struct RecordBehaviour<B, M> {
	inner: B,
	metrics: M
}

impl<B, M> NetworkBehaviour for RecordBehaviour<B, M> where M: Recorder<B::OutEvent> {
	
}

impl Deref for RecordBehaviour<B, M> { }
impl DerefMut for RecordBehaviour<B, M> { }
```

Instead of `Deref` we could also offer an `inner_mut()` function but that might be a bit verbose. It would be nice if the `RecordBehaviour` is in invisible layer on top.

**Comment by tcoratger** [comment]
@thomaseizinger Could you provide me with a little more detail on how to implement it (the overall roadmap)? If I understand how to do it, I could support this issue :)

**Comment by mxinden** [comment]
I think the above suggestion of a new abstraction requires some exploratory work, along the lines of "How can we make the integration of the current `libp2p-metrics` crate into ones application less verbose".

In regards to the concrete issue, namely to expose the lifetime (duration) of a connection, I would suggest the following:

- Add a `connection_id: ConnectionId,` to `SwarmEvent::ConnectionEstablished` and `SwarmEvent::ConnectionClosed`. This is in-line with what we already do in `FromSwarm::ConnectionEstablished` and `FromSwarm::ConnectionClosed`.
- In `libp2p-metrics` the `swarm` module, keep track of the establishment time of each connection, indexed by `ConnectionId`. When tracking a `SwarmEvent::ConnectionClosed`, calculate the duration of the connection.
- Introduce a `prometheus_client::Histogram` in the `libp2p-metrics` `swarm` module and track the connection duration there.

What do you think @tcoratger? Is this of some help?

**Comment by thomaseizinger** [comment]
> @thomaseizinger Could you provide me with a little more detail on how to implement it (the overall roadmap)? If I understand how to do it, I could support this issue :)

As Max said, I think this still needs some fleshing out. We should likely not block this issue on it but proceed the way Max suggested above.

I'll open a separate issue to discuss that.

**Comment by thomaseizinger** [comment]
> I'll open a separate issue to discuss that.

Done: https://github.com/libp2p/rust-libp2p/discussions/3868
