### ISSUE TITLE
Swarm: add `fn ban_peer_id_with_duration`

### ISSUE THREAD

**Issue by hanabi1224** [libp2p/rust-libp2p#3140]
## Description

Currently [`ban_peer_id`](https://docs.rs/libp2p/latest/libp2p/struct.Swarm.html#method.ban_peer_id) bans a peer for the entire lifetime of the swarm unless `unban_peer_id` is called.  It would be great to have another `ban_peer_id_with_duration` API that automatically unbans the peer after the specific duration.  

## Motivation

The peers being banned may "correct" their behavior and we would give them a chance to reconnect after a while so that we can re-evaluate them

## Requirements

1. the API accepts an additional `Duration` parameter
2. automatically unban the peer after the specified duration
3. the API change should be backward compatible, requiring only patch version bump 

## Are you planning to do it yourself in a pull request?

Maybe.

**Comment by mxinden** [comment]
If I am not mistaken, you can already achieve this behavior by calling `unban_peer_id` on `Swarm` once an external timer fired.

Unless there is a majority of users that would need this feature, I would advocate for this to live outside of rust-libp2p as described above.

Long term I advocate for making most of the connection management generic. See #2824.
