### ISSUE TITLE
`libp2p-webrtc` is already claimed on crates.io

### ISSUE THREAD

**Issue by thomaseizinger** [libp2p/rust-libp2p#3141]
It seems like @wngr has been developing a WebRTC transport too and published it on crates.io. We either need to rename our crate or talk to @wngr whether they would transfer the name to us :)

cc @melekes @mxinden

**Comment by mxinden** [comment]
A bit of background for you @wngr:

Over the last couple of months we have been working on a WebRTC transport for libp2p. The [specification](https://github.com/libp2p/specs/blob/master/webrtc/README.md) gives a good overview. There is an implementation in Rust (https://github.com/libp2p/rust-libp2p/pull/2622, about to be released), Go (https://github.com/libp2p/go-libp2p/pull/1655) and JS (https://github.com/little-bear-labs/js-libp2p-webrtc/).

For now this only covers the browser-to-server use-case (without signaling). We are working on browser-to-browser next. This would enable rust-libp2p running in the broser via WASM to communicate to any other browser. Thus this would be on par with your project https://github.com/wngr/libp2p-webrtc.

I see the above effort as a consolidation of the many libp2p WebRTC implementations out there. Would you agree that this would as well cover the use-case you are targeting with https://github.com/wngr/libp2p-webrtc?

**Comment by wngr** [comment]
No worries. Let me know who I should transfer it to.

**Comment by mxinden** [comment]
:pray: thanks @wngr. I have sent you an email.

**Comment by mxinden** [comment]
I am now an owner of the repository. Thanks @thomaseizinger for catching this early. Thanks @wngr for transferring ownership.
