### ISSUE TITLE
examples: Add example combining dns + tcp + quic + relay

### ISSUE THREAD

**Issue by mxinden** [libp2p/rust-libp2p#3143]
## Description

Combining these is tricky. I think we should have an example on how to combine them.

## Motivation

Helps users getting started.

## Are you planning to do it yourself in a pull request?

No

**Comment by dariusc93** [comment]
Although i do need to test quic with relay again, this should be pretty easy to do assuming the way I been doing it is correct. Would be helpful for anybody getting familiar with it and maybe even go as far as testing it with dcutr

**Comment by thomaseizinger** [comment]
Note that dcutr together with QUIC is not yet supported. See "long term": https://github.com/libp2p/rust-libp2p/issues/2883

**Comment by dariusc93** [comment]
> Note that dcutr together with QUIC is not yet supported. See "long term": #2883

Thanks for that. That does explain alot in earlier testing

**Comment by mxinden** [comment]
@thomaseizinger I remember you being opposed to adding QUIC to `development_transport`. What do you think of a transport-combination-example instead?

**Comment by thomaseizinger** [comment]
> @thomaseizinger I remember you being opposed to adding QUIC to `development_transport`. What do you think of a transport-combination-example instead?

I am guessing you are talking about https://github.com/libp2p/rust-libp2p/issues/3060#issuecomment-1289818482?

I am okay if we add it in the meantime, long-term, the composing must be so easy that we don't need an example for every transport.

**Comment by thomaseizinger** [comment]
Cross-referencing a discussion here: https://github.com/libp2p/rust-libp2p/discussions/3653

**Comment by thomaseizinger** [comment]
Closing as resolved with https://github.com/libp2p/rust-libp2p/pull/4120.
