### ISSUE TITLE
Unable to get tokio-mdns to discover peers on the same machine

### ISSUE THREAD

**Issue by dignifiedquire** [libp2p/rust-libp2p#3147]
I am currently trying to make iroh discover other nodes via MDNS, see https://github.com/n0-computer/iroh/pull/529. 
After upgrading to the latest `master` I am still not able to discover any peers on the same machine using tokio-mdns. They boot up and report sending listening and sending queries, but no peers are ever discovered. 

Some additional observations
- The mdns passive discovery example, does discover both peers (this is using async-std mdns).
- The chat tokio chat example seems to discover each other when running (though the chat functionality never ends up actually running, not sure where the issue there is ref https://github.com/libp2p/rust-libp2p/issues/3100

**Comment by rkuhn** [comment]
Ah yes, I saw that this week with ipfs-embed but didn’t have time to investigate. Perhaps it is time for some weekend wiresharking …

**Comment by dignifiedquire** [comment]
Got it to work, it was my own fault. The nodes had the same identity, which is why they ended up ignoring each other.

**Comment by rkuhn** [comment]
Hmm, then my problem was yet another one …
