### ISSUE TITLE
swarm/src/handler/multi.rs: `MultiHandler` isn't used anywhere inside rust-libp2p. Maybe get rid of it?

### ISSUE THREAD

**Issue by efarg** [libp2p/rust-libp2p#3171]
## Description

Currently `MultiHandler` isn't used anywhere inside the project. Is it possible to remove or modify it?

## Motivation

* `MultiHandler` violates the guideline of not implementing `UpgradeInfoSend`, `OutboundUpgradeSend`, and `InboundUpgradeSend` mentioned in `swarm/src/upgrade.rs`. See comment: https://github.com/libp2p/rust-libp2p/pull/2966#issuecomment-1314476317

* It's a hurdle in solving #2831. Try building WIP solution for the said issue at https://github.com/efarg/rust-libp2p/tree/2966
One of the errors encountered would be:

```
error[E0271]: expected `std::vec::IntoIter<IndexedProtoName>` to be an iterator that yields `ProtocolName`, but it yields `IndexedProtoName`
   --> swarm/src/handler/multi.rs:458:21
    |
458 |     type InfoIter = std::vec::IntoIter<IndexedProtoName>;
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `ProtocolName`, found struct `IndexedProtoName`
```

The error above is what brought thomaseizinger's attention to this issue. For further understanding, see comments: https://github.com/libp2p/rust-libp2p/issues/2831#issuecomment-1255151499 and https://github.com/libp2p/rust-libp2p/pull/2966#issuecomment-1314476317 and the replies by @thomaseizinger on the latter.

This happens due to changing the current definition of `UpgradeInfoSend` from this https://github.com/libp2p/rust-libp2p/blob/5b4eab7bafe6cba8fea6c806027ea680662b7cc6/swarm/src/upgrade.rs#L31-L39

to this

```
pub trait UpgradeInfoSend: Send + 'static {
    /// Equivalent to [`UpgradeInfo::InfoIter`](upgrade::UpgradeInfo::InfoIter).
    type InfoIter: Iterator<Item = upgrade::ProtocolName> + Send + 'static;

    /// Equivalent to [`UpgradeInfo::protocol_info`](upgrade::UpgradeInfo::protocol_info).
    fn protocol_info(&self) -> Self::InfoIter;
}
```

## Are you planning to do it yourself in a pull request?

Yes.

**Comment by thomaseizinger** [comment]
`MultiHandler` has been here ever since I started working on `rust-libp2p` but I personally never had a use for it.

@mxinden Do you know of any users?

**Comment by mxinden** [comment]
It is used in Substrate.

https://github.com/paritytech/substrate/blob/a92005a5092ebe6a636c96dcae814f9a378f5940/client/network/src/request_responses.rs#L49

I still need to read up on the above. Thanks @efarg for the detailed issue.

**Comment by thomaseizinger** [comment]
Okay, thanks for the insight. I think I already know how to fix the issue in #2966.

@efarg Did you push all your code? Then I might just push a quick patch on top fixing `MultiHandler`.

**Comment by efarg** [comment]
@thomaseizinger yes, the code that would give the multihandler error is all here https://github.com/efarg/rust-libp2p/tree/2966

**Comment by thomaseizinger** [comment]
I posted a patch onto the PR that fixes the multihandler issue: https://github.com/libp2p/rust-libp2p/pull/2966#issuecomment-1334631459
