### ISSUE TITLE
Unable to use QUIC Transport with SwarmBuilder

### ISSUE THREAD

**Issue by Firaenix** [libp2p/rust-libp2p#3179]
## Summary
Following the example at https://docs.rs/libp2p/latest/libp2p/quic/index.html, I tried to use the QUIC transport to create a Swarm object. However 
Example code:
![image](https://user-images.githubusercontent.com/8898038/204680756-0acf678c-f1cf-4833-9d85-d94830d0002c.png)

## Expected behaviour
I would expect the quic::Connection struct (Which implements StreamMuxer) to be boxed up and accepted as a transport for the SwarmBuilder parameter.

## Actual behaviour
I get the following compile-time error:
![image](https://user-images.githubusercontent.com/8898038/204680914-c2d862f2-ced9-451a-a529-c843f39300d5.png)

## Version
libp2p 0.50

**Comment by thomaseizinger** [comment]
For the time being, you need to box up the `Connection` object yourself. See the tests on how to: https://github.com/libp2p/rust-libp2p/blob/be0b62a78fe9d72811b9eda742137cc8ddc4da35/transports/quic/tests/smoke.rs#L310-L319

**Comment by Firaenix** [comment]
Great! Thats very helpful, thank you. I was wondering if there was something like that.

**Comment by thomaseizinger** [comment]
I think we should rework the API of `Swarm` to do the boxing internally so this is not necessary.

**Comment by thomaseizinger** [comment]
Related #3186. Adding a `T: Transport` type parameter and doing the boxing internally would solve this issue but creates a lot of type parameter and trait bound noise because we have `SwarmBuilder` and `Swarm` today. We should streamline the creation of a `Swarm` first to minimise the impact of this type parameter change.

@libp2p/rust-libp2p-maintainers Thoughts?

**Comment by mxinden** [comment]
No opinion here. Doing the boxing in `Swarm` or `SwarmBuilder` sounds fine to me.

**Comment by thomaseizinger** [comment]
Using QUIC and WebRTC together with other transports is a bit clunky at the moment:

https://github.com/libp2p/test-plans/blob/c916d4b247d40d20fee995ea070779365426814a/ping/rust/src/bin/testplan_0510.rs#L24-L40

**Comment by thomaseizinger** [comment]
With https://github.com/libp2p/rust-libp2p/pull/3588 merged, there is now only a single place to (`SwarmBuilder`) where we are accepting a `transport::Boxed`. I'd like to see if we can solve this issue by accepting a `T: Transport` instead, therefore doing the boxing internally and allow every `Transport` to be passed to `SwarmBuilder`.
