### ISSUE TITLE
Concurrent dials to the same peer with duplicated multiaddrs

### ISSUE THREAD

**Issue by stormshield-pj50** [libp2p/rust-libp2p#3209]
## Summary
Useless concurrent dials when a peer is found with two identical multiaddrs in the DHT: one with a peerid, and the other without a  peerid.

## Expected behaviour
When dialing a peer, identical multiaddrs (that only differ with the presence of the peerid) should be filtered out in order to prevent useless concurrent dials to the same peer.

## Actual behaviour
Two identical mutliaddrs filled by the DHT:

/ip4/10.10.0.1/tcp/80
and
/ip4/10.10.0.1/tcp/80/QmXXXXXXXX

are concurrently dialed twice.

## Possible Solution
[Maybe check uniqueness of multiaddrs without peerid](https://github.com/libp2p/rust-libp2p/blob/1c2712c1bc288dc608aaec5fc3458b0d07181feb/swarm/src/lib.rs#L590)

## Version

- libp2p version (version number, commit, or branch): 0.49

## Would you like to work on fixing this bug?
No

**Comment by thomaseizinger** [comment]
Thanks for the report! I agree that it makes sense to do some better filtering here.

**Comment by thomaseizinger** [comment]
Needs a test before we can consider this closed.

**Comment by thomaseizinger** [comment]
@stormshield-pj50 Does this still occur?

**Comment by stormshield-pj50** [comment]
> @stormshield-pj50 Does this still occur?

Not any more, that's fixed. You can close the issue.
