### ISSUE TITLE
gossipsub/tests: Remove `derive-builder` dependency

### ISSUE THREAD

**Issue by mxinden** [libp2p/rust-libp2p#3228]
Let's try to remove the `derive-builder` dependency in `libp2p-gossipsub`. It is only used in tests and thus likely doesn't warrant a dedicated dependency.

https://github.com/libp2p/rust-libp2p/issues/3177

**Comment by StemCll** [comment]
Hi @mxinden :wave: 
I've started to work on this issue. I'm planning to make it similar as [GossipsubConfigBuilder](https://github.com/libp2p/rust-libp2p/blob/master/protocols/gossipsub/src/config.rs#L408) is handled. Do you have any suggestions here? 
Thanks
