### ISSUE TITLE
Add builder for tls and quic config

### ISSUE THREAD

**Issue by tthebst** [libp2p/rust-libp2p#3237]
## Description

Add a builder for the tls and quic config struct to make all (most) config struct fields configurable. Especially the `rustls::ClientConfig` and `rustls::ServerConfig`. 

## Motivation

I don't want to pass the private key to libp2p and this would allow me to specify `with_cert_resolver` and `with_client_cert_resolver` for `rustls::ServerConfig` to "hide" the private key. 

## Current Implementation

TlsConfig and QuicConfig constructer take a `Keypair` as an argument and create the rest with some default parameters.

## Are you planning to do it yourself in a pull request?

Yes

**Comment by thomaseizinger** [comment]
TLS needs to be configured in a very particular way to be compatible with our own spec. What would you like to change?

**Comment by tthebst** [comment]
I looked at the spec again and I would need two things: 
- Ability to provide the libp2p cert extensions. 
- Ability to set a custom `Libp2pCertificateVerifier`

By having a builder that allows for specifying ` rustls::ServerConfig` I could do this.

**Comment by thomaseizinger** [comment]
What are you trying to do? Both of these are critical for our TLS handshake.

**Comment by tthebst** [comment]
I want to authenticate peers with TLS with the following two constraints: 
1. No access to the host's private key -> Can't create a host's `Keypair`, but there is the ability to request the signing of messages. 
2. Verify the public key in the certificate against a list of allowed public keys. 

The two issues are orthogonal but could be achieved with a correctly configured `rustls::ServerConfig` and `rustls::ClientConfig`. But I'm also not fully familiar with libp2p and I just find out if libp2p would be a fit for my problem. Thanks for the fast replies!

**Comment by thomaseizinger** [comment]
> I want to authenticate peers with TLS with the following two constraints: 
> 1. No access to the host's private key -> Can't create a host's `Keypair`, but there is the ability to request the signing of messages.

Can you share more background on this? Is this going towards the key being on some HSM?

> 2. Verify the public key in the certificate against a list of allowed public keys.

You can always terminate the connection immediately afterwards. I am currently working on #2824 which makes this trivial.

**Comment by tthebst** [comment]
> Can you share more background on this? Is this going towards the key being on some HSM?

Similar. All private key operations are done in a separate process (maybe in the future inside an HSM). Therefore the private key is not available to other processes. I.e the process in which libp2p runs. 

> You can always terminate the connection immediately afterward. 

This is certainly also possible. My idea was to just implement `ServerCertVerifier` for a custom verifier that includes the check against the public key list.

**Comment by thomaseizinger** [comment]
> > Can you share more background on this? Is this going towards the key being on some HSM?
> 
> Similar. All private key operations are done in a separate process (maybe in the future inside an HSM). Therefore the private key is not available to other processes. I.e the process in which libp2p runs.

`libp2p-tls` was not designed with that in mind and I think also `rustls` does not support that? We are passing the private key on to `rustls`: https://github.com/libp2p/rust-libp2p/blob/c1e68b75c0729102ee43e2ec3cedc643b4d1f324/transports/tls/src/lib.rs#L56

You might have to write your own `libp2p-tls` module for this.
 
> > You can always terminate the connection immediately afterward. 
> 
> This is certainly also possible. My idea was to just implement `ServerCertVerifier` for a custom verifier that includes the check against the public key list.  

I don't think we will expose that bit because it makes it hard for us to provide a misuse resistant API. You can always fork `libp2p-tls` too and just plug in your fork when you compose a `Transport`. You might need to fork `libp2p-quic` too if you want to use it in there.

**Comment by tthebst** [comment]
Thanks for the response.

>  I think also rustls does not support that

Rustls supports this pretty well since everything in rustls is a trait [object](https://docs.rs/rustls/latest/rustls/sign/trait.Signer.html). 

> We are passing the private key

I think this is not the host's [private key](https://sourcegraph.com/github.com/libp2p/rust-libp2p/-/blob/transports/tls/src/certificate.rs?L54-L55). The host's private key is only used to sign the Libp2p certificate extension if I read the code correctly. 

I will probably need to create a small fork to support this. Feel free to close the issue. Thanks for the help.

**Comment by thomaseizinger** [comment]
Right, thanks for clarifying! I'll close this for now but please don't hesitate to come back with a PR if you have a proposal for how to change the API :)
