### ISSUE TITLE
Encapsulate relay::client::Connection into an Newtype type that only exposes `AsyncRead` and `AsyncWrite`

### ISSUE THREAD

**Issue by jxs** [libp2p/rust-libp2p#3255]
## Motivation

As per [#3238/files#r1050261660](https://github.com/libp2p/rust-libp2p/pull/3238#pullrequestreview-1220127936) `Connection` is a public enum variant with struct variants, any change to it becomes a subsequent breaking change.

## Desired changes

Encapsulate that one into an Newtype that only exposes `AsyncRead` and `AsyncWrite` as its interface:

- Rename the type to `ConnectionState` & make it private
- Create  a struct `Connection`  as Newtype that encapsulates `ConnectionState`.
- Move the AsyncRead and AsyncWrite implementations from the enum to the struct

this depends on https://github.com/libp2p/rust-libp2p/pull/3238/ as it renames `RelayedConnection` to `Connection` and is itself a breaking change. Probably should also wait on the discussion started on https://github.com/libp2p/rust-libp2p/pull/3221#issuecomment-1345552921.

CC @thomaseizinger 

## Are you planning to do it yourself in a pull request?

Yes if required.

**Comment by mxinden** [comment]
Sounds good to me. Thanks for documenting it.

**Comment by Danijel-Enoch** [comment]
Hello guys I am new to Open Source Contribution . Can I try this?

**Comment by thomaseizinger** [comment]
> Hello guys I am new to Open Source Contribution . Can I try this?

Sure thing! Let me know if you need more mentoring or any other help :)
Best to have a go yourself and open a draft PR if you get stuck, then we can discuss things there!

**Comment by Danijel-Enoch** [comment]
Thanks
 Would get started
