### ISSUE TITLE
swallowed errors, or escalating too quickly

### ISSUE THREAD

**Issue by rkuhn** [libp2p/rust-libp2p#3269]
https://github.com/libp2p/rust-libp2p/blob/13a59a38d3385b4c58ef6e0e77694881b46cb7dc/swarm/src/handler/one_shot.rs#L214-L219

@mxinden This is where incoming stream upgrade errors are lost, as mentioned in today’s meeting. #3128 somewhat intentionally did not fix this since the error is returned from `Apply`. Since there is no obvious need for more reaction, I’d propose to log inbound upgrade errors on debug level in the above spot.

In the above code snippet, outbound upgrade errors lead to closing the connection. I’m not sure whether that is the best possible response given that many protocols may be composed and thus the escalation’s scope seems too large.

**Comment by thomaseizinger** [comment]
Agree with all your points!

Related: https://github.com/libp2p/rust-libp2p/issues/2894

**Comment by mxinden** [comment]
> I’d propose to log inbound upgrade errors on debug level in the above spot.

Sounds good to me.

> In the above code snippet, outbound upgrade errors lead to closing the connection. I’m not sure whether that is the best possible response given that many protocols may be composed and thus the escalation’s scope seems too large.

Agreed. Setting its `keep_alive` to `False` should be enough.

In my eyes #2894 would reduce some of the error handling complexity in most `ConnectionHandler` implementations.
