### ISSUE TITLE
Don't depend on the multihash identity feature

### ISSUE THREAD

**Issue by thomaseizinger** [libp2p/rust-libp2p#3276]
This feature is broken and will be removed eventually. To avoid deprecation warnings for our users that they can't fix, let's remove it here first.

See:

- https://github.com/multiformats/rust-multihash/pull/260
- https://github.com/multiformats/rust-multihash/issues/194

**Comment by jmmaloney4** [comment]
In the [the Peer ID spec](https://github.com/libp2p/specs/blob/master/peer-ids/peer-ids.md#peer-ids), it states that "keys that serialize to at most 42 bytes _must_ be hashed using the identity multihash codec." With [the deprecation of the identity multi hash](https://github.com/multiformats/rust-multihash/issues/194), however, we need to change this spec, or lobby to keep the identity multihash.

In a review on my PR, @rkuhn [brought up some important cases](https://github.com/libp2p/rust-libp2p/pull/3311#discussion_r1064015542) where removing the identity multihash support would be problematic.

**Comment by thomaseizinger** [comment]
Sorry for the brevity in the issue. Yes we need to keep the functionality, it is only the implementation in `multihash` that is broken.

Given that the identity hasher doesn't actually do any hashing we can easily replicate this in here by checking the `code` manually for `0x0`. That is what needs to be done as part of this issue :)
