### ISSUE TITLE
Extend NetworkBehaviourAction to add and remove listeners

### ISSUE THREAD

**Issue by dariusc93** [libp2p/rust-libp2p#3291]
## Description

Extend `NetworkBehaviourAction` with `NetworkBehaviourAction::ListenOn` and `NetworkBehaviourAction::RemoveListener` to allow adding or removing a listener within the `NetworkBehaviour`

## Motivation
 

One project that I am working on is an attempt at connecting to a relay automatically, which could benefit from this by emitting an event to listen on the relay and be able to remove it by using the listener id later if needed (eg relay becoming unreliable). Current workaround is emitting an event which is then seen when polling the swarm to then listen to  (and soon remove)  the address there. 

## Are you planning to do it yourself in a pull request?

Maybe

**Comment by thomaseizinger** [comment]
Related: https://github.com/libp2p/rust-libp2p/issues/3040

I am in favor of this, I think it makes sense to offer all capabilities through `NetworkBehaviour` and slowly but surely shrink the public API of `Swarm`.
