### ISSUE TITLE
dcutr: Remove `ActionBuilder`

### ISSUE THREAD

**Issue by mxinden** [libp2p/rust-libp2p#3299]
In `libp2p-dcutr` we introduced `ActionBuilder` as events from the `ConnectionHandler` could not be enriched with the local node's external addresses from the `on_*` event handlers. Instead, one had to wait for the `NetworkBehaviour::poll` method to access the addresses.

https://github.com/libp2p/rust-libp2p/blob/68d0f882bd7fc0b4a83a11d0d034ae9f085f3e62/protocols/dcutr/src/behaviour_impl.rs#L349-L363

Now that https://github.com/libp2p/rust-libp2p/pull/3153 is merged, event handlers have access to the external addresses right away, thus the `ActionBuilder` abstraction is no longer needed. Let's remove it.

**Comment by thomaseizinger** [comment]
Done in https://github.com/libp2p/rust-libp2p/pull/3304.
