### ISSUE TITLE
Manage an initial delay before the first mdns query is sent on an interface

### ISSUE THREAD

**Issue by stormshield-pj50** [libp2p/rust-libp2p#3319]
## Description

Based on identify behaviour, manage an initial delay before the first mdns query is sent on an interface.

## Motivation

In a docker environment, the first mdns query can be lost if the interface is not ready yet. As the interval query is by default rather large (5 minutes), using an initial delay before the first mdns query is sent would improve the speed of peers discovery.

## Current Implementation

No way to configure an initial delay.

## Are you planning to do it yourself in a pull request?

Yes

**Comment by thomaseizinger** [comment]
Interesting, I wonder if we can be more a bit more clever here.

Would it make sense to retry sending the first packet on a more frequent interval if we don't get a response within X seconds? We'd have to be careful to not spam the network too much so a max number of retries is probably a good idea.

**Comment by stormshield-damiend** [comment]
Indeed this is a good idea. We already have the work done for an initial_delay configuration token (as in identify) and will submit a PR soon. This is sufficient to fix our issue in docker, feel free to duplicate or create another issue for the iterative query at start.
