### ISSUE TITLE
Is secure WebSocket transport even working?

### ISSUE THREAD

**Issue by melekes** [libp2p/rust-libp2p#3330]
## Summary

So I'm currently debugging https://github.com/paritytech/substrate/issues/12024 and what I found is I don't really understand how secure WS transport (/wss) is supposed to work.

I give it an address like `/dns/polkadot-boot.dwellir.com/tcp/443/wss/p2p/<nodeID>` and expect it to connect. However, I get an error saying `invalid multi-address: /dns/polkadot-boot.dwellir.com/tcp/443/p2p/<nodeID>` address is invalid from inner TCP transport. Am I supposed to supply DNS as an inner transport if I want to support `/wss` addresses? Documentation is rather scarse.

## Expected behaviour

I'd expect for WSS transport to work kinda.

## Possible Solution

Use DNS transport as inner T when creating WSS transport.

## Version

0.50.0

## Would you like to work on fixing this bug?

Yes

**Comment by melekes** [comment]
Given https://github.com/paritytech/substrate/pull/13152 patch works, are you guys interested in me adding this to `WSConfig` documentation?

**Comment by mxinden** [comment]
For others that weren't there, we discussed this in the open maintainers call (https://github.com/libp2p/rust-libp2p/discussions/3332).

Suggestion in the call was to make `libp2p-websocket` no longer generic over the inner transport (`T`). Thinking about that some more, I am not sure how nicely this plays with configurations on the inner transport `T`, namely the configuration for `libp2p-dns` and `libp2p-tcp`.

An alternative might be to add a doc test, showcasing how to properly combine `libp2p-websocket` with other transports of which at least they contain `libp2p-tcp`.

Help welcome!

**Comment by thomaseizinger** [comment]
> the configuration for `libp2p-dns` and `libp2p-tcp`.

We could always accept those two config objects as parameters but also implement `Default` on the transport.
