### ISSUE TITLE
Create a script for recursive version bumping across the workspace

### ISSUE THREAD

**Issue by thomaseizinger** [libp2p/rust-libp2p#3348]
## Description

This issue tracks the creation of the script described in https://github.com/libp2p/rust-libp2p/issues/2902#issuecomment-1386915928.

The interface should look like this:

```sh
scripts/bump-version.sh <workspace-crate> <level>
```

For example:

```sh
scripts/bump-version.sh libp2p-core minor
```

The script needs to:

1. Use `cargo release version` to bump the specified crate by the provided level
2. Figure out, which workspace crates depend on this crate
3. Bump the version of those crates by the same level
4. Repeat (2) + (3) if new crates have been affected

As an example:

1. Issue a minor level bump for `libp2p-core`
2. `libp2p-swarm` depends on `libp2p-core` so it needs to be bumped by a minor level as well
3. `libp2p-identify` depends on `libp2p-swarm` so it also needs to be bumped by a minor level
4. `libp2p-metrics`  so it also needs to be bumped by a minor level
5. `libp2p-metrics` depends on `libp2p-identify` but also on `libp2p-core` so it would have already been bumped as part of (2) and should not be bumped again

To generalize the whole thing, one could introduce a configuration file in which one can specify, which version bumps end up "bubbling up" (which at the end of the day can be figured out by checking which ones appear in the public API).

Related https://github.com/crate-ci/cargo-release/issues/628.

## Motivation

Make version bumping as part of PRs and/or releases less manual and error-prone.

## Are you planning to do it yourself in a pull request?

Maybe.

**Comment by thomaseizinger** [comment]
Tagging this as `difficulty:easy` because it requires no knowledge of `rust-libp2p` internals and only shell-scripting skills.

**Comment by mxinden** [comment]
With humanities next big step in mind, namely to move off of bash scripts, I would not be opposed to using Python instead of Bash here.

**Comment by thomaseizinger** [comment]
I guess it will be more complicated than calling a few binaries and piping them together so perhaps a more capable language would be good yes.

If it can be done with just pipes and filters, I am not opposed to a bash solution.

**Comment by thomaseizinger** [comment]
Perhaps https://github.com/matklad/cargo-xtask/ is the way to go here.

**Comment by thomaseizinger** [comment]
I am closing this because now that we have #3715, this isn't actually a problem anymore.
