### ISSUE TITLE
Add a "channel" transport for testing purposes

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#335]
Using local TCP sockets in order to test a higher-level protocol is not very convenient.

Instead I suggest to add in `core` a way to do this: `let (tx, rx) = transport_channel();`
Once the channel is established, you can dial from `tx` and listen from `rx` in order to establish a bidirectional stream between the two.

The question of which multiaddress they accept is a bit tricky. They could accept all addresses automatically, but that would be a bit weird.

**Comment by twittner** [comment]
How about adding `/memory` to multiaddr and proposing it for inclusion?
