### ISSUE TITLE
Move away from `actions-rs/cargo`

### ISSUE THREAD

**Issue by thomaseizinger** [libp2p/rust-libp2p#3398]
## Description
The one feature we are currently getting from this action is check annotations as part of the pull request. We can replace this with something like: https://github.com/r7kamura/rust-problem-matchers. There might be better options out there.

There was a feature-request for `dtolnay/rust-toolchain` to add this but it was denied: https://github.com/dtolnay/rust-toolchain/issues/50

## Motivation

For the same reason as moving away from `actions-rs/toolchain`. See #3352.

## Are you planning to do it yourself in a pull request?

No.

**Comment by PopBogdan97** [comment]
Hi, I would like to help but I am quite new to contributing to open source projects. Can I give it a try?

**Comment by thomaseizinger** [comment]
> Hi, I would like to help but I am quite new to contributing to open source projects. Can I give it a try?

Definitely!

Let me know if you need any more help than what is described in the issue :)
As a starting point, [these](https://github.com/libp2p/rust-libp2p/tree/master/.github/workflows) are the files you want to have a look at.

For some early feedback, it is best to open a pull request, even if things are not working and then we can discuss on there!
