### ISSUE TITLE
Potentially unwoken tasks in `quic` and `web-rtc`

### ISSUE THREAD

**Issue by vnermolaev** [libp2p/rust-libp2p#3400]
## Description
A potentially unwoken task In the `quick` and `web-rtc` transports:

@thomaseizinger [sketched](https://github.com/libp2p/rust-libp2p/pull/3361#discussion_r1084685662) a scenario triggering such a behaviour:
> - Assume 1 active listener
> - Assume the listener had no work and returned `Pending`
> - We call `close` on the listener
> - Without an explicit waker, I believe the close will only happen once the listener gets polled again due to another event

to address: 

>
> We can move forward here by just adding the waker. Worst case, we have an unnecessary wake-up.
>
>    - Make a new field inside the listener, holding an `Option<Waker>`
>    - Call it `close_listener_waker`
>    - Set it before you return `Poll::Pending` at the bottom
>    - Use take to remove the listener within close and if it is present, call wake on it

## Current Implementation

Affected transports:
> Yes you are right. Would you be interested in doing patches to fix them there as well (in separate PRs; namely for `libp2p-quic` and `libp2p-webrtc`)?

## Are you planning to do it yourself in a pull request?
Yes

**Comment by mxinden** [comment]
With the above pull requests merged, I am closing here. Thanks @vnermolaev for debugging and providing a patch! Great work.
