### ISSUE TITLE
Kademlia tries to connect to the local node

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#341]
A Kademlia query can learn about the local node through the process, and request that we connect to the local node. This is obviously not great.

However the fix is maybe not as straight forward as `if requested_peer == local { continue }`, because opening a Kademlia query with the local node essentially means that we need locally-available information.

This needs some thoughts.

**Comment by tomaka** [comment]
Some update. Now that Kademlia has been correctly reworked, this is no longer an issue.
However we should still add checks to filter out our local node from results coming from other nodes.
In particular, we don't want to emit `Discovered` events and add elements in `untrusted_addresses` about our local node.

**Comment by romanb** [comment]
Closed by https://github.com/libp2p/rust-libp2p/pull/1097.
