### ISSUE TITLE
quic: implement stateless resets

### ISSUE THREAD

**Issue by marten-seemann** [libp2p/rust-libp2p#3419]
QUIC uses Stateless Resets to quickly recover from node crashes / reboots: https://datatracker.ietf.org/doc/html/rfc9000#name-stateless-reset

This is supported by `quinn` using the `new` constructor of `EndpointConfig`. See https://docs.rs/quinn/0.10.2/quinn/struct.EndpointConfig.html#method.new.

Instead of using `EndpointConfig::default`, we should use the `new` constructor here: https://github.com/libp2p/rust-libp2p/blob/e36e8ce4456ff059dd54614913b521194d2d478c/transports/quic/src/config.rs#L131

To make the key survive crashes / reboots, we should derive it from the identity key. This is also what `go-libp2p` does, see https://github.com/libp2p/go-libp2p/blob/ac038dbf2d38b17b9079ec10124fa6935ad1b7dc/config/quic_stateless_reset.go#L16-L27.

**Comment by thomaseizinger** [comment]
Should work with our new QUIC implementation because we now use `quinn` directly: https://github.com/quinn-rs/quinn/issues/1443

**Comment by marten-seemann** [comment]
Just out of curiosity, how do you configure the reset key?

**Comment by thomaseizinger** [comment]
Good catch, I didn't read the issue clearly enough. We don't expose that yet so there is more work to do here. My first idea would be to not make it configurable but derive it deterministically from our identity key. Thoughts on that?

**Comment by marten-seemann** [comment]
There's no need to make it configurable. It does need to survive host reboots, so deriving it from the node's private key sounds like a reasonable approach.

Here's our current implementation: https://github.com/libp2p/go-libp2p/blob/ac038dbf2d38b17b9079ec10124fa6935ad1b7dc/config/quic_stateless_reset.go#L16-L27
Some discussion on that design: https://github.com/libp2p/go-libp2p-quic-transport/pull/122

**Comment by thomaseizinger** [comment]
> It does need to survive host reboots

That is what I figured.

> deriving it from the node's private key sounds like a reasonable approach.

Great, thanks for the confirmation! I'll update the issue description :)

**Comment by jxs** [comment]
How should we get the private key from the `Keypair`? We can `match` on all of the key types, and call `secret()` but then how should we handle RSA?

**Comment by thomaseizinger** [comment]
I think ideally, we add functionality to our keypair that is an arbitrary KDF. In other words, given a certain domain separator, derive some secret bytes from the secret key.

Given that we only have the signing operation available for RSA, there is little we can do here and I think we should simply fail in that case, i.e. return a `Result`.

I toyed with the idea of abusing the `sign` function with a static randomness and message to "derive" a secret. This is dangerous though. AFAIK, RSA signatures heavily depend on secure randomness to not leak the key between multiple messages. Thus, handing out the key unaltered would make it possible to reverse-engineer the key if you are given the derived key.

However, if we use a proper KDF like [HKDF](https://docs.rs/hkdf/0.12.3/hkdf/), I think we should be fine on that front. The signature would only be used as IKM and be irretrievably obfuscated by multiple rounds of hashing and never exposed directly. Thus, as long as `sha-256` is not broken, we should be fine.

The API I am imagining is:

```rust
impl Keypair {
	pub fn derive_secret(&self, domain: &[u8]) -> [u8; 32];
}

let secret = keypair.derive_secret(b"QUIC_RESET_KEY");
```

**Comment by thomaseizinger** [comment]
As a first version though, we can just only support stateless resets when we have a keypair that gives us access to the secret bytes and make the key derivation an implementation detail of the QUIC module for now!

**Comment by jxs** [comment]
Sorry Thomas, haven't had time to look into this yet, but what you have just added makes it easier, so wdy suggest doing in case of RSA, panicking? As the [`new` function doesn't return `Result`](https://github.com/libp2p/rust-libp2p/blob/e36e8ce4456ff059dd54614913b521194d2d478c/transports/quic/src/transport.rs#L87)

**Comment by thomaseizinger** [comment]
> Sorry Thomas, haven't had time to look into this yet

No worries! :)

> but what you have just added makes it easier, so wdy suggest doing in case of RSA, panicking? As the [`new` function doesn't return `Result`](https://github.com/libp2p/rust-libp2p/blob/e36e8ce4456ff059dd54614913b521194d2d478c/transports/quic/src/transport.rs#L87)

Yeah I think that is a good way forward:

- Use `Keypair::type` to figure out which keypair we are
- If we are a "compatible" one, i.e. not RSA, extract the secret key by converting to a concrete one via `try_into()`
- Deterministically derive a reset key via an HKDF

If we are on RSA, we can log a warning that stateless resets are not going to work!
