### ISSUE TITLE
Yamux drops data when closed

### ISSUE THREAD

**Issue by Mubelotix** [libp2p/rust-libp2p#3483]
## Summary

I rely heavily on [MemoryTransport](https://github.com/libp2p/rust-libp2p/blob/d79c93abdb8a6afd625813202014ac9b96bcc2ff/core/src/transport/memory.rs#L95) for integration tests of a custom protocol. I have reasons to believe that the implementation of MemoryTransport doesn't flush the data appropriately and randomly discards data if closed too early after it was written.

Here is what my code is doing:

A node sends data to another

```rust
// https://github.com/Mubelotix/kamilata in file tasks/request_handler.rs line 58
stream.start_send_unpin(data).unwrap();
stream.flush().await.unwrap();
trace!("{our_peer_id} Sent the data to {remote_peer_id}.");
// stream is dropped here
```

While the other receives the data

```rust
// https://github.com/Mubelotix/kamilata in file tasks/request_maker.rs line 30
let data = match stream.next().await {
    Some(Ok(data)) => data,
    w => warn!("{our_peer_id} Error while receiving response from {remote_peer_id}: stream closed {w:?}"),
};
```

## Expected behaviour

Since I send and flush the outbound stream, the inbound stream should be able to receive the data before the stream is closed.

## Actual behaviour

The stream is closed before the data can be received.

<details><summary>Debug Output</summary>
<p>

50% of the time, I obtain the following logs on my machine:
It fails 95% on github's CI machines.

```log
[TRACE kam::tasks::request_handler] client 3 Sent data to client 1.
[WARN kam::tasks::request_maker] client 1 Error while receiving response from client 3: stream closed None
```

</p>
</details>

## Notes

I'm not 100% sure this comes from the MemoryTransport itself. Note that I use `KadOutStreamSink` and `KadInStreamSink` to stream data. Either way, this could be related to #1053

See the CI of [my project at commit 58cf168](https://github.com/Mubelotix/kamilata/actions/runs/4212021076/jobs/7310755183#step:6:320) for more logs and hopefully a way to reproduce.

## Version

- libp2p version 0.50.0

## Would you like to work on fixing this bug?

Maybe (depends on where the bug actually comes from)

**Comment by mxinden** [comment]
Thanks for the elaborate report @Mubelotix. Couple of questions:

- Are you able to reproduce this deterministically?
- Are you seeing these issues with both Yamux and Mplex? What if you disable one here https://github.com/Mubelotix/kamilata/blob/87e88a03cdb129924b0420c9f4996fa3a084afcd/tests/common/client.rs#L29-L32?
- Does the same happen when you use TCP?

**Comment by Mubelotix** [comment]
I was able to reproduce with Yamux and TCP, but it never occurred with Mplex. It seems I was wrong suspecting MemoryTransport. Testing this is awful and requires a lot of patience and luck. I was unable to create a minimal and reliable testing environment.

**Comment by Mubelotix** [comment]
Closing until someone is able to confirm
