### ISSUE TITLE
identify: remove initial delay

### ISSUE THREAD

**Issue by thomaseizinger** [libp2p/rust-libp2p#3485]
## Description

`libp2p-identify` has an initial delay of 500ms after a connection has been established before it runs the identify protocol. This seems unnecessary to me.

The origin of this goes back to the version introduction of the protocol to the codebase: https://github.com/libp2p/rust-libp2p/commit/9d9121719308491358ae6e4b0be83cdffa992985

Whatever the reasons were back then, I don't see why a remote wouldn't be able to instantly answer an identify request the moment a connection is established.

@mxinden Do you remember why this was introduced?

## Motivation

- Remove unnecessary cruft
- Speed up applications: Some may depend on identify information being available before they perform other tasks

## Are you planning to do it yourself in a pull request?

Maybe.

**Comment by mxinden** [comment]
> @mxinden Do you remember why this was introduced?

I don't know unfortunately.

I am in favor of this proposal.

**Comment by PopBogdan97** [comment]
I can try to tackle this issue. 
However, do you want to completely remove the `initial_delay` option or keep the option and just speed the application without any initial delay?

**Comment by mxinden** [comment]
I suggest completely removing the delay. Thank you @PopBogdan97 :pray:

**Comment by thomaseizinger** [comment]
Removing the field will be a breaking change for the identify protocol. I would suggest that in a first step, we only apply the `deprecated` attribute and set the value to `0`.
