### ISSUE TITLE
refactor `gossipsub`: make modules private

### ISSUE THREAD

**Issue by StemCll** [libp2p/rust-libp2p#3494]
## Description

As described [in this comment](https://github.com/libp2p/rust-libp2p/pull/3303#discussion_r1084698192):
- [ ] `protocol` - [PR](https://github.com/libp2p/rust-libp2p/pull/3495)
- [ ] `metrics` - [PR](https://github.com/libp2p/rust-libp2p/pull/3565)
- [ ] `subscription_filter` - [PR](https://github.com/libp2p/rust-libp2p/pull/3566)
- [ ] `time_cache` - [PR](https://github.com/libp2p/rust-libp2p/pull/3564)

## Are you planning to do it yourself in a pull request?

Yes

**Comment by tcoratger** [comment]
@thomaseizinger Is there an associated PR closed? Is it work in progress @StemCll ? After the work on `kad` modules in #3738, this seems straightforward to go through `gossipsub` ones, what do you think?

**Comment by thomaseizinger** [comment]
> @thomaseizinger Is there an associated PR closed? Is it work in progress @StemCll ? After the work on `kad` modules in #3738, this seems straightforward to go through `gossipsub` ones, what do you think?

There are 4 PRs linked in the description (all labeled `PR`) but I think @StemCll currently doesn't have the capacity to work on them. Feel free to take over! I think a single PR would be best.

**Comment by tcoratger** [comment]
@thomaseizinger Understood, will start working on that in the upcoming days.
