### ISSUE TITLE
kad: remove `allow_listening` handler config

### ISSUE THREAD

**Issue by thomaseizinger** [libp2p/rust-libp2p#3499]
_Originally posted by @mxinden in https://github.com/libp2p/rust-libp2p/pull/3254#discussion_r1111806268_

The `allow_listening` config option in Kademlia does nothing as it is always set to `true`. We should remove it.

**Comment by chirag-bgh** [comment]
Can I take this?

**Comment by thomaseizinger** [comment]
Definitely! :)

**Comment by thomaseizinger** [comment]
Outdated with the latest kad client/server mode implementation.
