### ISSUE TITLE
examples: Add quic to the example chat-tokio

### ISSUE THREAD

**Issue by yellowred** [libp2p/rust-libp2p#3501]
## Description

Currently, there is no example of how to start a node with QUIC. I suggest adding a new example `chat-tokio-quic` that uses `OrTransport` pattern to start a node with QUIC listener. There is a related issue https://github.com/libp2p/rust-libp2p/issues/3143, but looks like it's feature request is too broad.

## Motivation

It would be great for new starters to have a Chat App example with QUIC protocol. Right now everybody has to learn how to use QUIC from smoke tests just to try it out.

## Are you planning to do it yourself in a pull request?

Yes.

**Comment by mxinden** [comment]
I would prefer for the examples to be focused on one thing, e.g. in the case of chat-tokio how to build a chat with `tokio`. I would prefer a separate example or method that combines all transports (https://github.com/libp2p/rust-libp2p/issues/3143) among others QUIC.

**Comment by yellowred** [comment]
My point is that tokio and quic are two very important features of libp2p and should be clearly showcased. But I am fine with multi-transport example as long as other pieces are easy to add for those who needs them.

**Comment by thomaseizinger** [comment]
Thanks for wanting to improve `rust-libp2p` and sorry that the examples are a bit of a mess. My vision for fixing this is written down here: https://github.com/libp2p/rust-libp2p/issues/3111

Unfortunately, I haven't had time to work on this lately so any help is much appreciated!

Once #3111 is in place, I'd like to have more focused examples with less repetition amongst themselves.

Also, with the latest changes to the `Swarm` API (https://github.com/libp2p/rust-libp2p/issues/3068) the value of the chat-tokio example is questionable at best as there are (hopefully?) no more foot-guns in using `rust-libp2p` with tokio.

**Comment by yellowred** [comment]
@thomaseizinger Since we merged #3111, I wonder if I should add Quic as OrTransport to the chat-example or it has a place in `development_transport`?

**Comment by thomaseizinger** [comment]
> @thomaseizinger Since we merged #3111, I wonder if I should add Quic as OrTransport to the chat-example or it has a place in `development_transport`?

Let's add it to the chat example first. I am not quite sure what to do with `development_transport` yet. Ideas welcome!

**Comment by yellowred** [comment]
@thomaseizinger Added it here https://github.com/libp2p/rust-libp2p/pull/3635. The instantiation was copied from the smoke tests. Let me know if there is a better way of doing it.

**Comment by thomaseizinger** [comment]
Done in https://github.com/libp2p/rust-libp2p/pull/3635.
