### ISSUE TITLE
Non-semantic `libp2p-webrtc=0.4.0-alpha.2`

### ISSUE THREAD

**Issue by ppodolsky** [libp2p/rust-libp2p#3505]
@mxinden Sorry for disturbance, I do not know where to report it properly. Feel free to close this issue after reading.
Seems that non semantic version release that you have just done (libp2p-webrtc=0.4.0-alpha.2) may break Cargo beyound any possibity to repair

I've just tried to revert back and pin versions after `cargo update` with the following command: `cargo update -p libp2p-webrtc --precise 0.3.0`
but it said
`error: failed to select a version for the requirement libp2p-webrtc = "^0.4.0-alpha"` (no `.2` in the end of version)
Probably, tooling cannot deal with this version. So I can build nothing right now, unfortunately, cargo brings back this alpha version no matter how I'm trying to pin it.

**Comment by ppodolsky** [comment]
Tracked down issue to libp2p-tls crate. If I set libp2p-tls = "=0.1.0-alpha" in my Cargo.toml, Cargo downloads libp2p-tls = `0.1.0-alpha.2` anyway.

**Comment by mxinden** [comment]
@ppodolsky can you point me to something where I can reproduce the failures you are seeing?

**Comment by ppodolsky** [comment]
> @ppodolsky can you point me to something where I can reproduce the failures you are seeing?

Yeah, just create an empty project with only dependence: 
```
libp2p-tls = "=0.1.0-alpha"
```
and do `cargo update` / `cargo build`.
It downloads .2 version which breaks build further.

**Comment by mxinden** [comment]
> `libp2p-tls = "=0.1.0-alpha"`

In an empty project on my machine, this indeed builds `0.1.0-alpha`. If I set it to `libp2p-tls = "=0.1.0-alpha.2"` it builds `0.1.0-alpha.2`.

**Comment by ppodolsky** [comment]
Well, I did the same and it was working too. But I can't get this working anyway:
```
git clone -b feature/summa https://github.com/izihawa/iroh
cd iroh
cargo build
```
libp2p-tls pinned to 0.1.0-alpha in the root file, but in Cargo tree I see that:
0.1.0-alpha.2 brought by libp2p-quic=0.7.0-alpha.2 (which is also pinned to 0.7.0-alpha in Cargo.toml)

**Comment by ppodolsky** [comment]
If this is working for you too, let's say it is caching issue in crates.io :/

**Comment by nazar-pc** [comment]
I noticed a similar situation in the past, Cargo always seems to install latest pre-release version, I was already bitten by this when using pre-release versions of actix-web. I don't think this is libp2p's issue.

**Comment by thomaseizinger** [comment]
With https://github.com/libp2p/rust-libp2p/pull/3580 and https://github.com/libp2p/rust-libp2p/pull/3584, this issue should no longer occur, thus closing here.
