### ISSUE TITLE
kademlia: shrink public API of `libp2p-kad`

### ISSUE THREAD

**Issue by thomaseizinger** [libp2p/rust-libp2p#3533]
## Description

Currently, `libp2p-kad` has several public modules like `handler` that don't need to be public. This makes it much more likely that a change is breaking in practice despite likely being irrelevant to users. See https://github.com/libp2p/rust-libp2p/pull/3504 for an example.

## Implementation suggestion

We want to ship this as a non-breaking change, thus we should adopt a similar approach as done in https://github.com/libp2p/rust-libp2p/pull/3238 where we first deprecate these modules with a note that they will be made private.

## Are you planning to do it yourself in a pull request?

No.

**Comment by umgefahren** [comment]
Should I get the grant filecoin-project/devgrants#1421, I would include that.

**Comment by tcoratger** [comment]
@thomaseizinger Does #3738 solve this issue or is this issue more global and it therefore corresponds to the complete removal of the public modules for the moment notified as deprecated in #3738?

**Comment by thomaseizinger** [comment]
It is resolved by #3738, well spotted!
