### ISSUE TITLE
Wrap quick-protobuf::Error

### ISSUE THREAD

**Issue by kckeiks** [libp2p/rust-libp2p#3534]
## Description

In #3312 we introduced a wrapper around the `quick-protobuf::Error` type but had to remove the wrapped error because it introduced a breaking change related to auto traits.

## Motivation

Provides more information about the error to users.

## Current Implementation

We're not using `quick-protobuf::Error`  as explained above.

## Are you planning to do it yourself in a pull request?

No.

**Comment by thomaseizinger** [comment]
Including this in `v0.52` milestone. Once we decide to make a breaking change, we can fix the above and wrap the error again.
