### ISSUE TITLE
multistream-select uses a fixed-length prefix of 1 instead of a varint

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#354]

**Comment by romanb** [comment]
Is this ticket still relevant?

**Comment by tomaka** [comment]
I guess no!

https://github.com/libp2p/rust-libp2p/blob/c6e8e6328ae15de27df64249be9085965ecf96fe/misc/multistream-select/src/length_delimited.rs#L179
https://github.com/libp2p/rust-libp2p/blob/c6e8e6328ae15de27df64249be9085965ecf96fe/misc/multistream-select/src/length_delimited.rs#L248-L252
