### ISSUE TITLE
ci: always run `cargo` with `--locked`

### ISSUE THREAD

**Issue by mxinden** [libp2p/rust-libp2p#3547]
## Summary

Since https://github.com/libp2p/rust-libp2p/pull/3399 we are tracking the `Cargo.lock` file via version control. Currently CI does not fail when the checked in `Cargo.lock` is not up-to-date.

## Possible Solution

Replace all `cargo XXX` with `cargo --locked XXX`.

Can you think of a simpler solution @thomaseizinger?

## Would you like to work on fixing this bug?

Yes

**Comment by thomaseizinger** [comment]
Good idea!

Maybe there is an env variable we can set?

**Comment by mxinden** [comment]
https://github.com/libp2p/rust-libp2p/pull/3562 does the change as a flag. I could not figure out how to do the same with an environment variable. @thomaseizinger let me know if this works for you.

**Comment by mxinden** [comment]
Closing here in favor of #3587
