### ISSUE TITLE
feat(multistream-select): Use `Version::V1Lazy` by default

### ISSUE THREAD

**Issue by mxinden** [libp2p/rust-libp2p#3563]
## Description

Current default is `Version::V1`. There is no practical downside to using [`Version::V1Lazy`](https://docs.rs/libp2p/latest/libp2p/core/upgrade/enum.Version.html#variant.V1Lazy). We should use it as a default.

See https://github.com/libp2p/rust-libp2p/pull/3749 for a previous attempt with some useful information on how to proceed.

## Motivation

0 RTT protocol negotiation when only one protocol is available.

## Are you planning to do it yourself in a pull request?

Maybe

**Comment by mxinden** [comment]
Documenting an out-of-band discussion with @thomaseizinger. We might as well be able to drop `Version::V1` and thus all of `Version` and always do `V1Lazy`. Worth exploring.

**Comment by MarcoPolo** [comment]
Am I correct in my understanding that without this, streams pay a 1 RT penalty right now in rust-libp2p, and thus not cheap? cc @mxinden

**Comment by thomaseizinger** [comment]
> Am I correct in my understanding that without this, streams pay a 1 RT penalty right now in rust-libp2p, and thus not cheap? cc @mxinden

At the moment, users need to configure that they want the 0RTT behaviour. Removing this configuration option and simply always doing it is what this issue is about.

**Comment by thomaseizinger** [comment]
I've tagged https://github.com/libp2p/rust-libp2p/pull/4120 as closing this one because the config option will no longer be available to users through this builder.

**Comment by thomaseizinger** [comment]
@mxinden Given that #4120 will make this the default for a lot of users, do you mind attempting to add the test that we discussed in #3749 just to be sure that we don't break anyone unnecessarily?
