### ISSUE TITLE
remove rustc-serialize

### ISSUE THREAD

**Issue by gnunicorn** [libp2p/rust-libp2p#359]
As the investigation of #358 [showed](https://circleci.com/gh/libp2p/rust-libp2p/2354), we still rely on the (long time) deprecated `rustc-serialize`-crate, primarily through the (also abandoned?) rust-crypto dependency.

There seem to be only a few reasonable to deal with this: replace rust-crypto alltogether, switch it over to a wasm-compatible fork like the one from buttercup or fork the project and maintain our own fork (as [removing rustc-serialize doesn't seem to be too hard](https://github.com/buttercup/rust-crypto-wasm/commit/17c2f937544a33dae4504b3d49a8f2b5704ad138)).

**Comment by dignifiedquire** [comment]
Note: https://github.com/RustCrypto has pretty much all of the things from rust-crypto ported and updated

**Comment by tomaka** [comment]
Done in #386 and #477
