### ISSUE TITLE
kad: Remove `UserData` and replace with `QueryId`

### ISSUE THREAD

**Issue by thomaseizinger** [libp2p/rust-libp2p#3607]
## Description

At the moment, the `libp2p-kad` `ConnectionHandler` is generic over `TUserData`. In practise, this type variable is always set to `QueryId`.

The `handler` module is currently public, meaning this is a breaking change.

## Motivation

Simplify code.

## Are you planning to do it yourself in a pull request?

Maybe.

**Comment by drHuangMHT** [comment]
Can we make tracking progress of a query easier? It's a little troublesome to listen to events emitted by the behaviour and route the result accordingly.

**Comment by thomaseizinger** [comment]
> Can we make tracking progress of a query easier? It's a little troublesome to listen to events emitted by the behaviour and route the result accordingly.

This sounds like an unrelated issue to me, can you open a separate one please?

**Comment by mxinden** [comment]
Adding `easy`, `help-wanted` and `getting-started` here.
