### ISSUE TITLE
Allow converting ed25519::Keypair to enum Keypair

### ISSUE THREAD

**Issue by creativcoder** [libp2p/rust-libp2p#3618]
## Description

Add a From impl for libp2p::core::identity::Keypair for struct ed25519::Keypair.

## Motivation

This is from our use case in [forest](https://github.com/ChainSafe/forest/blob/6b8a3cf0db4313ea1efb4f4577622234ee91e5fb/forest/daemon/src/daemon.rs#L90), we require converting a `ed25519::Keypair` struct to the enum `libp2p::core::identity::Keypair`. It would be helpful to have `From` impl for Keypair.

## Requirements

1.
2.
3.

## Are you planning to do it yourself in a pull request?

Yes

**Comment by thomaseizinger** [comment]
That makes sense, happy to accept a PR.
