### ISSUE TITLE
protocol mod has a name clash with the protocol crate, which could lead to confusion

### ISSUE THREAD

**Issue by jamesray1** [libp2p/rust-libp2p#362]
I suggest to rename it. This is in https://github.com/libp2p/rust-libp2p/tree/master/kad/src. However, I guess it's not necessary since you would have to use `extern crate protocol` to import protocol, and only then would there be a name clash if you wanted to do this and use the protocol mod in the kad crate. Then again, that may be needed in crates that use the kad crate and the protocol crate, if not in either of the two.

**Comment by gnunicorn** [comment]
The `mod protocol` isn't `pub` in the `kad`-crate though, you can't import it from outside (no `use kad::protocol`) and even if you did, the rust compiler will error if you import two modules with the same name and then you could just import it through an alias (`use kad::protocol as kad_protocol`) and be done with it.

Considering how many crates contain a `protocol` in general, there is no point in renaming things to prevent clashes. Rust's solution is sufficient to circumvent this problem.
