### ISSUE TITLE
Re-export `Either` type for better DX

### ISSUE THREAD

**Issue by bajtos** [libp2p/rust-libp2p#3622]
## Description

In https://github.com/libp2p/rust-libp2p/pull/3337, `EitherError` was replaced with `either::Either`. This is fine, except that libp2p does not re-export the `Either` type, and therefore libp2p consumers have to add `either` to their dependencies. It's a bit of maintenance overhead and a risk of a versioning conflict.

I propose re-exporting the entire `either` crate from `libp2p`. 

This will also simplify the upgrade path from v0.50 to v0.51.

```diff
- use libp2p::core::either::EitherError;
+ use libp2p::core::either::Either;
```

## Are you planning to do it yourself in a pull request?

Yes, I am happy to contribute a pull request if we agree this is a change you will accept.

Should we export `either` as `libp2::core::either` or `libp2p::either`?

**Comment by thomaseizinger** [comment]
Given that `either` is already > 1.0 I am tempted to say that depending on it yourself is the way to go.

**Comment by drHuangMHT** [comment]
Consider closing this issue?
