### ISSUE TITLE
Confusing/unclear comment on creating a KadConnecConfig

### ISSUE THREAD

**Issue by jamesray1** [libp2p/rust-libp2p#363]
Not sure if this is a good way to create a KadConnecConfig, but otherwise I don't know of a better way, if any. https://github.com/jamesray1/rust-libp2p/blob/a0601a0b0893bacc279e0d59b147cb07918c0ebb/gossipsub/src/lib.rs#L110. PS I tried IRC a couple of times but nobody was online, and it seems that unlike Gitter two people need to be online at the same time to have a convo. Creating a gitter room for gossipsub would probably be more appropriate.

Context:
- https://github.com/libp2p/rust-libp2p/blob/7507e0bfd9f11520f2d6291120f1b68d0afce80a/kad/src/lib.rs#L27
- https://github.com/libp2p/rust-libp2p/blob/e0d057a1a6b418deb6db1bc8f52dfba1cef8eaae/kad/src/kad_server.rs#L26-L64
- protocol mod

**Comment by tomaka** [comment]
> PS I tried IRC a couple of times but nobody was online, and it seems that unlike Gitter two people need to be online at the same time to have a convo.

People usually leave an IRC client open at all time. I'm in #libp2p on freenode with a lot of people related to libp2p development.

**Comment by jamesray1** [comment]
I don't know if it's because of the time difference, but no one is on that channel right now. Leaving the computer on all the time is not energy efficient.

**Comment by jamesray1** [comment]
It's taking me a long time to get my head around how to implement this.

At the moment what I have implemented includes:

```
        let transport = TcpConfig::new()
            .with_upgrade({
                let upgrade = SecioConfig {
                // See the documentation of `SecioKeyPair`.
                key: ed25519_generated().unwrap(),
            }).unwrap();

            upgrade::map(upgrade, |out: SecioOutput<_>| out.stream).unwrap()
        });
       let kad_connec_config = KadConnecConfig::new();
       let kad_connec_config_transport = kad_connec_config
            .upgrade(transport, (), Dialer, Future::/ip4/0.0.0.0/tcp/0).unwrap();
```
Future::/ip4/0.0.0.0/tcp/0 is not quite right, but I'm not sure what to put for an appropriate instance of a MultiAddrFuture. I think it would be good to have struct types for different MultiAddrs, e.g. ip/.../tcp/... parses to IpTcpMultiAddr, etc.

**Comment by jamesray1** [comment]
A

**Comment by tomaka** [comment]
Sorry if the documentation and examples are not the greatest at the moment.
I'm a bit confused, if your objective is to implement gossip then I don't think you need to interface with Kademlia at all.

**Comment by jamesray1** [comment]
For [gossipsub](https://github.com/vyzo/gerbil-simsub#the-gossipsub-protocol) and [episub](https://github.com/libp2p/specs/blob/master/pubsub/gossipsub/episub.md) a DHT can be used for peer routing, i.e. 'the ability to look up addresses for peers'.

**Comment by tomaka** [comment]
Considering that the library has seen tremendous change since then, I'm going to close this issue!
