### ISSUE TITLE
gossipsub: refactor booleans in `Handler` to state machine

### ISSUE THREAD

**Issue by thomaseizinger** [libp2p/rust-libp2p#3655]
## Description

Currently, we use a combination of booleans and enums to represent how the remote peer supports gossipsub:

https://github.com/libp2p/rust-libp2p/blob/0e468655a4ebe2554a11403062311160aeec59bb/protocols/gossipsub/src/handler.rs#L109-L122

We can simplify this by narrowing down the possible state combinations. For example, currently the type system allows `peer_kind` to be `Some` and `peer_kind_sent` to be `true` which is not possible.

Something similar can likely be done with the current outbound stream and the `outbound_substream_establishing` flag. It could be an enum:

```rust
enum OutboundStream {
	Establishing,
	Some(S),
	None
}
```

## Motivation

- Less complexity in understanding the possible states of the handler
- Use the type system to our advantage

## Are you planning to do it yourself in a pull request?

No.

**Comment by Shubham8287** [comment]
looking to engage with libp2p, and would love to contribute to it or other beginner-friendly , If provided some help and pointers. Just wanted to ask if you are open for contribution as there is no Contribution.md

**Comment by thomaseizinger** [comment]
> looking to engage with libp2p, and would love to contribute to it or other beginner-friendly , If provided some help and pointers. Just wanted to ask if you are open for contribution as there is no Contribution.md

Definitely open to contributions, thank you!

Check out the issues labelled with `getting-started` and one that matches the difficulty you are after.

Writing a contribution guide is ironically also an open task: https://github.com/libp2p/rust-libp2p/issues/3743

**Comment by thomaseizinger** [comment]
I think @mxinden ended up fixing this particular issue in https://github.com/libp2p/rust-libp2p/pull/3625 so I am gonna close it.
