### ISSUE TITLE
Deprecate `mplex` module in `libp2p`

### ISSUE THREAD

**Issue by thomaseizinger** [libp2p/rust-libp2p#3677]
The recommended muxer (on top of single-stream transports like TCP) is yamux: https://github.com/libp2p/specs/blob/master/connections/README.md#interoperability

The API of our facade crate should represent the recommended modules that users should use. Currently, it still includes `mplex` but we don't recommend that anymore as `yamux` is strictly better.

To resolve this, we should mark the `mplex` module as `#[deprecated]` and encourage users to depend on it separately in case they need it.

This way, doing the "right" thing, (using yamux) is easy and the "wrong" thing (using mplex) is hard and annoying, which hopefully will discourage use. We don't want to make it impossible (yet) to use mplex to allow for legacy usecases.

The implementation should be done in a similar manner as https://github.com/libp2p/rust-libp2p/pull/3580.

**Comment by tcoratger** [comment]
I'll take this one :)
