### ISSUE TITLE
The Send/Sync situation

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#369]
Right now we use lots of `Box`es at various locations in the library, but most of them are not `Send` or `Sync`. This should be changed, or the boxes removed.

**Comment by tomaka** [comment]
The only `Box<Future>` left are in `protocols/observed` and `transports/websocket/browser`.

**Comment by romanb** [comment]
> The only Box<Future> left are in protocols/observed and transports/websocket/browser.

That code no longer exists. I think if there is something specific left to do here, we should create new issues that target specific uses of `Box`es. Feel free to reopen if you think this issue should still be kept open, despite its generality.
