### ISSUE TITLE
First outbound stream on WebRTC connection server side times out consistently

### ISSUE THREAD

**Issue by mxinden** [libp2p/rust-libp2p#3690]
## Summary

Using https://github.com/libp2p/universal-connectivity/pull/3, the first outbound substream always timeouts. When using libp2p-gossipsub as the first `NetworkBehaviour` that outbound substream drops the subscribe message to the remote.

```
[2023-03-27T18:00:16Z DEBUG libp2p_gossipsub::handler] Dial upgrade error: Protocol negotiation timeout.
```

## Version
Still need to write a reproducer. Posting here anyways for tracking purposes.

One can build a reproducer on top of https://github.com/libp2p/universal-connectivity/pull/3/commits/a8c18c84e5dcc6a76d22d3ec5bbd4e7af4d3a3d0.

Hacky solution for now is to retry on outbound substream dial upgrade error.

## Would you like to work on fixing this bug?

Maybe

**Comment by thomaseizinger** [comment]
In case the bug turns out to be in `webrtc` and not in our code, it is going to be difficult to fix because we can't upgrade at the moment. See https://github.com/libp2p/rust-libp2p/pull/3552.
