### ISSUE TITLE
Kademlia cannot find peer's own id

### ISSUE THREAD

**Issue by sgdxbc** [libp2p/rust-libp2p#3692]
## Summary

`Kademlia::get_closest_peers` never returns swarm's local peer id.

## Expected behaviour

```rust
let local_id = *swarm.local_peer_id();
swarm.behaviour_mut().kad.get_closest_peers(local_id.into()) == local_id  // omit event driven stuff
```

## Actual behaviour

Returned closest peer is always some remote peer id.

<details><summary>Debug Output</summary>
<p>

```
<output>
```
</p>
</details>

## Possible Solution

Not sure whether this behavior is intended. I do find related code that filter out local id from query responses, but I have not found any description in spec to ask for this behavior.

## Version

- libp2p version (version number, commit, or branch):
0.51.1

## Would you like to work on fixing this bug?

Yes (if it is actually a bug).

**Comment by dariusc93** [comment]
I believe this is intentional as it would not make sense to locate your own key using `Kademlia::get_closest_peers`.

**Comment by sgdxbc** [comment]
I don't understand why it would not make sense. The hash I pass in to `get_closest_peers` is a multihash of some data block, which is totally unrelated to peer id. I agree that the probability of hash colliding with peer id is negligible, but if local peer's id happens to be identical to that hash, it should be the closest by definition. And also, this behavior makes the query result from the peer itself diverge from the query result from any other peer in the network, which is unacceptable in my case.

**Comment by dariusc93** [comment]
This also apply in go-libp2p and js-libp2p where it would not yield one own peer id (at least i can confirm in go-libp2p). Although I dont know your use case for wanting to locate your own node from the same node, something like this would need to be discussed over at https://github.com/libp2p/specs

**Comment by sgdxbc** [comment]
Got it. Because there's inconsistency between spec and implementation I thought I should contact downstream first. Will further open issue for clarification in spec repo. Thanks for helping.
