### ISSUE TITLE
Unnecessary allocation in autonat Behaviour::add_server

### ISSUE THREAD

**Issue by dariusc93** [libp2p/rust-libp2p#3733]
## Summary

I've been noticing high memory usage while using libp2p (which may vary at times) and decided to inspect what may be going on. After letting one project one for several hours and seeing high memory usage, one thing I've noticed is that when it adds a server to Autonat via `Behaviour::add_server` that it pushes the `PeerId` into a `Vec`, which does not performs any check to determine if the peer already exist already or remove the peer later on, which may be causing unnecessary insertion into the `Behaviour::servers` (see below). Not sure if its intended to be designed this way though, however this seem to be more noticeable over time if one add a peer when receiving an `Event::Received` from `Identify` after checking to determine if the peer contains the autonat protocol (which may actually not be necessary anymore on my part), which would happen each time the peer sends the event. 

(snippet of code I use when getting a `Event::Received`)
```rust
if protocols
        .iter()
        .any(|p| p.as_bytes() == libp2p::autonat::DEFAULT_PROTOCOL_NAME)
    {
        for addr in listen_addrs {
            self.swarm
                .behaviour_mut()
                .autonat
                .add_server(peer_id, Some(addr));
        }
    }
```

https://github.com/libp2p/rust-libp2p/blob/6e93df79ae2a845760fe90d206cb6814b9542387/protocols/autonat/src/behaviour.rs#L268-L273

![image](https://user-images.githubusercontent.com/3918024/229571054-57d4e0a3-2862-4739-9db9-668933e655ea.png)

## Possible Solution

1. Perform a check to determine if the `servers` field contains the `PeerId` before pushing into it; or
2. Use a `HashSet` instead of a `Vec`

## Version

- libp2p version (version number, commit, or branch): 0.51.2

## Would you like to work on fixing this bug?

Maybe

**Comment by mxinden** [comment]
Thanks for the debugging work @dariusc93!

> Use a `HashSet` instead of a `Vec`

Off the top of my head, this is the easiest fix. Mind sending in a pull request?
