### ISSUE TITLE
Kademlia::add_address return type is not exported (public)

### ISSUE THREAD

**Issue by b-zee** [libp2p/rust-libp2p#3737]
## Description

The [`libp2p::kad::Kademlia::add_address`](https://docs.rs/libp2p/latest/libp2p/kad/struct.Kademlia.html#method.add_address) method returns a `RoutingUpdate` type which a developer can not inspect.

## Motivation

Knowing whether the address was successfully added or not is useful information that can be logged or else acted upon.

## Requirements

1. Export the [`RoutingUpdate`](https://github.com/libp2p/rust-libp2p/blob/7c85f92e31771b89f109f2e069eb8d0fea56bbdb/protocols/kad/src/behaviour.rs#L3176) type for use outside users.

## Are you planning to do it yourself in a pull request?

Yes.

**Comment by thomaseizinger** [comment]
Happy to accept a PR yes.

Cross-referencing https://github.com/libp2p/rust-libp2p/pull/3735 which would have caught this issue.
