### ISSUE TITLE
docs: Write a contribution guide

### ISSUE THREAD

**Issue by thomaseizinger** [libp2p/rust-libp2p#3743]
We have the most basic information written in the PR template but there are other questions that our contributors often run into:

- We squash merge PRs, meaning we'd like to discourage force pushes the diff between pushes is easier to review this way for us.
- Explain the use of mergify and the `send-it` label
- Explain the use of convential commits for the PR title (which will become the commit after squashing)
- Explain how to write changelog entries (see docs/release.md)
- Explain how to bump versions (see docs/release.md)
- Perhaps simplify the PR template by pointing to these new guidelines instead

**Comment by thomaseizinger** [comment]
There is some more information in: https://github.com/libp2p/rust-libp2p/issues/2808

**Comment by p-shahi** [comment]
@thomaseizinger I can take this on if you don't mind

**Comment by thomaseizinger** [comment]
> @thomaseizinger I can take this on if you don't mind

That would be great!

**Comment by tcoratger** [comment]
@p-shahi If you need help here don't hesitate to tell me, I can have a look :)
