### ISSUE TITLE
core: make `upgrade::apply` an implementation detail of transport upgrades

### ISSUE THREAD

**Issue by thomaseizinger** [libp2p/rust-libp2p#3748]
## Description

Currently, we expose the generic `upgrade::apply` function. I'd suggest we make it an implementation detail and transition all usages to something else. The usages are only in tests and in `from_fn` (which I am suggesting to remove: https://github.com/libp2p/rust-libp2p/pull/3747).

## Motivation

Smaller, more focused API surface.

## Are you planning to do it yourself in a pull request?

Yes.

**Comment by thomaseizinger** [comment]
@mxinden please voice your opinion on this.

**Comment by thomaseizinger** [comment]
The order of things to achieve this is:

1. Remove the dependency of `upgrade::apply` from all current usages:
- #3770 
- #3771 
- #3768 
- #3773
- #3772
- Replace `apply_inbound` and `apply_outbound` in `swarm::Connection`
- Replace `apply_inbound` and `apply_outbound` in identify-tests
2. Make the current function crate private and expose a deprecated, public wrapper. Telling people that it is not meant to be used.
3. With the next series of breaking changes, remove the function

**Comment by mxinden** [comment]
Sorry for the late reply. Fine by me. Is the change worth the effort though? I would not give it a high priority.

**Comment by thomaseizinger** [comment]
> Sorry for the late reply. Fine by me. Is the change worth the effort though? I would not give it a high priority.

I think it is worth the effort but I agree that it is not high priority. I am working on it as a small side project. Plus, I think the linked changes are a net-positive by themselves.

**Comment by thomaseizinger** [comment]
Also, really what I am doing is resolving your TODO from a year ago: https://github.com/libp2p/rust-libp2p/commit/96dbfcd1ade6de5b4ae623f59fb0d67b2916576a#diff-f176cef6da6d32fd9e595a428f86a279f3d84f0a06e41ab3b98491737048a91eR30 :upside_down_face:
