### ISSUE TITLE
On multiplexing, there is no way to differentiate a negotiating connection from no connection at all

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#377]
The `InboundSubstream` trait resolves only when a connection has been successfully upgraded. Therefore there is no way to know whether we have an incoming connection that is in the process of being upgraded, or if we have no incoming connection.

Required for #355

**Comment by gnunicorn** [comment]
Similarly, we are dropping connections when the last known stream is dropped, even if there is still a pending incoming stream and never answer that incoming stream.

**Comment by tomaka** [comment]
No longer relevant after the new API (#565)
