### ISSUE TITLE
`SwarmBuilder` won't accept `connection_limits::ConnectionLimits`

### ISSUE THREAD

**Issue by mycognosist** [libp2p/rust-libp2p#3791]
## Summary

The `SwarmBuilder` does not accept connection limits using the recommended `connection_limits::ConnectionLimits` `struct`. This previously worked with `swarm::ConnectionLimits` but that has been deprecated.

## Expected behaviour

I expect `connection_limits::ConnectionLimits` to be a drop-in replacement for `swarm::ConnectionLimits` when calling `.connection_limits()` on `SwarmBuilder`.

## Actual behaviour

```
error[E0308]: mismatched types
    --> aquadoggo/src/network/swarm.rs:36:28
     |
36   |         .connection_limits(network_config.connection_limits())
     |          ----------------- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `libp2p::libp2p_swarm::ConnectionLimits`, found struct `libp2p::libp2p_connection_limits::ConnectionLimits`
     |          |
     |          arguments to this function are incorrect
     |
     = note: struct `libp2p::libp2p_connection_limits::ConnectionLimits` and struct `libp2p::libp2p_swarm::ConnectionLimits` have similar names, but are actually distinct types
```

## Version

`0.51.3`

## Would you like to work on fixing this bug?

No.

**Comment by thomaseizinger** [comment]
You are meant to use the new `libp2p::connection_limits::Behaviour` instead :)
