### ISSUE TITLE
#[behaviour(ignore)] doesn't work

### ISSUE THREAD

**Issue by ghost** [libp2p/rust-libp2p#3793]
## Summary
```rust
#[derive(NetworkBehaviour)]
struct MyBehaviour {
    gossipsub: gossipsub::Behaviour,
    mdns: mdns::async_io::Behaviour,
    #[behaviour(ignore)]
    response_sender: UnboundedSender<Response>,
}
```
(https://github.com/SightNet/sightnet-app/blob/master/src/main.rs#L55)

## Expected behaviour
response_sender should be ignored

## Actual behaviour
compiling error

<details><summary>Debug Output</summary>
<p>

```
#[derive(NetworkBehaviour)]
   |          ^^^^^^^^^^^^^^^^ the trait `NetworkBehaviour` is not implemented for `tokio::sync::mpsc::UnboundedSender<Response>`
```
</p>
</details>

## Version
0.51.2

## Would you like to work on fixing this bug?
No

**Comment by thomaseizinger** [comment]
This has been removed in https://github.com/libp2p/rust-libp2p/pull/2842. Which documentation did you follow that tells you to use this attribute?

If it is anything in our repository, I'd appreciate a pull request fixing up the docs.  Let me know if you are up for it :)
