### ISSUE TITLE
(libp2p-identity) Confusing deprecation(s) on making PeerId from ed25519 PublicKey bytes

### ISSUE THREAD

**Issue by DougAnderson444** [libp2p/rust-libp2p#3802]
### Background

Suppose we want to create a new `PeerId` from someone's **public key bytes**, we can do this:

```rs
use libp2p_identity::ed25519;
use libp2p_identity::PeerId;
use libp2p_identity::PublicKey;

let pub_key = ed25519::PublicKey::decode(pb_bytes)
    .map(PublicKey::Ed25519)
    .unwrap();

let binary_peer_id = PeerId::from_public_key(&pub_key).to_bytes();
```

Which works as expected ✔️. 
...But with a deprecation notice says to use `PublicKey::into_ed25519` instead of the `PublicKey::Ed25519` enum:

https://github.com/libp2p/rust-libp2p/blob/96288b8984e5c19b821297b2278c428c8d0d3786/identity/src/keypair.rs#L394-L401

Which doesn't do the same thing, and also has it's own deprecation direction here:

https://github.com/libp2p/rust-libp2p/blob/96288b8984e5c19b821297b2278c428c8d0d3786/identity/src/keypair.rs#L111-L118

...which is also deprecated since `v0.2.0`, which is odd because identity is at `v0.1.1` 🤔 . 

THAT deprecation notice says to use `Keypair::try_into_ed25519`, which doesn't seem to exist.

So I'm sure you can sense my confusion.  

### **The issue is**: 
It's really confusing as to why the method that works points to 2 others which don't work or don't exist.

### Potential Solution

Unless there is a clear reason or working deprecation path, remove the deprecations? I'm not privy to the logic as to why this is all here.

**Comment by thomaseizinger** [comment]
Sorry for the confusion! Are you depending on `master` by any chance?

The latter deprecation warnings are not released yet I think?
I agree that the version numbers should be removed though, they are so easy to get wrong if PRs merge in a different order.

You should be able to use `.into` to promote your `ed25519::PublicKey` to an `identity::PublicKey`. That is missing from the deprecation warnings :/

A PR would be much appreciated and sorry for the confusion!

**Comment by DougAnderson444** [comment]
Thanks @thomaseizinger for understanding and the explanation! I'll send a PR to hopefully clear it up.

I will add `impl From<>` to PublicKey for the `.from/.into` to work

**Comment by thomaseizinger** [comment]
> I will add `impl From<>` to PublicKey for the `.from/.into` to work

Does that not work already? That was definitely an oversight, sorry for that!

**Comment by DougAnderson444** [comment]
No worries!

To answer your question about which version I was using, it was `0.1.1` from crates.io

I did try `.into()` and `::from()` but neither worked until I added the `impl From`, but it's all good!
