### ISSUE TITLE
Support separate inbound/outbound types in `request_response`

### ISSUE THREAD

**Issue by omegablitz** [libp2p/rust-libp2p#3826]
## Description

The `request_response` behavior's `Codec` trait [currently supports](https://github.com/libp2p/rust-libp2p/blob/master/protocols/request-response/src/codec.rs#L38-L41) a `type Request` (for inbound/outbound requests) and a `type Response` (for inbound/outbound responses).

Proposal: remove the Request/Response types and replace them with `type InRequest`, `type OutRequest`, `type InResponse`, and `type Response`.

## Motivation

Separating out the request/response types into In/Out versions would be more flexible for cases when inbound types differ from outbound types - and would still be backwards compatible with the current behavior.

## Current Implementation

Described above

## Are you planning to do it yourself in a pull request?

Yes

**Comment by thomaseizinger** [comment]
Can you achieve the same thing by instantiating your protocol twice, with different types and `ProtocolSupport::Inbound` and `ProtocolSupport::Outbound`?

**Comment by omegablitz** [comment]
Just to clarify, do you mean creating two separate `request_response::Behaviour` with the same `ProtocolName`, but have one be `ProtocolSupport::Inbound` (with `Codec<Request = InboundRequest>`) and the other be `ProtocolSupport::Outbound` (with `Codec<Request = OutboundRequest>`)?

I didn't think of that, that would achieve what I'm trying to do!

The only thing I don't love about that approach is that there'll be several unreachable functions that will be needed to be implemented regardless, even though at compile-time we know that they're unreachable - eg `Codec::read_request` and `Codec::write_response` for `Codec<Request = InboundRequest>` and `Codec::write_request` and `Codec::read_response` for `Codec<Request = InboundRequest>`. The same would also apply to the outbound event types that are emitted by `request_response::Behaviour`.

**Comment by thomaseizinger** [comment]
> Just to clarify, do you mean creating two separate `request_response::Behaviour` with the same `ProtocolName`, but have one be `ProtocolSupport::Inbound` (with `Codec<Request = InboundRequest>`) and the other be `ProtocolSupport::Outbound` (with `Codec<Request = OutboundRequest>`)?

Yes!

> The only thing I don't love about that approach is that there'll be several unreachable functions that will be needed to be implemented regardless, even though at compile-time we know that they're unreachable - eg `Codec::read_request` and `Codec::write_response` for `Codec<Request = InboundRequest>` and `Codec::write_request` and `Codec::read_response` for `Codec<Request = InboundRequest>`. The same would also apply to the outbound event types that are emitted by `request_response::Behaviour`.

Well, the codec still needs to be run on both ends of the wire, no? Somebody will have to deserialize that request and thus invoke `Codec::read_request`. I am not sure I see why you'd think that they are unreachable.

**Comment by omegablitz** [comment]
Hmm, maybe I'm confused...

What I want is a _single_ Codec with `Codec::write_request(OutRequest)`, `Codec::read_request() -> InRequest`, `Codec::write_response(OutResponse)`, and `Codec::read_response() -> InResponse`.

In order words, the sender has an `OutRequest`, serializes it as bytes, sends it over the wire, and the receiver deserializes it as `InRequest`. Conceptually this is different because only `OutRequest` needs to be serializable, and only `InRequest` needs to be deserializable.

Because `Codec` only has 1 Request type and 1 Response type, this isn't possible right now - there must be a single `Request` type that implements both serialization and deserialization.


My understanding of the suggestion was to have 2 codecs (for the same protocol) - but only use one of them for serialization (write_request, write_response), and one of them for deserialization (read_request, read_response).


Am I not understanding the suggestion properly?

**Comment by thomaseizinger** [comment]
> In order words, the sender has an `OutRequest`, serializes it as bytes, sends it over the wire, and the receiver deserializes it as `InRequest`. Conceptually this is different because only `OutRequest` needs to be serializable, and only `InRequest` needs to be deserializable.

I don't really understand the point of that. If `InRequest` can be deserialized from the same bytes that `OutRequest` serializes to, then they are the exact same data structure and can be represented by the same type?

It sounds to me like you are trying to bake too many requirements into a single type. If you want additional type-safety on top of the wire format, then I'd suggest to create your own `InRequest` and `OutRequest` new-types and only implement conversion in one direction in your codebase and add an additional layer on top of your networking code.

> Am I not understanding the suggestion properly?

I thought you wanted to configure your peers to only speak a certain protocol in one way, which you can achieve using the `ProtocolSupport` enum.

**Comment by omegablitz** [comment]
You're right that they're the same datastructure, the types have different meaning. Just for further context, I've tried to write down a rough example here:

Crate A:
```rust
// the contents of an UnverifiedMessage are private
pub struct UnverifiedMessage {
   data: T,
   signature: S,
}
// anyone can construct an unverified message, and anyone can verify one
impl UnverifiedMessage {
    pub fn new(data: T, signature: S) -> Self {
        Self {
            data,
            signature,
        }
    }
    // can construct a VerifiedMessage by verifying an unverified message's signature
    pub fn verify(self) -> Result<VerifiedMessage> { ... }
}
pub struct VerifiedMessage(UnverifiedMessage);
impl VerifiedMessage {
    // can construct a VerifiedMessage by providing your own keypair and signing a T
    pub fn new(keypair: K, data: T) { /* sign data */ }
    // the contents of a VerifiedMessage are public (via an accessor)
    pub fn data(&self) -> &T {
        &self.0.data
    }
}

trait Serializable {
    fn serialize(&self) -> Vec<u8>;
}
trait Deserializable {
    fn deserialize(&[u8]) -> Self;
}
// all deserialized messages are unverified
impl Deserializable for UnverifiedMessage { ... }
// can only serialize a verified message
impl Serializable for VerifiedMessage { ... }
```

In Crate B, I want a request/response implementation (backed by rust-libp2p) that's generic over `InRequest`/`OutRequest`, instead of over a single `Request` type. This is because my serialization/deserialization traits are tightly coupled to the `InRequest`/`OutRequest` by design. Because of this, I'm not sure that new-types are helpful in this case.



Regardless, I totally understand if this use-case is too obscure to justify extending the built-in `request_response` behavior - I'll go ahead and close this issue if so. Thanks for your patience!

**Comment by thomaseizinger** [comment]
I see. My suggestion would be:

- Have an "unsafe" interface using libp2p that simply represents the network messages.
- Build your safety layer on top by completely encapsulating the network layer.

It shouldn't be too hard to make this generic and only allow the user to pass in "verified" messages and always emit "unverified" ones.

Latest when you serialize to bytes, all the type system safety is gone. Meaning, there is always a layer somewhere that enforces this. I like how you are using the type system but I think it would be too specific to include in rust-libp2p, esp. because it can be layered on top.

If you wanted, you could even wrap `request_response::Behaviour` directly by implementing `NetworkBehaviour` yourself. Or make your own, dedicated `NetworkBehaviour` if `request_response::Behaviour` doesn't suit your needs :)

**Comment by omegablitz** [comment]
That makes sense, thanks for the feedback!
