### ISSUE TITLE
swarm: deprecate `KeepAlive::Until`

### ISSUE THREAD

**Issue by thomaseizinger** [libp2p/rust-libp2p#3844]
## Description

Deprecate the `KeepAlive::Until` variant. Users can achieve the same thing by having a timer internally.

## Motivation

Understanding how to properly use `KeepAlive::Until` is difficult. It requires keeping around `KeepAlive` as a field in the `ConnectionHandler` otherwise it will be updated forever with a new timestamp. Having `KeepAlive` as a field thus makes it more difficult to accurately compute it. It could be set from `No` to `Yes` and back etc

Ideally, a `ConnectionHandler` can just compute its `KeepAlive` value from its internal state. There should be no reason to keep an idle connection around. If a `ConnectionHandler` as nothing to do, it should immediately return `KeepAlive::No`.

To avoid connections from being shut-down directly after it is established, `NetworkBehaviour`s should pass initial state in `handle_established_outbound_connection` and `handle_established_inbound_connection`. This way, the `connection_keep_alive` function can correctly return `KeepAlive::Yes`.

Whether or not completely idle connections should be shut down or not is an application-wide decision and cannot reasonably be computed by a single `ConnectionHandler`. Users should use `swarm::Config::with_idle_connection_timeout` to configure that. See https://github.com/libp2p/rust-libp2p/issues/4121.

```[tasklist]
- [ ] https://github.com/libp2p/rust-libp2p/pull/3876
- [ ] https://github.com/libp2p/rust-libp2p/pull/3960
- [ ] https://github.com/libp2p/rust-libp2p/pull/4029
- [ ] https://github.com/libp2p/rust-libp2p/pull/4648
- [ ] https://github.com/libp2p/rust-libp2p/pull/4656
- [ ] https://github.com/libp2p/rust-libp2p/pull/4675
- [ ] https://github.com/libp2p/rust-libp2p/pull/4642
- [ ] https://github.com/libp2p/rust-libp2p/pull/4676
- [ ] https://github.com/libp2p/rust-libp2p/pull/4677
- [ ] https://github.com/libp2p/rust-libp2p/pull/4679
- [ ] https://github.com/libp2p/rust-libp2p/pull/4659
- [ ] https://github.com/libp2p/rust-libp2p/pull/4696
```

**Comment by thomaseizinger** [comment]
cc @nathanielc

**Comment by thomaseizinger** [comment]
Identify doesn't use `Until` but https://github.com/libp2p/rust-libp2p/pull/3876 still shows quite well how I think protocols should implement the keep-alive mechanism.

**Comment by thomaseizinger** [comment]
https://github.com/libp2p/rust-libp2p/pull/3876 is queued for merging now. In a first step towards deprecating `KeepAlive::Until`, I'd like to move all protocols to this new approach of handling `KeepAlive`. We should do it as one PR per protocol.

Once all protocols have been ported, we can deprecate the enum variant itself and have our users to the same.

**Comment by nathanielc** [comment]
> To avoid connections from being shut-down directly after it is established, NetworkBehaviours should pass initial state in handle_established_outbound_connection and handle_established_inbound_connection. This way, the connection_keep_alive function can correctly return KeepAlive::Yes.

Has this part already been implemented?  I had assumed this was a blocker to make many changes here. Was the `identity` protocol a simpler case?

**Comment by thomaseizinger** [comment]
> > To avoid connections from being shut-down directly after it is established, NetworkBehaviours should pass initial state in handle_established_outbound_connection and handle_established_inbound_connection. This way, the connection_keep_alive function can correctly return KeepAlive::Yes.
> 
> Has this part already been implemented?  I had assumed this was a blocker to make many changes here. Was the `identity` protocol a simpler case? 

Yes the identify protocol was simple in this regard because no messages are generated in the behaviour.

Help in migrating other protocols away from `KeepAlive::Until` would be much appreciated. Off the top of my head, kademlia might require some changes and perhaps gossipsub. I don't think any other protocol actively establishes connections?

**Comment by drHuangMHT** [comment]
After `Until` being removed, `KeepAlive` can be `Copy` or be replaced by boolean, any interest?

**Comment by thomaseizinger** [comment]
It is already `Copy`. Not sure there is any practical benefit from it being a boolean. Having a separate type gives us a place to put documentation on it for example.

**Comment by thomaseizinger** [comment]
@mxinden Do you think it makes sense to add a general `idle_connection_timeout` to `Swarm`? It would trigger as soon as all `ConnectionHandler`s report `KeepAlive::No`. We can default it to 0 seconds.

When trying to transition `libp2p-request-response` away from `KeepAlive::Until`, I ran into the issue that the perf protocol currently relies on setting the connection timeout. Tests would also benefit from such a config option.

One could even ask whether we shouldn't deprecate `keep_alive::Behaviour` completely in favor of an idle connection timeout setting on `Swarm`.

**Comment by tcoratger** [comment]
@thomaseizinger In the `relay` protocol, I saw that there was at the end of the `poll` function in the behavior `handler`, there was the following part:

```rust
// Check keep alive status.
if self.reservation_request_future.is_none()
    && self.circuit_accept_futures.is_empty()
    && self.circuit_deny_futures.is_empty()
    && self.alive_lend_out_substreams.is_empty()
    && self.circuits.is_empty()
    && self.active_reservation.is_none()
{
    match self.keep_alive {
        KeepAlive::Yes => {
            self.keep_alive = KeepAlive::Until(Instant::now() + Duration::from_secs(10));
        }
        KeepAlive::Until(_) => {}
        KeepAlive::No => panic!("Handler never sets KeepAlive::No."),
    }
} else {
    self.keep_alive = KeepAlive::Yes;
}
 ```
 
 If I'm correct, the goal of this snippet is to keep the connection alive few more seconds, even if the condition is false. By removing the `self.keep_alive` in the context of this issue, this snippet is removed and then we have to find a way to mimic this in order for the function `connection_keep_alive` to return `KeepAlive::Yes` in such circumstances, correct?

**Comment by thomaseizinger** [comment]
Yes, although in general, I'd like to move away from implicitly keeping connections open for longer than they are needed.

For the relay protocol, what happens if we just remove the `Until` bit and just determine `KeepAlive` based on the above conditions?

**Comment by mxinden** [comment]
Proposal above, namely to add an `idle_connection_timeout` to `Swarm` makes sense to me.

At first I wondered whether a `idle_at_start_connection_timeout` would make more sense. Thinking about it some more `idle_connection_timeout` i.e. a timeout applicable not only at the start of the connection, but throughout its lifecycle, might be easier to reason about.

**Comment by thomaseizinger** [comment]
> Proposal above, namely to add an `idle_connection_timeout` to `Swarm` makes sense to me.
> 
> At first I wondered whether a `idle_at_start_connection_timeout` would make more sense. Thinking about it some more `idle_connection_timeout` i.e. a timeout applicable not only at the start of the connection, but throughout its lifecycle, might be easier to reason about.

Yeah I think that is very hard to teach and is a bit too specialized for my taste. Also, with the strategy of initialising `ConnectionHandler`s with the work they should do, the "a connection that might be useful later is idle initially" is not a problem.

On the other hand, having connections not close immediately when they go idle _after_ doing some work is definitely a problem:

- in our tests
- in examples
- when running the benchmarks

The benchmarks in particular are a special-case of applications that aren't strictly p2p but more client-server style, i.e. you want to connect to very particular nodes.

I opened an issue here: https://github.com/libp2p/rust-libp2p/issues/4121

**Comment by thomaseizinger** [comment]
> After `Until` being removed, `KeepAlive` can be `Copy` or be replaced by boolean, any interest?

@drHuangMHT I've captured your idea as a task here: https://github.com/libp2p/rust-libp2p/issues/4306

I am open to go down that road actually if we have sufficient documentation _on_ the `ConnectionHandler::connection_keep_alive` method that explains how this all works. In that case, I think a boolean is equally expressive as a custom enum and the user needs fewer imports and has less concepts to deal with.

**Comment by thomaseizinger** [comment]
@mxinden Shall we put a `#[deprecated]` on `KeepAlive::Until` already and currently `#[allow]` them within our repository? That would give us a head-start and allow (pun intended) us to remove `KeepAlive::Until` with the next breaking release already!

**Comment by mxinden** [comment]
> @mxinden Shall we put a `#[deprecated]` on `KeepAlive::Until` already and currently `#[allow]` them within our repository? That would give us a head-start and allow (pun intended) us to remove `KeepAlive::Until` with the next breaking release already!

Works for me @thomaseizinger.

**Comment by thomaseizinger** [comment]
This is all done! Many thanks to @leonzchang for all the help!

**Comment by leonzchang** [comment]
> This is all done! Many thanks to @leonzchang for all the help!

@thomaseizinger Thanks for your guidance too!
