### ISSUE TITLE
examples: Better user guide for examples

### ISSUE THREAD

**Issue by tcoratger** [libp2p/rust-libp2p#3853]
## Description

When looking at the folder with the examples, there is an introductory `README.md` file which presents all the examples in the form of a list but to find a more detailed explanation of the example in question and the way to run it, you have to go directly to the `.rs` file and find the corresponding lines between the legal mentions and the beginning of the code. Why not put a small `README.md` file in each example folder with:
1. Two or three lines to introduce the example more precisely (interest, functioning, particularity...)
2. A guide for the user to explain how to run it.

## Motivation

Add clarity for new users who want to experience the repo through Github and want to start by understanding/running some examples.

## Are you planning to do it yourself in a pull request?

Yes / No / Maybe.

**Comment by mxinden** [comment]
Our examples seem relatively stable, thus I think this is a good idea. Contributions welcome.

**Comment by thomaseizinger** [comment]
I like the idea!

As of Rust 1.54, we can actually use `include_str!` as part of `#[doc]`, meaning we can just move the entire block that is currently documented in the rustdoc to the markdown file but still have it on top of main as well (which I think gives us compilation checking as part of rustdoc?)

See https://blog.guillaume-gomez.fr/articles/2021-08-03+Improvements+for+%23%5Bdoc%5D+attributes+in+Rust.

**Comment by mxinden** [comment]
:eyes: `include_str!` is a neat solution!
