### ISSUE TITLE
rendezvous: rewrite using `libp2p-request-response`

### ISSUE THREAD

**Issue by thomaseizinger** [libp2p/rust-libp2p#3878]
## Description

Currently, `libp2p-rendezvous` has its own abstractions for implementing a `ConnectionHandler` called a `StreamHandler`. I consider this a failed experiment and we should implement this by wrapping `libp2p-request-response`.

The API should stay the same, thus the tests should provide a good foundation for this refactoring.

## Motivation

Simplify code.

## Are you planning to do it yourself in a pull request?

Maybe, but contributions are most welcome.

**Comment by mxinden** [comment]
Agreed with goal and priority.

**Comment by dgarus** [comment]
@thomaseizinger @mxinden 
I'd like to try implementing this issue. 
What do you think?

**Comment by thomaseizinger** [comment]
> @thomaseizinger @mxinden I'd like to try implementing this issue. What do you think?

It would be much appreciated! At the moment, `libp2p-rendezvous` is quite unnecessarily complex because it has so many abstraction layers. My suggestion would be to not try and understand what is there but read the spec first and see if we can implement something from scratch that fulfills the same API!

Here is how I'd go about it:

- Read the spec to understand the overall functionality: https://github.com/libp2p/specs/tree/master/rendezvous
- Add a dependency on `libp2p-request-response`
- Implement a `request_response::Codec` using `asynchronous_codec::Framed` and `RendezvousCodec`
- Delete the `substream_handler` and `handler` module
- Add a `request_response::Behaviour` as a field to both `libp2p-rendezvous::client::Behaviour` and `libp2p-rendezvous::server::Behaviour` using the above codec
- Try to fix the compile errors by now delegating functionality to the inner request-response behaviour

The last point is the trickiest one. Feel free to open a PR at any time if a question comes up!

**Comment by dgarus** [comment]
> Feel free to open a PR at any time if a question comes up!

Ok, thanks!

**Comment by thomaseizinger** [comment]
In https://github.com/libp2p/rust-libp2p/pull/3646/commits/90964ffeace98cb7a8bd7ee17170091d1ce04950, @mxinden refactored another protocol from custom handlers to using `request-response`, perhaps that helps :)

**Comment by dgarus** [comment]
@thomaseizinger @mxinden 
Hi!

I read the rendezvous protocol spec and, unfortunately, didn't find:

1. How do node become a rendezvous point?
2. What should do a node when the rendezvous point doesn't respond?
3. How many should a network have rendezvous points?
4. How does a node know what rendezvous points it should connect to?

**Comment by thomaseizinger** [comment]
> 1. How do node become a rendezvous point?

By offering the rendezvous protocol. In `rust-libp2p` terms, by composing the `rendezvous::server::Behaviour` into its main behaviour.

>     2. What should do a node when the rendezvous point doesn't respond?

There are many edgecases here but it will result in some kind of error. Either a timeout or an unsupported protocol.

>     3. How many should a network have rendezvous points?

That is up to whoever builds a network that utilizes the protocol.

>     4. How does a node know what rendezvous points it should connect to?

Out of scope for the specification. Could be hard-coded as a bootnode. Could be passed in by the user.

**Comment by dgarus** [comment]
Did I understand right that the node registered as a regular peer can't become a rendezvous point? 
In other words, which nodes would be rendezvous points is defined in advance and can't be changed.

**Comment by thomaseizinger** [comment]
It can be combined! See this test: https://github.com/libp2p/rust-libp2p/blob/master/protocols/rendezvous/tests/rendezvous.rs#L252-L285

**Comment by dgarus** [comment]
> It can be combined! See this test: https://github.com/libp2p/rust-libp2p/blob/master/protocols/rendezvous/tests/rendezvous.rs#L252-L285

Ok.
I didn't look at the code, just was trying to understand how the rendezvous works from the spec.
Strange why these things are not described in the protocol.

**Comment by thomaseizinger** [comment]
> > It can be combined! See this test: https://github.com/libp2p/rust-libp2p/blob/master/protocols/rendezvous/tests/rendezvous.rs#L252-L285
> 
> Ok.
> I didn't look at the code, just was trying to understand how the rendezvous works from the spec.
> Strange why these things are not described in the protocol.

I wasn't part of the spec process but it isn't really relevant I'd say. What matters are the wire messages and how they are processed.

There wouldn't be anything wrong with just supporting the server or the client f.e.

`go-libp2p` for example has a completely different design (in general, I don't think they have a rendezvous implementation) to `rust-libp2p` but they both follow the same spec :)

**Comment by dgarus** [comment]
@thomaseizinger
Hello, Thomas!
I'm still working on this issue.
Could you please assign it to me?
