### ISSUE TITLE
feat(request-response): serde (json and/or cbor) support

### ISSUE THREAD

**Issue by mxinden** [libp2p/rust-libp2p#3905]
## Description

Add a type that implements `libp2p-request-response` [`Codec`](https://docs.rs/libp2p/latest/libp2p/request_response/trait.Codec.html) and takes as type parameters two types, one representing a request, one representing a response, both implementing `serde`'s `Serialize` and `Deserialize` traits.

Example:

``` rust
struct SerdeJsonCodec<Req, Resp> (PhantomData<(Req, Resp)>);

impl<Req, Resp> Codec for SerdeJsonCodec<Req, Resp> where
  Req: Serialize + Deserialize,
  Resp: Serialize + Deserialize,
{
  // ...
}

// In user code one can then use the above:

request_response::Behaviour<SerdeJsonCodec<MyRequestType, MyResponseType>>
```

See past discussion that sparked the idea: https://github.com/libp2p/rust-libp2p/discussions/3764#discussioncomment-5597077

## Motivation

Makes it very easy to implement a JSON or CBOR request-response protocol using idiomatic serde.

## Are you planning to do it yourself in a pull request?

No

**Comment by thomaseizinger** [comment]
A few minor suggestions:

1. Drop the `serde` prefix. I don't think we will ever support a serialization library out of the box that isn't `serde`.
2. Hide the actual codec implementation from the public API and expose:
- `request_response::json::Behaviour<Req, Res>`
- `request_response::cbor::Behaviour<Req, Res>`
3. Perhaps we want to expose one based on `quick_protobuf` too? `request_response::protobuf::Behaviour` maybe?

**Comment by thomaseizinger** [comment]
Changing this to easy because you just need to implement a single trait and create some type aliases.

**Comment by dgarus** [comment]
@thomaseizinger @mxinden 

Hi!
I'd like to do this issue. Ok?

> Hide the actual codec implementation from the public API

I'm not confident that it's real to hide `the actual codec implementation` because `Serialize` and `Deserialize` are defined in the `serde` implementation. Or did I understand something wrong?

**Comment by thomaseizinger** [comment]
> @thomaseizinger @mxinden 
> 
> Hi!
> I'd like to do this issue. Ok?

Certainly! Much appreciated :)

> > Hide the actual codec implementation from the public API
> 
> I'm not confident that it's real to hide `the actual codec implementation` because `Serialize` and `Deserialize` are defined in the `serde` implementation. Or did I understand something wrong?

I was referring to the `struct` that implements our `Codec` trait.

**Comment by dgarus** [comment]
@thomaseizinger 
Hello!
Could you please look at my PR?

If the main idea was implemented right, I try to fix the error:
```
error[E0437]: type `OutEvent` is not a member of trait `NetworkBehaviour`
   --> protocols/request-response/src/serde_codec.rs:280:5
    |
280 |     type OutEvent = Event<Req, Resp>;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not a member of trait `NetworkBehaviour`
``` 
and so on (format, add docs).

If you can tell me where I was wrong with the `error[E0437]` it would be great ))
I can't reproduce this error locally.

Thanks!

**Comment by thomaseizinger** [comment]
Make sure you update to latest master, this associated type recently got renamed.

**Comment by dgarus** [comment]
> Make sure you update to latest master, this associated type recently got renamed.

OMG! I wasted 4 hours.
It's strange, when I run locally, everything is built from my branch,
but on the GitHub isn't?

**Comment by thomaseizinger** [comment]
> > Make sure you update to latest master, this associated type recently got renamed.
> 
> OMG! I wasted 4 hours.
> It's strange, when I run locally, everything is built from my branch,
> but on the GitHub isn't?

Sorry to hear that :(

We run CI against the `pull_request` target which is a temporary merge commit with latest master.

**Comment by dgarus** [comment]
> > > Make sure you update to latest master, this associated type recently got renamed.
> > 
> > 
> > OMG! I wasted 4 hours.
> > It's strange, when I run locally, everything is built from my branch,
> > but on the GitHub isn't?
> 
> Sorry to hear that :(
> 
> We run CI against the `pull_request` target which is a temporary merge commit with latest master.

Cool, this is a good way to protect the `master` branch, which I've never seen before.
Thank you very much for the review!

**Comment by mxinden** [comment]
//CC @bajtos and @juliangruber this might be interesting for https://github.com/filecoin-station/zinnia/, more specifically your request-response mechanism provided to the sandbox.
