### ISSUE TITLE
Update the minimum version of `either` dependency from 1.5 to 1.8 in libp2p-core

### ISSUE THREAD

**Issue by kmdreko** [libp2p/rust-libp2p#3909]
## Summary

Seen in [this StackOverflow post](https://stackoverflow.com/questions/76220673), the user updated libp2p from v0.46 to v0.53.1 which updated libp2p-core to v0.39.2 and experienced a compilation error within the library:

```
error[E0599]: no method named `as_pin_mut` found for struct `Pin<&mut either::Either<A, B>>` in the current scope
   --> <project>/vendor/crates/libp2p-core-0.39.2/src/either.rs:147:20
    |
147 |         match self.as_pin_mut() {
    |                    ^^^^^^^^^^ help: there is a method with a similar name: `as_mut`

For more information about this error, try `rustc --explain E0599`
```

The user reports the version of either was v1.6.1.

## Possible Solution

It seems [a recent change introduced calling `.as_pin_mut()` on a `either::Either`](https://github.com/libp2p/rust-libp2p/blob/3fde13220b29f0878d6f98a3fe50bc9b008baf8a/core/src/either.rs#L132), but this method only exists as of v1.8 which is higher than the required version of `"1.5"` [in the Cargo.toml](https://github.com/libp2p/rust-libp2p/blob/3fde13220b29f0878d6f98a3fe50bc9b008baf8a/core/Cargo.toml#L14).

So the fix would be to either revert that part of the change or update the minimum version of either to v1.8.

**Comment by thomaseizinger** [comment]
A simple `cargo update` should fix this. I can also recommend using dependabot to avoid outdated dependencies in your lockfile.

Happy to take a patch to bump the minimum required version of `either`. cargo's version resolution is "highest available" by default so there are probably more issues like this if you try to pin to most minimal version.
