### ISSUE TITLE
Invalid code samples on Hole Punching tutorial

### ISSUE THREAD

**Issue by gmelodie** [libp2p/rust-libp2p#3911]
[This tutorial](https://docs.rs/libp2p/latest/libp2p/tutorials/hole_punching/index.html) seems to be outdated 

The following no longer work:

```## Inside the rust-libp2p repository.
cargo build --example relay_v2 -p libp2p-relay
```
error: `no example target named relay_v2`

```## Inside the rust-libp2p repository.
cargo build --example client -p libp2p-dcutr
```
error: `no example target named client`

I got the server to work using https://github.com/libp2p/go-libp2p-relay-daemon, but I can't seem to find where's the code/binary for the relay client

**Comment by thomaseizinger** [comment]
Ah yes. We recently consolidated the examples: https://github.com/libp2p/rust-libp2p/tree/master/examples

**Comment by mxinden** [comment]
Thanks for reporting! @gmelodie would you mind creating a pull request?
