### ISSUE TITLE
transport/noise: Implement NoiseExtensions

### ISSUE THREAD

**Issue by oblique** [libp2p/rust-libp2p#3988]
## Description

[NoiseExtensions] and a way to [retrieve them] after an upgrade is not currently implemented

[retrieve them]: https://github.com/libp2p/js-libp2p-webtransport/blob/76ebdffe424e79fe109cbf9c2cfe326d7c20ffd8/src/index.ts#L389-L403

## Motivation

I was trying to implement a `Transport` and `StreamMuxer` that was using [WebTransport] browser API. After implementing both I couldn't establish a connection because handshake was failing.

The Go implementation is sending [early data] as part of the handshake procedure and for that we need [NoiseExtensions].

## Current Implementation

Currently I didn't find any way to send early data. Are early data what we call `prologue` in the Rust implementation?

## Are you planning to do it yourself in a pull request?

Maybe. I'm still trying to understand the implementation.

[NoiseExtensions]: https://github.com/libp2p/go-libp2p/blob/305282b0cdda802712be5dbcf3b6921912613414/p2p/security/noise/pb/payload.proto#L4-L7
[WebTransport]: https://developer.mozilla.org/en-US/docs/Web/API/WebTransport
[early data]: https://github.com/libp2p/go-libp2p/blob/305282b0cdda802712be5dbcf3b6921912613414/p2p/transport/webtransport/listener.go#L176-L184

**Comment by thomaseizinger** [comment]
Prologue gets hashed into the session state. The handshake will fail if the parties set different prologues.

Early data is currently not exposed but I am guessing our underlying noise library supports it so it is just a matter of exposing that too.

**Comment by mxinden** [comment]
> Are early data what we call `prologue` in the Rust implementation?

To add to Thomas' comment above, they are not the same. Both are a Noise concept. See https://noiseprotocol.org/noise.html#prologue.



> ## Are you planning to do it yourself in a pull request?
> 
> Maybe. I'm still trying to understand the implementation.

That would be very welcomed.

Related see also https://github.com/libp2p/rust-libp2p/pull/3846/ and https://github.com/libp2p/rust-libp2p/issues/3825.
