### ISSUE TITLE
Error when importing libp2p with features

### ISSUE THREAD

**Issue by tapiocaboy** [libp2p/rust-libp2p#4008]
I tried to use libp2p crate in to Cargo.toml 

```toml
[package]
name = "tt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libp2p = { version = "0.51.3", features = ["ping", "macros", "tcp", "dns", "tokio", "websocket", "noise", "mplex", "yamux", "kad"]}

```

My rust version 

```
 Projects rustup show                             
Default host: aarch64-apple-darwin
rustup home:  /Users/kalanamith/.rustup

installed targets for active toolchain
--------------------------------------

aarch64-apple-darwin
wasm32-unknown-unknown

active toolchain
----------------

stable-aarch64-apple-darwin (default)
rustc 1.69.0 (84c898d65 2023-04-16

```

Im ended up with the following error when trying to build the project 

```
error[E0592]: duplicate definitions with name `is_soa`

#[derive(Debug, EnumAsInner, PartialEq, Clone, Eq)]
    |                 ^^^^^^^^^^^ duplicate definitions for `is_soa`
...
994 |     pub fn is_soa(&self) -> bool {
    |     ---------------------------- other definition for `is_soa`
    |
    = note: this error originates in the derive macro `EnumAsInner` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0592`.
error: could not compile `trust-dns-proto` due to previous error
warning: build failed, waiting for other jobs to finish...
```

Is there a fix for this issue?

**Comment by mxinden** [comment]
Moving to rust-libp2p here.

**Comment by thomaseizinger** [comment]
This is a compile-error in `trust-dns-proto`, not `rust-libp2p`.

- Have you checked upstream for issues?
- Have you tried to run `cargo update`?

**Comment by tapiocaboy** [comment]
Yes I have tried the both, also created an empty Rust project and added this on Cargo.toml and got the same error

**Comment by thomaseizinger** [comment]
> - Have you checked upstream for issues?

Found this: https://github.com/bluejekyll/trust-dns/issues/1946.

Closing here as an upstream problem.

**Comment by tapiocaboy** [comment]
How to use this library ? is there a workaround since none of those shows workaround for the issue

**Comment by thomaseizinger** [comment]
> How to use this library ? is there a workaround since none of those shows workaround for the issue

The workaround shown in https://github.com/bluejekyll/trust-dns/issues/1946#issuecomment-1566202251 does not work for you?

Have you tried pinning `enum-as-inner` to `0.5.1` via `cargo update`? Maybe the following helps (untested, perhaps need to fix syntax):

```
cargo update -p enum-as-inner --precise 0.5.1
```

**Comment by thomaseizinger** [comment]
> > How to use this library ? is there a workaround since none of those shows workaround for the issue
> 
> The workaround shown in [bluejekyll/trust-dns#1946 (comment)](https://github.com/bluejekyll/trust-dns/issues/1946#issuecomment-1566202251) does not work for you?
> 
> Have you tried pinning `enum-as-inner` to `0.5.1` via `cargo update`? Maybe the following helps (untested, perhaps need to fix syntax):
> 
> ```
> cargo update -p enum-as-inner --precise 0.5.1
> ```

You'll obviously need to have a lockfle for that.
