### ISSUE TITLE
core: remove `upgrade::transfer` module

### ISSUE THREAD

**Issue by thomaseizinger** [libp2p/rust-libp2p#4011]
## Description

This module contains functions for writing and reading varint-prefixed messages. These kind of utility functions do not belong in `libp2p-core` and unnecessarily increase the public API. All of its usages are actually as part of a `libp2p_request_response::Codec`.

```[tasklist]
- [ ] https://github.com/libp2p/rust-libp2p/issues/4489
- [x] `libp2p-request-response` tests: We can use one of newly added `cbor` or `json` codecs.
- [x] file-sharing example: We can use one of the newly added `cbor` or `json` codecs.
- [ ] https://github.com/libp2p/rust-libp2p/issues/4565
```

This issue should be tackled in 4 separate PRs, one for each of the above crates and a fourth one to deprecate all functions in the `upgrade::transfer` module. We can remove them in the next breaking release then.

## Motivation

Shrink public API of `libp2p-core` and thus avoid unnecessary version bumps in other crates.

## Are you planning to do it yourself in a pull request?

No.

**Comment by tcoratger** [comment]
@thomaseizinger Concerning `file-sharing` example, if I understand well, up to now, there is an implementation of the trait `request_response::Codec` for the structure `FileExchangeCodec`. 

The objective here is simply to copy paste the `Codec` implementation details that are applied to the structure `Codec` in `cbor.rs` for example? As `codec` in `cbor.rs` is a private module, we cannot access directly from the exterior.

**Comment by thomaseizinger** [comment]
> @thomaseizinger Concerning `file-sharing` example, if I understand well, up to now, there is an implementation of the trait `request_response::Codec` for the structure `FileExchangeCodec`. 
> 
> The objective here is simply to copy paste the `Codec` implementation details that are applied to the structure `Codec` in `cbor.rs` for example? As `codec` in `cbor.rs` is a private module, we cannot access directly from the exterior.

The `cbor` module is designed to be consumed via its `Behaviour` type alias. Check the documentation in there.

The objective is to use the `cbor::Behaviour` in the file sharing example instead of writing our own codec.

**Comment by tcoratger** [comment]
Concerning `AutoNAT` modification, if we choose to remove the `read_length_prefixed` and `write_length_prefixed` functions to use `quick_protobuf_codec::Codec` in combination with `asynchronous_codec::Framed`, this will mean to me that we will have to modify the `Codec trait` according to me (maybe I'm wrong).

For me, if we want to use `asynchronous_codec::Framed::new` via the `io`, then the `io` type must implement both `AsyncRead` and `AsyncWrite` and no longer one or the other, as it is currently depending on whether it is a read or a write.

**Comment by thomaseizinger** [comment]
See https://github.com/libp2p/rust-libp2p/pull/4051 for an example of how we use `Framed` with the codec trait
