### ISSUE TITLE
Example of chat doesnt work

### ISSUE THREAD

**Issue by ghost** [libp2p/rust-libp2p#4057]
## Summary

Example doesnt work: peers cannot discover each other

https://github.com/libp2p/rust-libp2p/discussions/4056

## Expected behaviour

Peers discover each other

## Actual behaviour

Logs:
```sh
Local node is listening on /ip4/127.0.0.1/udp/48367/quic-v1
Local node is listening on /ip4/xxx.xxx.xxx/udp/48367/quic-v1
Local node is listening on /ip4/xxx.xxx.xxx/udp/48367/quic-v1
Local node is listening on /ip4/127.0.0.1/tcp/36085
Local node is listening on /ip4/xxx.xxx.xxx/tcp/36085
Local node is listening on /ip4/xxx.xxx.xxx/tcp/36085
```

## Version

0.51.3

## Would you like to work on fixing this bug?

Maybe

**Comment by thomaseizinger** [comment]
Let's continue here: https://github.com/libp2p/rust-libp2p/discussions/4056.
