### ISSUE TITLE
rendezvous: synchronously return errors from behaviour functions

### ISSUE THREAD

**Issue by thomaseizinger** [libp2p/rust-libp2p#4070]
## Description

Originally described in https://github.com/libp2p/rust-libp2p/pull/4051/files#r1225343866.

## Motivation

Simpler code and better user experience.

## Current Implementation

An event is queued and later emitted as an error.

## Are you planning to do it yourself in a pull request?

No but maybe @dgarus is keen :)

**Comment by dgarus** [comment]
@thomaseizinger 
Ok

**Comment by dgarus** [comment]
@thomaseizinger Hello!
Could you please take a look at my PR?

**Comment by dgarus** [comment]
I'm not confident about backward compatibility.
