### ISSUE TITLE
Use a PathBuf in AddrComponent::UNIX

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#408]
I'm not sure how good of an idea this is, because we need paths to be cross-platform.

**Comment by gnunicorn** [comment]
While I see merit in this idea (we won't be able to open it unless we can convert it to a `PathBuf`/`Path` anyways), I don't think we want to attempt to convert it within the `AddrComponent` already. From the perspective of the `MultiAddr` its value is just an opaque String passed to the system. If we used a `PathBuf` we introduced a platform-specific component. I'd be against that.

**Comment by twittner** [comment]
I agree with @gnunicorn that for `Multiaddr` it would lead to platform-specific code given that encodings are not cross-platform. It is better to leave it as is and handle invalid paths outside of `Multiaddr`.

**Comment by tomaka** [comment]
Let's add a small comment in the code explaining that!

**Comment by Ericson2314** [comment]
I did stumble upon https://crates.io/crates/relative-path

**Comment by tomaka** [comment]
Well, if anything I think the path should always be absolute.
It's a bit of weird situation, because I don't see any real-life scenario where you'd want to send on the network a `Multiaddr` that contains `Unix`, except between programs running on the same machine, thus eliminating the issue of being cross-platform.
