### ISSUE TITLE
Support more Multihash-Protocols for PeerId?

### ISSUE THREAD

**Issue by gnunicorn** [libp2p/rust-libp2p#409]
Currently, we only support PeerIds in multihash using SHA2-256. In practice this appears to be the only being in use. However, it is unclear from the specification, whether other hash-algorithms should be used and how one should deal with the fact that the same underlying source would lead two different PeerIds depending on the hash used.

See https://github.com/libp2p/rust-libp2p/pull/407#discussion_r209276238 .

**Comment by tomaka** [comment]
Triaging.

The specs now exist: https://github.com/libp2p/specs/blob/16852be81d4557d16f4a4a26eeec7b2bde494496/peer-ids/peer-ids.md#peer-ids
Only SHA2-256 or identity are only ever used.

See also discussion in #1230
