### ISSUE TITLE
Support inline trait bounds in NetworkBehaviour macro

### ISSUE THREAD

**Issue by xDarksome** [libp2p/rust-libp2p#4124]
## Description

The `NetworkBehaviour` macro currently handles only the trait bounds inside the `where` clause. But there are also inline trait bounds.

## Motivation

For a small amount of type parameters the inline style is generally more widely used. 

## Current Implementation

Where-clause trait bound works
````rust
#[derive(NetworkBehaviour)]
pub struct Behaviour<C> 
    where C: TypeConfig
{
    request_reponse: request_response::Behaviour<C>,
}
````
Inline one doesn't
````rust
#[derive(NetworkBehaviour)]
pub struct Behaviour<C: TypeConfig> {
    request_reponse: request_response::Behaviour<C>,
}

````
## Are you planning to do it yourself in a pull request?

No. It's not a critical feature for me, just wanted to leave it here so it can be discovered next time someone is going to touch the macro.

**Comment by mxinden** [comment]
Thanks for reporting.

This is surprising, as I assumed the following unit test covers your use-case.

https://github.com/libp2p/rust-libp2p/blob/93aa21aba9c861f3fa2567ed368c54f6460fed10/swarm/tests/swarm_derive.rs#L192-L204

**Comment by xDarksome** [comment]
Yea, seems like the simple use-case works
```rust
#[derive(NetworkBehaviour)]
pub struct Behaviour<N: NetworkBehaviour> {
    request_reponse: N,
}
````

What I have is 
````rust
pub trait TypeConfig: Clone + Send + Sync + 'static {
    type Request: Serialize + DeserializeOwned + Clone + Send + Sync + 'static;
    type Response: Serialize + DeserializeOwned + Clone + Send + Sync + 'static;
}

#[derive(NetworkBehaviour)]
pub struct Behaviour<C: TypeConfig>{
    request_reponse: request_response::Behaviour<C>,
}

mod request_response {
    pub type Behaviour<C> = libp2p::request_response::Behaviour<Codec<C>>;

    #[derive(Clone)]
    pub struct Codec<C: TypeConfig> {
        _marker: PhantomData<C>,
    }

    impl<C: TypeConfig> libp2p::request_response::Codec for Codec<C> {
        type Request = C::Request;
        type Response = C::Response;
        ...
    }
}
````

**Comment by thomaseizinger** [comment]
Have you seen the recent additions of `cbor::Behaviour` and `json::Behaviour` for defining request-response behaviours that use `serde` encodings?

Those could be of use for you, or if not, they might be an inspiration for defining your own. I've made the experience that Rust often works better if you try to not be too generic but instead simply enumerate the cases that you've got.

**Comment by xDarksome** [comment]
Looked at them just now, and it is very similar, but we're using Message Pack.

We are going to have an enum of Requests and an enum of Responses, as you're proposing. 
However they're not going to reside in the same crate with `libp2p` machinery. And coupling between those components isn't desired.

**Comment by thomaseizinger** [comment]
> Looked at them just now, and it is very similar, but we're using Message Pack.

Is there a need for something generic then? Can't you make a message-pack codec and have the behaviour generic over request and response? Similar to our behaviours, you don't even need the derive but should be able to get away with a type-alias.

**Comment by xDarksome** [comment]
> Is there a need for something generic then?

Yes, to decouple networking implementation details from the main app.

> Can't you make a message-pack codec and have the behaviour generic over request and response?

I think it's exactly what we're doing. 

> Similar to our behaviours, you don't even need the derive but should be able to get away with a type-alias.

There's going to be more protocols inside the struct.

**Comment by thomaseizinger** [comment]
> > Can't you make a message-pack codec and have the behaviour generic over request and response?
> 
> I think it's exactly what we're doing.

Not quite. Your behaviour is generic over a type `C` that has two associated types whereas I am suggesting that you make a message-pack codec with two type parameters, `Req` and `Res`.

That removes the need for the `TypeConfig` trait and you can simply reference your behaviour like inside your larger behaviour:

```rust
#[derive(NetworkBehaviour)]
pub struct Behaviour<Req, Res>{
    request_reponse: request_response::Behaviour<MsgPackCodec<Req, Res>>,
}
```

Can you share what "doesn't work" actually means?

**Comment by xDarksome** [comment]
You would still need to have `Serialize + DeserializeOwned + ..` bounds for both `Req` and `Res` type parameters on your `Behaviour` product type.

But this way the trait bound would be so long that I would rather use `where` clause anyway.

I just tried specifying `Req`, `Resp` separately and it actually woks, even with the inline approach. So it's an even deeper edge-case then I thought.

> Can you share what "doesn't work" actually means?

````rust
#[derive(NetworkBehaviour)]
pub struct Behaviour<C: TypeConfig> {
    request_reponse: request_response::Behaviour<C>,
}
````

````
error[E0277]: the trait bound `request_response::Codec<C>: libp2p::libp2p_request_response::Codec` is not satisfied
   --> crates/libp2p/src/lib.rs:170:10
    |
170 | #[derive(NetworkBehaviour)]
    |          ^^^^^^^^^^^^^^^^ the trait `libp2p::libp2p_request_response::Codec` is not implemented for `request_response::Codec<C>`
    |
note: required by a bound in `libp2p::libp2p_request_response::Behaviour`
   --> /home/darksome/.cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-request-response-0.24.1/src/lib.rs:351:13
    |
351 |     TCodec: Codec + Clone + Send + 'static,
    |             ^^^^^ required by this bound in `Behaviour`
    = note: this error originates in the derive macro `NetworkBehaviour` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider extending the `where` clause, but there might be an alternative better way to express this requirement
    |
170 | #[derive(NetworkBehaviour, request_response::Codec<C>: libp2p::libp2p_request_response::Codec)]
    |                          ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

error[E0277]: the trait bound `C: TypeConfig` is not satisfied
   --> crates/libp2p/src/lib.rs:170:10
    |
170 | #[derive(NetworkBehaviour)]
    |          ^^^^^^^^^^^^^^^^ the trait `TypeConfig` is not implemented for `C`
    |
note: required by a bound in `request_response::Codec`
   --> crates/libp2p/src/request_response.rs:75:21
    |
75  | pub struct Codec<C: TypeConfig> {
    |                     ^^^^^^^^^^ required by this bound in `Codec`
    = note: this error originates in the derive macro `NetworkBehaviour` (in Nightly builds, run with -Z macro-backtrace for more info)
    ```

**Comment by thomaseizinger** [comment]
Your issue is that you are not satisfying the trait-bounds of `request_response::Behaviour`. You need to add a super-trait for `Codec` to `TypeConfig`:

```rust
pub trait TypeConfig: Codec {

}
```

**Comment by xDarksome** [comment]
I don't think so. `TypeConfig` isn't `Codec`. I've provided somewhat complete code structure in my first reply. 

I do agree that it's an edge case and fully understand if you don't want to support it.

**Comment by thomaseizinger** [comment]
> I don't think so. `TypeConfig` isn't `Codec`. I've provided somewhat complete code structure in my first reply.

Based on this:

```rust
#[derive(NetworkBehaviour)]
pub struct Behaviour<C: TypeConfig> {
    request_reponse: request_response::Behaviour<C>,
}
```

You are using it as if it were `Codec`. The type parameter passed to `request_response::Behaviour` needs to implement `Codec` and if that is not guaranteed via a super-trait, rustc will complain.

We can definitely fix any bugs with the macro but from what you've reported so far, it seems to be a usage error.

**Comment by xDarksome** [comment]
`request_response::Behaviour` is a local type alias. I have a local module called `request_response`. The code example may be a bit confusing from your perspective, sorry for that.

You can see the code structure in my first reply.

**Comment by thomaseizinger** [comment]
> `request_response::Behaviour` is a local type alias. I have a local module called `request_response`. The code example may be a bit confusing from your perspective, sorry for that.
> 
> You can see the code structure in my first reply.

Right, I missed that. Is there a reason you need this indirection of `TypeConfig`? Seems unnecessary to me if you could also just pass `Req` and `Res` to the codec.

**Comment by xDarksome** [comment]
I find it much more convenient, this way you only need to specify one type parameter, plus you don't need to write trait bounds on each type/impl.
I used this pattern before, but to a lesser extent. Recently, after working with https://github.com/datafuselabs/openraft I started to appreciate it more. They use it extensively throughout the whole codebase.

**Comment by thomaseizinger** [comment]
Tastes are different I guess. I've made the exact opposite experience. Traits are made for abstracting over behaviour. If you only use them for associated types, you are kind of using the wrong tool for the job.

In any case, I am glad it is working well for you :)
