### ISSUE TITLE
Peer discovery regression for Polkadot with mDNS

### ISSUE THREAD

**Issue by altonen** [libp2p/rust-libp2p#4127]
We updated libp2p to 0.51.3 for Polkadot 0.9.43 and since the update we're experiencing some regression with mDNS. Two peers in the same network are no longer able to discover each other using mDNS.

Two Polkadot 0.9.43 nodes are unable to discover each other but Polkadot 0.9.43 is able to discover 0.9.42 but not vice versa.

Based on what Wireshark is showing, there is an exchange of query requests and responses but the responses received presumable from 0.9.43 nodes are empty as far multiaddresses are concerned. The responses that a 0.9.42 node sends contain a multiaddress.

## Expected behaviour

Nodes are able to discover each other in the local network.

## Actual behaviour

Nodes using libp2p 0.51.3 don't discover each other. Node using libp2p 0.51.3 is able to discover another node using a lower version of libp2p

## Version

0.51.3

## Would you like to work on fixing this bug?

Yes / No / Maybe.

**Comment by thomaseizinger** [comment]
Any chance you can bisect to the commit that introduces the regression?

What version are you upgrading from?

**Comment by altonen** [comment]
We were upgrading from 0.50.0 so the amount of changes was quite large, all condensed into one nice and huge squashed commit so bisecting is going to be difficult.

If you don't have pointers w.r.t any potential problems recent changes in libp2p might have introduced, I will try to debug this on my own further.

**Comment by thomaseizinger** [comment]
> We were upgrading from 0.50.0 so the amount of changes was quite large, all condensed into one nice and huge squashed commit so bisecting is going to be difficult.

If you use cargo's patch feature and replace libp2p with a path dependency, you should be able to point it to a local checkout where you can move between the various commits.

**Comment by altonen** [comment]
I may be misunderstanding something but the problem is not on libp2p side, you have a clean history. On Substrate side the libp2p upgrade has been squashed into one commit so anything before it is using 0.50.0 and anything after is using 0.51.3. In order to bisect libp2p, I'd basically have to recreate the work we did in the Substrate PR as I traverse the history.

If that is the only way to do then it is what it is, but I think I will use that as the last resort.

**Comment by thomaseizinger** [comment]
The exchange you were seeing in wireguard, was that only a single exchange just after the nodes had booted? What happens if you let the nodes run for a bit, are they able to discover each other on the 2nd attempt?

Between those releases, we change the way mDNS requests the addresses of the local interfaces. It now takes them from events rather requesting them imperatively from `PollParameters`. Perhaps there is a race condition there somewhere although it puzzles me how our CI would pass then.

**Comment by altonen** [comment]
I was debugging this further and turns out we made a mistake when updating to 0.51.3 and forgot to inject `NewListenAddr` to mDNS. Sorry for the trouble and thanks for helping

**Comment by mxinden** [comment]
Thank you for the update here @altonen! Happy it is resolved.
