### ISSUE TITLE
gossipsub: remove `fast_message_id_fn`

### ISSUE THREAD

**Issue by mxinden** [libp2p/rust-libp2p#4138]
## Description

Today `libp2p-gossipsub` provides the `fast_message_id_fn` mechanism:

https://github.com/libp2p/rust-libp2p/blob/1eedcb5fcc0535f0d36740b7a679c86822594b4e/protocols/gossipsub/src/config.rs#L653-L667

Past motivation for the mechanism is the following . Ethereum compresses GossipSub messages. To avoid decompression just to find out that a message is a duplicate, introduce an additional message id method that can be applied pre-decompression.

Though the motivator itself, i.e. to avoid de-compression is no longer relevant. To quote @AgeManning:

> However, the fast-message-id thing probably doesn't really save us all that much, because our compression algo (snappy) is pretty quick and we're talking very small amount of processing. 

One might think that removing the `fast_message_id_fn` mechanism makes `libp2p-gossipsub` prone to DOS attacks where the attacker tries to exhaust the CPU through forcing lots of decompression. Though even with the mechanism, an attacker can send slightly altered messages, thus forcing the local machine to do the decompression work.

Next to the above no longer relevant optimization, the mechanism adds significant amount of complexity.

- One needs a translation mechanism.
    https://github.com/libp2p/rust-libp2p/blob/1eedcb5fcc0535f0d36740b7a679c86822594b4e/protocols/gossipsub/src/behaviour.rs#L326-L327
- It bloats implementations of e.g. `handle_received_message`.
    https://github.com/libp2p/rust-libp2p/blob/1eedcb5fcc0535f0d36740b7a679c86822594b4e/protocols/gossipsub/src/behaviour.rs#L1743-L1874
- It makes reasoning about attack scenarios difficult https://github.com/libp2p/rust-libp2p/security/advisories/GHSA-gv2v-chrf-46p3

## Motivation

Simplify `libp2p-gossipsub`.

@AgeManning extracted from our past discussion. Please comment in case I am missing something.

## Are you planning to do it yourself in a pull request?

No, but I am happy to mentor someone.

**Comment by StemCll** [comment]
Hi @mxinden :wave:  
I'm starting to work on this task :)

**Comment by mxinden** [comment]
Great thank you. Feel free to open a draft pull request in case you want early feedback @StemCll.

**Comment by StemCll** [comment]
Sure, I need to get into the implementation first
