### ISSUE TITLE
Use issue forms instead of templates

### ISSUE THREAD

**Issue by thomaseizinger** [libp2p/rust-libp2p#4151]
## Description

GitHub supports what is called issue forms: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms

They are more advanced forms of templates that provide more guidance to the user instead of the usual markdown text.

## Motivation

Making contributions easier. I find the current template hard to read because it is just one wall of text with little visual guidance. The HTML comments are meant to tell users what to fill in where. Editing issues and/or PRs is also more difficult because one has to find the actual text among the heads and comments.

## Current Implementation

Markdown-based issue templates.

## Are you planning to do it yourself in a pull request?

No.

**Comment by mxinden** [comment]
Fancy. Removing `decision-pending`.

**Comment by clebrin** [comment]
I wrote a PR #4560 for this issue. (This is my very first open source contribution !)

**Comment by thomaseizinger** [comment]
> I wrote a PR #4560 for this issue. (This is my very first open source contribution !)

Great! Honored that it is on our repository and welcome to the world of open source!
