### ISSUE TITLE
quic: ability to listen on ipv4 and v6

### ISSUE THREAD

**Issue by mxinden** [libp2p/rust-libp2p#4165]
## Summary

With `libp2p-quic` `v0.8.0-alpha` one can not listen on **both** a v4 and v6 address.

Unconfirmed whether https://github.com/libp2p/rust-libp2p/pull/3454 has the same issue.

## Expected behaviour

Calling `listen_on` with a v4 and v6 address to work.

## Actual behaviour

Apply the following diff:

``` diff
modified   examples/dcutr/src/main.rs
@@ -172,7 +172,10 @@ fn main() -> Result<(), Box<dyn Error>> {
     .build();
 
     swarm
-        .listen_on("/ip4/0.0.0.0/udp/0/quic-v1".parse().unwrap())
+        .listen_on("/ip4/0.0.0.0/udp/4001/quic-v1".parse().unwrap())
+        .unwrap();
+    swarm
+        .listen_on("/ip6/::/udp/4001/quic-v1".parse().unwrap())
         .unwrap();
     swarm
         .listen_on("/ip4/0.0.0.0/tcp/0".parse().unwrap())
```

and then run with:

```
cargo run -- --mode listen --secret-key-seed 0 --relay-address /ip4/127.0.0.1
```

resulting in:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Other(Custom { kind: Other, error: Transport(Right(Io(Os { code: 98, kind: AddrInUse, message: "Address already in use" }))) })', examples/dcutr/src/main.rs:179:10
```

<details><summary>Debug Output</summary>
<p>

```
<output>
```
</p>
</details>

## Possible Solution

My suspicion is that the ipv6 `UdpSocket` binds to both v4 and v6 in order to accept IPv4-mapped IPv6 traffic e.g. `::ffff:192.0.2.128`.

In such case we would need to call [`set_only_v6`](https://docs.rs/socket2/latest/socket2/struct.Socket.html#method.set_only_v6) on the socket.

See same code on the tcp side:

https://github.com/libp2p/rust-libp2p/blob/2671375cc48d501cffa56ada68012d2b1556a30e/transports/tcp/src/lib.rs#L356-L358

## Version

`libp2p-quic` `v0.8.0-alpha`

## Would you like to work on fixing this bug?

No

**Comment by eserilev** [comment]
hi, i'd like to work on this if its still relevant

**Comment by eserilev** [comment]
so far im having a bit of trouble recreating this bug

applying the diff you mentioned i'm getting a:
`thread 'main' panicked at 'OutgoingConnectionError { connection_id: ConnectionId(1), peer_id: None, error: Transport([("/ip4/127.0.0.1", Other(Custom { kind: Other, error: MultiaddrNotSupported("/ip4/127.0.0.1") }))]) }'`

**Comment by mxinden** [comment]
Help is much appreciated. Also since https://github.com/libp2p/rust-libp2p/pull/3454 is merged now, I don't suspect any larger merge conflicts to come up.

> so far im having a bit of trouble recreating this bug
> 
> applying the diff you mentioned i'm getting a: `thread 'main' panicked at 'OutgoingConnectionError { connection_id: ConnectionId(1), peer_id: None, error: Transport([("/ip4/127.0.0.1", Other(Custom { kind: Other, error: MultiaddrNotSupported("/ip4/127.0.0.1") }))]) }'`

I suspect this to be due to an error I made above. `--relay-address /ip4/127.0.0.1` should instead be a full QUIC address, e.g. `--relay-address /ip4/127.0.0.1/udp/<listen-port/quic-v1`. Does that fix the issue you are seeing?

**Comment by eserilev** [comment]
Thanks for the additional info

I took a step back and just tried to run this example as is, with the example command found in the readme, but I'm getting a Connection Refused error message 

applying the diff you mentioned and running with the following command:

`cargo run -- --mode listen --secret-key-seed 0 --relay-address /ip4/127.0.0.1/udp/4005/quic-v1`

I'm getting a HandshakeTimedOut error. I'm probably missing something here, so if you have any additional tips/hints please let me know. In the meantime I'll keep playing around with this and see how far I can get

**Comment by jxs** [comment]
Have you tried this after #3454 @mxinden?

UPD:

was able to reproduce your error with the ping example.
