### ISSUE TITLE
Replacement of serde_cbor for request_response protocol

### ISSUE THREAD

**Issue by zeeshanlakhani** [libp2p/rust-libp2p#4182]
Due to being unmaintained (our project received an advisory), should we also replace serde_cbor from the [request_response protocol](https://github.com/libp2p/rust-libp2p/blob/master/protocols/request-response/Cargo.toml#L23) with alternatives, e.g. [ciborium](https://crates.io/crates/ciborium) or [minicbor](https://crates.io/crates/minicbor)?

**Comment by thomaseizinger** [comment]
We need something that is `serde` compatible. I don't mind the specific implementation though :)

Are you willing to send a PR?

**Comment by zeeshanlakhani** [comment]
> We need something that is `serde` compatible. I don't mind the specific implementation though :)
> 
> Are you willing to send a PR?

Yep. Will do. Will prob incorporate https://github.com/quininer/cbor4ii.

**Comment by zeeshanlakhani** [comment]
And pr'ed: https://github.com/libp2p/rust-libp2p/pull/4187.
