### ISSUE TITLE
dcutr: DCUtR protocol is no longer advertised

### ISSUE THREAD

**Issue by dariusc93** [libp2p/rust-libp2p#4261]
## Summary

Not sure if this now an intended behaviour, but identify no longer show `/libp2p/dcutr` being listed apart of the protocols when it is expected to show. This can easily be observed by using the examples and monitor the identify event that was received by the relay

## Expected behaviour

`/libp2p/dcutr` to be listed in the supported protocols

## Actual behaviour

`/libp2p/dcutr` is not listed in the supported protocols

## Version

- libp2p version (version number, commit, or branch): 0.52.1 and master (as of commit 1acf4a5e17fe2c5c172cdd91d1ccd15b9b1004e3)

## Would you like to work on fixing this bug?

Yes / No / Maybe.

**Comment by mxinden** [comment]
I suspect that it is no longer advertised on direct connections (e.g. a direct connection to a relay node) as `libp2p-dcutr` uses a dummy::ConnectionHandler` on direct, i.e. non-relayed, connections:

https://github.com/libp2p/rust-libp2p/blob/1ebff97de74c8a4906bc0aafebbebe8ade2b5d2d/protocols/dcutr/src/behaviour_impl.rs#L189-L227

Does this pose an issue @dariusc93? Given that one would never try to hole-punch a direct connection, does one need to advertise the `/libp2p/dcutr` on a direct connection?

**Comment by dariusc93** [comment]
While it does not causes an issue, it does being to question on if the peer actually supports the protocol or not when looking at the protocols supplied by `identify` or any supplied by the connection handler.

**Comment by thomaseizinger** [comment]
> While it does not causes an issue, it does being to question on if the peer actually supports the protocol or not when looking at the protocols supplied by `identify` or any supplied by the connection handler.

Those two should always be identical. "A node supporting a protocol" means "there is a high chance that opening a stream with this protocol to the peer will succeed". It doesn't give you any information on which protocols the remote might use to establish a stream to you.

At least that is how I always looked at it, maybe others have a different view.
