### ISSUE TITLE
RUSTSEC-2022-0093

### ISSUE THREAD

**Issue by jxs** [libp2p/rust-libp2p#4327]
## Description

[RUSTSEC-2022-0093](https://rustsec.org/advisories/RUSTSEC-2022-0093) has just been issued which will make `cargo deny` fail on the CI. I tried updating `identity` and `noise` that depend on it, but we are blocked by https://github.com/mcginty/snow/issues/164

**Comment by thomaseizinger** [comment]
Will this be a patch-release in both cases? I hope 🤞

**Comment by mxinden** [comment]
Thank you @jxs for raising attention for this.

Trying to understand the impact of this vulnerability.

### `libp2p-identity`

When creating a `Keypair`, we use the bytes representation which contains both the public and the private key.

https://github.com/libp2p/rust-libp2p/blob/2c4c961d693414dccf338cbe8fe327bc57279609/identity/src/ed25519.rs#L48-L59

I don't see how an attacker would be able to influence the input public key to extract the private key, as the latter is already known to the attacker at that point.

### `libp2p-noise`

As far as I can tell `libp2p-noise`, i.e. `snow`, is using `[curve25519‑dalek](https://github.com/dalek-cryptography/curve25519-dalek/blob/main/curve25519-dalek)` and not [ed25519‑dalek](https://github.com/dalek-cryptography/curve25519-dalek/blob/main/ed25519-dalek). See [`snow`'s `Cargo.toml`](https://github.com/mcginty/snow/blob/master/Cargo.toml).

The RUSTSEC is only for [curve25519‑dalek](https://github.com/dalek-cryptography/curve25519-dalek/blob/main/curve25519-dalek).

@jxs am I missing something?

**Comment by jxs** [comment]
Ah, sorry for not being completely clear in the previous comment. 
The RUSTSEC is for `ed25519-dalek` which we use on `identity`. When i tried updating it, it conflicts with `snow` as `snow` uses `curve25519-dalek` `=4.0.0-rc.1` which conflicts with updating `ed25519-dalek` to `2.0.0` because it [uses  `curve25519-dalek` `4.0.0`](https://github.com/dalek-cryptography/curve25519-dalek/blob/main/ed25519-dalek/Cargo.toml#L28)

**Comment by kayabaNerve** [comment]
A new version of snow has been released.

**Comment by mxinden** [comment]
Great. Would either of you @jxs or @kayabaNerve mind sending a pull request updating [curve25519‑dalek](https://github.com/dalek-cryptography/curve25519-dalek/blob/main/curve25519-dalek) across the project?
