### ISSUE TITLE
feat(Ping): make it possible to distinguish between a reply to a ping sent out and a reply sending out in response to a ping

### ISSUE THREAD

**Issue by dhuseby** [libp2p/rust-libp2p#4330]
## Description

[Currently](https://docs.rs/libp2p/0.52.2/libp2p/ping/struct.Event.html#fields) the event emitted by the Ping behavior does not contain any information distinguishing between when we've received a reply to a ping we sent out and when we're sending out a reply to a ping we've received.

## Motivation

There are lots of useful things to be known from distinguishing between inbound replies to pings we sent and outbound replies to pings we received. It can be useful to know if we're receiving pings and how many and from how many different peers. It can also be useful to know when receiving the reply to a ping sent out so that we can calculate and display round trip time to a peer. There are many other situations where the distinction can be useful.

## Requirements

Modify the libp2p::ping::Event to contain an enum with the values Ping and Pong. Ping when the event was triggered by an inbound ping from the remote peer and Pong when the event was triggered by an inbound response to a ping we sent out.

## Are you planning to do it yourself in a pull request?

Maybe

**Comment by thomaseizinger** [comment]
I think this is simply a documentation bug. We don't have the RTT of inbound pings. I wouldn't even know how we'd measure that.

See https://github.com/libp2p/rust-libp2p/blob/master/protocols/ping/src/protocol.rs.

**Comment by dhuseby** [comment]
ok, reading through the code...does this behavior only emit the event when we receive the reply to a ping sent out? if that's the case then this becomes adding an event for whenever we receive a ping from another peer that the protocol is responding to. there's no RTT involved with that case obviously, just a notification of the PeerId and ConnectionId on which we received a ping.

**Comment by dhuseby** [comment]
Also, a tutorial on implementing a connection management heuristic that consumes ping events with RTT/failure and properly closes connections and disconnects peer Ids [as mentioned in the documentation](https://github.com/libp2p/rust-libp2p/blob/2c4c961d693414dccf338cbe8fe327bc57279609/protocols/ping/src/lib.rs#L32).

**Comment by thomaseizinger** [comment]
> ok, reading through the code...does this behavior only emit the event when we receive the reply to a ping sent out? if that's the case then this becomes adding an event for whenever we receive a ping from another peer that the protocol is responding to. there's no RTT involved with that case obviously, just a notification of the PeerId and ConnectionId on which we received a ping.

I don't think I see the value yet for such an event. The ping protocol always works both ways, so if you receive events for pinging a peer, you know that the other peer is pinging you.

I am hesitant to add more layers to the API to report such an event. I quite like its current simplicity of "here is the RTT".

Do you have a usecase where you need to programmatically react specifically to answered inbound pings?

**Comment by thomaseizinger** [comment]
> Also, a tutorial on implementing a connection management heuristic that consumes ping events with RTT/failure and properly closes connections and disconnects peer Ids [as mentioned in the documentation](https://github.com/libp2p/rust-libp2p/blob/2c4c961d693414dccf338cbe8fe327bc57279609/protocols/ping/src/lib.rs#L32).

Can you expand more on what exactly you'd like to have documentation for?

The usual pattern of using a `Swarm` is to use an event-loop. You can write arbitrary code in there in response to a ping-event, including calling connection management APIs like `Swarm::close_connection`.

Without knowing / making up a connection management policy, it is tricky to write a tutorial.

That said, more examples are always welcome if you can come up with something that you think adds value here! :)

**Comment by dhuseby** [comment]
> That said, more examples are always welcome if you can come up with something that you think adds value here! :)

true. not a high priority for me, though it is a good opportunity for a new tutorial.

**Comment by dhuseby** [comment]
So this one has little value. Silencing the noise.
