### ISSUE TITLE
RUSTSEC-2023-0052, RUSTSEC-2023-0053

### ISSUE THREAD

**Issue by jxs** [libp2p/rust-libp2p#4375]
## Description

see [here](https://rustsec.org/advisories/RUSTSEC-2023-0052), [here](https://rustsec.org/advisories/RUSTSEC-2023-0053), it affects us due to `libp2p-websockets` dependency on `futures-rustls`, `0053` is easily fixed by `cargo upgrad`ing but `0052` hasn't yet a solution

## Are you planning to do it yourself in a pull request?

Maybe.

**Comment by thomaseizinger** [comment]
Related: https://github.com/libp2p/rust-libp2p/pull/4378.

**Comment by jxs** [comment]
addressed with https://github.com/libp2p/rust-libp2p/pull/4387#issuecomment-1692110164

**Comment by jxs** [comment]
sorry this is still failing because of `webrtc-rs` via `webrtc-dtls` see https://github.com/webrtc-rs/webrtc/issues/491

**Comment by rainliu** [comment]
@jxs , webrtc v0.9.0 fixed WebPKI security issue

**Comment by jxs** [comment]
thanks @rainliu! @thomaseizinger want me to submit a PR with the update or we can wait for dependabot?

**Comment by thomaseizinger** [comment]
> thanks @rainliu! @thomaseizinger want me to submit a PR with the update or we can wait for dependabot?

It should come in very soon! They always come Sunday night :)

**Comment by thomaseizinger** [comment]
https://github.com/libp2p/rust-libp2p/pull/4475 does not quite resolve this unfortunately. See:

```
    = webpki v0.22.0
      ├── rustls v0.20.8
      │   ├── hyper-rustls v0.23.2
      │   │   └── fantoccini v0.20.0-rc.4
      │   │       └── thirtyfour v0.32.0-rc.8
      │   │           └── interop-tests v0.1.0
      │   └── tokio-rustls v0.23.4
      │       └── hyper-rustls v0.23.2 (*)
      └── tokio-rustls v0.23.4 (*)
```
