### ISSUE TITLE
feat(swarm): print local `PeerId` on `log::info!` level

### ISSUE THREAD

**Issue by mxinden** [libp2p/rust-libp2p#4394]
We currently repeat the line below across all our examples and binaries (e.g. `libp2p-server`):

https://github.com/libp2p/rust-libp2p/blob/c6984dd51db6be8e260be1494f2bbc9052a42206/examples/chat-example/src/main.rs#L49

Instead, let's print it on creation or first `poll` of `Swarm`.

Suggested by @thomaseizinger in https://github.com/libp2p/rust-libp2p/pull/4120#discussion_r1292733378.

**Comment by chirag-bgh** [comment]
@mxinden Does it mean we should only log `PeerId` only on creation or first poll of Swarm and remove any other occurrences?

**Comment by mxinden** [comment]
Yes. Once we have it in `swarm/` we don't need it in any of the `examples/` @chirag-bgh.
