### ISSUE TITLE
Combining quic and client relay transports

### ISSUE THREAD

**Issue by stormshield-ebzh** [libp2p/rust-libp2p#4408]
## Summary

In the dcutr example the transport is built as a combination of tcp + quic + relay

https://github.com/libp2p/rust-libp2p/blob/e36e8ce4456ff059dd54614913b521194d2d478c/examples/dcutr/src/main.rs#L94-L113

I would like to combine quic + relay (without tcp) but compilation fails

## Expected behaviour

I expected that removing the tcp part would compile

## Actual behaviour

Here is the code to build a quic + relay transport

```
let transport = {
        let relay_quic_transport = relay_transport.or_transport(quic::async_std::Transport::new(
            quic::Config::new(&local_key),
        ));

        relay_quic_transport
            .map(|either_output, _| match either_output {
                Either::Left((peer_id, muxer)) => (peer_id, StreamMuxerBox::new(muxer)),
                Either::Right((peer_id, muxer)) => (peer_id, StreamMuxerBox::new(muxer)),
            })
            .boxed()
    };
```

But I get the following error

<details><summary>Debug Output</summary>
<p>

```
   --> examples/dcutr/src/main.rs:102:30
    |
101 |             .map(|either_output, _| match either_output {
    |                                           ------------- this expression has type `futures::future::Either<libp2p::libp2p_relay::client::Connection, (PeerId, libp2p_quic::Connection)>`
102 |                 Either::Left((peer_id, muxer)) => (peer_id, StreamMuxerBox::new(muxer)),
    |                              ^^^^^^^^^^^^^^^^ expected struct `libp2p::libp2p_relay::client::Connection`, found tuple
    |
    = note: expected struct `libp2p::libp2p_relay::client::Connection`
                found tuple `(_, _)`
```
</p>
</details>

## Version
- libp2p version 0.52.2

## Would you like to work on fixing this bug?

Yes , given that you provide some directions

**Comment by thomaseizinger** [comment]
A relayed connection still needs an authentication module and a muxer so you cannot just remove the noise + yamux part. If you put those back, the code should work again :)

**Comment by mxinden** [comment]
@stormshield-ebzh does the above solve your issues? Note that once we merge https://github.com/libp2p/rust-libp2p/pull/4120 this will become significantly easier for you as a user.

**Comment by stormshield-ebzh** [comment]
In fact, i think that #4120 will help.

do you think this will work ?

```
   let mut swarm =
        libp2p::SwarmBuilder::with_existing_identity(generate_ed25519(opts.secret_key_seed))
            .with_quic()
            .with_dns()
            .await?
            .with_relay()
            .with_behaviour(|keypair, relay_behaviour| Behaviour {
                relay_client: relay_behaviour,
                ping: ping::Behaviour::new(ping::Config::new()),
                identify: identify::Behaviour::new(identify::Config::new(
                    "/TODO/0.0.1".to_string(),
                    keypair.public(),
                )),
                dcutr: dcutr::Behaviour::new(keypair.public().to_peer_id()),
            })?
            .build();
```

I will re-test once #4120 will be merged.

**Comment by thomaseizinger** [comment]
It would be great if you could test out #4120 and tell us what you think! But your usecase is definitely what we are aiming to support as first-class.

**Comment by stormshield-ebzh** [comment]
I hopefully be able to check this week

**Comment by stormshield-ebzh** [comment]
@mxinden 
I confirm that the new SwarmBuilder introduced in #4120 allows to successfully combine quic + relay (without tcp) 
thanks

**Comment by mxinden** [comment]
Wonderful. Thanks for reporting back! Glad it is useful.
