### ISSUE TITLE
gossipsub: make `Err` of config builder a proper error

### ISSUE THREAD

**Issue by thomaseizinger** [libp2p/rust-libp2p#4412]
Currently, this is returning `&'static str`, it should return a proper `std::error::Error` instead.

**Comment by p0mvn** [comment]
Hi there. Can I take this?

**Comment by thomaseizinger** [comment]
> Hi there. Can I take this?

Somebody beat to you it I am afraid! https://github.com/libp2p/rust-libp2p/pull/4445

**Comment by mxinden** [comment]
@p0mvn thank you for offering. In case you are still up for contributing:

https://github.com/libp2p/rust-libp2p/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22

**Comment by thomaseizinger** [comment]
@chirag-bgh Can you quickly comment on this issue so I can assign you? Thanks :)

**Comment by chirag-bgh** [comment]
> @chirag-bgh Can you quickly comment on this issue so I can assign you? Thanks :)

Sure.
