### ISSUE TITLE
Design new identify protocols

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#443]
The current identify protocol is not great, so let's design new ones.

I think we need three protocols:
- One that only reports the observed address, for NAT traversal.
- One that reports information about the node, including its name. That could be done in a generic way, in other words fields wouldn't be hard-coded.
- One that only reports the public key of the node.

All that is needed for each protocol is something similar to this: https://github.com/libp2p/rust-libp2p/blob/master/protocols/identify/src/protocol.rs
No need for new transports.

cc https://github.com/paritytech/substrate/issues/398

**Comment by romanb** [comment]
Closing as a result of https://github.com/libp2p/rust-libp2p/pull/1238.
