### ISSUE TITLE
multiformats crates should be moved to a multiformats folder in the workspace rather than misc

### ISSUE THREAD

**Issue by jamesray1** [libp2p/rust-libp2p#444]
Thanks for reorganizing the workspace. However, I think the multiformats crates should be moved to a multiformats folder in the workspace rather than being in misc.

**Comment by tomaka** [comment]
Would be closed by #758 #759

**Comment by romanb** [comment]
Since #759 is done and we still plan to do #758 I don't think there is a need for open issues about where to place that code in libp2p.
