### ISSUE TITLE
replace `custom-clippy` alias with workspace-wide `[lints]` configuration

### ISSUE THREAD

**Issue by thomaseizinger** [libp2p/rust-libp2p#4484]
Currently, we have an alias for standardizing our lint configuration:

https://github.com/libp2p/rust-libp2p/blob/240019f8099142354173d252bbb9d6fffd40be0f/.cargo/config.toml#L3

There is a new cargo feature on the way that allows to configure lints in the `Cargo.toml`. Together with workspace-inheritance,  we should be able to move our lint configuration away from the alias to a configuration that is only specified once in our root `Cargo.toml`.

Here is the tracking issue: https://github.com/rust-lang/cargo/issues/12115

This should stable from `nightly-2023-09-10` onwards. We should be able to start experimenting with this by adding the relevant nightly toolchain here: https://github.com/libp2p/rust-libp2p/blob/240019f8099142354173d252bbb9d6fffd40be0f/.github/workflows/ci.yml#L202-L205 and moving the configuration from `custom-clippy` over to `Cargo.toml`.

Contributions welcome!

**Comment by binsta** [comment]
can i take this one @thomaseizinger

**Comment by thomaseizinger** [comment]
> can i take this one @thomaseizinger

Yes! Thank you :)
