### ISSUE TITLE
kad: rename to follow naming convention across repository

### ISSUE THREAD

**Issue by thomaseizinger** [libp2p/rust-libp2p#4485]
As tracked in https://github.com/libp2p/rust-libp2p/issues/2217, we should rename the `Kademlia` behaviour to `Behaviour` and all related symbols such that users can import it as:

```rust
use libp2p::kad;

let b = kad::Behaviour::new(kad::Config::default());
```

**Comment by PanGan21** [comment]
Hi @thomaseizinger ! I am interested to contribute this issue. Just one question. 
`rename the Kademlia behaviour to Behaviour and all related symbols` apart from `Kademlia` -> `Behaviour` does it mean also to rename `KademliaBucketInserts` -> `BucketInserts`, `KademliaStoreInserts` -> `StoreInserts`, `KademliaConfig` -> `Config` and `KademliaCaching` -> `Caching` ?

**Comment by thomaseizinger** [comment]
> Hi @thomaseizinger ! I am interested to contribute this issue. Just one question. `rename the Kademlia behaviour to Behaviour and all related symbols` apart from `Kademlia` -> `Behaviour` does it mean also to rename `KademliaBucketInserts` -> `BucketInserts`, `KademliaStoreInserts` -> `StoreInserts`, `KademliaConfig` -> `Config` and `KademliaCaching` -> `Caching` ?

In general, yes!

The goal we want to achieve is a balance between symbol length, expressiveness and ambiguity.

The idea is that users can import the `libp2p::kad` module and then refer to symbols as `kad::Config`, `kad::Behaviour`. I'd suggest to think about it like that and rename symbols such that the combined us with the `kad::` prefix makes sense!

To start with, dropping the prefix from all symbols should be good enough. As a 2nd step, I'd recommend going over them and checking, that they still make sense. Depending on how thorough you want to be with that this might require diving into understanding what the protocol does (not sure if you are familiar with Kademlia at all?).

Let us know what your appetite is for working on this and we can set the scope accordingly :)

**Comment by thomaseizinger** [comment]
Note: We want this to be backwards compatible. I'd suggest reading some of the conversations in PRs linked in https://github.com/libp2p/rust-libp2p/issues/2217.
