### ISSUE TITLE
dns: rename to follow naming convention across repositry

### ISSUE THREAD

**Issue by thomaseizinger** [libp2p/rust-libp2p#4486]
As tracked in https://github.com/libp2p/rust-libp2p/issues/2217, we should rename the symbols in the `libp2p::dns` module to follow the naming convention.

This module has two flavours, one for the `tokio` runtime and one for the `async_std` runtime. The `libp2p::tcp` module should provide a good inspiration as to what we'd like the API to look like: https://docs.rs/libp2p/latest/libp2p/tcp/index.html

**Comment by whtsht** [comment]
Hello, @thomaseizinger. I would like to tackle this issue. Is it okay to just separate the type declarations that depend on tokio and async-std into `libp2p::dns::tokio` and `libp2p::dns::async_io`?

**Comment by thomaseizinger** [comment]
> Hello, @thomaseizinger. I would like to tackle this issue. Is it okay to just separate the type declarations that depend on tokio and async-std into `libp2p::dns::tokio` and `libp2p::dns::async_io`?

Great, thank you!

Yeah, more or less. We'd still like to reduce code duplication as much as possible. If you haven't yet, take a look at how the TCP transport is organised. DNS should roughly be the same :)

**Comment by whtsht** [comment]
I checked #2961. It seems that integrating `GenDnsConfig` with `Config` would be beneficial. Once the work is complete, I will submit a pull request.
