### ISSUE TITLE
kad: migrate to `quick-protobuf-codec` crate

### ISSUE THREAD

**Issue by thomaseizinger** [libp2p/rust-libp2p#4487]
In `/misc` we have the `quick-protobuf-codec` crate which makes working with protobuf structs over streams quite easy as you only need to construct a `asynchronous_codec::Framed` type and can read and write full protobuf messages on any `Async{Read,Write}`.

We should make use of this in `libp2p-kad`.

See https://docs.rs/quick-protobuf-codec.

Previous tracking issue: https://github.com/libp2p/rust-libp2p/issues/2500

**Comment by 0xcrust** [comment]
@thomaseizinger I'd love to give this an attempt if you don't mind

**Comment by thomaseizinger** [comment]
> @thomaseizinger I'd love to give this an attempt if you don't mind

Great! I've assigned you! If you look through the tracking issue (#2500) you should be able to find several links to PRs where we've already done something similar! :)

Feel free to open a draft PR at any time if you need help.
