### ISSUE TITLE
noise: migrate to `quick-protobuf-codec`

### ISSUE THREAD

**Issue by thomaseizinger** [libp2p/rust-libp2p#4488]
In `/misc` we have the `quick-protobuf-codec` crate which makes working with protobuf structs over streams quite easy as you only need to construct a `asynchronous_codec::Framed` type and can read and write full protobuf messages on any `Async{Read,Write}`.

We should make use of this in `libp2p-noise`.

See https://docs.rs/quick-protobuf-codec.

Previous tracking issue: https://github.com/libp2p/rust-libp2p/issues/2500

**Comment by 0xcrust** [comment]
Hello! I would like to also give this a shot

**Comment by thomaseizinger** [comment]
> Hello! I would like to also give this a shot

Sure thing! :)
