### ISSUE TITLE
dcutr: consider more than just external addresses

### ISSUE THREAD

**Issue by thomaseizinger** [libp2p/rust-libp2p#4496]
## Description

At the moment, the `dcutr::Behaviour` only sends _external addresses_ to the remote. See https://github.com/libp2p/rust-libp2p/blob/411a0495c5baa8dd714385a68871118ac98bbb61/protocols/dcutr/src/behaviour_impl.rs#L202 and https://github.com/libp2p/rust-libp2p/blob/411a0495c5baa8dd714385a68871118ac98bbb61/protocols/dcutr/src/behaviour_impl.rs#L103-L110

I'd argue this is kind of flawed. We don't need hole punching if we have external addresses. Instead, we should likely gather and use external address _candidates_ as well as allow the user to add their own candidates to the this list.

Likely, this is a left-over from before we landed https://github.com/libp2p/rust-libp2p/pull/3954.

**Comment by thomaseizinger** [comment]
cc @mxinden @jxs

**Comment by mxinden** [comment]
You are right. Good catch @thomaseizinger! `libp2p-dcutr` should use address candidates, e.g. reported through `libp2p-identify`.

**Comment by thomaseizinger** [comment]
> You are right. Good catch @thomaseizinger! `libp2p-dcutr` should use address candidates, e.g. reported through `libp2p-identify`.

FTR: Instead of using `ExternalAddresses`, we should be taking addresses from `FromSwarm::NewExternalAddrCandidate`.
