### ISSUE TITLE
Lots of Clippy warnings on type complexity in 1.72.0

### ISSUE THREAD

**Issue by jmfrank63** [libp2p/rust-libp2p#4506]
## Description

Currently, with 1.72.0 many Clippy warnings on complex types pollute the problem reporting.

## Motivation
To keep the build process clean, these warnings should be addressed.

## Current Implementation
With 1.65.0 these warnings weren't there.

## Are you planning to do it yourself in a pull request?
I am new to this crate, but I am willing to do a PR if this is welcomed. There aren't any major code changes,
all the warnings could be addressed with `#[allow(clippy::type_complexity)]`. However, a few can be addressed by actually refactoring types. I am willing to follow recommendations, on how to handle this (if at all).
The tests passed on my Mac M1, except for test_discovery_async_std_ipv6. However, the tests failed both on the unmodified master branch and on my PR branch.
If the PR makes sense, I would investigate the ipv6 issue and add the necessary docs, et al. (as described by the PR instructions).
There is also an issue with `rust-analyzer` complaining about Option::take() having the wrong number of arguments, for it detects the take as Iterator take. This could in theory be fixed by qualifying, but I don't think it is a great idea to work around a bug that is not related to the code itself. But `vscode` will show errors (and likely other editors which use `rust-analyzer` as well).

Yes

**Comment by thomaseizinger** [comment]
We are ignoring the type complexity lint and some others as well as they are very noisy and don't necessarily improve readability.

See https://github.com/libp2p/rust-libp2p/blob/508cad1f0db1149e586cd3aebda0642dfc11ce63/.cargo/config.toml#L3.

All others are enforced in CI! :)

If you are running clippy locally, use the `custom-clippy` alias!
