### ISSUE TITLE
Optimize `read_substream` in mplex

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#451]
It does quite a lot of data copies in the end and consumes a lot of CPU.

**Comment by romanb** [comment]
It is unclear what remains to be done here after https://github.com/libp2p/rust-libp2p/pull/456 and considering the changes `libp2p-mplex` has gone though over time. It would obviously still be good to have meaningful benchmarks but we still have the overarching https://github.com/libp2p/rust-libp2p/issues/744. So I'm going to close this and suggest new tickets to be created for specific performance issues with the latest `libp2p-mplex`.
