### ISSUE TITLE
`dcutr::Event::DirectConnectionUpgradeSucceeded` should include the `ConnectionId`

### ISSUE THREAD

**Issue by thomaseizinger** [libp2p/rust-libp2p#4519]
This would be useful to know, which of our connections is the direct connection to this peer.

**Comment by dariusc93** [comment]
Should the same be said for `Event::DirectConnectionUpgradeFailed` too?

**Comment by thomaseizinger** [comment]
> Should the same be said for `Event::DirectConnectionUpgradeFailed` too?

I guess so? We do certainly have a `ConnectionId` for that dial attempt so we could report it. I guess that makes sense for consistency's sake.
