### ISSUE TITLE
swarm: Default to keeping connections alive whilst there are active streams

### ISSUE THREAD

**Issue by thomaseizinger** [libp2p/rust-libp2p#4520]
Currently, whether or not a connection has active streams does not affect its keep-alive. However, for most protocols, that is the default. The only exception that we know of here is the ping protocol.

As a first step, we want to incorporate "counting" of active streams in the keep-alive algorithm of a connection. This code lives here: https://github.com/libp2p/rust-libp2p/blob/c52a2fc3af0d4f348068746edcd8326e6f237d0e/swarm/src/connection.rs#L348-L386

To count the number of active streams on a connection, we embed an `Arc<()>` in each stream. This is possible in a backwards-compatible way because `Stream` is instantiated within this module.

- At the start of the connection, we construct an `Arc<()>` as a stream counter and store it in `Connection`.
- Every time we make a new stream, be in inbound or outbound, we `clone` this `Arc` and store it in the `Stream`
- At any point, we can check how many streams there are by calling [`Arc::strong_count`](https://doc.rust-lang.org/std/sync/struct.Arc.html#method.strong_count).

If this count reaches `1`, we know that there are no active streams on this connection. This should be a _pre-condition_ to asking the `ConnectionHandler` via `ConnectionHandler::connection_keep_alive` whether or not the connection is still needed.

Overall, this will allow protocols to not having to do any tracking on their own in regards to whether to keep the connection alive because there are still streams running on it.

As a second step, we need to introduce an "opt-out" functionality for this behaviour:

```rust
impl Stream {
	pub fn no_keep_alive(&mut self);
}
```

Internally, this needs to downgrade the `Arc<()>` to a `Weak<()>` which automatically reduces the `strong_count` and thus "ignores" this stream. The ping protocol needs to call this function on every `Stream` received to not keep the connection alive if the only remaining streams are ping-streams.

Within the same PR, we should remove any book-keeping from protocols around active streams to make sure that this mechanism actually works.

**Comment by thomaseizinger** [comment]
@leonzchang I see you opened a draft PR for this, exciting! :)
Mind commenting on her so I can assign you to this issue?

**Comment by leonzchang** [comment]
Sure please☺️
