### ISSUE TITLE
quic: returning ListenerClosed on connection closed internally

### ISSUE THREAD

**Issue by jxs** [libp2p/rust-libp2p#4588]
## Current behaviour

In lighthouse while trying to shutdown the client, [SwarmEvent::Listenerclosed](https://github.com/sigp/lighthouse/blob/441fc1691b69f9edc4bbdc6665f3efab16265c9b/beacon_node/lighthouse_network/src/service/mod.rs#L1535-L1544) was returned and logged:
```
CRIT Listener closed reason: Err(Custom { kind: Other, error: Transport(Custom { kind: Other, error: Right(EndpointDriverCrashed) }) }), addresses: [\"/ip4/127.0.0.1/udp/9001/quic-v1\", \"/ip4/141.95.85.227/udp/9001/quic-v1\"], service: libp2p
```
In the `quic` transport, when polling the `Listener` :
https://github.com/libp2p/rust-libp2p/blob/399eaa39156f756956f38fab20083293da826fdd/transports/quic/src/transport.rs#L573-L595

as `quinn` (unlike tokio's `TcpStream` which cannot be closed) [`Accept`](https://docs.rs/quinn/0.10.2/quinn/struct.Accept.html) `Future` impl is `Option`, it yields `None` when the endpoint has been closed and `quic::Transport` returns `SwarmEvent::ListenerClosed`.

This is different from the other transports, namely `tcp` which only returns `SwarmEvent::ListenerClosed` when `Transport::remove_listener` is called.

## Possible Solution
Can we not send `SwarmEvent::ListenerClosed` when `Accept` returns `None` and just return `Poll::Ready(None)` to match other transports? @kpp what was the reason for considering `Accept` returning `None` a `EndpointDriverCrashed` ?

thanks
## Version

- libp2p version (version number, commit, or branch):

## Would you like to work on fixing this bug?

Yes

**Comment by thomaseizinger** [comment]
> Can we not send `SwarmEvent::ListenerClosed` when `Accept` returns `None` and just return `Poll::Ready(None)` to match other transports?

I think this is what is currently happening, right? We call `c.lose` on the listener which queues a `ListenerClosed` event:

https://github.com/libp2p/rust-libp2p/blob/399eaa39156f756956f38fab20083293da826fdd/transports/quic/src/transport.rs#L485-L502

This is then returned and eventually we return `Poll::Ready(None)`:

https://github.com/libp2p/rust-libp2p/blob/399eaa39156f756956f38fab20083293da826fdd/transports/quic/src/transport.rs#L563-L568

We might want to use a different reason though. I'd assume that `Accept` returning `None` means that the socket was closed gracefully and we should probably just pass `Ok(())` to `.close`.

**Comment by jxs** [comment]
> > Can we not send `SwarmEvent::ListenerClosed` when `Accept` returns `None` and just return `Poll::Ready(None)` to match other transports?
> 
> I think this is what is currently happening, right? We call `c.lose` on the listener which queues a `ListenerClosed` event:
>This is then returned and eventually we return Poll::Ready(None):

Yeah but we still send `SwarmEvent::ListenerClosed` before returning `Poll::Ready(None)` which doesn't happen in other transports.  I'd expect `SwarmEvent::ListenerClosed` would only be returned when a user specifically asks the swarm to remove such listener.

**Comment by thomaseizinger** [comment]
But `ListenerClosed` specifically has a `reason` field that may be set to an error. That can't be user-requested then, can it?

It sounds to me like the other transports would need to be changed here and not quic. Or am I misunderstanding something?

**Comment by jxs** [comment]
> But `ListenerClosed` specifically has a `reason` field that may be set to an error. That can't be user-requested then, can it?

indeed Thomas, thanks for pointing it out.

> It sounds to me like the other transports would need to be changed here and not quic. Or am I misunderstanding something?

The thing is, other transports don't return `None` when the `Endpoint` has been closed, for example take the [`Stream` implementation](https://docs.rs/tokio-stream/0.1.14/src/tokio_stream/wrappers/tcp_listener.rs.html#29-42) of tokio's [`TcpListener`](https://docs.rs/tokio/1.28.0/tokio/net/struct.TcpListener.html) It never returns `None`. Probably only when dropped .

What you wrote regarding the reason makes sense to me, so if you agree I can submit a PR that changes `Err(Error::EndpointDriverCrashed)` to `Ok(())` when calling `self.close`

**Comment by thomaseizinger** [comment]
> What you wrote regarding the reason makes sense to me, so if you agree I can submit a PR that changes `Err(Error::EndpointDriverCrashed)` to `Ok(())` when calling `self.close`

Yeah, I can't see any issue with that. Annoyingly, we don't know why the endpoint has been closed otherwise we could make it conditional on that.

**Comment by jxs** [comment]
submitted https://github.com/quinn-rs/quinn/issues/1676
