### ISSUE TITLE
request-response: Connection and codec failures are never reported

### ISSUE THREAD

**Issue by oblique** [libp2p/rust-libp2p#4597]
At Eiger we are facing an issue in [celestia-node-rs](https://github.com/eigerco/celestia-node-rs): As soon as there is a connection error on the request-response protocol, our code gets stall because we were assuming that [`OutboundFailure`](https://docs.rs/libp2p/latest/libp2p/request_response/enum.Event.html#variant.OutboundFailure) would be generated. After investigation we noticed that the same happens if we return an error from [`Codec`](https://docs.rs/libp2p/latest/libp2p/request_response/trait.Codec.html).

This is due to the fact that failures of [`upgrade_outbound`](https://github.com/libp2p/rust-libp2p/blob/f265f39e70cd34f86ab7b1755fc9bebf41164b4b/protocols/request-response/src/handler/protocol.rs#L162-L181)  stopped being reported by https://github.com/libp2p/rust-libp2p/pull/3913. We also noticed that there is an ongoing effort of moving out of the upgrade infrastructure in https://github.com/libp2p/rust-libp2p/pull/3914, which as we understood the issue will get fixed by it.

Is the wrapping the `ConnectionHandler` the only possible solution right now? 

When do you expect to merge #3914? Is there anything pending? Is there any way we can help?

**Comment by thomaseizinger** [comment]
> When do you expect to merge #3914? Is there anything pending? Is there any way we can help?

It will be merged with the next breaking release which we are aiming to start next week or the week after.

**Comment by thomaseizinger** [comment]
> This is due to the fact that failures of [`upgrade_outbound`](https://github.com/libp2p/rust-libp2p/blob/f265f39e70cd34f86ab7b1755fc9bebf41164b4b/protocols/request-response/src/handler/protocol.rs#L162-L181) stopped being reported by #3913

Hmm, that wasn't the intention. We should have probably returned the error and not just log it. If the current type signatures allow it, I am happy to merge and release a patch that forwards the error (but not by closing the connection).

**Comment by oblique** [comment]
Closing. This was fixed long ago.
