### ISSUE TITLE
Add a transport capability system

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#46]
A transport protocol like UDP doesn't guarantee reliability or ordering, but some upper layer protocols may require that the transport supports these characteristics.

Therefore it wouldn't be a bad idea to add methods to the `Transport` trait so that upper layers can check for these capabilities.

**Comment by Vurich** [comment]
The only problem I can see with this is it makes writing new `Transport`s a PITA, since you have to manually write which capabilities the type supports. This is true whether we do it in the type system or at runtime.

**Comment by tomaka** [comment]
I can see only two capabilities:

- Reliability ; are all packets guaranteed to arrive to destination?
- Ordering ; are packets arriving in order?
- Congestion control ; can we get flooded with data? (not sure whether this capability is useful to know though)

Examples: TCP and UTP would provide all three. UDP would provide none. Multiplex would remove the congestion control capability.

**Comment by tomaka** [comment]
One thing to note is that the `Transport` trait is currently not adapted to UDP.
The socket type that the trait implementation must provide must implement `AsyncRead + AsyncWrite`, which considers that data acts as a contiguous stream. In other words, it is not adapted to UDP.

A fix would be to replace the `AsyncRead + AsyncWrite` requirements with `Stream + Sink`. The TCP implementation would be free to split the packets of the `Sink` into multiple actual packets. However doing this properly would require support for HKTs in Rust, because we don't know the type of the items to use for the `Stream` and `Sink`.

**Comment by Vurich** [comment]
Maybe we can have `StreamTransport`, `PacketTransport` and `ReliablePacketTransport`/`OrderedPacketTransport` (the latter two being marker traits extending `PacketTransport`). We can `impl PacketTransport for T where T: StreamTransport` treating the whole stream as one huge packet, so most implementers just need to implement `StreamTransport` and don't need to care about reliability/order.

**Comment by Vurich** [comment]
How about this design:

```rust
pub trait StreamTransport: Transport where Self::Output: AsyncRead + AsyncWrite {}
pub trait PacketTransport: Transport where Self::Output: Stream {}
pub trait ReliablePacketTransport: PacketTransport where Self::Output: Stream {} // Need to reiterate bounds
pub trait OrderedPacketTransport: PacketTransport where Self::Output: Stream {} // Need to reiterate bounds
```

Then you just implement the correct markers for you

**Comment by tomaka** [comment]
I'm not sure I understand your design correctly, but providing an implementation of `AsyncRead + AsyncWrite` requires reliability and ordering though, as the implem. needs to be able to split the stream at any point.

**Comment by tomaka** [comment]
Transports must be reliable and ordered.

Because of this, one cannot just implement a raw UDP transport. It has to be a protocol on top of UDP.

**Comment by tomaka** [comment]
Actually, `Transport` now generate an `Output`.
Most of the time `Output` must implement `AsyncRead + AsyncWrite`, which implies reliable and ordered. However it is possible for `Output` to be anything.

Because of this, this issue is irrelevant anyway. And it should be possible to create an UDP transport.
