### ISSUE TITLE
feat(kad): add config option for bootstrap interval

### ISSUE THREAD

**Issue by mxinden** [libp2p/rust-libp2p#4730]
When using `libp2p-kad` it is recommended to regularly call `Kademlia::bootstrap` to ensure a healthy routing table.

https://github.com/libp2p/rust-libp2p/blob/fc6efaf56bec7e7ee97ba9c53da6b5856aa44391/protocols/kad/src/behaviour.rs#L846-L865

See e.g. `libp2p-server` calling `Kademlia::bootstrap` on an interval.

https://github.com/libp2p/rust-libp2p/blob/fc6efaf56bec7e7ee97ba9c53da6b5856aa44391/misc/server/src/main.rs#L26

Instead of requiring each user to setup their own interval on which to call `Kademlia::bootstrap`, provide a new option in `libp2p_kad::Config`. Something along the lines of:

``` diff
  /// The configuration for the `Kademlia` behaviour.
  ///
  /// The configuration is consumed by [`Behaviour::new`].
  #[derive(Debug, Clone)]
  pub struct Config {
+    bootstrap_interval(Option<Duration>), 
```

**Comment by thomaseizinger** [comment]
Is "bootstrap" a kademlia term (from the paper)? Maybe we should call it "refresh"?

**Comment by PanGan21** [comment]
Hi, I was looking at this issue. Since a new `refresh_interval` will be added in the Config of Kademlia, isn't it required to move the following logic from the server in the kademlia behaviour?
```
if let Poll::Ready(()) = futures::poll!(&mut bootstrap_timer) {
            bootstrap_timer.reset(BOOTSTRAP_INTERVAL);
            let _ = swarm.behaviour_mut().kademlia.as_mut().map(|k| {
                k.bootstrap();
            });
        }
``` 
Otherwise the interval should be exposed from kademlia in a way to the client code I think

**Comment by thomaseizinger** [comment]
Yes correct. We will have to have a timer within the `libp2p_kad::Behaviour` struct that is `poll`ed as part of `Behaviour::poll` (and calls `self.bootstrap()` when the timer fires). Does that make sense?

**Comment by PanGan21** [comment]
Makes sense yes. Can I give it a try?
