### ISSUE TITLE
Activate `clippy::manual_let_else` lint

### ISSUE THREAD

**Issue by thomaseizinger** [libp2p/rust-libp2p#4741]
### Description

We have recently upgraded to MSRV 1.73. This gives us access to `let else` which shipped in 1.65. Clippy has a lint that can detect "manual" implementations of `let else` via `match` uses that only have one other match arm: https://rust-lang.github.io/rust-clippy/master/index.html#/manual_let_else

I briefly activated this lint in the MSRV bump PR but it turned up too many results to fix at the time. This issue tracks activating the `let else` lint by adding it here as `warn`:

https://github.com/libp2p/rust-libp2p/blob/fb48fbb3b190827c78c122ca537acd3c2092da9c/Cargo.toml#L132-L137

### Motivation

We want to follow along with idiomatic usage of Rust. `let else` usually reduces the indentation of the happy path in a function.

### Current Implementation

We have many instances of "manua" let else in the code base.

### Are you planning to do it yourself in a pull request ?

No

**Comment by eserilev** [comment]
I'd like to pick this one up
