### ISSUE TITLE
Implement private networks

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#476]
Add an equivalent to https://github.com/libp2p/js-libp2p-pnet/

**Comment by rklaehn** [comment]
I might need this in the near future. Can we get a hint how we would go about implementing this?

**Comment by tomaka** [comment]
The implementation would be very similar to libp2p-secio: a struct that implements `OutboundUpgrade` and `InboundUpgrade`, and that apply the cipher on the stream of data by wrapping around the `AsyncRead`/`AsyncWrite`.
The only major difference with secio is the lack of handshake, and that we pass the private shared key directly in the configuration.

**Comment by rklaehn** [comment]
So I would sneak a manual upgrade into the place where the transport is built, like below, except with a yet to be written`PrivateSwarmConfig(swarm_key)` instead of the `PlainText1Config`?

```rust
    Ok(CommonTransport::new()?
        .and_then(move |io, endpoint| {
            libp2p_core::upgrade::apply(
                io,
                PlainText1Config{},
                endpoint,
                libp2p_core::transport::upgrade::Version::V1,
            )
        })
        .upgrade(core::upgrade::Version::V1)
        .authenticate(secio::SecioConfig::new(keypair))
        .multiplex(core::upgrade::SelectUpgrade::new(yamux::Config::default(), mplex::MplexConfig::new()))
        .map(|(peer, muxer), _| (peer, core::muxing::StreamMuxerBox::new(muxer)))
        .timeout(Duration::from_secs(20)))
```

**Comment by tomaka** [comment]
Yes! Normally it should work.

**Comment by rklaehn** [comment]
Very WIP, but does this go into the right direction?

https://github.com/libp2p/rust-libp2p/pull/1385

**Comment by tomaka** [comment]
I haven't looked into the details of the logic, but the general structure is what I'd expect, yes.

**Comment by tomaka** [comment]
Done in #1385
