### ISSUE TITLE
Non-strict Protocol Negotiation in rust-libp2p's multistream-select

### ISSUE THREAD

**Issue by frystal** [libp2p/rust-libp2p#4772]
### Summary

I find bug in the select function in multistream-select that does not strictly adhere to the libp2p specification for [Protocol Negotiation](https://github.com/libp2p/specs/blob/master/connections/README.md#protocol-negotiation).
 
As per the specification, if either side receives anything other than the multistream protocol id as the first message, they should abort the negotiation process. However, the implementation does not enforce this. The implementation https://github.com/libp2p/rust-libp2p/blob/master/misc/multistream-select/src/dialer_select.rs#L179C26-L195. If the first message does not contain the message header, it is ignored.

Moreover, the specification dictates that if a protocol is not supported, the listener must respond with the string "na" to denote that the requested protocol is Not Available. This is not the case when the node receives protocols are "Message::ListProtocols". During a multiplex handshake with a remote rust-libp2p peer, upon sending multistream, yamux, and a random protocol, the remote node responds only to the first two protocols and then immediately terminates the connection.
![image](https://github.com/libp2p/rust-libp2p/assets/44425340/27013f54-ac53-4471-a833-0ff8b43cb657)

I would be grateful to be told the reasoning behind this two behaviors that seems different from the specification requires.

### Expected behavior

1. If the node receives anything other than the multistream protocol id as the first message, they should abort the negotiation process.
2. The nodes should send back multistream, yamux, and "na".

### Actual behavior

1. When the node initiates a connection to a remote peer and the first message received does not include the multistream protocol id, the current implementation does not break the connection.
2. The nodes only send back multistream, yamux and break the connection.

### Would you like to work on fixing this bug ?

Maybe

**Comment by thomaseizinger** [comment]
> The nodes should send back multistream, yamux, and "na".

Are you expecting to speak that first protocol on a yamux stream? Are you using 0RTT negotiation (i.e. `Version::V1Lazy` on the dialer end)?

> If the node receives anything other than the multistream protocol id as the first message, they should abort the negotiation process.

That is probably right although I surprised this is not the case. The catch-all branch should error: https://github.com/libp2p/rust-libp2p/blob/ec157171a7c1d733dcaff80b00ad9596c15701a1/misc/multistream-select/src/dialer_select.rs#L195

**Comment by frystal** [comment]
> Are you expecting to speak that first protocol on a yamux stream? Are you using 0RTT negotiation (i.e. Version::V1Lazy on the dialer end)?

What do it mean "first protocol on a yamux stream". Yes, during the multiplexer negotiation, after the yamux protocol, we append a random protocol. According to the expected behavior, rust-libp2p should act as the responder and handle this random protocol by answering "na". However, the current issue is that instead of processing the random protocol as expected, rust-libp2p is breaking the connection. 

Initiator demo log:
![image](https://github.com/libp2p/rust-libp2p/assets/44425340/34f57da3-aac6-493f-9aad-20faf03a805d)

rust-libp2p as responder log:
![image](https://github.com/libp2p/rust-libp2p/assets/44425340/4d8e2252-e62e-4aae-b763-673a4af84f98)


> That is probably right although I surprised this is not the case. The catch-all branch should error:

To illustrate this problem more clearly, I have created a small demo. After the noise security negotiation, the remote sends the yamux protocol negotiation. At this point, we only respond to the yamux protocol and not the multistream protocol. According to the specification, the connection should break due to the absence of the multistream protocol as the first message. However, it continues to the yamux connection instead. Could this be due to the use of Version::V1Lazy?

Initiator demo log:

![image](https://github.com/libp2p/rust-libp2p/assets/44425340/295b12fa-3627-4b1e-9291-398c8b71b3c7)

rust-libp2p as responder log:

![image](https://github.com/libp2p/rust-libp2p/assets/44425340/8cfda478-7371-4cee-b2dc-001a905f1d07)

**Comment by thomaseizinger** [comment]
> > Are you expecting to speak that first protocol on a yamux stream? Are you using 0RTT negotiation (i.e. Version::V1Lazy on the dialer end)?
> 
> What do it mean "first protocol on a yamux stream". Yes, during the multiplexer negotiation, after the yamux protocol, we append a random protocol.

Once you've successfully negotiated yamux as a protocol, the stream/connection is assumed to now be a yamux connection. multistream-select implicitly ends as soon as the first protocol is successfully negotiated.

If you want to choose between multiple muxers, you'll need to do several roundtrips:

- First attempt to negotiate yamux
- If you receive n/a, send the next muxer protocol etc

If you want to use this 2nd protocol as a yamux stream, the bytes have to be correctly formatted as a yamux frame. That is what we are expecting which is why you see the parse error.

**Comment by thomaseizinger** [comment]
Which multistream-select implementation are you using? Are you writing your own?

**Comment by frystal** [comment]
> > > Are you expecting to speak that first protocol on a yamux stream? Are you using 0RTT negotiation (i.e. Version::V1Lazy on the dialer end)?
> > 
> > 
> > What do it mean "first protocol on a yamux stream". Yes, during the multiplexer negotiation, after the yamux protocol, we append a random protocol.
> 
> Once you've successfully negotiated yamux as a protocol, the stream/connection is assumed to now be a yamux connection. multistream-select implicitly ends as soon as the first protocol is successfully negotiated.
> 
> If you want to choose between multiple muxers, you'll need to do several roundtrips:
> 
> * First attempt to negotiate yamux
> * If you receive n/a, send the next muxer protocol etc
> 
> If you want to use this 2nd protocol as a yamux stream, the bytes have to be correctly formatted as a yamux frame. That is what we are expecting which is why you see the parse error.

Ok, thank you for your kind explain. 
For the  multistream-select implementation, the demo node is on my own, the rust-libp2p node is the version  "multistream-select 0.13.0" from the rust-libp2p example.

**Comment by frystal** [comment]
Do you consider the second issue where the node bypasses the verification process of the multistream protocol to be a bug?

**Comment by thomaseizinger** [comment]
> Do you consider the second issue where the node bypasses the verification process of the multistream protocol to be a bug?

Yeah that might be worthwhile fixing! I'll close this issue in favor of https://github.com/libp2p/rust-libp2p/issues/4792 :)
