### ISSUE TITLE
The hashes ordering in the secio handshake can be identical

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#479]
I didn't think this was possible, but apparently there are crashes: https://github.com/paritytech/polkadot/issues/18

Even if the two network public keys are identical, we incorporate the random nonces and that should be enough to remove any possibility of a collision.

**Comment by tomaka** [comment]
@twittner Any idea?

**Comment by twittner** [comment]
It seems that for some unknown reason we read a remote key and nonce equal to ours. Given that a simple echo of our local proposition could do this I don't think we should panic. However I don't have an explanation why this happened here.

**Comment by tomaka** [comment]
Why this happened remains a mystery.
However we now properly return an error, and this error has never been seen in the wild in the past few months, so let's close this.
