### ISSUE TITLE
relay: random crashes due to debug assertion

### ISSUE THREAD

**Issue by dariusc93** [libp2p/rust-libp2p#4822]
### Summary

Although i have not been able to reproduce it myself, the following lines are being asserted when attempting to use a relay.

```
panicked at /.cargo/registry/src/index.crates.io-6f17d22bba15001f/libp2p-relay-0.17.0/src/priv_client/handler.rs:340:13:
assertion `left == right` failed: expect to have one active request per inflight stream
  left: 10
 right: 11
```

https://github.com/libp2p/rust-libp2p/blob/0ef6feb397ede286dcd8c9831dc41fb288426885/protocols/relay/src/priv_client/handler.rs#L340-L344

This behaviour seems to be at random and not consistent to where i could reproduce it under the same settings.

### Expected behavior

Not to panic at the lines above

### Actual behavior

Randomly panics due to the debug assertion mention above

### Version

0.53

### Would you like to work on fixing this bug ?

Maybe

**Comment by thomaseizinger** [comment]
This is definitely a bug! I'll look into it.

**Comment by dariusc93** [comment]
Thanks @thomaseizinger. The only other panic if the debug assertion is ignored is from https://github.com/libp2p/rust-libp2p/blob/0ef6feb397ede286dcd8c9831dc41fb288426885/protocols/relay/src/priv_client/handler.rs#L384-L387
