### ISSUE TITLE
Expose libp2p::builder::phase::other_transport::TransportError

### ISSUE THREAD

**Issue by nazar-pc** [libp2p/rust-libp2p#4824]
### Summary

In 0.53.0 there is `libp2p::builder::phase::other_transport::TransportError` returned from `SwarmBuilder::with_other_transport` method, which while public, is not re-exported and thus unusable directly.

### Expected behavior

Public types like this should be available from the outside

### Actual behavior

Currently `libp2p::builder::phase::other_transport::TransportError` is located in a private sub-module.

### Would you like to work on fixing this bug ?

Maybe

**Comment by thomaseizinger** [comment]
Thanks for opening this! Happy for it to be re-exported from the crate-root.

**Comment by elenaf9** [comment]
Fixed in #5726.
