### ISSUE TITLE
connection-limits: Add functions to update `ConnectionLimits`

### ISSUE THREAD

**Issue by dariusc93** [libp2p/rust-libp2p#4826]
### Description

Add functions in `libp2p-connection-limits` to update `ConnectionLimits`. 

### Motivation

This would allow developers to update the limits accordingly without needing to restart the node to apply the changes. 

### Current Implementation

`libp2p-connection-limits` has limits that are fixed and can only be adjusted/modified prior to passing it to the behaviour. 

### Are you planning to do it yourself in a pull request ?

Yes

**Comment by thomaseizinger** [comment]
Hmm, I guess re-initializing the behaviour doesn't work here because we lose the internal state. I think it makes sense to add a `limits_mut` function.

**Comment by mxinden** [comment]
I assume that this is more difficult than it seems on the surface. Say that a node has a limit of 100 and current connection count of 75. Say that a user sets the new limit to 50. Does it now close 25 connections? If so, which ones?

**Comment by dariusc93** [comment]
> I assume that this is more difficult than it seems on the surface.

Correct, since at this time there is no way to notify swarm about this change and let it make the decision on which connection to shed. Might have to postpone this one for now and maybe open up some type of future discussion to talk about the connection manager.

**Comment by thomaseizinger** [comment]
> Does it now close 25 connections?

We could just say "no" to that. Updating the limits simply means we'll not allow new connections until it drops below the new limit.

**Comment by mxinden** [comment]
As long as it is documented well, I think this is a good idea.
