### ISSUE TITLE
Move libp2p::SwarmBuilder to libp2p_swarm or a new libp2p_builder crate

### ISSUE THREAD

**Issue by kayabaNerve** [libp2p/rust-libp2p#4827]
### Description

libp2p::SwarmBuilder requires importing the entire libp2p crate despite replacing an API (libp2p_swarm::SwarmBuilder) which didn't. Ideally, libp2p::SwarmBuilder is moved back to libp2p_swarm OR made into a new libp2p_builder crate (which would have a decently smaller subset of the tree size of libp2p).

### Motivation

libp2p::SwarmBuilder replaced libp2p_swarm::SwarmBuilder, and in doing so prevented use of libp2p_swarm to build a Swam using the now-recommended API. The monolithic libp2p crate must be used. While I fully support the UX for the monolithic crate, I'm interested in dependency tree minimization which means limiting mono-crate usage when their parts are available.

This recent movement prevented usage of the parts and forced mono-crate usage. My request restores usage via a component alone. If one uses libp2p for SwarmBuilder and nothing else, as one of my apps does, this would enable downsizing several crates from the potential package tree.

Yes, these excess crates would be linked out, yet I'm unsure if they're ever compiled and they exist in Cargo.lock regardless, making analysis more difficult. I'd prefer to simply be as hygenic as possible.

### Requirements

Move libp2p::SwarmBuilder to libp2p_swarm or a new libp2p_builder crate

### Are you planning to do it yourself in a pull request ?

Maybe

**Comment by thomaseizinger** [comment]
> dependency tree minimization

Just don't enable the features of `libp2p` that you don't need and the dependencies should be gone from your lockfile. There are only a handful utilities that are not feature-flagged but none of them bring in heavy dependencies.

The builder has to live in the `libp2p` crate because it needs access to all the sub-crates and offer certain APIs only when they are enabled.

Moving it back into `libp2p-swarm` would create circular dependencies which is not allowed (and also not a good idea).

If we move it into a separate crate, that crate _also_ has to depend on all the various subcrates and the features have to be unified again in the `libp2p` crate. I don't think that is worth the maintenance effort.

**Comment by kayabaNerve** [comment]
While I'm fine closing this, I'd like to note:

1) I did consider if the builder was actively using all sub-crates and thought I notices quite a few not used anywhere in the `builder/` folder. I apologize if I misread that.
2) Feature flagging alone isn't perfect re: lockfile. I have libp2p-quic in my lockfile despite never enabling "quic" nor "full" on any of my libp2p consumers (though a dedicated builder crate would still pull that specific example in).

**Comment by thomaseizinger** [comment]
> 2\. Feature flagging alone isn't perfect re: lockfile. I have libp2p-quic in my lockfile despite never enabling "quic" nor "full" on any of my libp2p consumers (though a dedicated builder crate would still pull that specific example in).

That surprised me. Can you debug what is pulling it in?

**Comment by thomaseizinger** [comment]
> 1. I did consider if the builder was actively using all sub-crates and thought I notices quite a few not used anywhere in the `builder/` folder. I apologize if I misread that.

You are right, it is not using any of the protocols, just the transports.

I guess we could have it in a separate crate that only depends on the transports and swarm? I am not sure it is worth it. It would mean we could potentially also use it in tests of protocol crates but in practice we have `libp2p-swarm-test` for that.

**Comment by kayabaNerve** [comment]
libp2p-quic is solely used by libp2p. I have multiple users of libp2p. None of them enable quic nor full. Cargo.lock just does sometimes include dependencies which aren't feature flagged.

I don't know the exact rules, as I have disabled features and have had dependencies removed from my Cargo.lock.

The practical solution is to run a tool which is accurate and then use its generated report for your analysis of your supply chain. It's just an extra hassle, and I'm decently OCD about the idea of minimization. Not only do I not want to have to perform that extra step, I don't want to risk Cargo ever downloading/building anything which won't end up in use (if some pipeline decides to download everything in the lock file while it works on the build pipeline/real graph building distinctly).

For what I believe to be the tracking issue on this topic, see https://github.com/rust-lang/cargo/issues/10801.

As for this issue, there definitely are fewer deps unused then I thought when I made this issue. Running my tree weighter...

Removing libp2p-quic would remove 9 crates in total from my lock file.
libp2p-dns 9
libp2p-upnp 6
libp2p-tls 5

Please note when I say my lock file, I literally mean *my* lockfile. My project involves a Substrate-based blockchain and an independent blockchain service also using LibP2p. "tree weighter" refers to a script I wrote to identify packages which:

- Have a low amount of users
- Have a high amount of dependencies

A 'most bang for the buck' program if you want to reduce your Cargo.lock (and with it, your compile times and list of people who can inject code every time you run `cargo update`).

Of those, only UPNP is a protocol. So if I were to request this change, and this effort was made, I'd no longer personally include in lock:

- attohttpc
- igd-next
- xml-rs
- xmltree
- libp2p-upnp itself


... that's not horrible. It's not great (like if quic was also removed, it's THE heaviest subtree in my Cargo.lock). A couple of those crates of non-trivial size/scope, and it'd also decrease the amount of consumers for all their dependencies by one (removing one more usage puts me one step closer to removing the crate entirely, if so desired). But I can't justify this as request to libp2p unless there's independent agreement it's a good design.  Since you don't believe this makes sense for rust-libp2p, I'm fine keeping this closed, and I don't find this of sufficient benefit to maintain a fork which has this property/simply deletes UPNP on the assumption my work won't use it (which may or may not be correct).

Thanks again for chiming in :)

EDIT: The libp2p-upnp tree has a much larger dependency tree behind it. Those are the dependencies unique to the libp2p-upnp subtree with no users outside of said subtree. That's why removal of libp2p-upnp from my lockfile would trigger the removal of all of those.

**Comment by thomaseizinger** [comment]
Are you using `resolver = 2` for your workspace? I know that the default resolver has issues with optional dependencies.

**Comment by thomaseizinger** [comment]
I fully agree with you that these dependencies should not show up in your lockfile if you have not enabled the feature. That is either a bug in our feature configuration or cargo's resolver.

**Comment by kayabaNerve** [comment]
I am, and it is an issue with Cargo to some degree. I have no reason to believe it's an issue with libp2p.

EDIT: I made the issue here partly to mitigate, partly because such a sub-crate would enable more theoretical improvements to analysis by explicitly limiting itself. Not because there's an active issue with libp2p.
