### ISSUE TITLE
Make `libp2p::builder::phase::behaviour::BehaviourError` importable

### ISSUE THREAD

**Issue by xDarksome** [libp2p/rust-libp2p#4829]
### Description

Currently there's no way to import `libp2p::builder::phase::behaviour::BehaviourError` as it's inside a private module. 
But it's being exposed in a public interface

### Motivation

No way to use it in user-code without boxing it (again)

### Current Implementation

Not publicly exposed

### Are you planning to do it yourself in a pull request ?

No

**Comment by thomaseizinger** [comment]
Similar to https://github.com/libp2p/rust-libp2p/issues/4824.

Was an oversight in the initial implementation, sorry! Happy to have to exposed in the top-level module. A PR would be much appreciated :)
