### ISSUE TITLE
Remove the MultiaddrFuture in favor of a simple Multiaddr in Transport

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#487]
After #486, there's no reason for the multiaddr produced by the `Transport` to be a future anymore.

Therefore it should be replaced with a simple `Multiaddr`.
Additionally, the `Listener` can produce that `Multiaddr` instead of the `ListenerUpgrade`.

The API of the new swarm should also be simplified in the process.

Depends on #486

**Comment by jamesray1** [comment]
I believe this has been done in https://github.com/libp2p/rust-libp2p/pull/568?

**Comment by tomaka** [comment]
Indeed!
