### ISSUE TITLE
Crash at request-reponse assertion

### ISSUE THREAD

**Issue by nazar-pc** [libp2p/rust-libp2p#4898]
I have request-response protocol crashing on this debug assertion:
https://github.com/libp2p/rust-libp2p/blob/0ceb6580941c010edff2a5689ada2e9e33c773cb/protocols/request-response/src/lib.rs#L656-L656

Logs with following level:
```
RUST_LOG=info,subspace_network=trace,libp2p_core=trace,libp2p_identify=trace,libp2p_swarm=trace,libp2p_kad=trace,libp2p_autonat=trace,libp2p_request_response=trace
```
[dsn-sync-debug-farmer-3.log.zip](https://github.com/libp2p/rust-libp2p/files/13404688/dsn-sync-debug-farmer-3.log.zip)

UPD: While reproducible, the same app with `RUST_LOG=trace`: 
[dsn-sync-debug-farmer-4.log.zip](https://github.com/libp2p/rust-libp2p/files/13404708/dsn-sync-debug-farmer-4.log.zip)

**Comment by thomaseizinger** [comment]
Could this be related to https://github.com/libp2p/rust-libp2p/issues/4773?

Do you use any connection management behaviours like connection limits? If yes, then the temporary fix is to put them as the very first field in your behaviour struct.

**Comment by nazar-pc** [comment]
Possibly related, we do use connection limits indeed. Will move connection limits to the beginning then and closing this as duplicate.
