### ISSUE TITLE
Generate PeerIDs given a target common prefix length (CPL)

### ISSUE THREAD

**Issue by vbhattaccmu** [libp2p/rust-libp2p#4913]
### Description

The current go-libp2p library allows us to generate a random peer ID given a target common prefix length (CPL) (Ref: [here](https://github.com/libp2p/go-libp2p-kbucket/blob/437b9fccd6a22835a67b8fe2a5eae0b92f307224/table_refresh.go#L45)).

The current `PeerID::random()` method in the rust-libp2p library provided [here](https://docs.rs/libp2p/latest/libp2p/struct.PeerId.html#method.random) does not allow us to create IDs with custom CPL.

I will be obliged if this feature is made available.

### Motivation

During the process of crawling DHTs, `target_cpl` can be utilized to generate custom peer IDs with prefixes that are common (only the first target_cpl bits) to bootstrapped peer IDs. These custom peer IDs can then be queried further to discover additional peers that are closer to them. This facilitates the peer discovery process.

### Requirements

A method within PeerID implementation which accepts self and `target_cpl` and generates a random peer ID. An example signature would look something like:- 

```rust
impl PeerID {
   /// Generate a random peer ID for a given CPL
   pub fn random(&self, target_cpl: u32) -> PeerID { ... }
}
```

### Are you planning to do it yourself in a pull request ?

Yes

**Comment by thomaseizinger** [comment]
We tend to be very conservative in what functionality we add to `libp2p-identity` because it is a dependency of the entire `libp2p` ecosystem.

Given that `PeerId` offers, `from_bytes,` am I right to assume that you can implement this on top of the APIs that are currently offered and it doesn't necessarily have to live in `libp2p-identity`?

Before we add an API like this, I'd like to first see it pulling its weight in where we use it.

**Comment by thomaseizinger** [comment]
> Before we add an API like this, I'd like to first see it pulling its weight in where we use it.

For example, it appears that this is mostly useful for Kademlia so it could also just be a private function in kademlia somewhere and doesn't have to go into the public API of `PeerId`.

**Comment by vbhattaccmu** [comment]
> We tend to be very conservative in what functionality we add to `libp2p-identity` because it is a dependency of the entire `libp2p` ecosystem.
> 
> Given that `PeerId` offers, `from_bytes,` am I right to assume that you can implement this on top of the APIs that are currently offered and it doesn't necessarily have to live in `libp2p-identity`?
> 
> Before we add an API like this, I'd like to first see it pulling its weight in where we use it.

Yes, it doesn't need to reside in `libp2p-identity`. This is mostly useful inside Kademlia.

**Comment by thomaseizinger** [comment]
> > We tend to be very conservative in what functionality we add to `libp2p-identity` because it is a dependency of the entire `libp2p` ecosystem.
> > Given that `PeerId` offers, `from_bytes,` am I right to assume that you can implement this on top of the APIs that are currently offered and it doesn't necessarily have to live in `libp2p-identity`?
> > Before we add an API like this, I'd like to first see it pulling its weight in where we use it.
> 
> Yes, it doesn't need to reside in `libp2p-identity`. This is mostly useful inside Kademlia.

Cool, thanks for the confirmation! Optimising DHT queries is definitely something we are very open to :)

**Comment by vbhattaccmu** [comment]
I have been able to successfully generate peer ids from the existing APIs provided using to_bytes() and from_multihash(). I will reach out with a separate pull request on an added method to optimize DHT queries in a while. Would like to close this for now as my issue has been resolved. Thanks!!

**Comment by mxinden** [comment]
@vbhattaccmu the two snippets below might give some additional inspiration:

https://github.com/libp2p/rust-libp2p/blob/bb2b79824d1fd9e4f9cf8395ace810d032363397/protocols/kad/src/behaviour.rs#L1349-L1372

https://github.com/libp2p/rust-libp2p/blob/bb2b79824d1fd9e4f9cf8395ace810d032363397/misc/keygen/src/main.rs#L71-L111
