### ISSUE TITLE
quic: Disconnection is not reported immediately 

### ISSUE THREAD

**Issue by dariusc93** [libp2p/rust-libp2p#4917]
### Summary

When two nodes using quic-v1 are connected and one disconnect, it takes around 30 seconds before the other node disconnects when it should report the disconnection immediately. Changing the timeout does not help either (which by default I had set to 30 seconds but lowering down to 5 seconds does not change the behaviour)

### Expected behavior

For the transport to report the disconnection immediately 

### Actual behavior

Disconnection being reported around 30 seconds after the connection closes. 

### Version

0.53.1

### Would you like to work on fixing this bug ?

Maybe

**Comment by dariusc93** [comment]
I guess I overlooked the timeout on quic itself 

https://github.com/libp2p/rust-libp2p/blob/d851d1b3f82735555c4b3716266793817728cee8/transports/quic/src/config.rs#L30-L31

https://github.com/libp2p/rust-libp2p/blob/d851d1b3f82735555c4b3716266793817728cee8/transports/quic/src/config.rs#L81

With this lowered, it emits the event at around the actual time set (which I lowered to 5 seconds just for testing). If this is the intended behaviour of quic in it reporting the disconnection at the max idle timeout (which default is 30s), I wonder if it should be lowered (though i dont recall this happening in past testing)

**Comment by mxinden** [comment]
Should we just adopt the Quinn default value here?

https://github.com/quinn-rs/quinn/blob/d1bb2b8b13ccf6fd6852e4bffcc983de1364b55d/quinn-proto/src/config.rs#L329

30s on the Internet seems very long to me. I would be fine with 5s as well.

**Comment by dariusc93** [comment]
> Should we just adopt the Quinn default value here?
> 
> https://github.com/quinn-rs/quinn/blob/d1bb2b8b13ccf6fd6852e4bffcc983de1364b55d/quinn-proto/src/config.rs#L329
> 
> 30s on the Internet seems very long to me. I would be fine with 5s as well.

We can adopt the default values, or even use a lower value like 5s, which is fine by me, although we would have to make sure we lower `keep_alive_interval` below `max_idle_timeout`,
