### ISSUE TITLE
broken example: browser-webrtc

### ISSUE THREAD

**Issue by DougAnderson444** [libp2p/rust-libp2p#4950]
### Summary

I fired up the latest https://github.com/libp2p/rust-libp2p/tree/master/examples/browser-webrtc to discover there's an error in the browser console

### Expected behavior

The example should ping back and forth between the server and browser, only 1 ping gets across before crashing

### Actual behavior

After the first ping, the browser crashes 

### Relevant log output

```shell
Uncaught Error: closure invoked recursively or after being dropped
    at imports.wbg.__wbindgen_throw (browser_webrtc_example.js:668:15)
    at browser_webrtc_example_bg.wasm:0xbed3a
    at browser_webrtc_example_bg.wasm:0xb6add
    at __wbg_adapter_30 (browser_webrtc_example.js:208:10)
    at RTCDataChannel.real (browser_webrtc_example.js:193:20)
```

### Possible Solution

I suspect one of the `web_sys` closures isn't being handled properly? It likely gets dropped and then called.

### Version

libp2p 0.53.1
libp2p_webrtc 0.6.1-alpha

### Would you like to work on fixing this bug ?

Maybe
```[tasklist]
### Tasks
- [ ] https://github.com/libp2p/rust-libp2p/pull/4952
- [ ] https://github.com/libp2p/rust-libp2p/pull/4966
```

**Comment by DougAnderson444** [comment]
Oh, also I see the logging was upgraded to `tracing` but it doesn't look like it's compatible with `wasm-logger` as I'm not seeing any browser logs

**Comment by DougAnderson444** [comment]
The logging is an easy fix, PR above.

**Comment by thomaseizinger** [comment]
> I suspect one of the `web_sys` closures isn't being handled properly?

Can we somehow identify which one?

**Comment by DougAnderson444** [comment]
I'm going to insert some tracing logs and try to figure out what is going wrong

**Comment by DougAnderson444** [comment]
### `Connection closed with error KeepAliveTimeout`

Relevant logs:

<pre style="white-space : pre-wrap !important; word-break: break-word;">
<code style="white-space : pre-wrap !important; word-break: break-word;">
DEBUG protocols/ping/src/handler.rs:284 ping succeeded rtt = 2ms;

browser_webrtc_example.js:313 INFO examples/browser-webrtc/src/lib.rs:46 
Ping successful: RTT: 2ms, from 12D3KooWKNSXqyYCpQvvt48a23rTs8sunjyMwH8Qdk7Co7ckoorA

browser_webrtc_example.js:313 TRACE transports/webrtc-websys/src/connection.rs:93 
connection::close_connection

browser_webrtc_example.js:313 DEBUG swarm/src/lib.rs:874 
Connection closed with error KeepAliveTimeout: Connected { endpoint: Dialer { address: "/ip4/10.0.0.140/udp/48471/webrtc-direct/certhash/uEiDxuSN86XFMzcZkqbI0mZE79FoMd5iy5BAIKMGz8KzYTw/p2p/12D3KooWKNSXqyYCpQvvt48a23rTs8sunjyMwH8Qdk7Co7ckoorA", role_override: Dialer }, peer_id: PeerId("12D3KooWKNSXqyYCpQvvt48a23rTs8sunjyMwH8Qdk7Co7ckoorA") } total_peers = 0;

browser_webrtc_example.js:313 INFO examples/browser-webrtc/src/lib.rs:49 
Swarm event: ConnectionClosed { peer_id: PeerId("12D3KooWKNSXqyYCpQvvt48a23rTs8sunjyMwH8Qdk7Co7ckoorA"), connection_id: ConnectionId(1), endpoint: Dialer { address: "/ip4/10.0.0.140/udp/48471/webrtc-direct/certhash/uEiDxuSN86XFMzcZkqbI0mZE79FoMd5iy5BAIKMGz8KzYTw/p2p/12D3KooWKNSXqyYCpQvvt48a23rTs8sunjyMwH8Qdk7Co7ckoorA", role_override: Dialer }, num_established: 0, cause: Some(KeepAliveTimeout) }

browser_webrtc_example.js:691 
Uncaught Error: closure invoked recursively or after being dropped
    at imports.wbg.__wbindgen_throw (browser_webrtc_example.js:691:15)
    at browser_webrtc_example_bg.wasm:0xcc313
    at browser_webrtc_example_bg.wasm:0xc2881
    at __wbg_adapter_30 (browser_webrtc_example.js:208:10)
    at RTCDataChannel.real (browser_webrtc_example.js:193:20)
imports.wbg.__wbindgen_throw @ browser_webrtc_example.js:691
$func1398 @ browser_webrtc_example_bg.wasm:0xcc313
$wasm_bindgen__convert__closures__invoke1_mut__h8a689f96ff52d314 @ browser_webrtc_example_bg.wasm:0xc2881
__wbg_adapter_30 @ browser_webrtc_example.js:208
real @ browser_webrtc_example.js:193
</code>
</pre>

Looks like a `KeepAliveTimeout` issue? Were there changes made to this recently? I seem to recall seeing something in a changelog

**Comment by DougAnderson444** [comment]
### Duration::from_secs(~~**5**~~ 20)

Ok, it was actually that easy. The idle was 5 seconds when the ping is 15 sec interval

## 🤦‍♂️

https://github.com/libp2p/rust-libp2p/blob/543408bec68c6d8fdef352a1a2a41994af9a4ca3/examples/browser-webrtc/src/lib.rs#L26-L27

**Comment by DougAnderson444** [comment]
It appears to be going idle and timing out, even though Pings are being received. Even if I extend the `with_idle_connection_timeout` it still goes idle and times out, even though it receives a few pings.

So this appears to be a `Ping`/`KeepAlive` issue, not a `WebRTC` issue

**Comment by DougAnderson444** [comment]
Is `Ping` designed to **_not_** keep the connection alive? Is there a way to override this for the example?

https://github.com/libp2p/rust-libp2p/blob/e889e2e446e32e29a6c979d4b37775181bb55455/swarm/src/handler.rs#L139-L143

I see what is done here though:

https://github.com/libp2p/rust-libp2p/blob/e889e2e446e32e29a6c979d4b37775181bb55455/examples/ping/src/main.rs#L42

which I can put into a PR.

**Comment by DougAnderson444** [comment]
After running the `ping` example to verify that it works fine on the command line (which it does), I tried these 3 experiments for our browser webrtc example:

```rust
.with_swarm_config(|c| {
            c.with_idle_connection_timeout(Duration::from_secs(
                // u64::MAX, // does not work, errors after 1 ping
                // js_sys::Number::MAX_SAFE_INTEGER as u64, // does not work, errors at ping # 1
                31_556_952u64, // works up to 3 pings, then errors
            ))
        })
```

The last value errored on `ping`:

```
TRACE transports/webrtc-websys/src/stream/poll_data_channel.rs:79 
DataChannel closed

DEBUG protocols/ping/src/handler.rs:262 
Ping failure: Other { error: Custom { kind: TimedOut, error: "ping protocol negotiation timed out" } }
```


I'm done troubleshooting for tonight 🌛, hopefully there's something obvious going on here that I don't know about.

**Comment by thomaseizinger** [comment]
> Is `Ping` designed to **_not_** keep the connection alive?

Not by itself at least, yes. But as you discovered, one can extend the idle connection timeout.

> I tried these 3 experiments for our browser webrtc example:

Did you extend the idle-connection-timeout for both the server and the browser?

**Comment by DougAnderson444** [comment]
> Did you extend the idle-connection-timeout for both the server and the browser?

🤦‍♂️ I did not... but when I did, it works!

Curiously, in `wasm` we cannot use `u64::MAX`. The `with_idle_connection_timeout` breaks in the browser on anything bigger than `32_212_254u64`

```rust
.with_swarm_config(|c| {
  c.with_idle_connection_timeout(Duration::from_secs(
   32_212_254u64,
   // 32_212_255u64, // breaks, too large for wasm?
  ))
})
```
