### ISSUE TITLE
example breaks when `path=` is replaced with `version=`

### ISSUE THREAD

**Issue by DougAnderson444** [libp2p/rust-libp2p#4953]
### Summary

When attempting to reproduce the code in the `/examples/browser-webrtc` directory in a new cargo folder, the example breaks when: 

```
libp2p = { path = "../../libp2p", ...
```

is replaced with:

```
libp2p = { version = "0.53.1", ...
```

### Expected behavior

I would expect to be able to drop in the same `version =` as the lib at `path =` and compile without issue.

### Actual behavior

Example doesn't compile when `path=` replaced with `version=`

### Relevant log output

```shell
error[E0599]: the method `map` exists for struct `Transport`, but its trait bounds were not satisfied
  --> examples/browser-webrtc/src/main.rs:36:14
   |
32 |               Ok(webrtc::tokio::Transport::new(
   |  ________________-
33 | |                 id_keys.clone(),
34 | |                 webrtc::tokio::Certificate::generate(&mut thread_rng())?,
35 | |             )
36 | |             .map(|(peer_id, conn), _| (peer_id, StreamMuxerBox::new(conn))))
   | |             -^^^ method cannot be called on `Transport` due to unsatisfied trait bounds
   | |_____________|
   | 
   |
  ::: /rust-libp2p/transports/webrtc/src/tokio/transport.rs:49:1
   |
49 |   pub struct Transport {
   |   --------------------
   |   |
   |   doesn't satisfy `libp2p_webrtc::tokio::Transport: Iterator`
   |   doesn't satisfy `libp2p_webrtc::tokio::Transport: StreamExt`
   |   doesn't satisfy `libp2p_webrtc::tokio::Transport: futures::Stream`
   |
   = note: the following trait bounds were not satisfied:
           `libp2p_webrtc::tokio::Transport: futures::Stream`
           which is required by `libp2p_webrtc::tokio::Transport: StreamExt`
           `&libp2p_webrtc::tokio::Transport: futures::Stream`
           which is required by `&libp2p_webrtc::tokio::Transport: StreamExt`
           `&mut libp2p_webrtc::tokio::Transport: futures::Stream`
           which is required by `&mut libp2p_webrtc::tokio::Transport: StreamExt`
           `libp2p_webrtc::tokio::Transport: Iterator`
           which is required by `&mut libp2p_webrtc::tokio::Transport: Iterator`
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
   |
3  + use libp2p_core::transport::Transport;
   |

warning: unused import: `futures::StreamExt`
 --> examples/browser-webrtc/src/main.rs:9:5
  |
9 | use futures::StreamExt;
  |     ^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused import: `core::Transport`
  --> examples/browser-webrtc/src/main.rs:12:5
   |
12 |     core::Transport,
   |     ^^^^^^^^^^^^^^^
```

### Possible Solution

I'm a bit stumped, as `libp2p::core` exports `Transport`, so I'm not really sure what's going on or why the traits would have issues based on the source of the library. The compile error even goes so far as to say that `core::Transport` is unused!

### Version

0.53.1

**Comment by DougAnderson444** [comment]
Is it possible this is due to the version discrepancy between `libp2p-webrtc-websys` and `../../libp2p_core`?

| crate | depends on  `libp2p-core` |
| --- | --- |
crates.io `libp2p-webrtc` v0.6.0-alpha |v0.40.1
../libp2p/ `v0.53.1` | v0.41.1

**Comment by thomaseizinger** [comment]
Ah I think I know what is happening here. It is because `libp2p-webrtc-websys` is _not_ exported from `libp2p`, we didn't bump its version in the latest release and thus we simply need a version bump here for this to work :)

Can you send a PR where you bump it to `0.3.0-alpha`? We can then release it from there and it should work!

**Comment by thomaseizinger** [comment]
We should probably start thinking about what it needs to get out of `alpha` state and just re-export it from `libp2p`.

**Comment by DougAnderson444** [comment]
Ok I can do the version bump PR. Actually I realized that the issue is actually on `libp2p-webrtc` so I can include both in the PR at the same time.

What is the rationale behind **not** exporting it from `libp2p` if it is `alpha`? Would that really cause problems?

**Comment by DougAnderson444** [comment]
I can confirm the only way I can get the crates to compile is by using the `git` source instead of `crates.io`

```
libp2p = { git = "https://github.com/libp2p/rust-libp2p.git", features = [ "ed25519", "macros", "ping", "tokio"] }
libp2p-webrtc = { git = "https://github.com/libp2p/rust-libp2p.git", features = ["tokio"] }
```
