### ISSUE TITLE
The basic_closest test of Kademlia kbuckets sometimes fails

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#496]
Seems to be random and happen only on CI.

**Comment by dvdplm** [comment]
A link to a failed CI job would be nice.

**Comment by tomaka** [comment]
It hasn't happened for a while, but it was a panic of some sort.
However the fact that the code should be deterministic but is not calls for a re-review I think.

**Comment by tomaka** [comment]
Since this hasn't happen for a long time, I guess we'll close this issue. If it happens again, let's reopen it.
