### ISSUE TITLE
chore: release v0.53.2

### ISSUE THREAD

**Issue by mxinden** [libp2p/rust-libp2p#4988]
### Description

Anyone any objections? @thomaseizinger?

### Are you planning to do it yourself in a pull request ?

Yes

**Comment by thomaseizinger** [comment]
> Anyone any objections? @thomaseizinger?

Nope :)

**Comment by mxinden** [comment]
Tagged and published the following crates:

- libp2p-connection-limits-v0.3.1
- libp2p-gossipsub-v0.46.1
- libp2p-identify-v0.44.1
- libp2p-kad-v0.45.3
- libp2p-quic-v0.10.2
- libp2p-request-response-v0.26.1
- libp2p-server-v0.12.5
- libp2p-swarm-derive-v0.34.1
- libp2p-swarm-v0.44.1
- libp2p-v0.53.2
- libp2p-websocket-websys-v0.3.1
- libp2p-yamux-v0.45.1
