### ISSUE TITLE
`tracing_subscriber` should log to stderr

### ISSUE THREAD

**Issue by mxinden** [libp2p/rust-libp2p#4992]
### Summary

Diagnostics (e.g. logging) should go to stderr. Output of a program should go to stdout.

### Expected behavior

`tracing_subscriber` to log to stderr.

### Actual behavior

`tracing_subscriber` is logging to stdout.

Upstream bug report https://github.com/tokio-rs/tracing/issues/2492

### Possible Solution

One can easily override the default:

``` rust
    let _ = tracing_subscriber::fmt()
        .with_env_filter(EnvFilter::from_default_env())
        .with_writer(std::io::stderr)
        .try_init();
```

Initialization of `tracing_subscriber` is already quite noisy. E.g. it requires 4 lines instead of the 1 line of `env_logger`. Should we introduce some abstraction?

### Version

`tracing_subscriber` introduced with https://github.com/libp2p/rust-libp2p/pull/4282.

### Would you like to work on fixing this bug ?

No

**Comment by eserilev** [comment]
I'd like to pick this up

**Comment by thomaseizinger** [comment]
> Initialization of `tracing_subscriber` is already quite noisy. E.g. it requires 4 lines instead of the 1 line of `env_logger`. Should we introduce some abstraction?

I think that would make sense. We only use this in examples and tests, neither of which get released to crates.io, so we can make a crate in `misc/` that is `publish = false`.

**Comment by JacobOgle** [comment]
@eserilev still working on this? If not I wouldn't mind taking a look

**Comment by eserilev** [comment]
@JacobOgle feel free to pick this up if you'd like

**Comment by nazreen** [comment]
Can I pick this up?

**Comment by JacobOgle** [comment]
@nazreen go for it! I've been too tied up with school to take a dive into it

**Comment by nazreen** [comment]
@JacobOgle cool! this will be my first time contributing to this repo. the label `getting-started` is synonymous with `good-first-issue` right?

**Comment by thomaseizinger** [comment]
> @JacobOgle cool! this will be my first time contributing to this repo. the label `getting-started` is synonymous with `good-first-issue` right?

Yes!

**Comment by drHuangMHT** [comment]
@nazreen Are you currently working on this? I would like to pick this up if you don't mind.

**Comment by nazreen** [comment]
Hey, I got caught up with other things, so go on ahead :)

**Comment by drHuangMHT** [comment]
I suppose we can use a macro to generate the code? And we temporarily override the default manually until 
 the upstream have fixed it. What do you think @thomaseizinger

**Comment by thomaseizinger** [comment]
I don't think there is a need for macros if we can just have a function that is reused across different places.

**Comment by drHuangMHT** [comment]
My plan is to put the function in `/libp2p/src/lib.rs`, any idea where to put the function?

**Comment by thomaseizinger** [comment]
> My plan is to put the function in `/libp2p/src/lib.rs`, any idea where to put the function?

We definitely don't want it in the libp2p crate because:

- It would make it part of the public API
- We would create a circular dependency

Like I said above, best to make a new crate that is marked as `publish = false` and only used as a dev-dependency.

**Comment by drHuangMHT** [comment]
> Like I said above, best to make a new crate that is marked as `publish = false` and only used as a dev-dependency.

Ok. What would you like to call it? `logging`? And put it under `misc`?

**Comment by thomaseizinger** [comment]
> > Like I said above, best to make a new crate that is marked as `publish = false` and only used as a dev-dependency.
> 
> Ok. What would you like to call it? `logging`? And put it under `misc`?

Yeah, `logging` works :)

**Comment by drHuangMHT** [comment]
I find another problem: dependency version. There has been multiple instances of `tracing` (and `tracing_subscribers`) in the manifests of all crates that depend on it, which will make depencency bumps harder to track. And `cargo deny` has been throwing a TON of warnings about duplicate entries of the same crate. Should we use `logging` to replace `tracing`(with re-exporting of course) across the repo?

**Comment by thomaseizinger** [comment]
> I find another problem: dependency version. There has been multiple instances of `tracing` (and `tracing_subscribers`) in the manifests of all crates that depend on it, which will make depencency bumps harder to track. And `cargo deny` has been throwing a TON of warnings about duplicate entries of the same crate. Should we use `logging` to replace `tracing`(with re-exporting of course) across the repo?

We can unify the version of tracing used across the entire workspace using workspace dependencies.

Re-exports don't work that well because we'd have to make `logging` a non-dev dependency then which means we'd have to publish it to crates.io.

**Comment by drHuangMHT** [comment]
> We can unify the version of tracing used across the entire workspace using workspace dependencies.

Yeah sure, workspace, I forgot that...
 
> Re-exports don't work that well because we'd have to make `logging` a non-dev dependency then which means we'd have to publish it to crates.io.

Not sure why it has to be published though.

**Comment by thomaseizinger** [comment]
> > Re-exports don't work that well because we'd have to make `logging` a non-dev dependency then which means we'd have to publish it to crates.io.
> 
> Not sure why it has to be published though.

If you want to use `logging` as a kind of "proxy" crate for tracing, you would also have to replace all uses of `tracing` that we use in the protocol crates for emitting logs. Those are published on crates.io and you can't publish something on crates.io with dependencies that aren't published there :)
