### ISSUE TITLE
Add support for Blowfish in secio?

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#500]
Go and JavaScript implementations support it, so we should support it as well.
It's not, however, very important if we don't.

This issue would be easy if there was a blowfish crate in the Rust ecosystem, but I'm not aware of any.

**Comment by tomaka** [comment]
Since Blowfish is deemed vulnerable, we could also just not support it and add a code comment explaining the situation.

**Comment by romanb** [comment]
Is it still worth to do anything at all except critical bug fixes for `secio` until it can eventually be removed?

**Comment by romanb** [comment]
I would say its not worth any effort.
