### ISSUE TITLE
kad: remove default IPFS DHT protocol name

### ISSUE THREAD

**Issue by mxinden** [libp2p/rust-libp2p#5006]
Today a new `kad::Config` will use the protocol name of the IPFS DHT, namely `/ipfs/kad/1.0.0`, by default.

This is problematic in the case where one wants to connect to a different DHT instance, or launch their own. E.g. in the past, new DHT networks have accidentally merged with the IPFS DHT instance.

To prevent this from happening in the future, we should not provide a default protocol name, but instead require a user to explicitly specify the protocol name and thus the DHT instance that they would like to join.

One possible fix would be to introduce `libp2p_kad::Config::new` taking a protocol name and to remove the `Default` implementation on `libp2p_kad::Config`.

https://github.com/libp2p/rust-libp2p/blob/305e02cccd88de935aca4f14ca937a50b4945e35/protocols/kad/src/behaviour.rs#L168-L202

**Comment by robin-rrt** [comment]
This looks simple enough. I'd like to work on this. Can I be assigned?

**Comment by dariusc93** [comment]
Sounds like it can mimic what `libp2p-identify` does by defining a protocol name, though in this case it would be an array (unless this will be cut back to just be a single define protocol for `libp2p-kad`). Honestly, it sounds like a better idea than relying on the default.

**Comment by thomaseizinger** [comment]
> though in this case it would be an array (unless this will be cut back to just be a single define protocol for `libp2p-kad`)

We added this back in #2837. I am wondering if we couldn't achieve the same thing by having multiple instances of `libp2p_kad::Behaviour` in your behaviour tree, all with a differently configured protocol name.
