### ISSUE TITLE
There seems to be bugs on the Chat example

### ISSUE THREAD

**Issue by ealione** [libp2p/rust-libp2p#5072]
### Summary

On lines 107, 113, 119 of the [chat](https://github.com/libp2p/rust-libp2p/blob/master/examples/chat/src/main.rs) example, that contain things like `(mdns::Event::Discovered(list)`. I get the errors: `Value used after being moved.`

### Expected behavior

Build and run the example without errors/warning or other issues.

### Actual behavior

Issue described above.

### Relevant log output

```shell
N/A
```

### Possible Solution

I'm in the process of learning Rust, so I don't have any.

### Version

latest

### Would you like to work on fixing this bug ?

No

**Comment by gnattu** [comment]
I *think* the respective lines should use `ref` so that the branch does not take ownership of the event:

```rust
SwarmEvent::Behaviour(MyBehaviourEvent::Mdns(mdns::Event::Discovered(ref list))) => {...}
SwarmEvent::Behaviour(MyBehaviourEvent::Mdns(mdns::Event::Expired(ref list))) => {...}
SwarmEvent::Behaviour(MyBehaviourEvent::Gossipsub(gossipsub::Event::Message {
                    propagation_source: ref peer_id,
                    message_id: ref id,
                    ref message,
                })) => ...


```

**Comment by ealione** [comment]
That indeed fixes the issue.

**Comment by thomaseizinger** [comment]
The examples are compiled in CI so I am surprised that they would contain compile errors. Are you running them from within the workspace? Did you copy them to a new project?

See https://github.com/libp2p/rust-libp2p/actions/runs/7463218376/job/20307376998#step:6:756 for the latest successful build of the example in CI.

What version of Rust are you using? Can you paste the output of `cargo check --package chat-example` after checking out latest master?

**Comment by thomaseizinger** [comment]
I'll close this for now because it works in CI.

**Comment by gnattu** [comment]
@thomaseizinger, I can confirm that `Rust 1.75.0` works both with and without `ref`. It seems that some versions of the borrow checker might not allow the direct use of the event in match cases.

Therefore, the example doesn't need to change if it's only targeting the current stable rust. However, if there are issues with a particular borrow checker, adding `ref` could serve as a workaround for the error.

**Comment by thomaseizinger** [comment]
Did you use edition 2021? I am pretty sure that this also works for Rust < 1.75 but there may have been changes across the editions.

Anyway, glad it is resolved!
