### ISSUE TITLE
Create a README.md and tests for every crate

### ISSUE THREAD

**Issue by folsen** [libp2p/rust-libp2p#51]
The top-level README should cover what packages/crates are in this repository and a high-level overview of what they do and maybe something similar to https://github.com/libp2p/go-libp2p.

Every package should also contain its own README with a clearer explanation of what the library is, how it's intended to be used and what the API is. Tests, examples and obviously rustdocs would also be required here.

Check off a package if you've added README, tests and rustdocs:

* [x] datastore
* [x] example
* [x] libp2p-peerstore
* [x] libp2p-ping
* [x] libp2p-secio
* [x] libp2p-swarm
* [x] libp2p-tcp-transport
* [x] multistream-select
* [x] rw-stream-sink

**Comment by tomaka** [comment]
Still needs to be done for the new crates such as multiplex I suppose.

**Comment by Vurich** [comment]
I'll do mplex now

**Comment by folsen** [comment]
Done for the current crates, but we should probably write up some doc somewhere about what documentation and testing standards are expected to be followed for new code.
