### ISSUE TITLE
mDNS: emit `ToSwarm::NewExternalAddrOfPeer`

### ISSUE THREAD

**Issue by thomaseizinger** [libp2p/rust-libp2p#5104]
### Description

With https://github.com/libp2p/rust-libp2p/pull/4371 merged, we have the foundation of https://github.com/libp2p/rust-libp2p/issues/4302 implemented.

`libp2p-mdns` needs to be extended to emit this new event whenever it discovers a new address via mDNS.

### Motivation

Other behaviours should be able to learn the addresses discovered by mDNS.

### Current Implementation

Only mDNS knows about its discovered addresses.

### Are you planning to do it yourself in a pull request ?

No

**Comment by 1010adigupta** [comment]
would like to work on this

**Comment by justcode740** [comment]
would like to take this one once previous one time out. @thomaseizinger , unsure the policy here.

**Comment by thomaseizinger** [comment]
Feel free to start! :)

I've not heard from @1010adigupta so far.

**Comment by justcode740** [comment]
> Feel free to start! :)
> 
> I've not heard from @1010adigupta so far.

ah, ok, just afraid there's some duplicated work done.

**Comment by 1010adigupta** [comment]
You can go for it, I got busy with some other stuff, didn't got time for this :)

**Comment by justcode740** [comment]
@thomaseizinger hey i have a question, isn't the mDNS service already inform Swarm when a new peer discovered? https://github.com/libp2p/rust-libp2p/blob/master/protocols/mdns/src/behaviour.rs#L351, what need to change here?

**Comment by thomaseizinger** [comment]
It emits an mDNS specific event that the user has to react to manually. The idea of the new event is that it is shared with other behaviours.
