### ISSUE TITLE
Opening a subsequent stream on the same protocol with the same peer fails

### ISSUE THREAD

**Issue by willscott** [libp2p/rust-libp2p#5134]
### Summary

When opening a subsequent stream on the same protocol with the same peer fails with "protocol not supported"

### Expected behavior

multiple streams of the same protocol should be opened, as happens in the go client

### Actual behavior

the subsequent open fails with "protocol not supported"

### Would you like to work on fixing this bug ?

Maybe

**Comment by thomaseizinger** [comment]
Please provide more information. Without version, component or reproducible example, we can't help you.
