### ISSUE TITLE
Quic `Protocol not available` error when running relay server example

### ISSUE THREAD

**Issue by grumbach** [libp2p/rust-libp2p#5139]
## Summary

When running the relay server example on my system (MacOS 10.14.6), I get the following error:

```
Error: Other(Custom { kind: Other, error: Other(Right(Io(Os { code: 42, kind: Uncategorized, message: "Protocol not available" }))) })
```

The error seems related to quic as it originates from this line in the code:

https://github.com/libp2p/rust-libp2p/blob/c40a8f17a75b6e15aa97a864e7ada24da3376e0a/examples/relay-server/src/main.rs#L82

Digging deeper, I could trace it back to:

https://github.com/libp2p/rust-libp2p/blob/0d9ad329f16f863818ef469f3f37b7a37a9319da/transports/quic/src/transport.rs#L118

- I tried going back to previous commits, to check if it's due to a recent change, all the way to commits 6 months back, same error. 
- This error doesn't occur for my colleagues with more recent versions of MacOS or other OSes. 

If there's anything else that I could do, I'd gladly help!

**Comment by grumbach** [comment]
The error code is from https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/intro.2.html

_42 ENOPROTOOPT Protocol not available. A bad option or level was specified in a getsockopt(2) or setsockopt(2) call._

**Comment by thomaseizinger** [comment]
> When running the relay server example on my system (MacOS 10.14.6), I get the following error:

This is a 6 year old operating system. We don't have a strict policy on what we support but I am just gonna say now that this is too old.

Plus, this is a downstream problem from the [`quinn`](https://github.com/quinn-rs/quinn) library so you'll have to try your luck there to see if you can get support for running on MacOS 10.14.

**Comment by dariusc93** [comment]
@grumbach Sounds like it might be related to quinn. Are you able to reproduce it using their examples? Given the age of your OS, I would not be surprised of the error.

**Comment by grumbach** [comment]
@thomaseizinger @dariusc93 thanks for your replies! It is indeed an old OS I'm running so I understand this error is of no priority. I ran all the examples on the `quinn` repo but the error did not occur. Maybe it has to do with something specific in the config? Will see if I can dig around this when I have some time.

**Comment by grumbach** [comment]
@dariusc93 @thomaseizinger, it seems this issue was fixed by `quinn` [here](https://github.com/quinn-rs/quinn/pull/1626). Testing locally by changing the quinn dependency in `transports/quic/Cargo.toml` to the latest `quinn` main:

```diff
-quinn = { version = "0.10.2", default-features = false, features = ["tls-rustls", "futures-io"] }
+quinn = { git = "https://github.com/quinn-rs/quinn", default-features = false, features = ["tls-rustls", "futures-io"] }
```

does the trick! I can successfully run the relay-server example with this!

**Comment by grumbach** [comment]
I opened a PR up here with a fix, bumping to a more recent rev of `quinn`, but understand if you guys decide to stay with a stable release version instead.

**Comment by thomaseizinger** [comment]
We can't make releases with git dependencies so we will have to wait for a release.
