### ISSUE TITLE
Audit the usage of FnvHashMap and figure out whether they are a DDoS vector

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#515]

**Comment by burdges** [comment]
Just using grep, I see these suspicious `FnvHashMap` and `FnvHashSet` keys:

 - `PeerId` in core/src/nodes/collection.rs core/src/nodes/swarm.rs protocols/kad/src/high_level.rs protocols/kad/src/query.rs
 - `Multiaddr` in protocols/floodsub/src/lib.rs core/src/connection_reuse.rs
 - `TopicHash` in protocols/floodsub/src/lib.rs protocols/identify/src/identify_transport.rs 

I suppose 16 or 32 bytes might qualify as "small" in whatever sense fnv means, and cryptographic ones looks random, but I read "*and* provides no protection against collision attacks" as saying an adversary can still DoS you even with these.  In particular, a collision resistant function composed with a non-collision resistant function is not necessarily collision resistant, although work may be required to find the collisions.

I'd assume any `usize` types like `TaskId` should be fine, along with any enums that looked local only.  It appears the `u64` key in `Inner::received` in protocols/floodsub/src/lib.rs too might be dangerous though.

**Comment by Vurich** [comment]
Why not just use siphash (the default)? Is it that performance-critical?

**Comment by thomaseizinger** [comment]
Closing as stale.
