### ISSUE TITLE
Opening a stream with MultiAddr as well as PeerId

### ISSUE THREAD

**Issue by youngjoon-lee** [libp2p/rust-libp2p#5178]
### Description

In the [stream](https://github.com/libp2p/rust-libp2p/tree/master/protocols/stream) protocol, the [`Control.open_stream`](https://github.com/libp2p/rust-libp2p/blob/e033385baa510510cca53b49da7557687d8dbfc4/protocols/stream/src/control.rs#L45) only accepts a PeerId. But, it would be good if it has another option that accepts a Multiaddr to cover the case when the user only knows a Multiaddr of the peer that he wants to connect to. 
Of course, the user can first dial to the peer using the Multiaddr and obtain the PeerId when the connection is established asynchronously. It requires much boilerplate. 
What do you think about this feature? If it is not planned yet, I can try to contribute.

### Motivation

To open a stream easily when the user doesn't know a PeerId of the peer she wants to connect to

### Requirements

1. Define another `open_stream` function with a parameter Multiaddr. This function makes a connection with the multiaddr and open a stream as the existing `open_stream` function does.

### Are you planning to do it yourself in a pull request ?

Maybe

**Comment by drHuangMHT** [comment]
You could dial the address first to see the peer ID. I believe it's the preferred way because there could be multiple peers behind the address.

**Comment by youngjoon-lee** [comment]
> You could dial the address first to see the peer ID. I believe it's the preferred way because there could be multiple peers behind the address.

Yeah. I just realized that using PeerId is the standard way in libp2p. Thank you
