### ISSUE TITLE
Need to use private stuff

### ISSUE THREAD

**Issue by jamesray1** [libp2p/rust-libp2p#518]
So far I need to use these private things:
```rust
// libp2p_floodsub::{RemoteInfo, Inner}
```
Shall we make them public, implement getters for them, or dare I say, copy and paste them?

_Originally posted by @jamesray1 in https://github.com/libp2p/rust-libp2p/pull/421#issuecomment-423884313_

**Comment by tomaka** [comment]
Please copy-paste them. They are private so that we can modify these structs without having to touch too much code.
