### ISSUE TITLE
kad: FIND_NODE not conform to specs

### ISSUE THREAD

**Issue by guillaumemichel** [libp2p/rust-libp2p#5269]
### Summary

According to [kad specs](https://github.com/libp2p/specs/tree/master/kad-dht#peer-routing), `FIND_NODE` is expected to return the closest node**s** to the requested key. Currently, receiving a `FIND_NODE` request for self (node's own key) results in an empty response. Because `FIND_NODE` is expected to return the closest node**s**, the closest nodes to self should also be returned in the response. 

IMO it isn't necessary to include self in the response though, because the requester is already aware of it.

Related issue: https://github.com/libp2p/go-libp2p-kad-dht/issues/966

### Expected behavior

When a `FIND_NODE` request for self (node's own key) is received, the response should contain the closest known peers.

### Actual behavior

When a `FIND_NODE` request for self (node's own key) is received, an empty response is returned.

https://github.com/libp2p/rust-libp2p/blob/a579e691c46a8efd2e38ebafca1c59a9b58fc56c/protocols/kad/src/behaviour.rs#L1183-L1184

### Possible Solution

Don't return an empty response, but rather the closest peers to the requested key (excluding self).

### Would you like to work on fixing this bug ?

Yes

**Comment by dariusc93** [comment]
This was discussed [here](https://github.com/libp2p/rust-libp2p/issues/3692) and [here](https://github.com/libp2p/specs/issues/535). I think if the latter was discussed more that could provide more clarification not just to `rust-libp2p` but other implementations as well but in my opinion, I dont believe it really make much sense to be able to find one self when calling `FIND_NODE`. I havent tested it recently but i know in go-libp2p i was not able to do the same when I tried it so did something change in the go implementation for this?

**Comment by dennis-tra** [comment]
IMO it can make sense that the peer returns itself. The response could include additional multiaddresses that the requestor isn't aware of yet. For example, the peer record could include a multiaddress that allows a direct connection while the requestor and requestee are connected through a relay.

You could argue that this is already covered by the identify protocol though 🤷‍♂️  personally I don't find this implicit dependency on another protocol a super compelling argument to not do the suggested change.

**Comment by guillaumemichel** [comment]
Currently go-libp2p-kad-dht is returning only itself when its own key is requested through `FIND_NODE`, which isn't either conform to the libp2p kad [specs](https://github.com/libp2p/specs/tree/master/kad-dht#peer-routing).

The question isn't: should the node return itself to such queries. It would be silly, because the requester already know the peer it is sending the request to.

My main concern here is that nodes should return the closest nodes to the requested key (excluding themselves, and the requester). `FIND_NODE` should never return an empty response, unless the routing table of the node is empty.

So both rust-libp2p and go-libp2p-kad-dht should should return the list of their closest peers, when receiving a `FIND_NODE` request for their own id.

**Comment by dennis-tra** [comment]
> It would be silly, because the requester already know the peer it is sending the request to.

As mentioned above, I think there could be a valid reason why you would want the latest peer record

**Comment by guillaumemichel** [comment]
@mxinden do you know why the empty response was introduced in https://github.com/libp2p/rust-libp2p/commit/ef9cb056b29a9ac8db299a862d047fb5adbe80c5?

**Comment by mxinden** [comment]
I don't unfortunately @guillaumemichel.

**Comment by guillaumemichel** [comment]
The [spec](https://github.com/libp2p/specs/blob/master/kad-dht/README.md) says:

> The libp2p Kademlia DHT offers the following types of operations:
> * Peer routing
>     * Finding the closest nodes to a given key via FIND_NODE.

> 3. Upon a response:
>     1. If successful the response will contain the k closest nodes the peer knows to the key Key. Add them to the candidate list Pn, except for those that have already been queried.

So the response should contain `k` peers (including/excluding self). An empty response isn't conform to specs

**Comment by dhuseby** [comment]
@achingbrain did you check the js-libp2p behavior to see how it behaves?

**Comment by achingbrain** [comment]
Sorry - I missed this.  It copies the go-libp2p-kad-dht behaviour as that was what was understood to be correct at the time.

This issue has an analogue here: https://github.com/libp2p/js-libp2p/issues/2450 - the fix is here: https://github.com/libp2p/js-libp2p/pull/2499

**Comment by hanabi1224** [comment]
Thanks for the fix! Is there a planned release of `libp2p-kad` anytime soon?

**Comment by dariusc93** [comment]
> Thanks for the fix! Is there a planned release of `libp2p-kad` anytime soon?

👋 To my knowledge this will be released after https://github.com/libp2p/rust-libp2p/pull/4568 is completed (which may prompt 0.54 release, cc @jxs). Of course, this could be backported too.

**Comment by hanabi1224** [comment]
@dariusc93 Thanks for the info! BTW, does rust-libp2p accept cross-language compatibility/regression tests? If so I can port https://github.com/ChainSafe/forest/pull/4622 to rust-libp2p. Thanks!

**Comment by jxs** [comment]
Hi @hanabi1224 I'd suggest to instead turn that into an [interop test](https://github.com/libp2p/test-plans) wdyt? cc @dhuseby
