### ISSUE TITLE
Flushing substreams means that we send a lot of small packets

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#527]
In other words, a simple layer that adds a `BufReader` and `BufWriter` to the opened sockets.

We should be careful that `flush()` is being called whenever we expect an answer from the remote. However since (afaik) we use `tokio-codec` everywhere, it should automatically flush whenever we send something.

**Comment by twittner** [comment]
We usually use `tokio_codec`'s `FramedWrite` which already buffers 8 KiB hence another buffering layer would not get us much.

**Comment by tomaka** [comment]
Here is a gist of the network traffic of a single connection of a Substrate node: https://gist.github.com/tomaka/1106fcf23d463ecb78dcde76a5b79b5f
The `len = #` lines indicate that secio has encoded a packet of the given length.
The `sent one elem` lines indicate when mplex calls `start_send` on the `Framed` object.

(the first three lines are the end of the secio handshake and the mplex protocol negotiation)

Things do indeed get buffered by tokio-codec, however I think we're calling `flush()` a bit too often.

Right now a common pattern seems to be that we write some data on substream 1, flush it because we need a response from the remote on substream 1, then write some data on substream 2, and flush it because we need a response from the remote on substream, and so on. Every flush unfortunately flushes the whole connection.
However fixing this would most likely require some API/design change.

**Comment by thomaseizinger** [comment]
We use codecs everywhere now.
