### ISSUE TITLE
mdns tokio timer panics

### ISSUE THREAD

**Issue by MOZGIII** [libp2p/rust-libp2p#5296]
### Summary

The tokio timer implementation is broken. The basic usage cases panic.

### Expected behavior

It must work.

The test I have added at https://github.com/libp2p/rust-libp2p/pull/5295 should pass.

### Actual behavior

It panics.

### Possible Solution

TBD.

### Version

From a loong time ago (2022-ish) till current `master`.

### Would you like to work on fixing this bug ?

Maybe

**Comment by jxs** [comment]
yeah confirmed it, see [here](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=78a725839584463557d5adf54c8f9228) `tokio::time::interval_at` panics when using `Duration::MAX` for the period, submitted #5297 to address it

**Comment by jxs** [comment]
fixed upstream see fixed upstream, see https://github.com/tokio-rs/tokio/pull/6487
