### ISSUE TITLE
Update openssl

### ISSUE THREAD

**Issue by theduke** [libp2p/rust-libp2p#537]
openssl `0.9` is not compatible with Openssl `1.1.1` +.

Due to this, libp2p won't compile on already upgraded distros like Arch at the moment.

I haven't tracked down which of the sub-crates is the culprit, but an update to openssl `0.10` would be nice.

For reference: https://github.com/sfackler/rust-openssl/issues/987

**Comment by tomaka** [comment]
The culprit is the `websocket` crate. There's already pending a pull request that does that: https://github.com/websockets-rs/rust-websocket/pull/186

Closing this issue in favour of that.

**Comment by theduke** [comment]
@tomaka awesome, cheers.
