### ISSUE TITLE
Peer nodes discovered through mDNS are not being added to the floodsub network

### ISSUE THREAD

**Issue by matttm** [libp2p/rust-libp2p#5411]
### Summary

I migrated a project from libp2p 0.3x.x to 0.53.2 and I cannot get my peers to connect. I created a Network Behavior composed of a mdns::Behavior and a floodsub::Behavior where all messagex are transformed to my EventType. From the debug logs, I can see the mDNS events getting logged and I try adding the peer but when I priint my peer count, it is 0.

I see the count mehod being called is on the swarm, whereas I invoke the peer addition through the floodsub instance, so I cannot tell if this is a user error or not. Even if it is, my peers are not sending the messages, and I cannot determine `publish`'s error as the API doesn't return a Result as Gossipsub does.

The MVP can be found here on branch `mvp` https://github.com/matttm/blockchain-rust/tree/mvp/src

The files with logic are `main.rs` and `p2p.rs`

### Expected behavior

I expect to see the peer count to increase and for messages to be sent upon `publish`.

### Actual behavior

The nodes see eachother and exchange mDNS events, which should trigger a eper add. The count is 0 though.

<img width="1788" alt="Screenshot 2024-05-21 at 6 24 22 PM" src="https://github.com/libp2p/rust-libp2p/assets/22200799/d38587e8-282e-4032-9f68-0378bd790a5a">

### Relevant log output

```shell
See above screenshot
```

### Possible Solution

The only thought I had was to have publish and add_peer return a Result. I am happy to help but just want to be sure I'm not making a dumb mistake before debuging toodeeis

### Version

0.53.2

### Would you like to work on fixing this bug ?

Yes

**Comment by dariusc93** [comment]
You would need to dial the peers that are discovered to add them to the network as mdns does not dial for you, it only discovers the peers via mdns (which you can use the `PeerId` since they are checked when dialing)

https://github.com/libp2p/rust-libp2p/blob/ad7ad5b3fc5b4bc9a431ece90e9a5ce8c33ca0e2/protocols/mdns/src/behaviour.rs#L239-L257

https://github.com/libp2p/rust-libp2p/blob/ad7ad5b3fc5b4bc9a431ece90e9a5ce8c33ca0e2/protocols/mdns/src/behaviour.rs#L333-L352

See gossipsub example for adding to pubsub network: https://github.com/libp2p/rust-libp2p/blob/ad7ad5b3fc5b4bc9a431ece90e9a5ce8c33ca0e2/examples/chat/src/main.rs#L107-L118

**Comment by matttm** [comment]
Thanks @dariusc93 for the quick response

I do try adding them in my code as in your shown example but with floodsub
```rust

                Some(p2p::EventType::DiscoveredEvent(peers)) => {
                    for (peer_id, _addr) in peers {
                        debug!("adding {peer_id} to floodsub");
                        swarm
                            .behaviour_mut()
                            .floodsub
                            .add_node_to_partial_view(peer_id);
                    }
                }
                Some(p2p::EventType::ExpiredEvent(peers)) => {
                    for (peer_id, _addr) in peers {
                        debug!("Rmoving {peer_id} from floodsub");
                        swarm
                            .behaviour_mut()
                            .floodsub
                            .remove_node_from_partial_view(&peer_id);
                    }
                }
```
                
The log shows the debug statement getting printed, but when getting the count from the swarm, it is 0.

I should note that I am getting the count from the swarm, not floodsub which seems problematic but I did not see an appropriate method on my floodsub instance. 
```rust
    let peers = swarm.connected_peers();
```
Also I am using `#[behaviour(to_swarm = "EventType")]
` to translate
```rust

impl From<mdns::Event> for EventType {
    fn from(event: mdns::Event) -> Self {
        match event {
            mdns::Event::Discovered(peers) => {
                debug!("Received Discovered MDNS event");
                return EventType::DiscoveredEvent(peers);
            }
            mdns::Event::Expired(peers) => {
                debug!("Received Expired mDNS event");
                return EventType::ExpiredEvent(peers);
            }
        }
    }
}
```
I do try sending messages at this [oint even though the count is 0. so even if this count is wrong, I am not seeing messages sent.

**Comment by dariusc93** [comment]
> Thanks @dariusc93 for the quick response
> 
> I do try adding them in my code as in your shown example but with floodsub
> 
> ```rust
>                 Some(p2p::EventType::DiscoveredEvent(peers)) => {
>                     for (peer_id, _addr) in peers {
>                         debug!("adding {peer_id} to floodsub");
>                         swarm
>                             .behaviour_mut()
>                             .floodsub
>                             .add_node_to_partial_view(peer_id);
>                     }
>                 }
>                 Some(p2p::EventType::ExpiredEvent(peers)) => {
>                     for (peer_id, _addr) in peers {
>                         debug!("Rmoving {peer_id} from floodsub");
>                         swarm
>                             .behaviour_mut()
>                             .floodsub
>                             .remove_node_from_partial_view(&peer_id);
>                     }
>                 }
> ```
> 
> The log shows the debug statement getting printed, but when getting the count from the swarm, it is 0.
> 
> I should note that I am getting the count from the swarm, not floodsub which seems problematic but I did not see an appropriate method on my floodsub instance.
> 
> ```rust
>     let peers = swarm.connected_peers();
> ```
> 
> I do try sending messages at this [oint even though the count is 0. so even if this count is wrong, I am not seeing messages sent.

Do you see any logs from `libp2p` (or `libp2p-swarm`) about dialing or connecting and if so do you see any errors? I would probably suggest expanding to capture those swarm events to log them.

**Comment by matttm** [comment]
I think I misinterpreted the logs initially.
```rust
  ~/projects/play/blockchain-rust ╱  mvp
❯ RUST_LOG=trace ./target/debug/blockchain-rust
 INFO  blockchain_rust > Initializing channels
 INFO  blockchain_rust > Node id: 12D3KooWLj6hvJp2qndu1GjiTB4UURip4f1TKgDw6mMtU249Zaqk
Creating genesis block
 DEBUG blockchain_rust::p2p > Subscribing to block topic
 TRACE mio::poll            > registering event source with poller: token=Token(140242472419968), interests=READABLE | WRITABLE
 TRACE mio::poll            > registering event source with poller: token=Token(140242472420352), interests=READABLE | WRITABLE
 TRACE mio::poll            > registering event source with poller: token=Token(140242472420736), interests=READABLE | WRITABLE
 DEBUG blockchain_rust::p2p > Received Discovered MDNS event
 DEBUG blockchain_rust      > Received DiscoveredEvent([(PeerId("12D3KooWKtHLT8DEiQq2FPfTVafQcbUK49gwPW7xhKmkHNYZZUp6"), "/ip4/192.168.1.69/tcp/59043/p2p/12D3KooWKtHLT8DEiQq2FPfTVafQcbUK49gwPW7xhKmkHNYZZUp6")]) from swarm
 DEBUG blockchain_rust      > adding 12D3KooWKtHLT8DEiQq2FPfTVafQcbUK49gwPW7xhKmkHNYZZUp6 to floodsub
 TRACE mio::poll            > registering event source with poller: token=Token(140242474516736), interests=READABLE | WRITABLE
 TRACE mio::poll            > registering event source with poller: token=Token(140242469273856), interests=READABLE | WRITABLE
 DEBUG multistream_select::dialer_select > Dialer: Proposed protocol: /noise
 TRACE multistream_select::protocol      > Received message: Header(V1)
 TRACE multistream_select::protocol      > Received message: Protocol(Protocol("/noise"))
 DEBUG multistream_select::dialer_select > Dialer: Received confirmation for protocol: /noise
 TRACE multistream_select::protocol      > Received message: Header(V1)
 TRACE multistream_select::protocol      > Received message: Protocol(Protocol("/noise"))
 DEBUG multistream_select::listener_select > Listener: confirming protocol: /noise
 DEBUG multistream_select::listener_select > Listener: sent confirmed protocol: /noise
 DEBUG multistream_select::dialer_select   > Dialer: Proposed protocol: /yamux/1.0.0
 TRACE multistream_select::protocol        > Received message: Header(V1)
 TRACE multistream_select::protocol        > Received message: Protocol(Protocol("/yamux/1.0.0"))
 DEBUG multistream_select::dialer_select   > Dialer: Received confirmation for protocol: /yamux/1.0.0
 DEBUG yamux::connection                   > new connection: f203a0f7 (Client)
 TRACE yamux::frame::io                    > f203a0f7: write: (WriteState::Init)
 TRACE yamux::frame::io                    > f203a0f7: write: (WriteState::Header (offset 0))
 TRACE yamux::frame::io                    > f203a0f7: write: (WriteState::Init)
 TRACE yamux::frame::io                    > f203a0f7: write: (WriteState::Init)
 TRACE mio::poll                           > deregistering event source from poller
 TRACE multistream_select::protocol        > Received message: Header(V1)
 TRACE multistream_select::protocol        > Received message: Protocol(Protocol("/yamux/1.0.0"))
 DEBUG multistream_select::listener_select > Listener: confirming protocol: /yamux/1.0.0
 DEBUG multistream_select::listener_select > Listener: sent confirmed protocol: /yamux/1.0.0
 DEBUG yamux::connection                   > new connection: e55e457b (Server)
 TRACE mio::poll                           > deregistering event source from poller
ls p
 INFO  blockchain_rust::p2p                > Peer count: 0
create b test
 INFO  blockchain_rust::p2p                > broadcasting new block
 DEBUG blockchain_rust::p2p                > Sending payload: {"id":1,"hash":"test","previousHash":"0000f816a87f806bb0073dcf026a64fb40c946b5abee2573702828694d5b4c43","timestamp":1716465603,"data":"test","nonce":1}
^C

```
Note the line `DEBUG yamux::connection                   > new connection: e55e457b (Server)`, so I think the nodes are in fact being added to the floodsub network. This makes me think the way I am getting my peer count is the wrong way. I don' t  see a way to get the peer count from the foodsub instance itself.

Also if the nodes are connecting I am clueless as to why there are no trace logs from libp2p when publishing.

Here is a snippet frpm p2p.rs to help in evaluation of the logs
```rust

pub fn handle_cmd_create_block(swarm: &mut Swarm<StateBehavior>, cmd: &str) {
    if let Some(data) = cmd.strip_prefix("create b ") {
        let last = swarm.behaviour().state.blocks.last().expect("Expect block");
        let block = Block::new(last.id + 1, last.hash.clone(), data.to_owned());
        let json = serde_json::to_string(&block).expect("can jsonify request");
        let behavior: &mut StateBehavior = swarm.behaviour_mut();
        behavior.state.blocks.push(block);
        println!("broadcasting new block");
        behavior
            .floodsub
            .publish(BLOCK_TOPIC.clone(), json.as_bytes());
    }
```
You can see that I publish right after logging `broadcasting new block` but there are no libp2p logs to aid in debugging.

**Comment by dariusc93** [comment]
In your code can you change https://github.com/matttm/blockchain-rust/blob/616d6e88be05efb69a959691056311fdbf29eb31/src/main.rs#L62-L67 to

```rust
debug!("Received {:?} from swarm", event_sw);
if let swarm::SwarmEvent::Behaviour(event) = event_sw {
    Some(event)
} else {
    Some(p2p::EventType::IgnoreEvent)
}
```

So this way the swarm events can be logged and you can see any other events (including events that may indicate that there was an error).

**Comment by matttm** [comment]
That was a great idea!

Doing, this I could see I wss getting a WrongPeeerId error, which led me to see I was using the wrong peer_id to  configure noise.

Thanks!!
