### ISSUE TITLE
Getting error when usin websocket feature 

### ISSUE THREAD

**Issue by shanithkk** [libp2p/rust-libp2p#5415]
### Summary

When i try to use the websocket feature libp2p, getting an error, 
Error throwing from `futures::future::ready(libp2p_dns::tokio::Transport::system( ` the error was 
`error[E0433]: failed to resolve: use of undeclared crate or module libp2p_dns`

<img width="932" alt="image" src="https://github.com/libp2p/rust-libp2p/assets/59169878/0b30ac08-b074-4f13-9994-b3dc9bace260">

### Expected behavior

We should able to use webscket feature

### Actual behavior

<img width="932" alt="image" src="https://github.com/libp2p/rust-libp2p/assets/59169878/f9fd1af3-7002-4add-8be3-c6328eefd351">

### Version

v0.53.2

### Would you like to work on fixing this bug ?

No

**Comment by dariusc93** [comment]
Do you have `dns` feature enabled too? This would be needed as well, though this could probably be split up at the builder level to use websocket transport without dns.

**Comment by shanithkk** [comment]
@dariusc93 got it ,thank you.
