### ISSUE TITLE
webRTC doesn't work with request-response

### ISSUE THREAD

**Issue by DougAnderson444** [libp2p/rust-libp2p#5438]
### Summary

After trying many different ways to use Req-Resp over WebRTC, I saw that it just doesn't work.

There is a bug in WebRTC utils, PR to fix is incoming shortly.

### Expected behavior

Request-Response protocol should work over WebRTC

### Actual behavior

The stream is dropped and the response is never sent or received

### Possible Solution

Fix WebRTC-utils

### Version

0.54.0

### Would you like to work on fixing this bug ?

Yes

**Comment by dariusc93** [comment]
Interesting. Didnt the universal-connectivity use request-response for files? Would have thought it would be caught there.

**Comment by DougAnderson444** [comment]
Likely not over WebRTC, I will take a look

**Comment by DougAnderson444** [comment]
Looks like the universal-connectivity is using the JavaScript for the file upload since it's got the front end, WebRTC and WebTransport
