### ISSUE TITLE
nat_traversal assumes dialing protocol = listening protocol

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#544]
Right now `nat_traversal` assumes that the protocol used for dialing is the same as the one used for listening.

For example say we dial `/ip4/1.2.3.4/tcp/30333` and are listening on `/ip4/0.0.0.0/tcp/80/ws`. The remote will observe us as, for example `/ip4/90.91.92.93/tcp/5052`.
Calling `nat_traversal` with these two addresses as parameter will return `None` instead of `/ip4/90.91.92.93/tcp/80/ws` as expected.

We could easily fix this for websockets, but `nat_traversal` as a whole probably needs some deeper thinking in order to be implemented correctly.

**Comment by tomaka** [comment]
Because of this, listening on a `/ws` address with Polkadot/Substrate doesn't work at the moment.

**Comment by twittner** [comment]
Should `Transport` impls not just translate a matching prefix of the address?

**Comment by tomaka** [comment]
I guess so!
