### ISSUE TITLE
libp2p-ping sometimes panics in WASM

### ISSUE THREAD

**Issue by oblique** [libp2p/rust-libp2p#5442]
### Summary

While researching our https://github.com/eigerco/lumina/issues/256 bug we found one of the causes were bacause libp2p-ping was panicking.

This was due to inconsistent behavior in `futures-timer` when it was used in WASM.

### Expected behavior

Not to panic

### Actual behavior

Panics

### Possible Solution

We fixed the issue with https://github.com/async-rs/futures-timer/pull/74 PR and we are waiting to be reviewed and get merged.

If `futures-timer` rejects or do not merge our fix, then another fix can be applied directly in `libp2p-ping`.

### Would you like to work on fixing this bug ?

Yes

**Comment by dariusc93** [comment]
Thanks for the report and good catch. I havent been able to reproduce this myself though during my testing, so out of curiosity was there any specific conditions in which a panic would happen?

**Comment by oblique** [comment]
It is a bit hard to reproduce it. In our case sometimes takes 30 minute to reproduce. The following flow  triggers it:

1. The first ping request is send ([code](https://github.com/libp2p/rust-libp2p/blob/68301b8db54816a616900d088342010fd0493a29/protocols/ping/src/handler.rs#L315-L317))
2. A timeout or IO error is produced ([code](https://github.com/libp2p/rust-libp2p/blob/68301b8db54816a616900d088342010fd0493a29/protocols/ping/src/handler.rs#L195-L202)). These can happen only because of network issues.
3. In [this](https://github.com/libp2p/rust-libp2p/blob/68301b8db54816a616900d088342010fd0493a29/protocols/ping/src/handler.rs#L185) line only `self.outbound` is reset.
4. Because of (3), [this](https://github.com/libp2p/rust-libp2p/blob/68301b8db54816a616900d088342010fd0493a29/protocols/ping/src/handler.rs#L310) is called for a second time and will panic.

More info:

* `gloo-timers` panic if an expired `TimeoutFuture` is reused ([code](https://github.com/rustwasm/gloo/blob/dc0e61e7b24fe0f33d66960385909dc0f4195bd9/crates/timers/src/future.rs#L104)).
* `futures-timer`'s native implementation does not panic, but they didn't apply this behavior for WASM ([code](https://github.com/async-rs/futures-timer/blob/07dbe53da1b5ddb703cdfc74ad59e15cb4134ce0/src/wasm.rs#L34))

The following fixes the issue in `libp2p-ping`, however we need to recheck all the places that `futures_timer::Delay` is used in libp2p to make sure that no other places are affected.

```patch
diff --git a/protocols/ping/src/handler.rs b/protocols/ping/src/handler.rs
index b9bd25c52..af7a55a13 100644
--- a/protocols/ping/src/handler.rs
+++ b/protocols/ping/src/handler.rs
@@ -183,6 +183,7 @@ impl Handler {
         >,
     ) {
         self.outbound = None; // Request a new substream on the next `poll`.
+        self.interval.reset(Duration::new(0, 0));

         let error = match error {
             StreamUpgradeError::NegotiationFailed => {
```

**Comment by dariusc93** [comment]
Thanks for the info. I will see what i can do on my end to reproduce it just out of my curiosity. In the meantime, maybe we should work on getting a patch done here in `libp2p-ping` since it might be a while before somebody review your fix in `futures-timer` (going based on the previous history there).

**Comment by oblique** [comment]
I created a repository with reproduction: https://github.com/oblique/libp2p-issue-5442
Please read `README.md` for more info.
