### ISSUE TITLE
websocket wasm cannot dial /tls/ws addresses

### ISSUE THREAD

**Issue by sukunrt** [libp2p/rust-libp2p#5509]
### Summary

Dialing `/dns/dht.nonsequitur.xyz/tcp/5123/tls/ws/p2p/12D3KooWPvLLPbUzs33TicVYPY78AEZSnd671irhqyi3UWLSBH8H` fails.

Dialing `/dns/dht.nonsequitur.xyz/tcp/5123/wss/p2p/12D3KooWPvLLPbUzs33TicVYPY78AEZSnd671irhqyi3UWLSBH8H` works fine(Edited based on: https://github.com/libp2p/rust-libp2p/issues/5509#issuecomment-2251187938). 

### Expected behavior

Both the dials should work. 

### Actual behavior

`/tls/ws` dials fail

### Possible Solution

`/tls/ws` and `/wss` are equivalent with `/wss` deprecated in favor of the more explicit `tls/ws`. The dialing logic should consider this. 

### Would you like to work on fixing this bug ?

Maybe

**Comment by sukunrt** [comment]
There was an issue that was supposed to handle this https://github.com/libp2p/rust-libp2p/issues/2449. But all the comments there only consider the multiaddr library aspects of the problem and not the dialing part of the problem. 

Recently, this was brought up here https://github.com/eigerco/lumina/issues/314

**Comment by aschmahmann** [comment]
Do you mean:
> Dialing /dns/dht.nonsequitur.xyz/tcp/5123/wss/p2p/12D3KooWPvLLPbUzs33TicVYPY78AEZSnd671irhqyi3UWLSBH8H works fine.

rather than `..../tls/wss/p2p/.... works fine` since `/tls/wss` should be invalid
