### ISSUE TITLE
Implement Protocol Labs' daemon interface for interoperability

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#552]
https://github.com/libp2p/go-libp2p-daemon

Interoperability testing uses this interface.

**Comment by seanmikalson** [comment]
Hello! I'm new to rust and libp2p, and interested in contributing. I have got a start of an implementation of the daemon specification and, to start, plan to get the connect interop tests to pass. Once I have that, getting some feedback on the implementation would be great!

**Comment by mxinden** [comment]
Closing here since we now have the Testground infrastructure. See https://github.com/libp2p/test-plans/tree/master/ping.
