### ISSUE TITLE
webrtc-websys: __Nonexhaustive does not exist

### ISSUE THREAD

**Issue by dariusc93** [libp2p/rust-libp2p#5557]
### Summary

web-sys recently released a patch update which include renaming `__Nonexhaustive` to `__Invalid` (see https://github.com/rustwasm/wasm-bindgen/pull/3915), which would cause an compile time error for anyone checking `__Nonexhaustive` like we do here

https://github.com/libp2p/rust-libp2p/blob/fc9b1ad51655b79561e3c552859554e99e2b0040/transports/webrtc-websys/src/stream/poll_data_channel.rs#L146

### Expected behavior

Not to error when compiling

### Actual behavior

Error while compiling using latest patch release

### Possible Solution

While the solution would be to pin the previous patch release, I do feel that we could make a change here by either renaming `__Nonexhaustive` to `__Invalid` while updating `web-sys` to `0.3.70` or remove checking `__Nonexhaustive`  altogether (without updating the dependency) if we do not need to explicitly check it.

### Version

0.53, 0.54, master

### Would you like to work on fixing this bug ?

Maybe

**Comment by mickvandijke** [comment]
I'm running into the same problem when using: `libp2p-webrtc-websys = "0.4.0-alpha"`. I see that someone made a patch, but it isn't published to crates.io yet. Is there any other way to fix this while still using `0.4.0-alpha`?

**Comment by DougAnderson444** [comment]
> I'm running into the same problem when using: `libp2p-webrtc-websys = "0.4.0-alpha"`. I see that someone made a patch, but it isn't published to crates.io yet. Is there any other way to fix this while still using `0.4.0-alpha`?

@mickvandijke No, you need to use the latest patch. I recently asked jxs to publish to crates.io, hopefully will be done soon.

Until then, I am using this branch: https://github.com/DougAnderson444/rust-libp2p/tree/webrtc-websys-deps
