### ISSUE TITLE
Add ECDSA public key format

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#556]
https://github.com/libp2p/specs/pull/100

**Comment by twittner** [comment]
Is there a specific need for this? In the spec ECDSA is optional and does not seem particularly attractive on its own.

**Comment by tomaka** [comment]
We don't have any need for this, but let's have an issue open for this.

**Comment by davxy** [comment]
Hi @tomaka , I've started working on this issue.

I already have a working implementation compatible with the go-libp2p one but, before PR submission, I would like to ask some opinions wrt multiple curves support.

Preliminary:
- I've used RustCrypto `p256` crate. I also made an attempt using `ring` but I would like to have support for wasm and I prefer a plain Rust crate.
- The feature is optional (as rsa and secp256k1)
- Currently the implementation (as the golang one) supports only p256 curve with sha256.

I was wondering if we would like to keep a door open for more curves that may be inserted in the future.

For example: my current implementation has introduced the following function in `identity.rs`:
```
+    #[cfg(feature = "ecdsa")]
+    pub fn generate_ecdsa() -> Keypair {
+        Keypair::Ecdsa(ecdsa::Keypair::generate())
+    }
```

Maybe could be good to define a `CurveId` enum in `ecdsa` module:

```
    pub enum CurveId {
        Secp256r1
    }
```
And then define `ecdsa::Keypair::generate` to take a `CurveId` parameter (maybe optional with default to P256?).

As I said, for the moment there is only one possibility (i.e. p256), but maybe is a good idea to keep a door open for future extensions.

Thank you

**Comment by mxinden** [comment]
> I've used RustCrypto p256 crate. I also made an attempt using ring but I would like to have support for wasm and I prefer a plain Rust crate.

@burdges and @dignifiedquire, as experts on rust crypto, do you have any opinions on this?

> As I said, for the moment there is only one possibility (i.e. p256), but maybe is a good idea to keep a door open for future extensions.

I am not too worried making breaking changes at the in-process API level in the future in case we do decide to support other curves. (Quite the opposite for network level breaking changes.)
