### ISSUE TITLE
Kademlia protocol name disappeared in `0.54` version

### ISSUE THREAD

**Issue by sh3ll3x3c** [libp2p/rust-libp2p#5607]
### Summary

When updated from the `rust-libp2p` version `0.53.2` to `0.54` the Kademlila protocol name cannot be found in the list of supported protocols in the `identify` protocol.

### Expected behavior

In `0.53.2` the Kademlia protocol name was present, along with the other protocols.

We're using the `Info` struct in the `Identify::Event::Received` which contains the list of protocols that's used to decide whether a new peer is able to join the network or not.

```rust
pub struct Info {
    /// The public key of the local peer.
    pub public_key: PublicKey,
    /// Application-specific version of the protocol family used by the peer,
    /// e.g. `ipfs/1.0.0` or `polkadot/1.0.0`.
    pub protocol_version: String,
    /// Name and version of the peer, similar to the `User-Agent` header in
    /// the HTTP protocol.
    pub agent_version: String,
    /// The addresses that the peer is listening on.
    pub listen_addrs: Vec<Multiaddr>,
    /// The list of protocols supported by the peer, e.g. `/ipfs/ping/1.0.0`.
    pub protocols: Vec<StreamProtocol>,
    /// Address observed by or for the remote.
    pub observed_addr: Multiaddr,
}
```

### Actual behavior

When updated to 0.54, the list of supported protocols contain:
- Ping
- Relay
- Id
- Autonat

But Kademlia protocol string is missing.

### Version

0.54

### Would you like to work on fixing this bug ?

Maybe

**Comment by dariusc93** [comment]
Hey! The reason why you might not see it is likely due to the behavior being in client mode, which it is by default until an external address is set or the mode is explicitly changed to Mode::Server via Behaviour::set_mode. Is this the case for you?

**Comment by sh3ll3x3c** [comment]
@dariusc93 you're correct! Turns out I've accidentally started the client in `client` instead of `server` mode, which led me to a wild chase. The protocol name is still there, didn't disappear 🤣  

Thanks for the quick answer and sorry for the bother!
