### ISSUE TITLE
Support Identity multihash

### ISSUE THREAD

**Issue by mgoelzer** [libp2p/rust-libp2p#564]
Multihash does not currently have a [proper spec](https://github.com/multiformats/specs), but the canonical Go implementation includes an ["identity" (null) hash](https://github.com/multiformats/go-multihash/blob/97cdb562a04c6ef66d8ed40cd62f8fbcddd396d6/multihash.go#L39) that maps a byte array onto itself.

https://github.com/libp2p/rust-libp2p/issues/555 depends on this

**Comment by tomaka** [comment]
This has been done in #1230/#1237
