### ISSUE TITLE
Primitive types conversion from InboundRequestId and OutboundRequestId

### ISSUE THREAD

**Issue by MrishoLukamba** [libp2p/rust-libp2p#5657]
### Description

It is so limiting to work with InboundRequestId and OutboundRequestId in request and response protocol as they are wrappes for u64, so why not add the conversion to u64

### Motivation

Easy to work with different encoding schemes

### Current Implementation

does not include the conversion

### Are you planning to do it yourself in a pull request ?

Yes

**Comment by jxs** [comment]
Hi, offering those methods would defeat the purpose of the new type wrapping it as we'd be exposing it's inner `u64`. 
The `u64` is not accessible so that it may change and not cause a breaking change.

Can you exemplify your use case and show the limitations?

**Comment by MrishoLukamba** [comment]
> Hi, offering those methods would defeat the purpose of the new type wrapping it as we'd be exposing it's inner `u64`. The `u64` is not accessible so that it may change and not cause a breaking change.
> 
> Can you exemplify your use case and show the limitations?

Encoding and decoding that type, but Ive gone around it by hashing the InboundReqId and use the hash value.

**Comment by jxs** [comment]
Ok nice, going to close this then. Thanks!
