### ISSUE TITLE
Make identify::Config fields private

### ISSUE THREAD

**Issue by jxs** [libp2p/rust-libp2p#5660]
### Description

they don't need to be public, we should make it consistent across the project and have them private with getters and setters 

### Motivation

see https://github.com/libp2p/rust-libp2p/pull/5574#discussion_r1746736993 for more information on the why
NB: We should take advantage of the minor version https://github.com/libp2p/rust-libp2p/pull/5574 introduces and land this with it

### Current Implementation

Current implementation has `identify::Config` fields public

### Are you planning to do it yourself in a pull request ?

Maybe

**Comment by kamuik16** [comment]
@jxs If anyone's not taking this, can I work on it?

**Comment by jxs** [comment]
thanks @kamuik16! Go for it :grin:

**Comment by kamuik16** [comment]
> thanks @kamuik16! Go for it 😁

Already opened a PR for it!
