### ISSUE TITLE
Code formatting with `rustfmt.toml` config

### ISSUE THREAD

**Issue by kamuik16** [libp2p/rust-libp2p#5684]
### Description

We can add a `rustfmt.toml` file to the repo and use some of the nightly features like
```toml
reorder_imports  = true
imports_granularity = "Crate"
format_code_in_doc_comments = true
```

Read more about these configs in [here](https://rust-lang.github.io/rustfmt/?version=v1.6.0&search=).

### Motivation

Highly improved code formatting and readability.
Formatting imports.
Formatting the code in doc as well.
Example: [reth - rustfmt.toml](https://github.com/paradigmxyz/reth/blob/main/rustfmt.toml)

### Current Implementation

This:
```rust
pub use self::behaviour::{Behaviour, Event, MessageAuthenticity};
pub use self::config::{Config, ConfigBuilder, ValidationMode, Version};
pub use self::error::{ConfigBuilderError, PublishError, SubscriptionError, ValidationError};
pub use self::metrics::Config as MetricsConfig;
pub use self::peer_score::{
    score_parameter_decay, score_parameter_decay_with_base, PeerScoreParams, PeerScoreThresholds,
    TopicScoreParams,
};
pub use self::subscription_filter::{
    AllowAllSubscriptionFilter, CallbackSubscriptionFilter, CombinedSubscriptionFilters,
    MaxCountSubscriptionFilter, RegexSubscriptionFilter, TopicSubscriptionFilter,
    WhitelistSubscriptionFilter,
};
pub use self::topic::{Hasher, Topic, TopicHash};
pub use self::transform::{DataTransform, IdentityTransform};
pub use self::types::{Message, MessageAcceptance, MessageId, RawMessage};
```

will look like this:
```rust
pub use self::{
    behaviour::{Behaviour, Event, MessageAuthenticity},
    config::{Config, ConfigBuilder, ValidationMode, Version},
    error::{ConfigBuilderError, PublishError, SubscriptionError, ValidationError},
    metrics::Config as MetricsConfig,
    peer_score::{
        score_parameter_decay, score_parameter_decay_with_base, PeerScoreParams,
        PeerScoreThresholds, TopicScoreParams,
    },
    subscription_filter::{
        AllowAllSubscriptionFilter, CallbackSubscriptionFilter, CombinedSubscriptionFilters,
        MaxCountSubscriptionFilter, RegexSubscriptionFilter, TopicSubscriptionFilter,
        WhitelistSubscriptionFilter,
    },
    topic::{Hasher, Topic, TopicHash},
    transform::{DataTransform, IdentityTransform},
    types::{Message, MessageAcceptance, MessageId, RawMessage},
};
```

This is just one of the example across repo.

### Are you planning to do it yourself in a pull request ?

Yes

**Comment by kamuik16** [comment]
Curios to know the opinions of the maintainers here :)

**Comment by jxs** [comment]
Hi, there was one, introduced in #18, which was then removed in #137.
No strong opinion, just wouldn't like something that changes the code style too much with lots of diffs. If it's mostly imports makes sense to me

**Comment by kamuik16** [comment]
> Hi, there was one, introduced in #18, which was then removed in #137. No strong opinion, just wouldn't like something that changes the code style too much with lots of diffs. If it's mostly imports makes sense to me

yes, related to imports and formatting code in the docs which are in the `///`. But we'll have to use the nightly toolchain like `cargo +nightly fmt` so if it makes sense to you, I can open a PR for it. We'll have to change cargo fmt check in the ci to use the nightly feature. wdyt?

**Comment by jxs** [comment]
yeah, thanks for it! With a PR we can then discuss and possible fine tune the changes

**Comment by kamuik16** [comment]
Closed by https://github.com/libp2p/rust-libp2p/pull/5695
