### ISSUE TITLE
Huge increase in memory allocation

### ISSUE THREAD

**Issue by stormshield-frb** [libp2p/rust-libp2p#5712]
### Summary

We have a server dedicated to stress testing our network and since the recent rebase of our fork with the libp2p master branch, this server gets OOM killed a lot.

In order to find out what was happening, our team has discovered that the configurability of the Kademlia bucket size (https://github.com/libp2p/rust-libp2p/pull/5414) has introduced a huge increase in memory allocation, which imply an increase in memory fragmentation. 

More precisely, it seems to be related to this code change : https://github.com/libp2p/rust-libp2p/commit/417968e07cfb79163a541ee2e5871a9bb6fe9534#diff-25d9554b592e6280d215bfc8b0bdb5a61eea3a6ca795849e6c7400414cb00c1cR288.

Previously, there was no heap allocation but now there is. 

### Expected behavior

Don't have heap allocation at every `get_closest_peers` request.

### Actual behavior

An allocation happens at every `get_closest_peers` request.

### Possible Solution

Maybe use a `SmallVec` with the default `K_VALUE` in order to have the same behaviour than before ?

Or maybe use const generic ? It would not allow users to define the `K_VALUE` at runtime but it would allow them to define it in there code base.

### Would you like to work on fixing this bug ?

Maybe

**Comment by guillaumemichel** [comment]
The `SmallVec` solution sounds good. So only systems with a bucket size larger than `K_VALUE` will actually pay the heap allocation price?

**Comment by stormshield-frb** [comment]
Yeah that is the idea. At least on our part because we don't plan to change the `K_VALUE` so we just want to go back to how it was :joy: But I don't know if it would be an acceptable solution for people wishing to change the `K_VALUE`.

**Comment by guillaumemichel** [comment]
If users wish to reduce the bucket size, they wouldn't be penalized.

And for those willing to have a higher bucket size, are there alternatives to allow defining the bucket size at run time?

**Comment by stormshield-frb** [comment]
I don't think so. Personally, I only see the `SmallVec` solution and the one were we define a `const generic` argument on the Kad behaviour. But maybe there is and I did not think about it. 

On our end we are going to patch our fork with the `SmallVec` solution for now to mitigate the effect quickly. But we can take a little more time to have some other opinions before choosing what to do for the permanent solution. What do you think ? Maybe other contributors will propose a better solution.

The question is what could be the maximum smart `K_VALUE` value that someone could define ? If it is `20` or not much higher, we put this value (20, 25?) in the `SmallVec` I think. If it is much higher, then the people wishing to do that would still be able to change the value in a patch at compile time.

**Comment by guillaumemichel** [comment]
This sounds good! I am not aware of any live kademlia system using a value larger than `20` as bucket size. If it becomes useful at some point to have larger bucket values for some users, we can reevaluate.

**Comment by dariusc93** [comment]
Out of curiosity do you have any memory reports showing the increase in allocations before that change, with the change and with your proposed PR?

**Comment by stormshield-frb** [comment]
Hi @dariusc93. I have put a picture of the allocations after the bucket size configurability in the PR (https://github.com/libp2p/rust-libp2p/pull/5715#issuecomment-2548148781). However, we don't have memory reports of before the configurability and after my PR since there was and there is no more heap allocation and everything is in the stack.
