### ISSUE TITLE
Project won't compile on Windows with latest Visual Studio bc of ring 0.12 dependency

### ISSUE THREAD

**Issue by bellicapax** [libp2p/rust-libp2p#576]
As mentioned in this issue on ring https://github.com/briansmith/ring/issues/648 the latest Visual Studio won't compile versions of ring earlier than 0.13 because of warnings treated as errors.

I pulled the project and got around the issue by pointing my local ring dependency to 0.13.2 (latest atm) and also updating untrusted to ring's dependency version (0.6.2).

**Comment by tomaka** [comment]
I'm going to assume that this is fixed. We're using the latest version of ring, so if it still doesn't work, an issue should be opened on `ring` instead.
