### ISSUE TITLE
Split ConnectionUpgrade between dialer and listener

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#586]
While for `Transport` I don't think it's *that* useful, for `ConnectionUpgrade` I've noticed that the `Output` is very often dependant on whether we are dialing or listening.

`identify`, `kad`, `ping` and `relay` are totally asymmetric and would benefit from this for stronger typing.
Only the transport-level upgrades (`secio`, `mplex`, `yamux`) and `floodsub` are very symmetric.

**Comment by tomaka** [comment]
However I'm not sure whether we want to split it in two separate traits. I think two separate methods and two separate `Output` associated types are enough.

**Comment by twittner** [comment]
Done: https://github.com/libp2p/rust-libp2p/pull/642
