### ISSUE TITLE
NodeStream does not check the outbound state until there's at least one outbound substream

### ISSUE THREAD

**Issue by dvdplm** [libp2p/rust-libp2p#609]
The current `NodeStream` implementation does not check the outbound state until there is at least one item in the `outbound_substreams` collection ([code](https://github.com/libp2p/rust-libp2p/blob/master/core/src/nodes/node.rs#L283)).
Make it behave like the inbound case and [fix tests](https://github.com/libp2p/rust-libp2p/pull/584/files#diff-dea5f941e495f207489ed6e87c902662R632) accordingly.

**Comment by tomaka** [comment]
I opened this issue thinking that it was just a problem in the polling system. It turns out the `StreamMuxer` is not capable of doing that.

This needs more thoughts whether this is actually an issue, or we can close it as "doesn't matter".

**Comment by romanb** [comment]
This seems very much outdated.
