### ISSUE TITLE
Implement all the traits on `!` once `!` is stable

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#645]
Additionally, clean up the code in order to use `!` where we use `Void`, `DeniedTransport` or `DeniedUpgrade`.

**Comment by tomaka** [comment]
Marking as `blocked` because `!` still isn't stable.

**Comment by mxinden** [comment]
Closing here. I don't think we have to track this in rust-libp2p specifically. For those interested, please follow https://github.com/rust-lang/rust/issues/35121.
