### ISSUE TITLE
Destroying a `StreamMuxer::OutboundSubstream` does not inform the remote.

### ISSUE THREAD

**Issue by twittner** [libp2p/rust-libp2p#651]
Opening and polling a `StreamMuxer::OutboundSubstream` typically results in some kind of `Open` frame being sent to the remote (cf. mplex). However, if the `OutboundSubstream` is destroyed before polling has finished and hence no `Substream` handle is available to hand over to `shutdown_substream`, no corresponding `Close` or `Reset` frame is sent.

Should we perhaps augment `StreamMuxer` with a `fn shutdown_outbound(&self, s: &mut Self::OutboundSubstream) -> Poll<(), std::io::Error>` method, mirroring the existing `shutdown_substream` method and demand that client code which wants to interrupt the opening of a new substream has to call that method?

**Comment by romanb** [comment]
I think the situation at the time of writing is the following:

  * Mplex resolves the `OutboundSubstream` to a `Substream` as soon as the `Open` frame is sent, so the situation where an `Open` frame has been sent but the `OutboundSubstream` is still pending (and may be dropped / destroyed) can no longer arise.

  * Yamux uses [`abort_open_stream()`](https://github.com/paritytech/yamux/blob/524589e813ae689d190dc3476e3b3af9e0165526/src/connection/control.rs#L100-L102) on `destroy_outbound()` but that doesn't seem to do anything special to inform the remote in case the `Open` frame has already been sent.
