### ISSUE TITLE
Add the possibility to assume that multistream-select will succeed

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#659]
If the connection upgrade only accepts one protocol, we can optimize the `multistream-select` process by assuming that it works, and closing the connection/substream altogether if later the remote returns `"na"`.

I would suggest modifying `dialer_select_proto` so that if the `size_hint()` of the protocols list returns a maximum of 1, immediately succeed after sending the data without waiting for the remote to confirm, and wraps around the returned stream.

The behaviour should also be precisely documented.

**Comment by tomaka** [comment]
This should be integrated in such a way that [multistream-select 2.0](https://github.com/libp2p/specs/pull/95) is easy to plug in later.

**Comment by tomaka** [comment]
I think that `multistream-select` should simplfy add a `Negotiated<T>` wrapper around the successfully negotiated substreams (even on the listening side), so that we can do whatever we want underneath.

**Comment by tomaka** [comment]
Note that shutdown should check the outcome of the negotiation and produce an error if it failed, otherwise failed negotiations would be undetected for write-only substreams.

**Comment by tomaka** [comment]
This is actually harder than expected to do properly, because the code of multistream-select is from a period of time where I didn't really know how tokio/futures worked and thus isn't that great.

I would actually suggest a rewrite for multistream-select 2.0.

**Comment by romanb** [comment]
This has been done in https://github.com/libp2p/rust-libp2p/pull/1212 and is supported by the `multistream-select` crate, though `libp2p-core` cannot fully make use of such optimistic negotiation to avoid pitfalls (see the discussion on the PR). I suggest to eventually create a new issue for the implementation of multi(stream)select-2.0, once that leaves that design phase (see https://github.com/libp2p/specs/pull/205).
