### ISSUE TITLE
How to inherit protocol FloodSub?

### ISSUE THREAD

**Issue by daogangtang** [libp2p/rust-libp2p#670]
Hi, How to inherit protocol FloodSub? I want to dev my own protocol based on FloodSub protocol, what's the best practice with that?

Thanks.

**Comment by tomaka** [comment]
Hi,

I would say that you can either copy-paste the code of floodsub (if you require a lot of modifications), or internally use some elements of floodsub as implementation details of your own protocol.

**Comment by daogangtang** [comment]
Ok, I find this feature is wonderful and can fit my needs!  https://github.com/libp2p/rust-libp2p/pull/619

Thank you.
