### ISSUE TITLE
DeniedTransport: still useful?

### ISSUE THREAD

**Issue by dvdplm** [libp2p/rust-libp2p#672]
Figure out if we still need ~~these two~~ it. If we do, make changes to make ~~them~~ it usable with e.g. `RawSwarm` (at least `DeniedTransport` need changes to the `Output` assoc type) and export  as needed. If we don't, remove ~~them~~it.

**Comment by dvdplm** [comment]
cc @twittner – thoughts on this?

**Comment by twittner** [comment]
`DeniedUpgrade` is certainly needed, e.g. for implementations of `ProtocolsHandler` which support either inbound or outbound upgrades. See for example `PeriodicPingHandler` or `PeriodicIdentification`.

As for `DeniedTransport` I am not sure if we still have a need for it.

**Comment by twittner** [comment]
Cf. https://github.com/libp2p/rust-libp2p/pull/673.

**Comment by twittner** [comment]
`DeniedTransport` has been removed.
