### ISSUE TITLE
Example not working on OSX

### ISSUE THREAD

**Issue by cetra3** [libp2p/rust-libp2p#675]
Hi All,

Not sure if I'm doing anything wrong but the master doesn't appear to work on OSX as far as I can tell. 

## Environment Details

OS: OSX Mojave 10.14.1 (18B75)
Rust Version:  Both `1.32.0-nightly (b3d0b2e54 2018-11-15)` & `1.30.1`
Commit: `1da97242da9167dcf8294b49484d2d4e84eb287f`

## Steps to replicate

* Run the following in one terminal:

```
cargo run --example chat
```

* Record the `Listening on` address

* Run the following in another terminal:

```
cargo run --example chat -- /ip4/127.0.0.1/tcp/<listen address>
```

### Expected outcome

I am not sure, I would expect to see one terminal reflected in the other terminal

### Actual Outcome

Nothing, just the following:

```
 cargo run --example chat -- /ip4/127.0.0.1/tcp/55767
    Finished dev [unoptimized + debuginfo] target(s) in 0.35s                                                                                       
     Running `target/debug/examples/chat /ip4/127.0.0.1/tcp/55767`
Local peer id: PeerId(Qmb3Q21jLPHBcT3FrPEvuM5aKxieJEAicZd1pufjq4pNGV)
Listening on "/ip4/0.0.0.0/tcp/55768"
Dialed "/ip4/127.0.0.1/tcp/55767"
```

**Comment by dvdplm** [comment]
Hi, thank you for the report. Yes, I see the same; will fix asap!

**Comment by twittner** [comment]
https://github.com/libp2p/rust-libp2p/pull/677 should fix this.

**Comment by cetra3** [comment]
No worries I'll have a look.   Is there a way to convert the example into a more futures-driven one? Rather than polling and looping?  I tried myself but I couldn't clone the `swarm` object to use in two different futures.

**Comment by tomaka** [comment]
Closing as outdated.
