### ISSUE TITLE
Kademlia uses SHA256(SHA256(publickey))

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#694]
The libp2p Kademlia in fact rehashes everything with SHA256 before inserting into k-buckets. This needs to be fixed in our code base.

Let's wait for #580 before doing this.

**Comment by dvc94ch** [comment]
I see what you mean since you are using the hash as a key into a hash table. While it may be better for performance if it weren't rehashed, it shouldn't change the correctness of the lookups no?

**Comment by anacrolix** [comment]
Could you clarify? Do you refer to the fact that peer IDs are a hash of a public key, and then the key used in the DHT is a hash of the peer ID?

**Comment by dvc94ch** [comment]
@anacrolix Mmh, so the comment refers to the `PeerId` being wrong not to the fact that a multihash is used as a key into `FnvHashMap`?

```rust
/// List of values and peers that are providing them.
///
/// Our local peer ID can be in this container.
// TODO: Note that in reality the value is a SHA-256 of the actual value (https://github.com/libp2p/rust-libp2p/issues/694)
values_providers: FnvHashMap<Multihash, SmallVec<[PeerId; 20]>>,
```

**Comment by tomaka** [comment]
> Could you clarify? Do you refer to the fact that peer IDs are a hash of a public key, and then the key used in the DHT is a hash of the peer ID?

Yes!

**Comment by romanb** [comment]
Isn't this resolved by https://github.com/libp2p/rust-libp2p/pull/1025?
