### ISSUE TITLE
Chat example doesn't show who has sent a message

### ISSUE THREAD

**Issue by jamesray1** [libp2p/rust-libp2p#702]
If one participant sends a message the other participants see the message that was sent but do not see the PeerId of the participant that sent the message. This would obviously be problematic.

**Comment by dvdplm** [comment]
The `FloodsubMessage` does contain the `PeerId`, so I think in a real application this would not be a problem. You're right though, we should probably do `println!("Received: {:?} from {:?}", String::from_utf8_lossy(&message.data), &message.source);` instead.

**Comment by twittner** [comment]
#705 has been merged.
