### ISSUE TITLE
Should the nodes floodsub sends messages to be better defined?

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#713]
Right now, when we publish a message with floodsub, this message is simply sent to all the nodes we are connected to and that are subscribed to the topic of the message.

The problem is that by itself, floodsub will never open any connection. If you just create a brand new swarm then publish a message, then nothing will happen because no connection exists. Opening a connection to a node that happens to support a topic we're interested in has to happen through a different mechanism that could be totally unrelated to floodsub.

On a theoretical level, the correct solution is to try to maintain a connection to every single node in the topology. That is however not realistically possible for any non-trivial example.
One could also argue that this is a fundamental limitation of floodsub because it is so basic, and that better pubsub systems are designed to tackle that.

**Comment by echupriyanov** [comment]
Thanks for pointing me at this issue.

We at Stegos (https://github.com/stegos/stegos) are heavily using Floodsub for communications. To solve the topology problem, we have created custom libp2p protocol to form a connected (but not fully meshed) network of the nodes, and run this protocol alongside the Floodsub over the same TCP connection.

So, it's probably ok for Floodsub to operate on all open connections.

What is really concerns me, is that in not fully meshed network, we can have like 2 not directly  connected nodes subscribed to the same topic, and intermediate nodes which are not subscribed to this topic wouldn't route messages between them. But, probably, that is fine too.

**Comment by tomaka** [comment]
> What is really concerns me, is that in not fully meshed network, we can have like 2 not directly connected nodes subscribed to the same topic, and intermediate nodes which are not subscribed to this topic wouldn't route messages between them. But, probably, that is fine too.

Floodsub initially relayed all messages, but we changed it to only relay messages from topics we are subscribed to in order to have the same behaviour as the JS and Go implementations.
Whether this is the best thing to do, I'm not sure.

**Comment by tomaka** [comment]
After #889 it is now well-defined which nodes we send messages to, add we add and remove them from a list.
