### ISSUE TITLE
The mDNS implementation may not be conformant

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#734]
The DNS and mDNS standards are quite complicated, and we overlooked a lot of details.
The current implementation, while functional, should eventually be revisited to be conformant.

**Comment by tomaka** [comment]
To be clear, in this issue I mean "conformant to the mDNS standard".

**Comment by andrewtj** [comment]
Would using platform native mDNS APIs as a part of doing this be acceptable?

**Comment by eskimor** [comment]
@andrewtj I think offering an mdns feature based on the platform's avahi or bonjour daemon makes a lot of sense. This could be done based on the zeroconf crate and the feature could be offered in addition to the current mdns implementation, so we have it as a fallback for when avahi/bonjour are not available.

I am in fact currently looking into that, as this would be the easiest way to have a fully standard conformant and battle tested implementation and also offering improved system performance as only one process on the system needs to send/and receive mdns packets.

**Comment by tomaka** [comment]
Note that libp2p embeds the implementation of mDNS because we only implement the subset necessary for libp2p-mdns to work.
Any actual mDNS implementation should probably be in an external crate.

**Comment by eskimor** [comment]
@tomaka That makes a lot of sense.  My next go will be to see whether we can use the zeroconf crate to offer an alternative mdns implementation, which is more standard conformant but will only work when avahi or bonjour are present and running and should obviously be used in that case, as it is beneficial to only have a single mdns implementation running on a given system.

**Comment by mxinden** [comment]
Closing here. As far as I know the implementation is conformant with mDNS and the libp2p specification. Please open a new issue if that is not the case.
