### ISSUE TITLE
Measure and improve performances

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#744]
This is a very general issue, but we should start having benchmarks (behind a Cargo feature, as benches are unstable in Rust) and fix the costly operations.

There is a lot of room for improvements. We are currently making a lot of cloning around that could be avoided.

**Comment by mxinden** [comment]
Closing as not actionable. https://github.com/libp2p/rust-libp2p/pull/3508 is one step forward on a large scale. Small scale benchmarks are always appreciated.
