### ISSUE TITLE
Add a IntoNetworkBehaviour trait

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#745]
Instead of directly accepting a `NetworkBehaviour`, the `Swarm` should accept a `IntoNetworkBehaviour`.

Something like:

```rust
trait IntoNetworkBehaviour {
    type Behaviour: NetworkBehaviour;
    fn into(self, local_public_key: &PublicKey, local_peer_id: &PeerId) -> Self::Behaviour;
}
```

This makes it possible for the network behaviour to know the local public key and peer ID in advance without requiring the user to pass them manually (like it's the case for `Kademlia` and `Floodsub` at the moment).

**Comment by tomaka** [comment]
This is harder than expected because of the custom derive.

**Comment by thomaseizinger** [comment]
Closing as outdated and not planned for the near future. We have several `NetworkBehaviour`s that need the `identity::Keypair` or local `PeerId` passed in. I agree that it would be nice to avoid that but at the same time, it is an API that most users only call once in their codebase so it is not a big ergonomic hit.
