### ISSUE TITLE
Create a communication channel

### ISSUE THREAD

**Issue by MaiaVictor** [libp2p/rust-libp2p#746]
I've just started a brand new Rust project with Cargo, replaced `lib.rs` by the [chat example](https://github.com/libp2p/rust-libp2p/blob/9102266d7031c024e2fbce48198478edb0e40728/examples/chat.rs), added those dependencies:

```
[dependencies]
libp2p = { git = "https://github.com/libp2p/rust-libp2p" }
futures = "0.1"
env_logger = "0.6.0"
tokio = "0.1"
```

Attempted to run it with `cargo +nightly run`, got this error:

```
   Compiling foo v0.1.0 (/Users/v/vic/dev/bitlog)
error[E0433]: failed to resolve: use of undeclared type or module `tokio_stdin_stdout`
   --> src/main.rs:103:17
    |
103 |     let stdin = tokio_stdin_stdout::stdin(0);
    |                 ^^^^^^^^^^^^^^^^^^ use of undeclared type or module `tokio_stdin_stdout`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0433`.
error: Could not compile `foo`.
```

Did I forget to do anything?

Also: is there any place where I can ask newbie libp2p questions?

**Comment by dvdplm** [comment]
> Did I forget to do anything?

I think you forgot a crate! Try adding `tokio-stdin-stdout = "0.1"` to your `Cargo.toml`. :)

> any place where I can ask newbie libp2p questions?

That's a great question actually. Opening issues is perfectly fine ofc, maybe with a `question` label. But maybe we should have a gitter or some such. Let me get back to you on this. :)

**Comment by MaiaVictor** [comment]
> I think you forgot a crate! Try adding tokio-stdin-stdout = "0.1" to your Cargo.toml. :)

Damn, so stupid.

> But maybe we should have a gitter or some such.

Yes, that'd be amazing. I'm trying to use libp2p to cover the communication part in a project that basically a Bitcoin without a currency, i.e., a data-only log of events with similar blockchain structure. I've read all the libp2p specs, but that is still not enough to, for example, understand everything that is going on [char.rs](https://github.com/libp2p/rust-libp2p/blob/9102266d7031c024e2fbce48198478edb0e40728/examples/chat.rs). I couldn't find a specific/detailed documentation for any of the things used there, so, if that isn't ready yet, having a quick chat where I can ask quick questions would certainly be very helpful!

**Comment by AgeManning** [comment]
> That's a great question actually. Opening issues is perfectly fine ofc, maybe with a `question` label. But maybe we should have a gitter or some such. Let me get back to you on this. :)

I'm also starting to help contribute and have a few questions, which I imagine will be quick for you guys to answer but will take me a bit of time to figure out myself. I figure the IRC channel isn't the best place for such queries.

**Comment by tomaka** [comment]
https://discuss.libp2p.io/ is now open with a Rust subsection where people can ask questions!
We should put that in the README before closing this issue.
