### ISSUE TITLE
Question: Best way to handle Swarm types

### ISSUE THREAD

**Issue by AgeManning** [libp2p/rust-libp2p#775]
I'm wondering about the best way/practice to handle `Swarm`'s. 

Specifically, consider a helper function which builds a `Swarm` by choosing a specific transport(s) and `NetworkBehaviours`. I would like the function to return the built `Swarm`, however will need to specify the return type of the built `Swarm`.  
The type of a given specific `Swarm` is generally complex, is there an easy way to handle this return type. Perhaps there is a trait or generics that simplify my problem?

**Comment by tomaka** [comment]
The type of the `Swarm` shouldn't be very complex, except for the `Transport` (see #717 for that).
Do you have a more concrete example code?

**Comment by AgeManning** [comment]
Hey, thanks for the quick reply. 

I didn't see #717, this does resolve my  problem. Thanks :).
