### ISSUE TITLE
Question: how to start ping?

### ISSUE THREAD

**Issue by daogangtang** [libp2p/rust-libp2p#776]
Hi, I have mounted PingListen to a swarm A, and in another console, mounted PeriodicPing to a swarm B,  they all listen_on correctly, and B dialed to A, but nothing else happened.

What should I do else to start the ping procedure?

Thanks.

**Comment by tomaka** [comment]
The pinging is automatic; the job of the `PeriodicPing` is to close the connection if the node doesn't respond. If there's a need for more features, it can be expanded.

**Comment by daogangtang** [comment]
See #778.
