### ISSUE TITLE
The return value of `libp2p::build_*` cannot be `.boxed()`

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#783]
Calling `libp2p::build_development_transport(...).boxed()` fails to compile because of trait requirements.

**Comment by romanb** [comment]
With https://github.com/libp2p/rust-libp2p/pull/1783 the development transports are essentially already fully `.boxed()` (the `StreamMuxer` was already boxed before that) which could even be reflected in the return type instead of using an opaque `impl` return type.

**Comment by romanb** [comment]
Obsoleted by https://github.com/libp2p/rust-libp2p/pull/1794.
