### ISSUE TITLE
The MdnsService fails to start if no network is available

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#789]
More precisely, `join_multicast_v4()` errors.

Instead I think that it should just silently do nothing.

I'm not sure what the right fix is, though. Should we list the network interfaces and join the multicast IP once per interface?

**Comment by dvdplm** [comment]
Perhaps dumb q: why is it wrong to return an error? Isn't network availability a pre-requisite?

> Instead I think that it should just silently do nothing.

This is fine iff it "magically" starts working once networking becomes available again, but that sounds like an application level concern to me.

**Comment by tomaka** [comment]
What I had indeed in mind is that the `MdnsService` would automatically "adjust" to whatever network you connect.

If you're not connected to anything, it doesn't do anything. If an additional network interface appears, it starts broadcasting to it as well.

**Comment by tomaka** [comment]
In particular, I expect things the `MdnsService` to "magically" work if for example you switch from a wi-fi network to another, or if you go offline for a few seconds.

One can indeed argue that this is the job of the application to detect errors and recreate the `MdnsService`, but in my opinion doing this is difficult enough and desirable enough that libp2p should provide a way to do it automatically.

**Comment by romanb** [comment]
This was fixed by https://github.com/libp2p/rust-libp2p/pull/1830.
