### ISSUE TITLE
Enforce that listeners cannot close gracefully

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#797]
Right now a listener (eg. `TcpStream`) can either close gracefully or with an error.
This was done in order to mimic the API of `futures::Stream`.
In practice, though, we probably don't want listeners to close gracefully, as it is very surprising and difficult to handle. Always having an error is also better for diagnostics.

**Comment by tomaka** [comment]
Good point, I had forgotten that the listener is a `futures::Stream` and not a trait that we control.

We could either design our own trait, or turn that into an `Err` as you mentioned.

I think it's a bit overkill right now to design our own trait. However when we discussed UPnP/PCP, we have encountered some problems that might be solved by extending the listener, in which case it would make sense to have our own trait.

**Comment by thomaseizinger** [comment]
Listeners are now part of the transport polling.
