### ISSUE TITLE
Add a BufWriter layer between the multiplexer and secio

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#808]
Right now every single packet of data from the multiplexer is encoded individually by secio, with a hmac being calculated. For example, opening two substreams, sending "hello" on each of them, and closing them, takes 6 packets, each individually hashed.
Instead, we should only encode and calculate the hmac when `flush()` is called.

This can be done by inserting a `BufWriter` in the stack of upgrades.

**Comment by tomaka** [comment]
Fixing this issue should ideally be accompanied by a before & after benchmark comparison that shows how much it improves performances.

**Comment by twittner** [comment]
Duplicate of #527.
