### ISSUE TITLE
Add helpers to make it possible to easily create a protocol

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#833]
It is too difficult right now to create a custom protocol.
Similarly, the complexity of `kad`, `ping`, `identify` is quite high. We should eventually simplify them.

**Comment by drozdziak1** [comment]
Hey, what part do you think would be the hardest to refactor?

**Comment by tomaka** [comment]
The problem with this issue is that any helper is going to be highly opinionated.

For example we can make it easy to implement communications encoded with JSON, but people might not want to use JSON.

Figuring out the design of the thing is the hard part of this issue.

**Comment by romanb** [comment]
I guess the new `libp2p-request-response` covers this issue for request-response protocols and https://github.com/libp2p/rust-libp2p/issues/1727 seems to overlap with what possibly remains to do for this issue (i.e. maybe we can close this in favour of https://github.com/libp2p/rust-libp2p/issues/1727)?
