### ISSUE TITLE
Rewrite the desktop implementation of libp2p-websocket using twist

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#849]
So that we don't depend on `hyper`.

`twist` seems to be a nice library that implements websockets using `tokio-codec`: https://docs.rs/twist

**Comment by montekki** [comment]
`twist` depends on tokio-proto which is deprecated with no current replacement.

**Comment by tomaka** [comment]
Discussed in private with @montekki 

We basically either need to update `twist`, or fork `twist` and update it, or write our own alternative to `twist`.

**Comment by twittner** [comment]
See https://github.com/paritytech/soketto
