### ISSUE TITLE
core-derive is still broken

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#858]
#853 broke this piece of code: https://github.com/paritytech/substrate/blob/1264cfdce9b34abea9d35f238e00cd0ab1858d83/core/network-libp2p/src/behaviour.rs#L32-L48

cc @dlrobertson Do you want to handle this? :sweat_smile:

**Comment by dlrobertson** [comment]
:+1:

**Comment by tomaka** [comment]
Sorry, false alarm. My build error was unrelated.
