### ISSUE TITLE
Add timeout to `ProtocolsHandlerEvent::OutboundSubstreamRequest`

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#864]
Right now the substream opening timeout is set for each connection by the node handler. Instead it is the `ProtocolsHandler` that should handle this.

At the same time, making `connection_keep_alive()` return true should be done by the `ProtocolsHandler` as well, and not by the `NodeHandler`.

**Comment by tomaka** [comment]
The second point hasn't been done in order to reduce the difficulty of implementing `ProtocolsHandler`. However after #833 this should no longer be a valid reason.

**Comment by romanb** [comment]
Closed by https://github.com/libp2p/rust-libp2p/pull/1049.
