### ISSUE TITLE
mDNS does not support IPv6

### ISSUE THREAD

**Issue by dlrobertson** [libp2p/rust-libp2p#873]
## Summary

The MdnsService only joins and sends queries to IPv4 mDNS multicast address. It should also participate via IPv6. Per [RFC 6762]

> A dual-stack (v4/v6) host can participate in both ".local." zones, and should register its name(s) and perform its lookups both using IPv4 and IPv6.  This enables it to reach, and be reached by, both IPv4-only and IPv6-only hosts.  In effect, this acts like a multihomed host, with one connection to the logical "IPv4 Ethernet segment", and a connection to the logical "IPv6 Ethernet segment".

## Possible solution

I think a reasonable way to do this would be to keep the single `query_send_buffer` responsible for advertising oneself, but split out the `MdnsService::send_buffer` and `MdnsService::socket` into separate `v4` and `v6` instances. Depending on whether the sender is `v6` or `v4` we can give the `MdnsPacket` the correct `send_buffer`.

## Open Questions

 - Does this need to be configurable? Perhaps the `MdnsService` constructors should take a parameter that conditionally enables IPv6 and IPv4 support.
 - [RFC 6762] states that a host responding via IPv6 and IPv4 should result in a single host with two records (`A` and `AAAA`). Is there anything in the `mdns` behaviour that needs to be changed to ensure we don't end up with two separate hosts?

[RFC 6762]: https://tools.ietf.org/html/rfc6762

**Comment by majchrzamemil** [comment]
Hi I am new to Rust, open source and libp2p, but I got interested by this issue and created some solution. If you would find that interesting and useful I can create MR and you can point me in good direction. Code is available on my fork and branch mDns: https://github.com/majchrzamemil/rust-libp2p/tree/mDns 
I attach screen from wireshark after running modified example(IPv6):
![image](https://user-images.githubusercontent.com/17731933/110096972-cd716e80-7d9e-11eb-95f6-1959e2090bb7.png)

**Comment by kczimm** [comment]
Does #2161 close this?

**Comment by mxinden** [comment]
Indeed. Thanks @kczimm!
