### ISSUE TITLE
Question: Best method to handle node protocol in NetworkBehaviour?

### ISSUE THREAD

**Issue by AgeManning** [libp2p/rust-libp2p#880]
I'm interested in handling the protocol of a connected node in the `NetworkBehaviour` trait or something similar. 
My particular issue relates to a `NetworkBehaviour` that provides two distinct sets of logic that is dependent on the protocol the node is using. More specifically, `gossipsub` handles a set of `floodsub` and `gossipsub` peers respectively (lets say in a mapping that resides in a struct that implements `NetworkBehaviour`)
Ideally, (and as an example) in the `inject_connected` function of the `NetworkBehaviour` trait, I would like to determine the protocol of the connected peer to perform protocol-specific logic. 
Any suggestions about dealing with this is welcome :).

**Comment by tomaka** [comment]
You have two possibilities:

- Let the user synchronize the states of `Floodsub` and `Gossipsub` manually (eg. gossipsub generates an event, that when received must be propagated to floodsub, and vice-versa)
- (the one I'd recommend) Have `Gossipsub` handle both the floodsub and gossip protocols together, as the `ProtocolsHandler` associated type can represent multiple protocols together (see `ProtocolsHandlerSelect`).

**Comment by tomaka** [comment]
> Ideally, (and as an example) in the inject_connected function of the NetworkBehaviour trait, I would like to determine the protocol of the connected peer to perform protocol-specific logic.

About that, it's not possible to know in advance which protocols a node support. The only way you can determine that is if you receive an error when opening an outbound substream.

**Comment by AgeManning** [comment]
Thanks for the prompt reply!
My understanding of this is limited. So apologies in advance if I'm way out here. But my understanding was that I could combine protocols using `ProtocolsHandlerSelect` such that the `NetworkBehaviour` would apply to both underlying protocols? More specifically the network behaviour does not distinguish between different nodes, rather applies it's logic uniformly? 
If this is the case, I need another solution where the network behaviour can apply distinct logic based on whether the node is a `floodsub` or a `gossipsub`. I'll do a bit more digging, but if you could point me in the right direction, it would be very helpful. 
Thanks again.

**Comment by tomaka** [comment]
There is no such thing as a "floodsub node", a "gossipsub node", or a "<protocol name> node" from the point of view of a `NetworkBehaviour`.
It always "applies" its protocols to all nodes we connect to, and then we know that a node doesn't support a certain protocol if using it produces an error.

**Comment by AgeManning** [comment]
Thanks for the clarification. I guess I'll have to think a little bit more about how to segregate nodes that use different protocols. To give you a clearer idea of where I'm coming from, I'd assumed a similar design in the protocol handling as the go implementation. 
Their pubsub has an `addPeer(peerId, protocolId)`:
https://github.com/libp2p/go-libp2p-pubsub/blob/d4589956d289b383aa66807840b5baa3f6916f9f/pubsub.go#L126
https://github.com/libp2p/go-libp2p-pubsub/blob/d4589956d289b383aa66807840b5baa3f6916f9f/gossipsub.go#L79
which allows them to connect peers based on the `protocolId`. 

The `addPeer()` gets called when they have a new stream, the streams for each node contain a `protocolId` field
https://github.com/libp2p/go-libp2p-net/blob/58e96baf5d7e630201e3f18062a1e8ced63aa9ac/interface.go#L26

The spec for `gossipsub` requires individual mappings of peers to their protocol, i.e a mapping of `gossipsub` nodes and `floodsub` nodes. It routes like `floodsub` to all `floodsub` nodes. 

I'm currently leaning towards having the user specify their type. I.e send a message signifying it is a gossip node, and by default treat all nodes as `floodsub`. The issue with this is extra messaging across the network, and may not be compatible with other clients. 

Let me know if you can think of a better workaround. 

Thanks in advance.
