### ISSUE TITLE
Need to know the expected PublicKey in upgrades

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#882]
When negotiating the encryption protocol, we can remove one roundtrip by knowing the public key of the remote in advance. This requires some changes in the APIs.

cc #881

**Comment by tomaka** [comment]
One idea would be to pass the expected public key to `Transport::dial`, then to the closure of `Transport::and_then`, and build the connection upgrade on-the-fly.

However this raises questions:
- Is it valid for a transport to return a peer identity that is different from the expected one?
- Should the peer identity be a generic, or hard-coded to a specific type?

**Comment by burdges** [comment]
I'd expect you know this, but..  We only need one party A to know the public key of the other party B, because the handshake can send A's public key to B encrypted behind ee and es key exchanges.  We've slightly different handshakes that determine if A or B initiates the connection.

**Comment by tomaka** [comment]
#888 has been merged but is not usable in practice because of this issue.

**Comment by twittner** [comment]
@tomaka: It depends on the handshake pattern. One could use XX for instance which works without pre-shared static keys. The IK pattern of course requires this issue to be resolved first.

**Comment by thomaseizinger** [comment]
Closing in favor of https://github.com/libp2p/rust-libp2p/issues/2946.
