### ISSUE TITLE
Abstract over tokio-timer in order to compile for the browser

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#900]
I don't know exactly *how*, but we should not use `tokio-timer` when compiling for WASM/Emscripten, as this will not work.

**Comment by tomaka** [comment]
The best way to do that is probably to remove all references from `Instant::now()` and `tokio-timer` from protocols, and put some time management in the core. I'm not sure exactly how we would proceed then, but that would make things easier.

**Comment by najamelan** [comment]
Maybe check again, but for me tokio-timer compiles on wasm32-unknown-unknown. I made [actix compile on wasm](https://users.rust-lang.org/t/another-small-step-to-wasm-compatibility-actix-actors-in-the-browser/26318), and it uses tokio-timer. I have not run tests using the actual functionality that relies on tokio-timer.

**Comment by tomaka** [comment]
It compiles just fine, but any attempt to use it will panic because we are not within a tokio runtime. The last time I checked, "plugging" a clock required being able to put the current thread to sleep, which is obviously not possible in WASM.

**Comment by najamelan** [comment]
It would be possible to make a wasm compatible version of tokio-timer with [gloo, which has timers,](https://github.com/rustwasm/gloo) and wasm-bindgen-futures, which has spawn_local for futures. You can switch dependencies based on the target, [as described in the wasm book](https://rustwasm.github.io/docs/book/reference/add-wasm-support-to-crate.html). This would allow you to make the target transparent to the code using tokio timers. I [turn the js callback mechanisms into futures](https://github.com/najamelan/wasm_websocket_stream/blob/573679cb96bad62ee39f310b1c678c717b678a4d/src/callback_future.rs) by creating a channel, giving the sender to a closure that you feed to the Js apis that take callbacks and polling the channel.

**Comment by tomaka** [comment]
> It would be possible to make a wasm compatible version of tokio-timer with gloo, which has timers

Gloo seems far from being ready though, and since libp2p is published on crates.io we have to stick to dependencies that are also published on crates.io.

**Comment by tomaka** [comment]
And again, I've got a `wasm-time` in #970 that just works. The question in play here is not "how to make it work", but "how to make it work in an elegant way without making the code unreadable".
