### ISSUE TITLE
`libp2p` v0.3.0 fails to build

### ISSUE THREAD

**Issue by echupriyanov** [libp2p/rust-libp2p#908]
I'm getting bunch of errors like:
```
error[E0277]: the trait bound `rand_xorshift::XorShiftRng: rand_core::SeedableRng` is not satisfied
   --> /Users/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/rand-0.6.5/src/deprecated.rs:242:5
```
They all seem to be related to crate `rand` v0.6.5

**Comment by tomaka** [comment]
Can you tell me which crate exactly fails to compile?
Also, maybe `cargo update` solves it?

**Comment by echupriyanov** [comment]
Yes! `cargo update` solved this issue. Sorry for false alarm :)
