### ISSUE TITLE
Allow multiple simultaneous connections to the same peer

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#912]
Right now, in order to simplify the implementations of `NetworkBehaviour`, we only have allow connection per peer ID.
Allowing multiple connections would, in my opinion, considerably increase the difficulty of implementing this trait. If we provide helpers for `NetworkBehaviour`, though, we could allow multiple connections per peer.

Note that we should have ways to properly identify each connection. Having multiple connections shouldn't be implicit.

**Comment by tomaka** [comment]
> Allowing multiple connections would, in my opinion, considerably increase the difficulty of implementing this trait. If we provide helpers for `NetworkBehaviour`, though, we could allow multiple connections per peer.

I just realized that is not necessarily true. We can tell the behaviour that "connected" means "connected for the first time", and "disconnected" means "zero connections remaining".
There could be either one `NodeHandler` for all the connections, or one `NodeHandler` per connection, I'm not sure.

**Comment by tomaka** [comment]
Bumping to "important". See https://github.com/paritytech/substrate/issues/4272 for context.

**Comment by romanb** [comment]
This is now in `libp2p-core`, but `libp2p-swarm` does not yet permit explicitly creating multiple connections per peer. I guess this ticket should stay open until `libp2p-swarm` fully "embraces" the notion of multiple connections per peer?

**Comment by romanb** [comment]
Considered closed with https://github.com/libp2p/rust-libp2p/pull/1519.
