### ISSUE TITLE
parity-multihash: Leave the hashing to the user and only provide APIs for encoding

### ISSUE THREAD

**Issue by seamlik** [libp2p/rust-libp2p#933]
This is a [mirror issue](https://github.com/multiformats/rust-multihash/issues/32).

Right now `parity-multihash` does the hashing and encoding in a single function, and also depends on crates for 4 hashing algorithms (SHA-1/2/3 and Blake2). This is problematic if one wants to use a 5th algorithm.

Wouldn't it be cleaner if the crate only handles the Multihash encoding, and leave the hashing to the user?

**Comment by burdges** [comment]
We avoid using multi-hash in polkadot and substrate itself, right?  

Any protocol is weakened by using multi-hash:  It'll always complicate the the security analysis.  It risks future downgrade attacks as witnessed in TLS 1.2.  Almost all PoS schemes use tools like VRFs and VDFs that must not be used on multi-hashed data.  

There are applications like IPFS that want multi-hash for ancient content lookups, but we should favor protocol versioning and avoid multi-hash whenever possible.

**Comment by tomaka** [comment]
> This is problematic if one wants to use a 5th algorithm.

Considering that the list of algorithms is centralized in a specs, each algorithm is either supported by rust-multihash, or is envisioned to be supported. In other words, if an algorithm isn't supported, feel welcome to open a PR that adds support.
In other words, there is no point in supporting this algorithm separately from rust-multihash just to use the output in combination with rust-multihash afterwards.

> We avoid using multi-hash in polkadot and substrate itself, right?

Yes, it's only used for `PeerIds` at the moment.

**Comment by seamlik** [comment]
FYI: The upstream crate is [introducing](https://github.com/multiformats/rust-multihash/pull/26) a function to encode without hashing.

**Comment by tomaka** [comment]
For what it's worth, I'm all for adding methods to create a `Multihash` from an existing hash, as long as we check that the length is correct.
However I don't really agree with the "only provide APIs for encoding" part.

**Comment by mxinden** [comment]
Closing due to being outdated.
