### ISSUE TITLE
Chat example not working because of E0658

### ISSUE THREAD

**Issue by sherryxiao1988** [libp2p/rust-libp2p#936]
**Errors:**
![image](https://user-images.githubusercontent.com/1202426/52556282-1b695180-2e27-11e9-9d62-0f06ff56b9bc.png)

I already followed the error explains and switched to the nightly build (rustc 1.33.0-nightly), but still got the same error.

**Operating System**
macos High Sierra 10.13.6

I am new to Rust and libp2p. Can anyone help? Thanks!

**Comment by sherryxiao1988** [comment]
I am looking through the go examples:
https://github.com/libp2p/go-libp2p-examples

I wonder if there is any rust specific examples / tutorials? Thanks!

**Comment by tomaka** [comment]
It's a bit weird, because the error message looks legitimate (as in, it is *actually* an error), yet it compiles on my machine with the same version of Rust as you.

**Comment by twittner** [comment]
AFAIK the `uniform_paths` feature was stabilised in version 1.32.0: https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1320-2019-01-17

**Comment by sherryxiao1988** [comment]
hmm interesting... this is the result when i run rustc
➜  quartz git:(change-to-minimal-utxo) rustc --version
rustc 1.33.0-nightly (14b96659e 2018-12-25)

**Comment by sherryxiao1988** [comment]
problem solved once i reverted to rustc 1.32.0
