### ISSUE TITLE
Add an upgrade randomizer

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#940]
For testing purposes, it would be useful to have a type that wraps around a `ProtocolInfo`/`InboundUpgrade`/`OutboundUpgrade` and randomizes the priority of the protocols.

Example use cases:
- Randomly select between mplex and yamux.
- If you support multiple versions of a protocol at the same time (eg. `/myproto/1.0`, `/myproto/2.0`, ...) you can write tests that target all the versions at once.

**Comment by whereistejas** [comment]
@mxinden how about this one? is this a good issue to get started with? I have no clue about what I'm walking into. I would really appreciate your guidance.

**Comment by thomaseizinger** [comment]
Closing until a concrete need arises.
