### ISSUE TITLE
floodsub need help

### ISSUE THREAD

**Issue by Harzu** [libp2p/rust-libp2p#945]
Hello to all. sorry for my english, i'm not very good at it

I learn libp2p.rs and me needed help for my questions.
I try it implement chat rooms on floodsub protocol. The example is very clear, thanks for it
I don't understand how connect two devices in different networks.
I understood that the mDNS protocol is not suitable for this because all connections inner one network.

My second question.
Is it possible to launch such a connection in the browser through WASM or better to use libp2p.js and ipfs-pubsub-room for this task

**Comment by tomaka** [comment]
> I don't understand how connect two devices in different networks.

You basically need bootstrap nodes (nodes whose IP/port is hard-coded in your code), and some sort of discovery mechanism. There's no good example of that yet in the repository, unfortunately.

> Is it possible to launch such a connection in the browser through WASM or better to use libp2p.js and ipfs-pubsub-room for this task

WASM support for rust-libp2p is in progress, but there are issues with eg. `Instant::now()` panicking. We either need to refactor some code to continue, or wait for the Rust WASM support to improve.

**Comment by Harzu** [comment]
thx for answer)! i wait stable wasm support
