### ISSUE TITLE
The ping behaviour shouldn't use the OneShotHandler

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#950]
Ping's job is to maintain connections alive, which is too "meta" to be handled by the `OneShotHandler`.
In the process, tests should be written for ping.

**Comment by romanb** [comment]
What does "too meta" mean in this context?

**Comment by tomaka** [comment]
The role of the `OneShotHandler` is to handle a basic protocol where we send messages and optionally receive responses.
However the role of "ping" is also to close the connection if no response is received in a given time. This is too different from a `OneShotHandler` that they shouldn't share their code.

**Comment by romanb** [comment]
Closed by https://github.com/libp2p/rust-libp2p/pull/1049.
