### ISSUE TITLE
Improve the API of RawSwarm

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#959]
The `Connected`, `Replaced` and `NodeEvent` events of the `RawSwarm` should contain a `PeerConnected` instead of a `PeerId`.
Similarly, the `NodeClosed` and `NodeError` events should contain a `PeerNotConnected`.

**Comment by romanb** [comment]
I think this issue is too dated and we should create new issues with a more elaborate motivation for the desired API.
