### ISSUE TITLE
Cancelling an outgoing dial on purpose should be reported with an event

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#963]
Situation: node A dials B, then receives an incoming connection from B, and therefore cancels its dialing because it can just use the newly-opened connection.
At the moment there's no event that reports this cancellation.

**Comment by tomaka** [comment]
Once done, revisit the "simultaneous dialing" test.

**Comment by romanb** [comment]
Since the canceling is no longer done and simultaneous dialing simply results in two connections, I guess this can be closed.
