### ISSUE TITLE
Support /dnsaddr in multiaddr (and maybe /dns as well?)

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#967]
We don't support multiaddresses with the `/dnsaddr` component.

The `/dns` component is marked as "reserved" [here](https://github.com/multiformats/multiaddr/blob/f3bb08e27b81523d1f1f0371eb1800395b98922d/protocols.csv#L8), so it's unclear whether it should be implemented or not.

This issue also covers adding support for that in `libp2p-dns`, or alternatively opening a different issue for adding support in `libp2p-dns`.

**Comment by raulk** [comment]
go-multiaddr-dns currently handles dns4, dns6, and dnsaddr resolutions. My guess is that dns was reserved as a safeguard to avoid future appropriations that could lead to confusion.

**Comment by lgierth** [comment]
At the time we weren't certain about the needed scope of `/dns`, so we marked it reserved and went with `/dns4` and `/dns6` instead. `/dnsaddr` is an additional mechanism apart from regular A/AAAA record resolution.

**Comment by ackintosh** [comment]
> Support /dnsaddr

I would like to tackle to this issue.  ✨
