### ISSUE TITLE
Enforce #![deny(missing_docs)] everywhere

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#976]
Add `#![deny(missing_docs)]` everywhere, and start with the core.

However the point of this issue is not to hastily comment everything in order to close the issue as fast as possible. The point is to actually properly document things.

**Comment by romanb** [comment]
In that context, maybe it would also make sense to adopt some stylistic conventions for a consistent appearance, e.g. [these](https://github.com/steveklabnik/rfcs/blob/api_comment_conventions/text/0000-api-comment-conventions.md).

**Comment by thomaseizinger** [comment]
Closing as stale.
