### ISSUE TITLE
How to relay message inside floodsub inject_event?

### ISSUE THREAD

**Issue by sherryxiao1988** [libp2p/rust-libp2p#983]
Hi all,

I am new to libp2p and currently looking at the `chat` example provided in the examples folder.

```
    impl<TSubstream: libp2p::tokio_io::AsyncRead + libp2p::tokio_io::AsyncWrite> libp2p::core::swarm::NetworkBehaviourEventProcess<libp2p::floodsub::FloodsubEvent> for MyBehaviour<TSubstream> {
        // Called when `floodsub` produces an event.
        fn inject_event(&mut self, message: libp2p::floodsub::FloodsubEvent) {
            if let libp2p::floodsub::FloodsubEvent::Message(message) = message {
                println!("Received: '{:?}' from {:?}", String::from_utf8_lossy(&message.data), message.source);
            }
        }
    }
```
^ Here the logic to handle incoming Floodsub message is written. Inside this `inject_event` function, I want to relay this message out to other thread through channel. Is there any way for me to do that? Say to pass in a channel sender?

I couldn't find solutions online by looking at the documents.  Thanks a lot for your help!

**Comment by tomaka** [comment]
Hi,

The "normal" way to do that would be to add an "event" enum (https://github.com/paritytech/substrate/blob/f6f4e45dfd949e399d8858f24de1dbf1f168689e/core/network-libp2p/src/behaviour.rs#L147-L199), and a queue of events in the behaviour (eg. https://github.com/paritytech/substrate/blob/f6f4e45dfd949e399d8858f24de1dbf1f168689e/core/network-libp2p/src/behaviour.rs#L46-L48), put the events in this list when they happen (eg. https://github.com/paritytech/substrate/blob/f6f4e45dfd949e399d8858f24de1dbf1f168689e/core/network-libp2p/src/behaviour.rs#L255), and add a poll method on the behaviour to produce these events back (eg. https://github.com/paritytech/substrate/blob/f6f4e45dfd949e399d8858f24de1dbf1f168689e/core/network-libp2p/src/behaviour.rs#L298-L306). You will need to add an attribute to the custom derive for it to work (https://github.com/paritytech/substrate/blob/f6f4e45dfd949e399d8858f24de1dbf1f168689e/core/network-libp2p/src/behaviour.rs#L35).


Polling the `Swarm` will then produce these events (https://github.com/paritytech/substrate/blob/f6f4e45dfd949e399d8858f24de1dbf1f168689e/core/network-libp2p/src/service_task.rs#L383).
I agree that this is a bit complicated. We'd like to make this easier, but finding the right way to make this easier is not easy.

**Comment by sherryxiao1988** [comment]
hi @tomaka,

Thanks for the detailed explain. I am using libp2p a blockchain project right now. It seems to me it might be easier to use substrate directly than using libp2p? Could you share some advice to newcomers like me?

Thanks!

**Comment by romanb** [comment]
For building a blockchain project in Rust, it is certainly worthwhile to look into Substrate rather than using libp2p directly. I'm not sure what still needs answering here, so I'm closing this ticket, but feel free to re-open or create new issues or discussions.
