### ISSUE TITLE
Add variables in NetworkBehaviour

### ISSUE THREAD

**Issue by carlosb1** [libp2p/rust-libp2p#990]
Hi, I am a little newbie with the library and I have a few problems to modify the `chat.rs` example for my use case. How I can add functionalities in the `struct NetworkBehaviour` to  save source address...  It seems the library doesn't permit this and I don't find way to add any functionality.

this is the original code:

```
#[derive(NetworkBehaviour)]
struct MyBehaviour<TSubstream: libp2p::tokio_io::AsyncRead + libp2p::tokio_io::AsyncWrite> {
    floodsub: libp2p::floodsub::Floodsub<TSubstream>,
    mdns: libp2p::mdns::Mdns<TSubstream>,
    addresses: Vec<String>, <-- ADDED FOR MY USE CASE
}


//TODO class to parse values
impl<TSubstream: libp2p::tokio_io::AsyncRead + libp2p::tokio_io::AsyncWrite> libp2p::core::swarm::NetworkBehaviourEventProcess<libp2p::floodsub::FloodsubEvent> for MyBehaviour<TSubstream> {
    fn inject_event(&mut self, message: libp2p::floodsub::FloodsubEvent) {
        if let libp2p::floodsub::FloodsubEvent::Message(message) = message {
            self.addresses.push(message.data.clone());  <-- ADDED FOR MY USE CASE
            println!("Received '{:?}' from {:?}", String::from_utf8_lossy(&message.data), message.source);
        }
    }
}
```

And then I receives errors like this:

> 
>    |
> 70 |         libp2p::Swarm::new(transport, behaviour, local_peer_id)
>    |         ^^^^^^^^^^^^^^^^^^ the trait `libp2p_core::swarm::NetworkBehaviour` is not implemented for `std::vec::Vec<std::string::String>`
> 

I don't know how the library provides the option to add variables and (in general) how to add new functionalities when It receives messages.

**Comment by tomaka** [comment]
Hi,

You can add an `#[behaviour(ignore)]` attribute on top of variables that shouldn't be taken into account.
For example:

```rust
#[derive(NetworkBehaviour)]
struct MyBehaviour<TSubstream: libp2p::tokio_io::AsyncRead + libp2p::tokio_io::AsyncWrite> {
    floodsub: libp2p::floodsub::Floodsub<TSubstream>,
    mdns: libp2p::mdns::Mdns<TSubstream>,
    #[behaviour(ignore)]
    addresses: Vec<String>,
}
```

**Comment by tomaka** [comment]
Note that this is not a very nice API and ideally we'd love to improve it. In practice I'm not sure how to do that.

**Comment by carlosb1** [comment]
@tomaka  It works perfectly now, thanks, I hope you can help you for any of these changes,
