### ISSUE TITLE
Hidden Message  Length Settings

### ISSUE THREAD

**Issue by yinhu-prismalab** [libp2p/rust-libp2p#991]
hi,  just start playing with libp2p here. It seems there are some limit on the message length? 

I tried to code following the chat example and there seems a limit around 1974 bytes. (simply modify the chat example to send a lot of bytes can reproduce the issue.)

Looked into yamux or mplex or tcp settings for buffer size and seems no help changing values there. 

Is there anything i am missing here?

Thanks!

**Comment by tomaka** [comment]
The size limit for a network message is specific to each protocol and is here: https://github.com/libp2p/rust-libp2p/blob/master/protocols/floodsub/src/protocol.rs#L60
I agree that it should indeed be configurable.

Mplex and yamux also have a limit, but they will automatically split outgoing messages.

**Comment by yinhu-prismalab** [comment]
> The size limit for a network message is specific to each protocol and is here:
> 
> [rust-libp2p/protocols/floodsub/src/protocol.rs](https://github.com/libp2p/rust-libp2p/blob/26df15641ce160e70ca243bfb7a09f9693a82a51/protocols/floodsub/src/protocol.rs#L60)
> 
> Line 60 in [26df156](/libp2p/rust-libp2p/commit/26df15641ce160e70ca243bfb7a09f9693a82a51)
> 
>  upgrade::read_one_then(socket, 2048, (), |packet, ()| { 
> (2048)
> I agree that it should indeed be configurable.
> Mplex and yamux also have a limit, but they will automatically split outgoing messages.

Thanks!

Since floodsup is the entry point of the call, i guess there's  no way to go around this limit via mplex or yamux settings. 

Any suggestion if i do need a larger message? reference the crate via a modified repo instead of version number? Will there be any serious side effect if i modify the value? e.g. 1MB ?

**Comment by mxinden** [comment]
Closing here in favor of gossipsub 1.0 and 1.1.
