### ISSUE TITLE
Limit the number of outgoing connections per second

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#997]
Some ISP will think we're malicious if we open too many connections per second.

**Comment by romanb** [comment]
`libp2p-core` now has a configurable limit for the total number of concurrent outgoing connections. This is only indirectly a limit on the _rate of change_ though - the number of outgoing connections _per second_ still depends on how quickly connections are established. Furthermore, https://github.com/libp2p/rust-libp2p/pull/1506 adds a configurable limit on the number of concurrent outgoing connections _per peer_ (which, before https://github.com/libp2p/rust-libp2p/pull/1506, i.e. in the current `master`, is simply always 1).

**Comment by romanb** [comment]
Is the time component, i.e. _per second_, really important? We already have a means to limit the number of concurrent pending as well as established connections, separately for incoming/outgoing with  https://github.com/libp2p/rust-libp2p/pull/1848.

**Comment by thomaseizinger** [comment]
Can be built on top of the new connection management API, see https://github.com/libp2p/rust-libp2p/pull/3386 for example.
