### ISSUE TITLE
Update libp2p-noise to use core::identity::Keypair

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#998]
cc @romanb

**Comment by romanb** [comment]
I'm not sure I understand what this ticket is about. The identity keypairs and the noise keypairs are principally of different types (RSA/Secp256k1/Ed25519 vs X25519) with the only option of converting from Ed25519 to X25519, which is offered by `libp2p-noise` both for [public](https://github.com/libp2p/rust-libp2p/blob/master/protocols/noise/src/protocol/x25519.rs#L158) and [secret](https://github.com/libp2p/rust-libp2p/blob/master/protocols/noise/src/protocol/x25519.rs#L178) keys, e.g. one could do the following:

```rust
let noise_keypair: noise::Keypair<X25519> = match identity_keypair {
    identity::Keypair::Ed25519(pair) => noise::SecretKey<X25519>::from_ed25519(pair.secret()).into(),
    _ => noise::Keypair<X25519>::new()
};
```

Do you mean that should be a function provided by `libp2p-noise`? Or do you mean something else entirely?

**Comment by tomaka** [comment]
The objective of #903 was to remove the redundancy between `libp2p_secio::SecioKeypair` and `libp2p_noise::Keypair`. The idea was to merge them into a single type.
The second part would be, I suppose, to move `X25519` to `libp2p_core::identity` and replace `libp2p_noise::Ed25519` with `libp2p_code::identity::Ed25519`.

**Comment by romanb** [comment]
> The objective of #903 was to remove the redundancy between libp2p_secio::SecioKeypair and libp2p_noise::Keypair.

Right, it is just that the only redundancy I saw was that both defined a type for an Ed25519 keypair and that redundancy got resolved.

> The second part would be, I suppose, to move X25519 to libp2p_core::identity [..]

Not sure why you would want `X25519` keypairs in `libp2p_core::identity`, since the latter is for keypairs for signing (at least that was the idea) while `X25519` is for key exchange.

> [..] and replace  libp2p_noise::Ed25519 with libp2p_code::identity::Ed25519.

There are no more ed25519 keypairs in `libp2p_noise`, that was the redundancy that got removed.

**Comment by tomaka** [comment]
> There are no more ed25519 keypairs in libp2p_noise, that was the redundancy that got removed.

Oh sorry, I didn't notice that.

**Comment by romanb** [comment]
Can this be closed by now?

**Comment by tomaka** [comment]
I guess so.
